#!/usr/bin/env python3
from __future__ import annotations
from typing import Any

def derive_human_review_ready(*,clean_pass_count:int,coverage_percent:float,critical:int,high:int,unresolved_medium:int,suspicious_confirmed:int,contradictions:int,unsupported_claims:int,critical_omissions:int,regression_suite:str,adversarial_suite:str,source_sha_binding:str,artifact_hash_chain:str)->bool:
 return clean_pass_count>=2 and coverage_percent==100.0 and all(x==0 for x in (critical,high,unresolved_medium,suspicious_confirmed,contradictions,unsupported_claims,critical_omissions)) and all(x=='PASS' for x in (regression_suite,adversarial_suite,source_sha_binding,artifact_hash_chain))

def convergence_receipt(*,source_sha256:str,code_head_sha:str,configuration_id:str,configuration_sha256:str,clean_passes:list[dict],coverage_percent:float,counts:dict[str,int],regression_suite:str,adversarial_suite:str,source_sha_binding:str,artifact_hash_chain:str)->dict[str,Any]:
 ready=derive_human_review_ready(clean_pass_count=len(clean_passes),coverage_percent=coverage_percent,critical=counts.get('critical',0),high=counts.get('high',0),unresolved_medium=counts.get('unresolved_medium',0),suspicious_confirmed=counts.get('suspicious_confirmed',0),contradictions=counts.get('contradictions',0),unsupported_claims=counts.get('unsupported_claims',0),critical_omissions=counts.get('critical_omissions',0),regression_suite=regression_suite,adversarial_suite=adversarial_suite,source_sha_binding=source_sha_binding,artifact_hash_chain=artifact_hash_chain)
 return {'schema_version':'p0-convergence-receipt-v4/v1','source_sha256':source_sha256,'code_head_sha':code_head_sha,'configuration_id':configuration_id,'configuration_sha256':configuration_sha256,'clean_passes':clean_passes,'grader_coverage_percent':coverage_percent,'critical':counts.get('critical',0),'high':counts.get('high',0),'unresolved_medium':counts.get('unresolved_medium',0),'suspicious_confirmed':counts.get('suspicious_confirmed',0),'contradictions':counts.get('contradictions',0),'unsupported_claims':counts.get('unsupported_claims',0),'critical_omissions':counts.get('critical_omissions',0),'regression_suite':regression_suite,'adversarial_suite':adversarial_suite,'source_sha_binding':source_sha_binding,'artifact_hash_chain':artifact_hash_chain,'human_review_ready':ready,'result':'PASS_P0_V4_CLOSED_LOOP' if ready else 'BLOCKED_CONVERGENCE'}
