#!/usr/bin/env python3
from p0_visual_quality_primitives import *
from p0_visual_quality_primitives import _crop_reread,_inside,_region_box,_contains_box,_next_element_id
from p0_visual_remediation import *
def run_loop(*,image_path:Path,admission_path:Path,processing_manifest_path:Path|None,source_image_ref:str,config:dict[str,Any],output_dir:Path,execution_id:str,judge_identity:str,code_head_sha:str="LOCAL_TEST")->dict[str,Any]:
    output_dir.mkdir(parents=True,exist_ok=True);admission=validate_admission(image_path,admission_path,processing_manifest_path);cfg=runtime_config_check(config)
    if not admission["pass"]:return {"result":"BLOCKED_SOURCE_QUALITY","human_review_ready":False,"admission":admission,"config":cfg}
    if not cfg["registered"]:return {"result":"BLOCKED_MODEL_CONFIGURATION","human_review_ready":False,"admission":admission,"config":cfg}
    if not cfg["calibration_current"]:return {"result":"BLOCKED_CALIBRATION","human_review_ready":False,"admission":admission,"config":cfg}
    candidate,diagnostics=build_consolidated(image_path,source_image_ref=source_image_ref,execution_id=execution_id,config=config);evidence_manifest_sha=canonical_sha(diagnostics.get("evidence_manifest",{}));raw_manifest={"schema_version":"p0b-raw-evidence-manifest/v1","execution_id":execution_id,"source_image_ref":source_image_ref,"source_sha256":admission["source_sha256"],"configuration_id":cfg["configuration_id"],"configuration_sha256":cfg["config_sha256"],"code_head_sha":code_head_sha,"idempotency_key":idempotency_key(config,admission["source_sha256"]),"raw_ocr_observation_count":diagnostics.get("raw_observation_count",diagnostics["raw_word_count"]),"reconciled_ocr_word_count":diagnostics["raw_word_count"],"raw_ocr_line_count":diagnostics["raw_line_count"],"geometry_counts":diagnostics["geometry_counts"],"evidence_manifest_sha256":evidence_manifest_sha,"scan_scales":config["ocr"]["scan_scales"],"adaptive_crop_scale":config["ocr"]["adaptive_crop_scale"],"role":"P0B_RAW_EVIDENCE_ONLY","human_review_ready":False,"created_at":now_iso()};(output_dir/"p0b-raw-evidence-manifest.json").write_bytes(canonical_bytes(raw_manifest));raw_sha=canonical_sha(raw_manifest)
    max_cycles=int(config["quality"]["max_remediation_cycles"]);cycles=[];seen_fingerprints=set();current=candidate;cycle=0
    while True:
        reader_exec=current["execution_id"];judge_exec=f"{execution_id}-J00-{cycle}";audit=audit_candidate(image_path,current,execution_id=judge_exec,identity=judge_identity,reader_execution_id=reader_exec,config=config);fingerprint=finding_fingerprint(audit)
        if audit["judgment"]=="PASS":break
        if cycle>=max_cycles:result="BLOCKED_MAX_REMEDIATION";break
        if fingerprint in seen_fingerprints:result="BLOCKED_MAX_REMEDIATION";break
        seen_fingerprints.add(fingerprint);cycle+=1;remediated,actions=remediate_once(image_path,current,audit,config,cycle);changed=canonical_sha(remediated)!=canonical_sha(current);cycles.append({"cycle":cycle,"before_candidate_sha256":canonical_sha(current),"before_j00":audit,"finding_fingerprint":fingerprint,"actions":actions,"state_changed":changed,"after_candidate_sha256":canonical_sha(remediated)});current=remediated
        if not changed:continue
    else:result="BLOCKED_VISUAL_QUALITY"
    if audit["judgment"]=="PASS":result="PASS_VISUAL_QUALITY"
    current_sha=canonical_sha(current);counts=counts_from(current,audit);privacy=config.get("privacy_security",{});hard_checks={"evidence_integrity_pass":admission["pass"],"visual_structure_pass":not any(str(f.get("code","")).startswith("VISUAL_STRUCTURE") for f in audit.get("findings",[])),"visual_semantic_pass":not audit.get("contradictions") and not audit.get("unsupported_claims"),"visual_completeness_pass":not any(x.get("material") for x in audit.get("audit_only",[])),"source_admission_binding_pass":admission["pass"],"j00_independence_pass":audit.get("execution_id")!=current.get("execution_id") and audit.get("identity")!="P0_VISUAL_READER","security_pass":privacy.get("screenshot_text_untrusted") is True and privacy.get("action_tools_allowed") is False and privacy.get("network_deny_by_default") is True,"privacy_pass":privacy.get("raw_source_private") is True,"model_configuration_registered":cfg["registered"],"calibration_policy_current":cfg["calibration_current"],"packet_hashes_reconcilable":audit.get("candidate_sha256")==current_sha and audit.get("source_sha256")==admission["source_sha256"]};zero_hard=all(counts[k]==0 for k in ("critical_omissions","contradictions","unsupported_claims","pending_remediations","unresolved_critical_uncertainties"));ready=result=="PASS_VISUAL_QUALITY" and audit.get("judgment")=="PASS" and all(hard_checks.values()) and zero_hard
    if not ready and result=="PASS_VISUAL_QUALITY":result="BLOCKED_VISUAL_QUALITY"
    report={"schema_version":"p0-machine-visual-quality-report/v1","execution_id":f"{execution_id}-QUALITY","source_image_refs":[source_image_ref],"source_sha256":admission["source_sha256"],"raw_visual_output_sha256":raw_sha,"consolidated_visual_reading_sha256":current_sha,"p0h_execution_id":f"{execution_id}-P0H","j00_execution_id":audit["execution_id"],"j00_identity":audit["identity"],"remediation_cycles":cycle,"max_remediation_cycles":max_cycles,"counts":counts,"checks":hard_checks,"result":result,"human_review_ready":ready,"blocking_assertions":[] if ready else sorted({*[k for k,v in hard_checks.items() if not v],*[k for k in ("critical_omissions","contradictions","unsupported_claims","pending_remediations","unresolved_critical_uncertainties") if counts[k]!=0],*(["j00_judgment"] if audit.get("judgment")!="PASS" else [])}),"created_at":now_iso(),"model_configuration_id":cfg["configuration_id"],"calibration_reference":config["calibration"]["calibration_reference"]}
    receipt={"schema_version":"p0-visual-quality-loop-receipt/v1","execution_id":execution_id,"code_head_sha":code_head_sha,"configuration_id":cfg["configuration_id"],"configuration_sha256":cfg["config_sha256"],"idempotency_key":idempotency_key(config,admission["source_sha256"]),"execution_controls":config.get("execution_controls",{}),"source_sha256":admission["source_sha256"],"admission":admission,"runtime_config":cfg,"raw_evidence_manifest_sha256":raw_sha,"initial_candidate_sha256":canonical_sha(candidate),"final_candidate_sha256":current_sha,"cycles":cycles,"final_j00":audit,"machine_quality_result":result,"human_review_ready":ready,"p0_5_denominator_eligible":empirical_p0_5_eligible(config,"REAL_SCREEN_RUN"),"created_at":now_iso()};(output_dir/"consolidated-visual-reading.json").write_bytes(canonical_bytes(current));(output_dir/"j00-visual-audit.json").write_bytes(canonical_bytes(audit));(output_dir/"machine-visual-quality-report.json").write_bytes(canonical_bytes(report));(output_dir/"p0-visual-quality-loop-receipt.json").write_bytes(canonical_bytes(receipt));return {"result":result,"human_review_ready":ready,"report":report,"receipt":receipt}
def main()->int:
    ap=argparse.ArgumentParser();ap.add_argument("--image",type=Path,required=True);ap.add_argument("--admission",type=Path,required=True);ap.add_argument("--processing-manifest",type=Path);ap.add_argument("--source-image-ref",required=True);ap.add_argument("--config",type=Path,required=True);ap.add_argument("--output-dir",type=Path,required=True);ap.add_argument("--execution-id",required=True);ap.add_argument("--judge-identity",default="P0_VISUAL_JUDGE");ap.add_argument("--code-head-sha",required=True);args=ap.parse_args();config=json.loads(args.config.read_text(encoding="utf-8"));result=run_loop(image_path=args.image,admission_path=args.admission,processing_manifest_path=args.processing_manifest,source_image_ref=args.source_image_ref,config=config,output_dir=args.output_dir,execution_id=args.execution_id,judge_identity=args.judge_identity,code_head_sha=args.code_head_sha);summary={"result":result["result"],"human_review_ready":result["human_review_ready"],"remediation_cycles":result.get("report",{}).get("remediation_cycles"),"counts":result.get("report",{}).get("counts"),"final_candidate_sha256":result.get("report",{}).get("consolidated_visual_reading_sha256"),"j00_execution_id":result.get("report",{}).get("j00_execution_id")};print(json.dumps(summary,sort_keys=True));return 0 if result["human_review_ready"] else 2
if __name__=="__main__":raise SystemExit(main())
