#!/usr/bin/env python3
from __future__ import annotations
import argparse, hashlib, json
from pathlib import Path
from jsonschema import Draft7Validator
ROOT=Path(__file__).resolve().parents[2]; SKILL=ROOT/'skills'/'creating-integral-user-stories'; PATH=SKILL/'schemas/story-pack.schema.json'
SECTIONS=['identity','core','interaction','fields','validations','observations','errors','security_privacy','states','audit','tokens_messages','analytics','observability','responsive_accessibility','tests','dependencies_risks','judges_evidence']
def main():
 parser=argparse.ArgumentParser();parser.add_argument('--report-dir',type=Path,required=True);args=parser.parse_args();raw=PATH.read_bytes();schema=json.loads(raw);valid=True;error=None
 try: Draft7Validator.check_schema(schema)
 except Exception as exc: valid=False;error=f'{type(exc).__name__}:{exc}'
 budget=schema.get('definitions',{}).get('context_budget',{}); checks={'draft7':schema.get('$schema')=='http://json-schema.org/draft-07/schema#','schema_valid':valid,'object_closed':schema.get('type')=='object' and schema.get('additionalProperties') is False,'required_17':schema.get('required')==SECTIONS,'definitions_present':all(x in schema.get('definitions',{}) for x in ('acceptance_criterion','field_contract','test_case','context_budget')),'context_budget_required':set(budget.get('required',[]))=={'measurement_method','canonical_story_tokens','implementation_view_tokens','active_context_tokens','context_band','direct_load_allowed','specialized_views_required','atomicity_review_required','atomicity_review_result','measured_at','model_reference','source_ref'},'context_budget_cross_rules':len(budget.get('allOf',[]))>=2,'identity_closed':schema.get('properties',{}).get('identity',{}).get('additionalProperties') is False,'core_closed':schema.get('properties',{}).get('core',{}).get('additionalProperties') is False,'tests_min_one':schema.get('properties',{}).get('tests',{}).get('minItems')==1,'status_safe':set(schema.get('properties',{}).get('identity',{}).get('properties',{}).get('status',{}).get('enum',[]))=={'CANDIDATO_READ_ONLY','PENDING_DECISION','BLOCKED'},'validator_exists':(SKILL/'scripts/validate_story_pack.py').is_file(),'contract_exists':(SKILL/'references/story-pack-contract.md').is_file()}
 score=10.0 if all(checks.values()) else round(8+2*sum(checks.values())/len(checks),2);out={'artifact_code':'A30','relative_path':'schemas/story-pack.schema.json','sha256':hashlib.sha256(raw).hexdigest(),'checks':checks,'schema_error':error,'claude_score':score,'github_score':score,'technical_score':score,'final_score':score,'result':'PASS_WITH_EVIDENCE' if score>9.5 and all(checks.values()) else 'RETURN_TO_WORKER','findings':[k for k,v in checks.items() if not v]};args.report_dir.mkdir(parents=True,exist_ok=True);(args.report_dir/'A30.json').write_text(json.dumps(out,indent=2)+'\n');print(json.dumps(out,sort_keys=True));return 0 if out['result']=='PASS_WITH_EVIDENCE' else 1
if __name__=='__main__':raise SystemExit(main())
