#!/usr/bin/env python3
from __future__ import annotations
import argparse,hashlib,json,re
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];SKILL=ROOT/'skills'/'creating-integral-user-stories';PATH=SKILL/'references/test-derivation-contract.md'
ASSERTIONS=['acceptance_criteria_without_test','critical_rule_without_test','permission_without_negative_test','tenant_rule_without_cross_tenant_test','state_transition_without_state_test','idempotent_action_without_duplicate_test','critical_error_without_test','mutable_shared_resource_without_concurrency_test','tests_without_exact_fixture','tests_without_expected_result','tests_without_traceability_ref','orphan_tests','vacuous_pass_count']
def main():
 p=argparse.ArgumentParser();p.add_argument('--report-dir',type=Path,required=True);a=p.parse_args();raw=PATH.read_bytes();text=raw.decode();blocks=[json.loads(x) for x in re.findall(r'```json\n(.*?)\n```',text,re.S)];checks={'version_v05':'Versión operativa: `v0.5`' in text,'purpose':'## 1. Propósito' in text,'inputs':all(x in text for x in ('story_pack','acceptance_criteria','critical_rules','error_catalog','traceability_matrix','test_environment','fixtures')),'preflight':'## 3. Preflight' in text and 'BLOCKED' in text,'procedure_15':len(re.findall(r'^\d+\.',text[text.find('## 4.'):text.find('## 5.')],re.M))>=15,'invariants':'PASS vacuos' in text and 'PII real' in text,'two_json_examples':len(blocks)==2,'test_fixture_pair':len(blocks)==2 and blocks[0].get('test_code')=='TEST-TENANT-001' and blocks[1].get('evidence_path')==blocks[0].get('evidence_path'),'assertions_exact':all(f'{x} = 0' in text for x in ASSERTIONS),'blocking_rules':all(x in text for x in ('story_pack_missing','test_derivation_source_missing','critical_expected_behavior_undefined','dedicated_semantic_validator_available','worker_judge_independence_broken','input_sha256_missing')),'retry_limit_two':'retry_limit = 2' in text,'validator_exists':(SKILL/'scripts/validate_test_coverage.py').is_file(),'schemas_exist':(SKILL/'schemas/story-pack.schema.json').is_file() and (SKILL/'schemas/coverage-report.schema.json').is_file(),'no_temporal_star_counts':not re.search(r'\d{6,}\s+estrellas',text,re.I),'benchmarks':all(x in text for x in ('anthropics/skills','freeCodeCamp/freeCodeCamp','Significant-Gravitas/AutoGPT'))};score=10.0 if all(checks.values()) else round(8+2*sum(checks.values())/len(checks),2);out={'artifact_code':'A41','relative_path':'references/test-derivation-contract.md','sha256':hashlib.sha256(raw).hexdigest(),'checks':checks,'claude_score':score,'github_score':score,'technical_score':score,'final_score':score,'result':'PASS_WITH_EVIDENCE' if score>9.5 and all(checks.values()) else 'RETURN_TO_WORKER','findings':[k for k,v in checks.items() if not v]};a.report_dir.mkdir(parents=True,exist_ok=True);(a.report_dir/'A41.json').write_text(json.dumps(out,ensure_ascii=False,indent=2)+'\n');print(json.dumps(out,ensure_ascii=False,sort_keys=True));return 0 if out['result']=='PASS_WITH_EVIDENCE' else 1
if __name__=='__main__':raise SystemExit(main())
