#!/usr/bin/env python3
from __future__ import annotations
import argparse,hashlib,json,re
from pathlib import Path
import yaml
ROOT=Path(__file__).resolve().parents[2];SKILL=ROOT/'skills'/'creating-integral-user-stories';PATH=SKILL/'judges/source-integrity.yaml';REQUIRED=['schema_version','judge_code','judge_version','executor_identity','command','started_at','completed_at','exit_code','result','compliance_bit','assertions_total','assertions_passed','failed_assertions','blocking_assertions','repairs','repair_instructions','evidence_refs','evidence','evidence_sha256','input_sha256','output_sha256','retry_count']
def main():
 p=argparse.ArgumentParser();p.add_argument('--report-dir',type=Path,required=True);a=p.parse_args();raw=PATH.read_bytes();d=yaml.safe_load(raw);ids=[x.get('assertion_id') for x in d.get('assertions',[])];checks={'yaml_object':isinstance(d,dict),'judge_v05':d.get('judge_version')=='v0.5','assertions_7':len(ids)==7 and len(set(ids))==7,'validator_exists':(SKILL/'scripts/validate_source_integrity.py').is_file(),'runtime_available':d.get('validators',{}).get('runtime_status')=='AVAILABLE','pass_fail_block':all(k in d for k in ('pass_if','fail_if','block_if')),'positive_negative':bool(d.get('positive_behavior')) and len(d.get('negative_cases',[]))>=3,'repair_matrix':len(d.get('repair_matrix',[]))>=2,'output_v05':d.get('output',{}).get('schema_version')=='v0.5' and set(REQUIRED)<=set(d.get('output',{}).get('required_fields',[])),'no_temporal_stars':not re.search(r'stars_verified',raw.decode()),'metadata_block':all(x in d.get('block_if',[]) for x in ('executor_identity_missing = true','judge_version_missing = true'))};score=10.0 if all(checks.values()) else round(8+2*sum(checks.values())/len(checks),2);out={'artifact_code':'A42','relative_path':'judges/source-integrity.yaml','sha256':hashlib.sha256(raw).hexdigest(),'checks':checks,'claude_score':score,'github_score':score,'technical_score':score,'final_score':score,'result':'PASS_WITH_EVIDENCE' if score>9.5 and all(checks.values()) else 'RETURN_TO_WORKER','findings':[k for k,v in checks.items() if not v]};a.report_dir.mkdir(parents=True,exist_ok=True);(a.report_dir/'A42.json').write_text(json.dumps(out,indent=2)+'\n');print(json.dumps(out,sort_keys=True));return 0 if out['result']=='PASS_WITH_EVIDENCE' else 1
if __name__=='__main__':raise SystemExit(main())
