import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { Pool } from "jsr:@db/postgres@0.19.5";
const OBJECT_ID="3f23317d-58a3-4432-9cf2-f9477c5d103f";
const EXPECTED_BYTES=2100658;
const EXPECTED_SHA256="009866bbd0de99088d9fe8131593d476058a123aa7bcca25b676c03d6b028964";
const EXPECTED_CHALLENGE="CH-P0-HUMAN-E90A2F9EFAE0-CANONICAL-20260817001504";
const EXPECTED_RENDERER_BLOB="91144c0f3c01f22b84f5c8a79c43a4e378cb9d18";
const TOKEN_SHA256="17ed2ccb35e105718943c93c75ec38b7fe415b4981b87bc7407f67f787164311";
const EXPIRES_AT="2026-08-18T00:15:04.648Z";
const DB_URL=Deno.env.get("SUPABASE_DB_URL")?.trim()??"";if(!DB_URL)throw new Error("SUPABASE_DB_URL_MISSING");const pool=new Pool(DB_URL,1,true);
function hex(b:Uint8Array){return Array.from(b,x=>x.toString(16).padStart(2,"0")).join("")}async function shaBytes(d:Uint8Array){return hex(new Uint8Array(await crypto.subtle.digest("SHA-256",d)))}async function shaText(s:string){return shaBytes(new TextEncoder().encode(s))}function eq(a:string,b:string){if(a.length!==b.length)return false;let d=0;for(let i=0;i<a.length;i++)d|=a.charCodeAt(i)^b.charCodeAt(i);return d===0}
function decodeHex(v:string){const s=v.startsWith("\\x")?v.slice(2):v;if(s.length%2||!/^[0-9a-f]*$/i.test(s))throw new Error("BYTEA_TEXT_INVALID");const o=new Uint8Array(s.length/2);for(let i=0;i<o.length;i++)o[i]=parseInt(s.slice(i*2,i*2+2),16);return o}function bytes(v:unknown){if(v instanceof Uint8Array){if(v.byteLength===EXPECTED_BYTES)return v;if(v.byteLength>=2&&v[0]===92&&v[1]===120)return decodeHex(new TextDecoder().decode(v));return v}if(v instanceof ArrayBuffer)return bytes(new Uint8Array(v));if(typeof v==="string")return decodeHex(v);if(Array.isArray(v))return bytes(new Uint8Array(v as number[]));throw new Error("BYTEA_TYPE_UNSUPPORTED")}
function blocked(status:number,code:string){return new Response(code,{status,headers:{"content-type":"text/plain; charset=utf-8","cache-control":"no-store, max-age=0","x-content-type-options":"nosniff","referrer-policy":"no-referrer"}})}
Deno.serve(async(req:Request)=>{if(req.method!=="GET")return blocked(405,"METHOD_NOT_ALLOWED");const u=new URL(req.url),token=u.searchParams.get("token")??"";if(!token)return blocked(401,"TOKEN_REQUIRED");if(Date.now()>Date.parse(EXPIRES_AT))return blocked(410,"LINK_EXPIRED");if(!eq(await shaText(token),TOKEN_SHA256))return blocked(401,"TOKEN_INVALID");const cn=await pool.connect();try{const q=await cn.queryObject<{content:Uint8Array|string;mime_type:string;content_bytes:number|bigint;content_sha256:string;metadata:Record<string,unknown>}>({text:"select content,mime_type,content_bytes,content_sha256,metadata from private.lf_p0_review_evidence_objects_v1 where evidence_object_id=$1::uuid",args:[OBJECT_ID]});if(q.rows.length!==1)return blocked(404,"EVIDENCE_OBJECT_NOT_FOUND");const r=q.rows[0],b=bytes(r.content);if(Number(r.content_bytes)!==EXPECTED_BYTES||b.byteLength!==EXPECTED_BYTES)return blocked(409,"BYTE_LENGTH_MISMATCH");if(!eq(String(r.content_sha256),EXPECTED_SHA256)||!eq(await shaBytes(b),EXPECTED_SHA256))return blocked(409,"CONTENT_SHA256_MISMATCH");if(String(r.metadata?.renderer_blob_sha??"")!==EXPECTED_RENDERER_BLOB)return blocked(409,"RENDERER_BLOB_MISMATCH");const h=new TextDecoder().decode(b);const markers=[EXPECTED_CHALLENGE,'data-review-shell-version="4.2"','id="review-tabs"','IMAGEN ORIGINAL CON ANOTACIONES','LISTA DE ELEMENTOS DETECTADOS','M.counts.total','id="source-stage"','id="source-canvas"','id="source-image"','id="overlay"','id="selected-crop"',"pageOrder=['summary','screen','elements','detail','decision']",'id="p0-human-language-v2"'];if(markers.some(m=>!h.includes(m)))return blocked(409,"CANONICAL_V42_CONTRACT_MISMATCH");const cropCount=(h.length-h.replaceAll('id="selected-crop"','').length)/'id="selected-crop"'.length;if(cropCount!==1||h.toLowerCase().includes('crop-gallery'))return blocked(409,"CANONICAL_CROP_POLICY_MISMATCH");return new Response(b,{status:200,headers:{"content-type":"text/html; charset=utf-8","content-length":String(b.byteLength),"cache-control":"no-store, max-age=0, private","pragma":"no-cache","x-content-type-options":"nosniff","referrer-policy":"no-referrer","x-frame-options":"DENY","content-security-policy":"default-src 'none'; img-src data:; style-src 'unsafe-inline'; script-src 'unsafe-inline'; connect-src 'none'; object-src 'none'; base-uri 'none'; frame-ancestors 'none'; form-action 'none'"}})}catch(e){console.error(e instanceof Error?e.message:String(e));return blocked(500,"REVIEW_WEB_INTERNAL_ERROR")}finally{cn.release()}});