-- DEPRECATED: LF_WORK_PROTOCOL_MANIFEST_V1
-- WORK_PROTOCOL_V1_DEPRECATED_DO_NOT_USE
-- No canonical deployable Work Protocol V1 candidate exists.
-- Historical bytes are available only through Git history.
