-- S29 / LF asset lifecycle operation recorder v1
-- SOURCE_ONLY / NOT_DEPLOYED / CANDIDATE_READ_ONLY
-- Scope intentionally limited to ACTUALIZACION_CARD_LF and RETIRO_ACTIVO_LF.
-- Reuses the governed transactional recorder pattern from lf_record_profile_operation_step_v1.
-- A migration must be generated by the governed Supabase CLI flow before any deployment.

create or replace function public.lf_record_asset_lifecycle_step_v1(
  p_execution_id text,
  p_step_id text,
  p_evidence_ref text,
  p_evidence_payload jsonb,
  p_actor_execution_id text
)
returns jsonb
language plpgsql
security invoker
set search_path to 'public'
as $function$
declare
  v_execution public.lf_operation_execution%rowtype;
  v_step public.lf_operation_steps%rowtype;
  v_contract public.lf_operation_step_contracts%rowtype;
  v_binding public.lf_operation_step_judge_bindings%rowtype;
  v_existing public.lf_operation_execution_steps%rowtype;
  v_asset public.lf_activos%rowtype;
  v_key text;
  v_missing_keys text[] := array[]::text[];
  v_prior_missing integer := 0;
  v_prior_bad integer := 0;
  v_blocking_codes jsonb := '[]'::jsonb;
  v_payload jsonb;
  v_attempt_history jsonb := '[]'::jsonb;
  v_existing_retryable boolean := false;
  v_block_code text;
  v_block_details jsonb := '{}'::jsonb;
  v_trust jsonb;
  v_server_consumer_count integer := 0;
  v_server_distinct_consumer_count integer := 0;
begin
  if p_execution_id is null or btrim(p_execution_id) = '' or p_step_id is null or btrim(p_step_id) = '' then
    return jsonb_build_object('outcome','BLOCKED','code','STEP_IDENTITY_MISSING','durable',false);
  end if;
  if p_step_id = 'init_execution' then
    return jsonb_build_object('outcome','BLOCKED','code','INIT_STEP_IMMUTABLE','durable',false);
  end if;
  if p_evidence_payload is null or jsonb_typeof(p_evidence_payload) <> 'object' then
    return jsonb_build_object('outcome','BLOCKED','code','EVIDENCE_PAYLOAD_INVALID','durable',false);
  end if;

  select * into v_execution
  from public.lf_operation_execution
  where execution_id = p_execution_id
  for update;

  if not found
     or v_execution.operation_code not in ('ACTUALIZACION_CARD_LF','RETIRO_ACTIVO_LF') then
    return jsonb_build_object('outcome','BLOCKED','code','EXECUTION_IDENTITY_INVALID','durable',false);
  end if;
  if v_execution.operation_code = 'ACTUALIZACION_CARD_LF' and v_execution.target_type <> 'CARD' then
    return jsonb_build_object('outcome','BLOCKED','code','CARD_UPDATE_TARGET_TYPE_INVALID','durable',false);
  end if;
  if v_execution.operation_code = 'RETIRO_ACTIVO_LF'
     and v_execution.target_type not in ('PERFIL','CARD','ADAPTER','SKILL') then
    return jsonb_build_object('outcome','BLOCKED','code','RETIRE_TARGET_TYPE_UNAUTHORIZED','durable',false);
  end if;
  if v_execution.status <> 'IN_PROGRESS' then
    return jsonb_build_object('outcome','BLOCKED','code','EXECUTION_NOT_IN_PROGRESS','status',v_execution.status,'durable',false);
  end if;

  select * into v_step
  from public.lf_operation_steps
  where operation_code = v_execution.operation_code
    and step_id = p_step_id
    and active is true;
  if not found then
    return jsonb_build_object('outcome','BLOCKED','code','STEP_NOT_ACTIVE','durable',false);
  end if;

  select * into v_contract
  from public.lf_operation_step_contracts
  where operation_code = v_execution.operation_code
    and step_id = p_step_id
    and status = 'ACTIVE_ENFORCEMENT';
  if not found then
    return jsonb_build_object('outcome','BLOCKED','code','STEP_CONTRACT_NOT_ACTIVE_ENFORCEMENT','durable',false);
  end if;

  select * into v_binding
  from public.lf_operation_step_judge_bindings
  where operation_code = v_execution.operation_code
    and step_id = p_step_id
    and status = 'ACTIVE_ENFORCEMENT';
  if not found then
    return jsonb_build_object('outcome','BLOCKED','code','STEP_JUDGE_BINDING_MISSING','durable',false);
  end if;

  select * into v_existing
  from public.lf_operation_execution_steps
  where execution_id = p_execution_id
    and step_id = p_step_id;

  if found then
    if v_existing.status = v_binding.clean_result_value
       and v_existing.evidence_ref = p_evidence_ref
       and v_existing.evidence_payload @> p_evidence_payload then
      return jsonb_build_object('outcome','STEP_RECORDED','replay',true,'step_id',p_step_id,'status',v_existing.status);
    end if;
    if v_existing.status in (v_binding.blocked_result_value,v_binding.return_result_value) then
      v_existing_retryable := true;
      if jsonb_typeof(v_existing.evidence_payload->'attempt_history') = 'array' then
        v_attempt_history := v_existing.evidence_payload->'attempt_history';
      end if;
    else
      return jsonb_build_object('outcome','BLOCKED','code','STEP_ALREADY_RECORDED_DIFFERENT_EVIDENCE','status',v_existing.status,'durable',true);
    end if;
  end if;

  select count(*) into v_prior_missing
  from public.lf_operation_steps s
  where s.operation_code = v_execution.operation_code
    and s.required is true
    and s.active is true
    and coalesce(s.execution_order,0) < coalesce(v_step.execution_order,0)
    and not exists (
      select 1 from public.lf_operation_execution_steps es
      where es.execution_id = p_execution_id and es.step_id = s.step_id
    );

  select count(*) into v_prior_bad
  from public.lf_operation_steps s
  join public.lf_operation_execution_steps es
    on es.execution_id = p_execution_id and es.step_id = s.step_id
  left join public.lf_operation_step_judge_bindings pb
    on pb.operation_code = s.operation_code
   and pb.step_id = s.step_id
   and pb.status = 'ACTIVE_ENFORCEMENT'
  where s.operation_code = v_execution.operation_code
    and s.required is true
    and s.active is true
    and coalesce(s.execution_order,0) < coalesce(v_step.execution_order,0)
    and (pb.clean_result_value is null or es.status <> pb.clean_result_value);

  if v_prior_missing > 0 or v_prior_bad > 0 then
    v_block_code := 'PRIOR_REQUIRED_STEP_NOT_CLEAN';
    v_block_details := jsonb_build_object('prior_missing',v_prior_missing,'prior_bad',v_prior_bad);
  end if;

  if v_block_code is null then
    for v_key in select jsonb_array_elements_text(v_binding.required_evidence_keys) loop
      if not (p_evidence_payload ? v_key)
         or p_evidence_payload->v_key is null
         or p_evidence_payload->v_key = 'null'::jsonb
         or (jsonb_typeof(p_evidence_payload->v_key) = 'string' and btrim(p_evidence_payload->>v_key) = '') then
        v_missing_keys := array_append(v_missing_keys,v_key);
      end if;
    end loop;
    if cardinality(v_missing_keys) > 0 then
      v_block_code := 'REQUIRED_EVIDENCE_MISSING';
      v_block_details := jsonb_build_object('missing_keys',to_jsonb(v_missing_keys));
    end if;
  end if;

  if v_block_code is null and p_evidence_payload ? 'blocking_codes' then
    if jsonb_typeof(p_evidence_payload->'blocking_codes') <> 'array' then
      v_block_code := 'BLOCKING_CODES_INVALID';
    else
      v_blocking_codes := p_evidence_payload->'blocking_codes';
      if jsonb_array_length(v_blocking_codes) > 0 then
        v_block_code := coalesce(v_contract.blocking_code,'STEP_BLOCKED');
        v_block_details := jsonb_build_object('caller_blocking_codes',v_blocking_codes);
      end if;
    end if;
  end if;

  -- Card Update: compare step-60 claims against the connector-derived capsule already
  -- persisted in the execution manifest. The provider-side requiredRevisionId remains
  -- a second independent guard before any Google Docs write.
  if v_block_code is null
     and v_execution.operation_code = 'ACTUALIZACION_CARD_LF'
     and p_step_id = 'pre_write_execution_binding_gate' then
    v_trust := v_execution.manifest->'connector_trust_context';
    if jsonb_typeof(v_trust) <> 'object' then
      v_block_code := 'CARD_UPDATE_CONNECTOR_TRUST_CONTEXT_MISSING';
      v_block_details := jsonb_build_object('reason','execution.manifest.connector_trust_context required');
    elsif v_trust->>'carrier_type' <> 'GOOGLE_DOC_EMBEDDED_BLOCK' then
      v_block_code := 'CARD_UPDATE_SERVER_TRUST_CARRIER_UNSUPPORTED';
      v_block_details := jsonb_build_object('observed_carrier_type',v_trust->>'carrier_type');
    elsif p_evidence_payload->>'execution_id' <> v_execution.execution_id
       or p_evidence_payload->>'card_code' <> v_execution.target_code
       or p_evidence_payload->>'trusted_context_ref' <> v_trust->>'trust_context_ref'
       or p_evidence_payload->>'carrier_type' <> v_trust->>'carrier_type'
       or p_evidence_payload->>'carrier_ref' <> v_trust->>'document_id'
       or p_evidence_payload->>'carrier_revision' <> v_trust->>'revision_id'
       or p_evidence_payload->>'block_anchor' <> v_trust->>'block_anchor'
       or v_trust->>'provider_guard' <> 'requiredRevisionId'
       or v_trust->>'provider_guard_value' <> v_trust->>'revision_id'
       or coalesce((p_evidence_payload->>'pre_write_gate_passed')::boolean,false) is not true then
      v_block_code := 'CARD_UPDATE_SERVER_TRUST_CONTEXT_MISMATCH';
      v_block_details := jsonb_build_object(
        'expected_card_code',v_execution.target_code,
        'expected_carrier_ref',v_trust->>'document_id',
        'expected_revision',v_trust->>'revision_id',
        'expected_block_anchor',v_trust->>'block_anchor',
        'submitted_revision',p_evidence_payload->>'carrier_revision'
      );
    end if;
  end if;

  -- RETIRE: derive target identity and incoming consumer count directly from Supabase.
  -- An incoming relation counts while its source asset is not archived. This reproduces
  -- the six relation-level consumers observed for ACT-0043 and zero for the positive profile canary.
  if v_block_code is null
     and v_execution.operation_code = 'RETIRO_ACTIVO_LF'
     and p_step_id = 'pre_write_execution_binding_gate' then
    select * into v_asset
    from public.lf_activos
    where codigo_activo = v_execution.target_code;

    if not found then
      v_block_code := 'RETIRE_SERVER_TARGET_NOT_FOUND';
      v_block_details := jsonb_build_object('target_code',v_execution.target_code);
    elsif v_asset.archived_at is not null then
      v_block_code := 'RETIRE_SERVER_TARGET_ALREADY_ARCHIVED';
      v_block_details := jsonb_build_object('archived_at',v_asset.archived_at,'archived_reason',v_asset.archived_reason);
    elsif v_asset.tipo_activo <> v_execution.target_type
       or v_asset.tipo_activo not in ('PERFIL','CARD','ADAPTER','SKILL') then
      v_block_code := 'RETIRE_SERVER_TARGET_TYPE_MISMATCH';
      v_block_details := jsonb_build_object('execution_target_type',v_execution.target_type,'asset_type',v_asset.tipo_activo);
    else
      select count(*),count(distinct r.codigo_activo)
        into v_server_consumer_count,v_server_distinct_consumer_count
      from public.lf_activo_relaciones r
      join public.lf_activos source_asset
        on source_asset.codigo_activo = r.codigo_activo
       and source_asset.archived_at is null
      where r.relacionado_codigo = v_execution.target_code;

      if p_evidence_payload->>'execution_id' <> v_execution.execution_id
         or p_evidence_payload->>'target_code' <> v_execution.target_code
         or p_evidence_payload->>'target_type' <> v_execution.target_type then
        v_block_code := 'RETIRE_SERVER_EXECUTION_BINDING_MISMATCH';
        v_block_details := jsonb_build_object('expected_target_code',v_execution.target_code,'expected_target_type',v_execution.target_type);
      elsif coalesce((p_evidence_payload->>'incoming_active_consumer_count')::integer,-1) <> v_server_consumer_count then
        v_block_code := 'RETIRE_SERVER_CONSUMER_COUNT_MISMATCH';
        v_block_details := jsonb_build_object('server_relation_count',v_server_consumer_count,'server_distinct_source_count',v_server_distinct_consumer_count,'submitted_count',p_evidence_payload->>'incoming_active_consumer_count');
      elsif v_server_consumer_count > 0 then
        v_block_code := 'RETIRE_SERVER_ACTIVE_INCOMING_CONSUMER';
        v_block_details := jsonb_build_object('server_relation_count',v_server_consumer_count,'server_distinct_source_count',v_server_distinct_consumer_count);
      elsif btrim(coalesce(p_evidence_payload->>'reason','')) = ''
         or btrim(coalesce(p_evidence_payload->>'write_plan','')) = ''
         or coalesce((p_evidence_payload->>'pre_write_gate_passed')::boolean,false) is not true then
        v_block_code := 'RETIRE_SERVER_PREWRITE_SCOPE_INVALID';
        v_block_details := jsonb_build_object('reason_required',true,'write_plan_required',true,'pre_write_gate_passed_required',true);
      end if;
    end if;
  end if;

  if v_block_code is not null then
    v_payload := p_evidence_payload;
    for v_key in select jsonb_array_elements_text(v_binding.required_evidence_keys) loop
      if not (v_payload ? v_key) then
        v_payload := v_payload || jsonb_build_object(v_key,null);
      end if;
    end loop;
    v_attempt_history := v_attempt_history || jsonb_build_array(
      jsonb_build_object('at',clock_timestamp(),'outcome','BLOCKED','code',v_block_code,'evidence_ref',p_evidence_ref,'details',v_block_details)
    );
    v_payload := v_payload || jsonb_build_object(
      'step_result',v_binding.blocked_result_value,
      'blocking_findings',jsonb_build_array(v_block_code),
      'blocking_codes',jsonb_build_array(v_block_code),
      'return_to_worker_reasons','[]'::jsonb,
      'assertions_checked',coalesce(v_payload->'assertions_checked','[]'::jsonb),
      'hard_fails_checked',coalesce(v_payload->'hard_fails_checked','[]'::jsonb),
      'blocked_by_recorder',true,
      'blocked_reason_code',v_block_code,
      'blocked_details',v_block_details,
      'server_incoming_active_consumer_count',case when v_execution.operation_code='RETIRO_ACTIVO_LF' then to_jsonb(v_server_consumer_count) else null end,
      'attempt_history',v_attempt_history,
      'mini_judge_code',v_binding.judge_code,
      'mini_judge_result',v_binding.blocked_result_value,
      'recorded_by_rpc','lf_record_asset_lifecycle_step_v1'
    );
    if v_existing_retryable then
      update public.lf_operation_execution_steps
      set status=v_binding.blocked_result_value,evidence_ref=p_evidence_ref,evidence_payload=v_payload,
          notes='Blocked attempt persisted transactionally; retry remains allowed on same row.',updated_by_execution_id=p_actor_execution_id,updated_at=now()
      where execution_id=p_execution_id and step_id=p_step_id;
    else
      insert into public.lf_operation_execution_steps(execution_id,step_order,step_id,status,evidence_ref,evidence_payload,notes,created_by_execution_id)
      values(p_execution_id,v_step.step_order,p_step_id,v_binding.blocked_result_value,p_evidence_ref,v_payload,
             'Blocked attempt persisted transactionally by governed asset lifecycle recorder.',p_actor_execution_id);
    end if;
    return jsonb_build_object(
      'outcome','BLOCKED','code',v_block_code,'durable',true,'execution_id',p_execution_id,
      'operation_code',v_execution.operation_code,'step_id',p_step_id,'status',v_binding.blocked_result_value,
      'retryable',true,'attempt_count',jsonb_array_length(v_attempt_history)
    ) || v_block_details;
  end if;

  v_payload := p_evidence_payload || jsonb_build_object(
    'step_result',v_binding.clean_result_value,
    'blocking_codes','[]'::jsonb,
    'blocking_findings','[]'::jsonb,
    'return_to_worker_reasons','[]'::jsonb,
    'server_incoming_active_consumer_count',case when v_execution.operation_code='RETIRO_ACTIVO_LF' then to_jsonb(v_server_consumer_count) else null end,
    'mini_judge_code',v_binding.judge_code,
    'mini_judge_result',v_binding.clean_result_value,
    'recorded_by_rpc','lf_record_asset_lifecycle_step_v1',
    'attempt_history',v_attempt_history
  );

  if v_existing_retryable then
    update public.lf_operation_execution_steps
    set status=v_binding.clean_result_value,evidence_ref=p_evidence_ref,evidence_payload=v_payload,
        notes='Clean retry accepted transactionally; prior blocked attempts preserved in attempt_history.',updated_by_execution_id=p_actor_execution_id,updated_at=now()
    where execution_id=p_execution_id and step_id=p_step_id;
  else
    insert into public.lf_operation_execution_steps(execution_id,step_order,step_id,status,evidence_ref,evidence_payload,notes,created_by_execution_id)
    values(p_execution_id,v_step.step_order,p_step_id,v_binding.clean_result_value,p_evidence_ref,v_payload,
           'Recorded transactionally by governed asset lifecycle operation recorder.',p_actor_execution_id);
  end if;

  return jsonb_build_object(
    'outcome','STEP_RECORDED','replay',false,'execution_id',p_execution_id,'operation_code',v_execution.operation_code,
    'step_id',p_step_id,'step_order',v_step.step_order,'execution_order',v_step.execution_order,
    'status',v_binding.clean_result_value,'mini_judge_code',v_binding.judge_code,'mini_judge_result',v_binding.clean_result_value,
    'next_gate',v_contract.next_if_pass,'resumed_from_blocked',v_existing_retryable,
    'prior_attempt_count',jsonb_array_length(v_attempt_history)
  );
end;
$function$;

revoke all on function public.lf_record_asset_lifecycle_step_v1(text,text,text,jsonb,text) from public;
revoke all on function public.lf_record_asset_lifecycle_step_v1(text,text,text,jsonb,text) from anon;
revoke all on function public.lf_record_asset_lifecycle_step_v1(text,text,text,jsonb,text) from authenticated;
grant execute on function public.lf_record_asset_lifecycle_step_v1(text,text,text,jsonb,text) to service_role;
