-- SADM-PP-L3-018 WAIVER_AUTHORITY source-only candidate.
-- DO NOT APPLY before canonical prerequisites are materialized and explicit DB apply is authorized.
-- Dedicated POST-PASE waiver storage; private.lf_event_validation_exemptions is never reused as closure authority.

begin;

do $pre$
begin
  if not exists(select 1 from public.lf_activos where codigo_activo='LF_GOVERNANCE' and archived_at is null) then raise exception 'BLOCK_WAIVER_AUTHORITY_LF_GOVERNANCE_NOT_MATERIALIZED'; end if;
  if not exists(select 1 from public.lf_activos where codigo_activo='CAPABILITY_EXECUTION_CONTRACT' and archived_at is null) then raise exception 'BLOCK_WAIVER_AUTHORITY_EXECUTION_CONTRACT_NOT_MATERIALIZED'; end if;
  if not exists(select 1 from public.lf_activos where codigo_activo='PLAN_AUTHORITY_DRIFT_GUARD' and archived_at is null) then raise exception 'BLOCK_WAIVER_AUTHORITY_PLAN_AUTHORITY_NOT_MATERIALIZED'; end if;
  if not exists(select 1 from public.lf_activos where codigo_activo='CURRENTNESS_AUTHORITY' and archived_at is null) then raise exception 'BLOCK_WAIVER_AUTHORITY_CURRENTNESS_NOT_MATERIALIZED'; end if;
  if not exists(select 1 from public.lf_activos where codigo_activo='AUTHORITY_READBACK' and archived_at is null) then raise exception 'BLOCK_WAIVER_AUTHORITY_APPROVAL_READBACK_NOT_MATERIALIZED'; end if;
  if exists(select 1 from public.lf_capability_registry where capability_code='WAIVER_AUTHORITY') then raise exception 'BLOCK_WAIVER_AUTHORITY_PREMATURE_EXECUTABLE_REGISTRATION'; end if;
end
$pre$;

create table if not exists private.lf_post_pase_waivers(
  waiver_id bigint generated by default as identity primary key,
  post_pase_execution_id text not null,
  control_id text not null,
  plan_digest text not null check(plan_digest ~ '^[0-9a-f]{64}$'),
  merge_sha text not null check(merge_sha ~ '^[0-9a-f]{40}$'),
  source_revision text not null check(source_revision ~ '^[0-9a-f]{40}$'),
  subject_ref text not null,
  rationale text not null,
  expires_at timestamptz not null,
  approval_event_id bigint not null,
  approval_authority text not null default 'LF_GOVERNANCE',
  created_by_execution_id text not null,
  created_at timestamptz not null default clock_timestamp(),
  max_uses integer not null default 1 check(max_uses=1),
  uses_count integer not null default 0 check(uses_count between 0 and 1),
  active boolean not null default true,
  grant_sha256 text not null check(grant_sha256 ~ '^[0-9a-f]{64}$'),
  consumed_at timestamptz,
  consumed_by_execution_id text,
  consumed_by_request_digest text check(consumed_by_request_digest is null or consumed_by_request_digest ~ '^[0-9a-f]{64}$')
);
revoke all on private.lf_post_pase_waivers from public,anon,authenticated;

create or replace function private.fn_lf_post_pase_waiver_hash_v1(
  p_post_pase_execution_id text,p_control_id text,p_plan_digest text,p_merge_sha text,
  p_source_revision text,p_subject_ref text,p_rationale text,p_expires_at timestamptz,
  p_approval_event_id bigint,p_max_uses integer
) returns text language sql immutable set search_path to 'pg_catalog','extensions' as $$
  select encode(extensions.digest(convert_to(
    coalesce(p_post_pase_execution_id,'')||E'\n'||coalesce(p_control_id,'')||E'\n'||
    coalesce(p_plan_digest,'')||E'\n'||coalesce(p_merge_sha,'')||E'\n'||
    coalesce(p_source_revision,'')||E'\n'||coalesce(p_subject_ref,'')||E'\n'||
    coalesce(p_rationale,'')||E'\n'||coalesce(p_expires_at::text,'')||E'\n'||
    coalesce(p_approval_event_id::text,'')||E'\n'||coalesce(p_max_uses::text,'0'),'UTF8'),'sha256'),'hex');
$$;

create or replace function private.fn_lf_post_pase_waiver_json_digest_v1(p_payload jsonb)
returns text language sql immutable set search_path to 'pg_catalog','extensions' as $$
  select encode(extensions.digest(convert_to(coalesce(p_payload,'{}'::jsonb)::text,'UTF8'),'sha256'),'hex');
$$;

create or replace function private.fn_issue_lf_post_pase_waiver_v1(
  p_post_pase_execution_id text,p_control_id text,p_plan_digest text,p_merge_sha text,
  p_source_revision text,p_subject_ref text,p_rationale text,p_expires_at timestamptz,
  p_approval_event_id bigint,p_execution_id text
) returns bigint language plpgsql security definer set search_path to 'pg_catalog','public','private' as $$
declare v_hash text; v_id bigint;
begin
  if nullif(btrim(coalesce(p_execution_id,'')),'') is null
     or nullif(btrim(coalesce(p_post_pase_execution_id,'')),'') is null
     or nullif(btrim(coalesce(p_control_id,'')),'') is null
     or nullif(btrim(coalesce(p_subject_ref,'')),'') is null
     or coalesce(p_plan_digest,'') !~ '^[0-9a-f]{64}$'
     or coalesce(p_merge_sha,'') !~ '^[0-9a-f]{40}$'
     or coalesce(p_source_revision,'') !~ '^[0-9a-f]{40}$'
     or length(btrim(coalesce(p_rationale,'')))<20
     or p_expires_at<=clock_timestamp() or p_expires_at>clock_timestamp()+interval '1 hour'
     or coalesce(p_approval_event_id,0)<=0 then
    raise exception 'BLOCK_POST_PASE_WAIVER_ISSUE_INPUT_INVALID';
  end if;
  v_hash:=private.fn_lf_post_pase_waiver_hash_v1(p_post_pase_execution_id,p_control_id,p_plan_digest,p_merge_sha,p_source_revision,p_subject_ref,p_rationale,p_expires_at,p_approval_event_id,1);
  if not exists(
    select 1 from public.lf_eventos e
    where e.id=p_approval_event_id and e.evento_tipo='POST_PASE_WAIVER_APPROVED'
      and e.payload->>'evidence_schema_version'='post-pase-waiver-governance/v1'
      and e.payload->>'decision'='APPROVED' and e.payload->>'approval_authority'='LF_GOVERNANCE'
      and e.payload->>'post_pase_execution_id'=p_post_pase_execution_id
      and e.payload->>'control_id'=p_control_id and e.payload->>'plan_digest'=p_plan_digest
      and e.payload->>'merge_sha'=p_merge_sha and e.payload->>'source_revision'=p_source_revision
      and e.payload->>'subject_ref'=p_subject_ref and e.payload->>'grant_sha256'=v_hash
      and e.created_by_execution_id=p_execution_id
  ) then raise exception 'BLOCK_POST_PASE_WAIVER_APPROVAL_MISSING_OR_MISMATCHED'; end if;
  insert into private.lf_post_pase_waivers(
    post_pase_execution_id,control_id,plan_digest,merge_sha,source_revision,subject_ref,rationale,
    expires_at,approval_event_id,approval_authority,created_by_execution_id,max_uses,uses_count,active,grant_sha256
  ) values (
    p_post_pase_execution_id,p_control_id,p_plan_digest,p_merge_sha,p_source_revision,p_subject_ref,p_rationale,
    p_expires_at,p_approval_event_id,'LF_GOVERNANCE',p_execution_id,1,0,true,v_hash
  ) returning waiver_id into v_id;
  return v_id;
end
$$;

create or replace function private.fn_read_lf_post_pase_waiver_v1(
  p_waiver_id bigint,p_post_pase_execution_id text,p_control_id text,p_plan_digest text,
  p_merge_sha text,p_source_revision text,p_subject_ref text
) returns jsonb language plpgsql stable set search_path to 'pg_catalog','private' as $$
declare w private.lf_post_pase_waivers%rowtype; v_scope jsonb; v_out jsonb; v_current boolean;
begin
  select * into w from private.lf_post_pase_waivers where waiver_id=p_waiver_id;
  if not found then return jsonb_build_object('schema_version','LF_POST_PASE_WAIVER_GRANT_READBACK_V1','authority_layer','WAIVER_AUTHORITY_STORE','decision','WAIVER_GRANT_BLOCKED','ready',false,'waiver_id',p_waiver_id,'reason','WAIVER_NOT_FOUND'); end if;
  v_scope:=jsonb_build_object('post_pase_execution_id',w.post_pase_execution_id,'control_id',w.control_id,'plan_digest',w.plan_digest,'merge_sha',w.merge_sha,'source_revision',w.source_revision,'subject_ref',w.subject_ref);
  v_current:=w.active and w.uses_count=0 and w.max_uses=1 and w.consumed_at is null and w.expires_at>clock_timestamp()
    and w.post_pase_execution_id=p_post_pase_execution_id and w.control_id=p_control_id and w.plan_digest=p_plan_digest
    and w.merge_sha=p_merge_sha and w.source_revision=p_source_revision and w.subject_ref=p_subject_ref
    and w.grant_sha256=private.fn_lf_post_pase_waiver_hash_v1(w.post_pase_execution_id,w.control_id,w.plan_digest,w.merge_sha,w.source_revision,w.subject_ref,w.rationale,w.expires_at,w.approval_event_id,w.max_uses);
  v_out:=jsonb_build_object(
    'schema_version','LF_POST_PASE_WAIVER_GRANT_READBACK_V1','authority_layer','WAIVER_AUTHORITY_STORE',
    'decision',case when v_current then 'WAIVER_GRANT_CURRENT' else 'WAIVER_GRANT_BLOCKED' end,'ready',v_current,
    'waiver_id',w.waiver_id,'scope',v_scope,'approval_authority',w.approval_authority,'approval_decision','APPROVED',
    'approval_event_id',w.approval_event_id,'max_uses',w.max_uses,'uses_count',w.uses_count,'active',w.active,
    'consumed_at',w.consumed_at,'rationale',w.rationale,'grant_sha256',w.grant_sha256,'expires_at',w.expires_at);
  return v_out||jsonb_build_object('readback_digest',private.fn_lf_post_pase_waiver_json_digest_v1(v_out));
end
$$;

create or replace function private.fn_consume_lf_post_pase_waiver_v1(
  p_waiver_id bigint,p_post_pase_execution_id text,p_control_id text,p_plan_digest text,
  p_merge_sha text,p_source_revision text,p_subject_ref text,p_consumer_execution_id text,p_request_digest text
) returns jsonb language plpgsql security definer set search_path to 'pg_catalog','private' as $$
declare w private.lf_post_pase_waivers%rowtype; v_scope jsonb; v_out jsonb;
begin
  if nullif(btrim(coalesce(p_consumer_execution_id,'')),'') is null or coalesce(p_request_digest,'') !~ '^[0-9a-f]{64}$' then raise exception 'BLOCK_POST_PASE_WAIVER_CONSUME_INPUT_INVALID'; end if;
  update private.lf_post_pase_waivers
  set uses_count=1,active=false,consumed_at=clock_timestamp(),consumed_by_execution_id=p_consumer_execution_id,consumed_by_request_digest=p_request_digest
  where waiver_id=p_waiver_id and post_pase_execution_id=p_post_pase_execution_id and control_id=p_control_id
    and plan_digest=p_plan_digest and merge_sha=p_merge_sha and source_revision=p_source_revision and subject_ref=p_subject_ref
    and max_uses=1 and uses_count=0 and active and consumed_at is null and expires_at>clock_timestamp()
  returning * into w;
  if not found then return jsonb_build_object('schema_version','LF_POST_PASE_WAIVER_CONSUMPTION_READBACK_V1','authority_layer','WAIVER_AUTHORITY_STORE','decision','WAIVER_NOT_CONSUMED','ready',false,'waiver_id',p_waiver_id,'reason','MISSING_EXPIRED_SCOPE_MISMATCH_OR_REPLAY'); end if;
  v_scope:=jsonb_build_object('post_pase_execution_id',w.post_pase_execution_id,'control_id',w.control_id,'plan_digest',w.plan_digest,'merge_sha',w.merge_sha,'source_revision',w.source_revision,'subject_ref',w.subject_ref);
  v_out:=jsonb_build_object(
    'schema_version','LF_POST_PASE_WAIVER_CONSUMPTION_READBACK_V1','authority_layer','WAIVER_AUTHORITY_STORE',
    'decision','WAIVER_CONSUMED','ready',true,'waiver_id',w.waiver_id,'scope',v_scope,
    'max_uses',w.max_uses,'uses_count',w.uses_count,'active',w.active,'consumed_at',w.consumed_at,
    'consumed_by_execution_id',w.consumed_by_execution_id,'consumed_by_request_digest',w.consumed_by_request_digest,'grant_sha256',w.grant_sha256);
  return v_out||jsonb_build_object('readback_digest',private.fn_lf_post_pase_waiver_json_digest_v1(v_out));
end
$$;

revoke all on function private.fn_issue_lf_post_pase_waiver_v1(text,text,text,text,text,text,text,timestamptz,bigint,text) from public,anon,authenticated;
revoke all on function private.fn_consume_lf_post_pase_waiver_v1(bigint,text,text,text,text,text,text,text,text) from public,anon,authenticated;

insert into public.lf_activos(
  codigo_activo,nombre_canonico,tipo_activo,subtipo_activo,formato_nativo,estado_original,estado_documental,
  estado_operativo,impacto_automatico,version,ruta_esperada,owner_name,source_spreadsheet_id,source_spreadsheet_title,
  source_sheet_name,source_row_number,raw_payload,metadata,migration_batch_id,created_by_execution_id,updated_by_execution_id
) values (
  'WAIVER_AUTHORITY','TRANSVERSAL_POST_PASE_WAIVER_AUTHORITY','CAPABILITY','TRANSVERSAL_ONE_USE_WAIVER_AUTHORITY',
  'GITHUB_CONTRACT','CANDIDATE_READ_ONLY','CANDIDATO','READ_ONLY','BLOQUEADO','1.0.0-candidate',
  'sandbox/lf_contract_gate_test/waiver_authority/README.md','LF_GOVERNANCE','NATIVE_SUPABASE','LF_TRANSVERSAL_CAPABILITY_INVENTORY','WAIVER_AUTHORITY_20261001',1,
  jsonb_build_object('solution_code','WAIVER_AUTHORITY_V1','work_code','SADM-PP-L3-018','store','private.lf_post_pase_waivers','max_uses',1,'max_ttl','PT1H','event_validation_exemption_store_reused',false,'supabase_applied',false,'cutover_authorized',false,'runtime_authorized',false,'production_authorized',false),
  jsonb_build_object('schema_version','WAIVER_AUTHORITY_ASSET_METADATA_V1','approval_authority','LF_GOVERNANCE','entry_guard','ORCHESTRATOR_EXECUTION_GUARD_V1','closure_status_owner','CLOSURE_GATE','waived_decision_forbidden',true,'anti_replay','ATOMIC_CONSUME_BEFORE_AUTHORIZATION_RECEIPT'),
  '8c1d2f6c-4a1c-4f80-9d3d-018000000001'::uuid,'EXEC-WAIVER-AUTHORITY-SOURCE-PROJECTION-V1','EXEC-WAIVER-AUTHORITY-SOURCE-PROJECTION-V1'
) on conflict(codigo_activo) do nothing;

insert into public.lf_activo_relaciones(codigo_activo,relacionado_codigo,relacion_tipo,valor_original,fuente,migration_batch_id,created_by_execution_id,updated_by_execution_id) values
 ('WAIVER_AUTHORITY','LF_GOVERNANCE','RELACIONADO_CAPACIDADES','administrative owner and approval authority','sandbox/lf_contract_gate_test/waiver_authority/waiver_authority_v1.json','8c1d2f6c-4a1c-4f80-9d3d-018000000001'::uuid,'EXEC-WAIVER-AUTHORITY-SOURCE-PROJECTION-V1','EXEC-WAIVER-AUTHORITY-SOURCE-PROJECTION-V1'),
 ('WAIVER_AUTHORITY','CAPABILITY_EXECUTION_CONTRACT','DEPENDE_DE','orchestrated request envelope','sandbox/lf_contract_gate_test/waiver_authority/waiver_authority_v1.json','8c1d2f6c-4a1c-4f80-9d3d-018000000001'::uuid,'EXEC-WAIVER-AUTHORITY-SOURCE-PROJECTION-V1','EXEC-WAIVER-AUTHORITY-SOURCE-PROJECTION-V1'),
 ('WAIVER_AUTHORITY','PLAN_AUTHORITY_DRIFT_GUARD','DEPENDE_DE','plan digest authority','sandbox/lf_contract_gate_test/waiver_authority/waiver_authority_v1.json','8c1d2f6c-4a1c-4f80-9d3d-018000000001'::uuid,'EXEC-WAIVER-AUTHORITY-SOURCE-PROJECTION-V1','EXEC-WAIVER-AUTHORITY-SOURCE-PROJECTION-V1'),
 ('WAIVER_AUTHORITY','CURRENTNESS_AUTHORITY','DEPENDE_DE','source revision authority','sandbox/lf_contract_gate_test/waiver_authority/waiver_authority_v1.json','8c1d2f6c-4a1c-4f80-9d3d-018000000001'::uuid,'EXEC-WAIVER-AUTHORITY-SOURCE-PROJECTION-V1','EXEC-WAIVER-AUTHORITY-SOURCE-PROJECTION-V1'),
 ('WAIVER_AUTHORITY','AUTHORITY_READBACK','DEPENDE_DE','approval readback boundary','sandbox/lf_contract_gate_test/waiver_authority/waiver_authority_v1.json','8c1d2f6c-4a1c-4f80-9d3d-018000000001'::uuid,'EXEC-WAIVER-AUTHORITY-SOURCE-PROJECTION-V1','EXEC-WAIVER-AUTHORITY-SOURCE-PROJECTION-V1'),
 ('WAIVER_AUTHORITY','VALIDATION_EXEMPTION_ONE_USE','RELACIONADO_CAPACIDADES','pattern provenance only; semantic/store reuse forbidden','sandbox/lf_contract_gate_test/waiver_authority/waiver_authority_inventory_v1.json','8c1d2f6c-4a1c-4f80-9d3d-018000000001'::uuid,'EXEC-WAIVER-AUTHORITY-SOURCE-PROJECTION-V1','EXEC-WAIVER-AUTHORITY-SOURCE-PROJECTION-V1')
on conflict do nothing;

commit;
