\set ON_ERROR_STOP on

-- Synthetic, data-free V3-V6 boundary for exercising the V7 source package.
-- Run as lf_ci_cluster_admin in a disposable PostgreSQL 17 database.

create role anon nologin noinherit;
create role authenticated nologin noinherit;
create role service_role nologin noinherit;
create role lf_governance_owner_v3 nologin noinherit nobypassrls;

-- Model the managed grantor: it must retain ADMIN OPTION for the membership
-- edge it grants to postgres to remain attributable and independently revocable.
grant lf_governance_owner_v3 to lf_ci_cluster_admin
  with admin true, inherit false, set false;

grant lf_governance_owner_v3 to postgres
  with admin true, inherit false, set false
  granted by lf_ci_cluster_admin;

create schema private authorization postgres;
create schema vault authorization postgres;
create schema extensions authorization postgres;

create extension pgcrypto with schema extensions;

grant usage on schema private, vault, extensions to postgres;
grant usage, create on schema private, public to lf_governance_owner_v3;

create table vault.decrypted_secrets (
  name text,
  decrypted_secret text
);
alter table vault.decrypted_secrets owner to postgres;

create table private.lf_architecture_alerts_v4 (
  id bigint generated by default as identity primary key,
  alert_key text,
  alert_type text,
  severity text,
  state text,
  subject text,
  details jsonb,
  fingerprint_sha256 text,
  source_observed_at timestamptz,
  created_by_execution_id text,
  created_at timestamptz
);

create table private.lf_architecture_delivery_secrets_v4 (
  secret_id smallint primary key,
  secret_key bytea,
  created_by_execution_id text,
  rotated_at timestamptz,
  is_active boolean,
  not_before timestamptz,
  not_after timestamptz
);

create table private.lf_architecture_monitor_runs_v4 (
  id bigint generated by default as identity primary key,
  execution_id text,
  status text,
  state_sha256 text,
  metrics jsonb,
  error_sqlstate text,
  error_message text,
  started_at timestamptz,
  completed_at timestamptz
);

create table private.lf_architecture_notification_attempts_v4 (
  id bigint generated by default as identity primary key,
  outbox_id bigint,
  request_id bigint,
  endpoint text,
  attempt_status text,
  request_signature text,
  request_body_sha256 text,
  error_message text,
  created_by_execution_id text,
  created_at timestamptz,
  completed_at timestamptz,
  success boolean,
  http_status integer,
  response_body_sha256 text,
  receipt_id bigint,
  completion_source text,
  delivery_schema_version text,
  signature_issued_at timestamptz,
  signature_nonce uuid,
  secret_version smallint,
  receiver_received_at timestamptz,
  receiver_receipt_id bigint,
  receiver_response_status integer,
  dispatcher_observed_http_status integer,
  dispatcher_response_body_sha256 text
);

create table private.lf_architecture_notification_outbox_v4 (
  id bigint generated by default as identity primary key,
  alert_id bigint,
  channel text,
  payload jsonb,
  payload_sha256 text,
  created_by_execution_id text,
  created_at timestamptz
);

create table private.lf_architecture_notification_receipts_v4 (
  id bigint generated by default as identity primary key,
  outbox_id bigint,
  receipt_status text,
  http_status integer,
  payload_sha256 text,
  response_sha256 text,
  details jsonb,
  received_by_execution_id text,
  received_at timestamptz,
  attempt_id bigint,
  delivery_schema_version text,
  signature_nonce uuid,
  secret_version smallint,
  receiver_response_status integer
);

create table private.lf_artifact_inventory_baseline_v3 (
  artifact_id bigint,
  skill_code text,
  artifact_code text,
  relative_path text,
  artifact_type text,
  baseline_version integer,
  baseline_content_sha256 text,
  required_for_closure boolean,
  baseline_execution_id text,
  baselined_at timestamptz
);

create table private.lf_edge_function_deployment_evidence_v6 (
  function_slug text,
  deployed_version integer,
  deployment_sha256 text,
  verify_jwt boolean,
  authentication_mode text,
  verification_source text,
  verified_by_execution_id text,
  verified_at timestamptz
);

create table private.lf_event_contract_provenance_overlay_v4 (
  event_type text,
  contract_version integer,
  contract_sha256 text,
  contract_snapshot jsonb,
  approval_event_id bigint,
  correction_reason text,
  recorded_by_execution_id text,
  recorded_at timestamptz
);

create table private.lf_gate_test_runs_v3 (
  id bigint generated by default as identity primary key,
  test_code text,
  artifact_id bigint,
  gate_code text,
  test_kind text,
  target_relation text,
  probe_preimage jsonb,
  probe_sha256 text,
  expected_outcome jsonb,
  observed_outcome jsonb,
  persisted_effects jsonb,
  persisted_effects_sha256 text,
  passed boolean,
  runner_type text,
  runner_identity text,
  source_workflow_run_id bigint,
  source_commit_sha text,
  evidence_event_id bigint,
  executed_by_execution_id text,
  executed_at timestamptz,
  verified_at timestamptz,
  writer_authentication text,
  writer_signature_sha256 text
);

create table private.lf_github_reconciliation_runs_v3 (
  id bigint generated by default as identity primary key,
  artifact_id bigint,
  repository text,
  target_branch text,
  artifact_path text,
  pr_number integer,
  pr_state text,
  merged boolean,
  merge_commit_sha text,
  workflow_run_id bigint,
  workflow_name text,
  workflow_event text,
  workflow_head_sha text,
  workflow_conclusion text,
  artifact_git_blob text,
  artifact_sha256 text,
  file_touched_by_merge boolean,
  branch_protection_status text,
  result text,
  authoritative boolean,
  failure_reasons jsonb,
  details jsonb,
  verification_payload_sha256 text,
  source_external_event_id bigint,
  evidence_event_id bigint,
  reconciled_by_execution_id text,
  observed_at timestamptz,
  reconciled_at timestamptz,
  artifact_exercised_by_workflow boolean,
  audit_artifact_name text,
  audit_manifest_sha256 text,
  writer_authentication text,
  writer_signature_sha256 text
);

create table private.lf_legacy_event_quarantine_v4 (
  event_id bigint,
  event_type text,
  assessment_status text,
  evidence_schema_version text,
  payload_sha256 text,
  cutoff_group text,
  quarantine_reason text,
  quarantined_by_execution_id text,
  quarantined_at timestamptz
);

create table private.lf_reconciliation_writer_nonces_v6 (
  nonce_sha256 text,
  proof_scope text,
  preimage_sha256 text,
  expires_at timestamptz,
  consumed_at timestamptz,
  request_role text
);

create table private.lf_schema_fingerprint_baseline_v4 (
  object_identity text,
  object_type text,
  definition_sha256 text,
  definition_snapshot text,
  baseline_execution_id text,
  baselined_at timestamptz
);

create table private.lf_skill_artifacts (
  id bigint generated by default as identity primary key,
  skill_code text,
  artifact_code text,
  relative_path text,
  artifact_type text,
  version integer,
  is_current boolean,
  content text,
  content_sha256 text,
  source_refs jsonb,
  classification text,
  artifact_status text,
  dependencies jsonb,
  validation_status text,
  validation_evidence jsonb,
  in_enumerated_inventory boolean,
  created_by_execution_id text,
  created_at timestamptz,
  updated_by_execution_id text,
  updated_at timestamptz
);

create table public.lf_eventos (
  id bigint generated by default as identity primary key,
  evento_tipo text,
  entidad_tipo text,
  entidad_codigo text,
  descripcion text,
  severidad text default 'INFO',
  payload jsonb default '{}'::jsonb,
  origen text default 'RUNTIME_CI_FIXTURE',
  migration_batch_id uuid,
  created_at timestamptz default clock_timestamp(),
  created_by_execution_id text,
  updated_by_execution_id text,
  updated_at timestamptz
);

alter table private.lf_artifact_inventory_baseline_v3 owner to lf_governance_owner_v3;
alter table private.lf_gate_test_runs_v3 owner to lf_governance_owner_v3;
alter table private.lf_github_reconciliation_runs_v3 owner to lf_governance_owner_v3;
alter table private.lf_skill_artifacts owner to lf_governance_owner_v3;

create or replace function private.fn_guard_governed_relation_v3()
returns trigger
language plpgsql
set search_path to 'pg_catalog'
as $function$
begin
  if current_user <> 'lf_governance_owner_v3' then
    raise exception using
      errcode='42501',
      message=format(
        'governed relation %I.%I only accepts writes through an authorized v3 writer',
        tg_table_schema,
        tg_table_name
      );
  end if;
  if tg_argv[0]='APPEND_ONLY' and tg_op in ('UPDATE','DELETE') then
    raise exception using
      errcode='55000',
      message=format('%I.%I is append-only',tg_table_schema,tg_table_name);
  end if;
  if tg_op='DELETE' then return old; end if;
  return new;
end
$function$;
alter function private.fn_guard_governed_relation_v3()
  owner to lf_governance_owner_v3;

create or replace function private.fn_lf_dependency_array(p_dependencies jsonb)
returns jsonb
language sql
immutable
set search_path to 'pg_catalog'
as $function$
  select case jsonb_typeof(p_dependencies)
    when 'array' then p_dependencies
    when 'object' then coalesce(p_dependencies->'referencia_a','[]'::jsonb)
    else '[]'::jsonb
  end
$function$;
alter function private.fn_lf_dependency_array(jsonb) owner to postgres;

create or replace function private.fn_lf_try_timestamptz(p_value text)
returns timestamptz
language plpgsql
stable
set search_path to 'pg_catalog'
as $function$
begin
  if nullif(btrim(coalesce(p_value,'')),'') is null then return null; end if;
  return p_value::timestamptz;
exception when others then
  return null;
end
$function$;
alter function private.fn_lf_try_timestamptz(text) owner to postgres;

create or replace function public.record_external_ci_verification_v5(jsonb,text,text,text)
returns bigint language sql as 'select null::bigint';
alter function public.record_external_ci_verification_v5(jsonb,text,text,text)
  owner to lf_governance_owner_v3;

create or replace function public.record_lf_gate_test_v5(jsonb,text,text,text)
returns bigint language sql as 'select null::bigint';
alter function public.record_lf_gate_test_v5(jsonb,text,text,text)
  owner to lf_governance_owner_v3;

create or replace function public.record_external_ci_verification_v6(jsonb,text,text,text)
returns bigint language sql as 'select null::bigint';
alter function public.record_external_ci_verification_v6(jsonb,text,text,text)
  owner to postgres;

create or replace function public.record_lf_gate_test_v6(jsonb,text,text,text)
returns bigint language sql as 'select null::bigint';
alter function public.record_lf_gate_test_v6(jsonb,text,text,text)
  owner to postgres;

create or replace function public.promote_lf_artifact_pass_v3(bigint,bigint,bigint[],text)
returns boolean language sql as 'select false';
alter function public.promote_lf_artifact_pass_v3(bigint,bigint,bigint[],text)
  owner to lf_governance_owner_v3;

create or replace view public.v_lf_architecture_closure_v7
with (security_invoker=true)
as
select
  clock_timestamp() as computed_at,
  0::bigint as artifact_count,
  0::bigint as pass_v3_count,
  0::bigint as inventory_integrity_gaps,
  0::bigint as judge_count,
  0::bigint as judges_pass_v3,
  0::bigint as reconciliation_count,
  0::bigint as ci_artifacts_exercised,
  0::bigint as branch_protection_gaps,
  0::bigint as github_pass_count,
  0::bigint as latest_gate_tests,
  0::bigint as passed_gate_tests,
  0::bigint as failed_gate_tests,
  0::bigint as provenance_gaps,
  0::bigint as nonconforming_events,
  0::bigint as quarantined_events,
  0::bigint as quarantined_acceptance_references,
  true as quarantine_control_complete,
  0::bigint as baseline_objects,
  0::bigint as schema_drift_gaps,
  0::bigint as external_notifications,
  0::bigint as delivered_notifications,
  0::bigint as unresolved_notifications,
  0::bigint as unmigrated_legacy_notifications,
  null::text as latest_monitor_status,
  null::timestamptz as latest_monitor_at,
  0::bigint as active_exemptions,
  0::bigint as typed_schema_registry_gaps,
  0::bigint as open_findings,
  0::bigint as unresolved_internal_findings,
  0::bigint as blocking_capabilities,
  false as internal_control_ready,
  0::integer as external_blocker_count,
  '{}'::jsonb as residual_observations,
  false as closure_ready,
  'NOT_READY'::text as computed_closure_status;
alter view public.v_lf_architecture_closure_v7 owner to postgres;

revoke create on schema private, public from lf_governance_owner_v3;

-- Match the managed Supabase postgres boundary: role administration without
-- superuser or BYPASSRLS. All V7 source migrations run after this statement.
alter role postgres with
  nosuperuser createrole createdb login inherit nobypassrls;
