-- S30 / LF Assurance Method V1 — source-first completion for Workflow + Strategy Router.
-- Existing assurance tables are append-only; v2 rows supersede incomplete v1 provenance without UPDATE/DELETE.
-- Governed execution: EXEC-S30-LF-ASSURANCE-METHOD-V1-BASELINE-20260916-001
-- No assurance evaluation is executed by this migration.

DO $pre$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM public.lf_operation_execution
    WHERE execution_id='EXEC-S30-LF-ASSURANCE-METHOD-V1-BASELINE-20260916-001'
      AND operation_code='ACTUALIZACION_ESTRATEGIA_LF'
      AND target_type='STRATEGY'
      AND target_code='LF_OPERATING_CONSTITUTION_POLICY_AUTONOMOUS_OPERATIONS_20260906'
      AND status='IN_PROGRESS'
  ) THEN RAISE EXCEPTION 'LF_ASSURANCE_S30_GOVERNED_EXECUTION_MISSING'; END IF;
  IF EXISTS (SELECT 1 FROM public.lf_assurance_evaluations) THEN
    RAISE EXCEPTION 'LF_ASSURANCE_PRODUCTIVE_EVALUATION_ALREADY_EXISTS';
  END IF;
END $pre$;

INSERT INTO public.lf_assurance_obligation_catalog
(obligation_code,version,claim_code,claim_version,requirement_ref,implementation_ref,condition_ref,verification_method,positive_test_ref,negative_test_ref,adversarial_test_ref,structural_coverage_mode,evidence_contract,failure_taxonomy_code,required,status,source_ref,created_by_execution_id)
VALUES
('WF-DIAG-TEST-IDENTITY-V1',2,'WF_DIAGNOSTIC_COMPLETE_V1',1,'test identity','github://.github/workflows/validate-lf-packs.yml#validate-lf-packs','failure => exact workflow/job/step/script/test identity','TEST','github://validate-lf-packs/known-failing-test','github://validate-lf-packs/missing-test-identity','github://validate-lf-packs/same-rc-multiple-tests','BRANCH','{"required_fields":["workflow_run_id","job_id","step","script_or_command","test_file","test_case_or_check_id","source_sha"],"durable_evidence_required":true}'::jsonb,'OBSERVABILITY_GAP',true,'CANDIDATO','github://cristhianlujan/claude-persona-lf-patch/supabase/source_plans/s30_assurance_method_v1_workflow_router_completion.sql','EXEC-S30-LF-ASSURANCE-METHOD-V1-BASELINE-20260916-001'),
('WF-DIAG-ASSERTION-V1',2,'WF_DIAGNOSTIC_COMPLETE_V1',1,'assertion/error','github://.github/workflows/validate-lf-packs.yml#validate-lf-packs','failure => exact assertion or error class/message','TEST','github://validate-lf-packs/assertion-failure','github://validate-lf-packs/assertion-missing','github://validate-lf-packs/stdout-lost','CONDITION','{"required_fields":["error_class","assertion_or_error","rc","test_case_or_check_id"],"durable_evidence_required":true}'::jsonb,'EVIDENCE_NOT_DURABLE',true,'CANDIDATO','github://cristhianlujan/claude-persona-lf-patch/supabase/source_plans/s30_assurance_method_v1_workflow_router_completion.sql','EXEC-S30-LF-ASSURANCE-METHOD-V1-BASELINE-20260916-001'),
('WF-DIAG-DURABLE-V1',2,'WF_DIAGNOSTIC_COMPLETE_V1',1,'durable artifact','github://.github/workflows/validate-lf-packs.yml#validate-lf-packs','failure => durable artifact or canonical LF evidence row survives runner/log loss','DEMONSTRATION','github://validate-lf-packs/durable-artifact-retrievable','github://validate-lf-packs/ephemeral-only-evidence','github://validate-lf-packs/artifact-loss','CONDITION','{"required_fields":["durable_ref","sha256_or_integrity_ref","retention_or_canonical_store","correlation"],"ephemeral_stdout_insufficient":true}'::jsonb,'EVIDENCE_NOT_DURABLE',true,'CANDIDATO','github://cristhianlujan/claude-persona-lf-patch/supabase/source_plans/s30_assurance_method_v1_workflow_router_completion.sql','EXEC-S30-LF-ASSURANCE-METHOD-V1-BASELINE-20260916-001'),
('WF-DIAG-EXPECTED-ACTUAL-V1',1,'WF_DIAGNOSTIC_COMPLETE_V1',1,'expected/actual','github://.github/workflows/validate-lf-packs.yml#validate-lf-packs','assertion/gate failure => expected and actual values independently recoverable','TEST','github://validate-lf-packs/expected-actual-present','github://validate-lf-packs/expected-or-actual-missing','github://validate-lf-packs/ambiguous-shared-rc','CONDITION','{"required_fields":["expected","actual","operator_or_condition","assertion_or_error"],"durable_evidence_required":true}'::jsonb,'EVIDENCE_WEAK',true,'CANDIDATO','github://cristhianlujan/claude-persona-lf-patch/supabase/source_plans/s30_assurance_method_v1_workflow_router_completion.sql','EXEC-S30-LF-ASSURANCE-METHOD-V1-BASELINE-20260916-001'),
('WF-DIAG-CORRELATION-V1',1,'WF_DIAGNOSTIC_COMPLETE_V1',1,'correlation','github://.github/workflows/validate-lf-packs.yml#validate-lf-packs','failure evidence => workflow run/job/step/source/test/evidence share one correlation chain','TEST','github://validate-lf-packs/correlation-chain-valid','github://validate-lf-packs/orphan-artifact','github://validate-lf-packs/cross-run-artifact-reuse','MC_DC_LIKE','{"required_fields":["workflow_run_id","job_id","step","source_sha","test_case_or_check_id","durable_ref","correlation_id"],"cross_run_reuse_forbidden":true}'::jsonb,'TRACEABILITY_BROKEN',true,'CANDIDATO','github://cristhianlujan/claude-persona-lf-patch/supabase/source_plans/s30_assurance_method_v1_workflow_router_completion.sql','EXEC-S30-LF-ASSURANCE-METHOD-V1-BASELINE-20260916-001'),
('WF-DIAG-OWNER-REPAIR-RESUME-V1',1,'WF_DIAGNOSTIC_COMPLETE_V1',1,'owner/repair/resume','github://.github/workflows/validate-lf-packs.yml#validate-lf-packs','localized failure => exact owner, repair target and resume checkpoint are durable','DEMONSTRATION','github://validate-lf-packs/owner-repair-resume-present','github://validate-lf-packs/owner-or-resume-missing','github://validate-lf-packs/wrong-owner-routing','CONDITION','{"required_fields":["owner","repair_target","first_bad_step","resume_checkpoint","rerun_scope"],"full_restart_not_default":true}'::jsonb,'OBSERVABILITY_GAP',true,'CANDIDATO','github://cristhianlujan/claude-persona-lf-patch/supabase/source_plans/s30_assurance_method_v1_workflow_router_completion.sql','EXEC-S30-LF-ASSURANCE-METHOD-V1-BASELINE-20260916-001'),

('ROUTER-EXEC-BIND-V1',2,'STRATEGY_ROUTER_AUTHENTIC_V1',1,'execution binding','supabase://public/lf_router_resolve_v1','receipt.execution_id = governed execution.execution_id','TEST','supabase://router-assurance/same-execution','supabase://router-assurance/other-execution','supabase://router-assurance/replayed-valid-receipt','MC_DC_LIKE','{"required_fields":["execution_id","route_receipt","producer_ref"],"expected_actual_required":true,"zero_effect_on_fail":true}'::jsonb,'TRACEABILITY_BROKEN',true,'CANDIDATO','github://cristhianlujan/claude-persona-lf-patch/supabase/source_plans/s30_assurance_method_v1_workflow_router_completion.sql','EXEC-S30-LF-ASSURANCE-METHOD-V1-BASELINE-20260916-001'),
('ROUTER-OP-BIND-V1',2,'STRATEGY_ROUTER_AUTHENTIC_V1',1,'operation binding','supabase://public/lf_router_resolve_v1','receipt.operation_code = execution.operation_code','TEST','supabase://router-assurance/same-operation','supabase://router-assurance/other-operation','supabase://router-assurance/valid-receipt-other-operation','MC_DC_LIKE','{"required_fields":["operation_code","route_receipt"],"expected_actual_required":true,"zero_effect_on_fail":true}'::jsonb,'TRACEABILITY_BROKEN',true,'CANDIDATO','github://cristhianlujan/claude-persona-lf-patch/supabase/source_plans/s30_assurance_method_v1_workflow_router_completion.sql','EXEC-S30-LF-ASSURANCE-METHOD-V1-BASELINE-20260916-001'),
('ROUTER-TARGET-BIND-V1',2,'STRATEGY_ROUTER_AUTHENTIC_V1',1,'target binding','supabase://public/lf_router_resolve_v1','receipt target identity = exact execution target identity','TEST','supabase://router-assurance/same-target','supabase://router-assurance/other-target','supabase://router-assurance/target-swap','MC_DC_LIKE','{"required_fields":["target_type","target_code","target_path"],"expected_actual_required":true,"zero_effect_on_fail":true}'::jsonb,'TRACEABILITY_BROKEN',true,'CANDIDATO','github://cristhianlujan/claude-persona-lf-patch/supabase/source_plans/s30_assurance_method_v1_workflow_router_completion.sql','EXEC-S30-LF-ASSURANCE-METHOD-V1-BASELINE-20260916-001'),
('ROUTER-FRESHNESS-V1',2,'STRATEGY_ROUTER_AUTHENTIC_V1',1,'freshness','supabase://public/lf_router_resolve_v1','route receipt is current to material revision at effect boundary','TEST','supabase://router-assurance/current-receipt','supabase://router-assurance/stale-receipt','supabase://router-assurance/revision-change-after-route','MC_DC_LIKE','{"required_fields":["receipt_revision","current_revision","observed_at"],"expected_actual_required":true,"zero_effect_on_fail":true}'::jsonb,'CURRENTNESS_GAP',true,'CANDIDATO','github://cristhianlujan/claude-persona-lf-patch/supabase/source_plans/s30_assurance_method_v1_workflow_router_completion.sql','EXEC-S30-LF-ASSURANCE-METHOD-V1-BASELINE-20260916-001'),
('ROUTER-REPLAY-V1',2,'STRATEGY_ROUTER_AUTHENTIC_V1',1,'replay resistance','supabase://public/lf_router_resolve_v1','receipt is valid only in its bound execution/operation/target/revision context','TEST','supabase://router-assurance/first-valid-use','supabase://router-assurance/cross-context-reuse','supabase://router-assurance/concurrent-replay','MC_DC_LIKE','{"required_fields":["receipt_fingerprint","execution_id","operation_code","target_code","revision"],"zero_effect_on_fail":true}'::jsonb,'REPLAY_GAP',true,'CANDIDATO','github://cristhianlujan/claude-persona-lf-patch/supabase/source_plans/s30_assurance_method_v1_workflow_router_completion.sql','EXEC-S30-LF-ASSURANCE-METHOD-V1-BASELINE-20260916-001'),
('ROUTER-ZERO-EFFECT-V1',2,'STRATEGY_ROUTER_AUTHENTIC_V1',1,'zero effect on failure','supabase://public/lf_operation_execution','any invalid route condition => material before_state = after_state','DEMONSTRATION','supabase://router-assurance/valid-route-can-proceed','supabase://router-assurance/invalid-route-blocks','supabase://router-assurance/concurrent-invalid-route','CONDITION','{"required_fields":["before_state_ref","after_state_ref","effect_delta","blocking_code"],"effect_delta_required":"ZERO"}'::jsonb,'ASSURANCE_GAP',true,'CANDIDATO','github://cristhianlujan/claude-persona-lf-patch/supabase/source_plans/s30_assurance_method_v1_workflow_router_completion.sql','EXEC-S30-LF-ASSURANCE-METHOD-V1-BASELINE-20260916-001'),
('ROUTER-REVISION-BIND-V1',1,'STRATEGY_ROUTER_AUTHENTIC_V1',1,'revision binding','supabase://public/lf_router_resolve_v1','route receipt binds exact material subject/operation revision consumed at effect boundary','TEST','supabase://router-assurance/exact-revision','supabase://router-assurance/wrong-revision','supabase://router-assurance/revision-substitution','MC_DC_LIKE','{"required_fields":["receipt_revision","expected_revision","current_revision"],"expected_actual_required":true,"zero_effect_on_fail":true}'::jsonb,'CURRENTNESS_GAP',true,'CANDIDATO','github://cristhianlujan/claude-persona-lf-patch/supabase/source_plans/s30_assurance_method_v1_workflow_router_completion.sql','EXEC-S30-LF-ASSURANCE-METHOD-V1-BASELINE-20260916-001'),
('ROUTER-PRODUCER-AUTHORITY-V1',1,'STRATEGY_ROUTER_AUTHENTIC_V1',1,'producer authority','supabase://public/lf_router_resolve_v1','route trust is accepted only when produced by canonical ACT-0001/Router authority','TEST','supabase://router-assurance/canonical-producer','supabase://router-assurance/caller-declared-trust','supabase://router-assurance/forged-producer','MC_DC_LIKE','{"required_fields":["producer_ref","authority_ref","route_receipt"],"caller_assertions_not_authority":true,"zero_effect_on_fail":true}'::jsonb,'EVIDENCE_NOT_INDEPENDENT',true,'CANDIDATO','github://cristhianlujan/claude-persona-lf-patch/supabase/source_plans/s30_assurance_method_v1_workflow_router_completion.sql','EXEC-S30-LF-ASSURANCE-METHOD-V1-BASELINE-20260916-001'),
('ROUTER-SPOOF-RESISTANCE-V1',1,'STRATEGY_ROUTER_AUTHENTIC_V1',1,'spoof resistance','supabase://public/lf_router_resolve_v1','plausible caller-supplied route fields cannot substitute canonical producer receipt','TEST','supabase://router-assurance/canonical-receipt','supabase://router-assurance/fabricated-route-fields','supabase://router-assurance/forged-trust-payload','MC_DC_LIKE','{"required_fields":["canonical_receipt_ref","producer_ref","trust_validation"],"zero_effect_on_fail":true}'::jsonb,'TRACEABILITY_BROKEN',true,'CANDIDATO','github://cristhianlujan/claude-persona-lf-patch/supabase/source_plans/s30_assurance_method_v1_workflow_router_completion.sql','EXEC-S30-LF-ASSURANCE-METHOD-V1-BASELINE-20260916-001'),
('ROUTER-TOCTOU-RESISTANCE-V1',1,'STRATEGY_ROUTER_AUTHENTIC_V1',1,'TOCTOU resistance','supabase://public/lf_router_resolve_v1','target/currentness is revalidated immediately before material effect','TEST','supabase://router-assurance/unchanged-before-effect','supabase://router-assurance/changed-before-effect','supabase://router-assurance/concurrent-change-window','MC_DC_LIKE','{"required_fields":["route_observed_revision","pre_effect_revision","pre_effect_check_at"],"zero_effect_on_fail":true}'::jsonb,'CURRENTNESS_GAP',true,'CANDIDATO','github://cristhianlujan/claude-persona-lf-patch/supabase/source_plans/s30_assurance_method_v1_workflow_router_completion.sql','EXEC-S30-LF-ASSURANCE-METHOD-V1-BASELINE-20260916-001')
ON CONFLICT (obligation_code,version) DO NOTHING;

INSERT INTO public.lf_assurance_defeater_catalog
(defeater_code,version,claim_code,claim_version,obligation_code,defeater_class,description,required_counterevidence,zero_effect_required,status,source_ref,created_by_execution_id)
VALUES
('WF-D-STDOUT-LOSS-V1',2,'WF_DIAGNOSTIC_COMPLETE_V1',1,'WF-DIAG-DURABLE-V1','EVIDENCE_NOT_DURABLE','Failure can only be reconstructed from ephemeral stdout.','{"test_ref":"github://validate-lf-packs/artifact-loss","required":"diagnostic retrievable without job log"}'::jsonb,false,'CANDIDATO','github://cristhianlujan/claude-persona-lf-patch/supabase/source_plans/s30_assurance_method_v1_workflow_router_completion.sql','EXEC-S30-LF-ASSURANCE-METHOD-V1-BASELINE-20260916-001'),
('WF-D-EXPECTED-ACTUAL-MISSING-V1',1,'WF_DIAGNOSTIC_COMPLETE_V1',1,'WF-DIAG-EXPECTED-ACTUAL-V1','EVIDENCE_WEAK','Failure identifies a check but not the expected/actual condition.','{"test_ref":"github://validate-lf-packs/expected-or-actual-missing"}'::jsonb,false,'CANDIDATO','github://cristhianlujan/claude-persona-lf-patch/supabase/source_plans/s30_assurance_method_v1_workflow_router_completion.sql','EXEC-S30-LF-ASSURANCE-METHOD-V1-BASELINE-20260916-001'),
('WF-D-CORRELATION-BROKEN-V1',1,'WF_DIAGNOSTIC_COMPLETE_V1',1,'WF-DIAG-CORRELATION-V1','TRACEABILITY_BROKEN','Evidence from another run/source can be mistaken for the failing test evidence.','{"test_ref":"github://validate-lf-packs/cross-run-artifact-reuse"}'::jsonb,false,'CANDIDATO','github://cristhianlujan/claude-persona-lf-patch/supabase/source_plans/s30_assurance_method_v1_workflow_router_completion.sql','EXEC-S30-LF-ASSURANCE-METHOD-V1-BASELINE-20260916-001'),
('WF-D-OWNER-RESUME-MISSING-V1',1,'WF_DIAGNOSTIC_COMPLETE_V1',1,'WF-DIAG-OWNER-REPAIR-RESUME-V1','OBSERVABILITY_GAP','Failure is localized but lacks durable owner/repair/resume information.','{"test_ref":"github://validate-lf-packs/owner-or-resume-missing"}'::jsonb,false,'CANDIDATO','github://cristhianlujan/claude-persona-lf-patch/supabase/source_plans/s30_assurance_method_v1_workflow_router_completion.sql','EXEC-S30-LF-ASSURANCE-METHOD-V1-BASELINE-20260916-001'),
('ROUTER-D-WRONG-EXEC-V1',2,'STRATEGY_ROUTER_AUTHENTIC_V1',1,'ROUTER-EXEC-BIND-V1','WRONG_EXECUTION','A valid receipt from another execution is accepted.','{"test_ref":"supabase://router-assurance/other-execution"}'::jsonb,true,'CANDIDATO','github://cristhianlujan/claude-persona-lf-patch/supabase/source_plans/s30_assurance_method_v1_workflow_router_completion.sql','EXEC-S30-LF-ASSURANCE-METHOD-V1-BASELINE-20260916-001'),
('ROUTER-D-WRONG-TARGET-V1',2,'STRATEGY_ROUTER_AUTHENTIC_V1',1,'ROUTER-TARGET-BIND-V1','WRONG_TARGET','A valid receipt for another target is accepted.','{"test_ref":"supabase://router-assurance/other-target"}'::jsonb,true,'CANDIDATO','github://cristhianlujan/claude-persona-lf-patch/supabase/source_plans/s30_assurance_method_v1_workflow_router_completion.sql','EXEC-S30-LF-ASSURANCE-METHOD-V1-BASELINE-20260916-001'),
('ROUTER-D-STALE-V1',2,'STRATEGY_ROUTER_AUTHENTIC_V1',1,'ROUTER-FRESHNESS-V1','STALE','A receipt bound to an old material revision is accepted.','{"test_ref":"supabase://router-assurance/stale-receipt"}'::jsonb,true,'CANDIDATO','github://cristhianlujan/claude-persona-lf-patch/supabase/source_plans/s30_assurance_method_v1_workflow_router_completion.sql','EXEC-S30-LF-ASSURANCE-METHOD-V1-BASELINE-20260916-001'),
('ROUTER-D-REPLAY-V1',2,'STRATEGY_ROUTER_AUTHENTIC_V1',1,'ROUTER-REPLAY-V1','REPLAY','A receipt is replayed in a new context and accepted.','{"test_ref":"supabase://router-assurance/cross-context-reuse"}'::jsonb,true,'CANDIDATO','github://cristhianlujan/claude-persona-lf-patch/supabase/source_plans/s30_assurance_method_v1_workflow_router_completion.sql','EXEC-S30-LF-ASSURANCE-METHOD-V1-BASELINE-20260916-001'),
('ROUTER-D-SPOOF-V1',2,'STRATEGY_ROUTER_AUTHENTIC_V1',1,'ROUTER-SPOOF-RESISTANCE-V1','SPOOF','Caller-supplied route fields/trust assertions are accepted without canonical Router production.','{"test_ref":"supabase://router-assurance/forged-trust-payload"}'::jsonb,true,'CANDIDATO','github://cristhianlujan/claude-persona-lf-patch/supabase/source_plans/s30_assurance_method_v1_workflow_router_completion.sql','EXEC-S30-LF-ASSURANCE-METHOD-V1-BASELINE-20260916-001'),
('ROUTER-D-TOCTOU-V1',2,'STRATEGY_ROUTER_AUTHENTIC_V1',1,'ROUTER-TOCTOU-RESISTANCE-V1','TOCTOU','Target/currentness changes after route validation but before material effect.','{"test_ref":"supabase://router-assurance/changed-before-effect"}'::jsonb,true,'CANDIDATO','github://cristhianlujan/claude-persona-lf-patch/supabase/source_plans/s30_assurance_method_v1_workflow_router_completion.sql','EXEC-S30-LF-ASSURANCE-METHOD-V1-BASELINE-20260916-001'),
('ROUTER-D-WRONG-OP-V1',1,'STRATEGY_ROUTER_AUTHENTIC_V1',1,'ROUTER-OP-BIND-V1','WRONG_OPERATION','A receipt from another operation is accepted.','{"test_ref":"supabase://router-assurance/other-operation"}'::jsonb,true,'CANDIDATO','github://cristhianlujan/claude-persona-lf-patch/supabase/source_plans/s30_assurance_method_v1_workflow_router_completion.sql','EXEC-S30-LF-ASSURANCE-METHOD-V1-BASELINE-20260916-001'),
('ROUTER-D-WRONG-REVISION-V1',1,'STRATEGY_ROUTER_AUTHENTIC_V1',1,'ROUTER-REVISION-BIND-V1','WRONG_REVISION','A receipt for another material revision is accepted.','{"test_ref":"supabase://router-assurance/wrong-revision"}'::jsonb,true,'CANDIDATO','github://cristhianlujan/claude-persona-lf-patch/supabase/source_plans/s30_assurance_method_v1_workflow_router_completion.sql','EXEC-S30-LF-ASSURANCE-METHOD-V1-BASELINE-20260916-001'),
('ROUTER-D-PRODUCER-AUTHORITY-V1',1,'STRATEGY_ROUTER_AUTHENTIC_V1',1,'ROUTER-PRODUCER-AUTHORITY-V1','SPOOF','A non-authoritative producer is accepted as Router authority.','{"test_ref":"supabase://router-assurance/forged-producer"}'::jsonb,true,'CANDIDATO','github://cristhianlujan/claude-persona-lf-patch/supabase/source_plans/s30_assurance_method_v1_workflow_router_completion.sql','EXEC-S30-LF-ASSURANCE-METHOD-V1-BASELINE-20260916-001')
ON CONFLICT (defeater_code,version) DO NOTHING;
