do $do$
declare
  v_parent bigint:=170; v_new bigint; v_screen integer:=56;
  v_validator_identity text:='INPUT_VALIDATOR:v0.5r1-auth-56-v512-semantic-coherence';
  v_source_sha text; v_assert jsonb; v_readbacks jsonb;
  v_assessment record; v_proposal record;
begin
  if programacion.fn_input_readiness_run_is_current(v_parent) then raise exception 'V512_PARENT_MUST_BE_STALE:%',v_parent; end if;
  insert into programacion.input_readiness_runs(version_id,pantalla_id,universe_rule_id,supersedes_run_id,status,scope,universe_snapshot_sha256,family_count,contract_version,curator_identity,curator_component_id)
  select version_id,pantalla_id,universe_rule_id,id,'CURATING',scope||jsonb_build_object('mode','CANDIDATE_V512_SEMANTIC_COHERENCE','remediation','V512_SEMANTIC_COHERENCE_PROPOSAL_SEPARATION_20260822','parent_run_id',id,'research_basis','IGA_2026','canon_vs_proposal','STRICT_SEPARATION'),universe_snapshot_sha256,family_count,contract_version,'INPUT_CURATOR:v0.5r1-auth-56-v512-semantic-coherence',curator_component_id
  from programacion.input_readiness_runs where id=v_parent returning id into v_new;

  insert into programacion.input_family_assessments(run_id,family_code,severity,applicability,coverage_status,well_defined_status,story_ready_status,implementation_ready_status,qa_ready_status,production_ready_status,source_refs,rationale,blockers,negative_requirements,test_obligations,freshness,curator_evidence,curator_sha256,validator_outcome,validator_findings,validator_evidence,validator_identity,validator_sha256,validator_assessed_at,subject_coverage,threat_coverage,semantic_depth_sha256)
  select v_new,src.family_code,
    case when src.family_code in ('FEATURE_FLAGS','I18N_FORMATS','STATES','TRANSITIONS') then 'P0' when src.family_code in ('REDUCED_MOTION','FORCED_COLORS_CONTRAST') then 'P2' when src.family_code='ACCESSIBILITY' then 'P4' else src.severity end,
    case when src.family_code in ('FEATURE_FLAGS','I18N_FORMATS','STATES','TRANSITIONS') then 'UNRESOLVED' else src.applicability end,
    case when src.family_code in ('FEATURE_FLAGS','I18N_FORMATS','STATES','TRANSITIONS') then 'PENDING' when src.family_code in ('ACCESSIBILITY','REDUCED_MOTION','FORCED_COLORS_CONTRAST') then 'COMPLETE' when src.family_code='THEME_LIGHT_DARK_SYSTEM' then 'PARTIAL' else src.coverage_status end,
    case when src.family_code in ('FEATURE_FLAGS','I18N_FORMATS','STATES','TRANSITIONS') then 'PENDING' when src.family_code in ('ACCESSIBILITY','REDUCED_MOTION','FORCED_COLORS_CONTRAST') then 'COMPLETE' when src.family_code='THEME_LIGHT_DARK_SYSTEM' then 'PARTIAL' else src.well_defined_status end,
    case when src.family_code in ('FEATURE_FLAGS','I18N_FORMATS','STATES','TRANSITIONS') then 'BLOCKED' when src.family_code in ('ACCESSIBILITY','REDUCED_MOTION','FORCED_COLORS_CONTRAST','THEME_LIGHT_DARK_SYSTEM') then 'READY' else src.story_ready_status end,
    case when src.family_code in ('FEATURE_FLAGS','I18N_FORMATS','STATES','TRANSITIONS') then 'BLOCKED' when src.family_code in ('ACCESSIBILITY','REDUCED_MOTION','FORCED_COLORS_CONTRAST') then 'READY' when src.family_code='THEME_LIGHT_DARK_SYSTEM' then 'NOT_READY' else src.implementation_ready_status end,
    case when src.family_code in ('FEATURE_FLAGS','I18N_FORMATS','STATES','TRANSITIONS') then 'BLOCKED' when src.family_code='ACCESSIBILITY' then 'READY' when src.family_code in ('REDUCED_MOTION','FORCED_COLORS_CONTRAST') then 'NOT_READY' when src.family_code='THEME_LIGHT_DARK_SYSTEM' then 'BLOCKED' else src.qa_ready_status end,
    case when src.family_code in ('FEATURE_FLAGS','I18N_FORMATS','STATES','TRANSITIONS') then 'BLOCKED' when src.family_code='ACCESSIBILITY' then 'READY' when src.family_code in ('REDUCED_MOTION','FORCED_COLORS_CONTRAST') then 'NOT_READY' when src.family_code='THEME_LIGHT_DARK_SYSTEM' then 'BLOCKED' else src.production_ready_status end,
    case when src.family_code='PERMISSIONS' then src.source_refs||jsonb_build_array(jsonb_build_object('kind','RULE','codigo','B2B-RULE-AUTH-029')) else src.source_refs end,
    case when src.family_code='ACCESSIBILITY' then 'A11Y-001/002/003/004 are present in the current canonical rule set. Accessibility input coverage is complete; runtime/QA obligations remain tracked in dedicated subfamilies. | V5.12 semantic coherence recuration.' when src.family_code='REDUCED_MOTION' then 'B2B-RULE-A11Y-003 explicitly requires prefers-reduced-motion, removes/reduces non-essential motion and forbids functional dependence on motion. Input definition is complete; implementation/QA remains pending. | V5.12 semantic coherence recuration.' when src.family_code='FORCED_COLORS_CONTRAST' then 'B2B-RULE-A11Y-004 explicitly requires forced-colors support, visible focus and non-color-only state semantics. Input definition is complete; implementation/QA remains pending. | V5.12 semantic coherence recuration.' when src.family_code='THEME_LIGHT_DARK_SYSTEM' then 'B2B-RULE-THEME-001/002/003 explicitly define LIGHT/DARK/SYSTEM resolution, persistence and no-flash behavior. Coverage is PARTIAL because dark tokens require decision and first-paint behavior requires implementation/QA. | V5.12 semantic coherence recuration.' when src.family_code='FEATURE_FLAGS' then 'UNRESOLVED: current sources show no feature-flag relation, but absence is not positive exclusion authority under GOV-012. A canonical applicability decision is required.' when src.family_code='I18N_FORMATS' then 'UNRESOLVED: current sources show no i18n/locale relation, but absence is not positive exclusion authority under GOV-012. A canonical applicability decision is required.' when src.family_code='STATES' then 'UNRESOLVED: SCREEN_STATE_SET is empty. An empty set does not prove states are not applicable; an explicit applicability decision or canonical state model is required.' when src.family_code='TRANSITIONS' then 'UNRESOLVED: no canonical transition model is materialized. Absence cannot self-authorize N/A; applicability must be explicitly decided consistently with STATES.' when src.family_code='DESIGN_SYSTEM' then src.rationale||' | V5.12 removed zero-count blocker noise.' when src.family_code='PERMISSIONS' then 'NOT_APPLICABLE with positive authority: B2B-RULE-AUTH-029 explicitly restricts the verified recovery context to PASSWORD_UPDATE_ONLY and denies operational authorization before completion; empty permission matrices are complementary evidence only. | V5.12 direct-rule authority.' else src.rationale||' | Recurated under INPUT_READINESS_CONTRACT 5.12.' end,
    case when src.family_code='ACCESSIBILITY' then '[]'::jsonb when src.family_code='REDUCED_MOTION' then '[{"code":"PENDING_IMPLEMENTATION_QA","source_ref":"B2B-RULE-A11Y-003"}]'::jsonb when src.family_code='FORCED_COLORS_CONTRAST' then '[{"code":"PENDING_IMPLEMENTATION_QA","source_ref":"B2B-RULE-A11Y-004"}]'::jsonb when src.family_code='THEME_LIGHT_DARK_SYSTEM' then '[{"code":"DARK_TOKENS_PENDING_DECISION","source_ref":"B2B-RULE-THEME-002"},{"code":"FIRST_PAINT_THEME_QA_PENDING","source_ref":"B2B-RULE-THEME-003"}]'::jsonb when src.family_code in ('FEATURE_FLAGS','I18N_FORMATS','STATES','TRANSITIONS') then jsonb_build_array(jsonb_build_object('code','APPLICABILITY_AUTHORITY_REQUIRED','family_code',src.family_code,'blocks_story',true,'source_ref','GOV-012')) when src.family_code='DESIGN_SYSTEM' then coalesce((select jsonb_agg(j.value) from jsonb_array_elements(src.blockers) j(value) where not (j.value->>'code'='SCREEN_ELEMENT_INVENTORY_MISSING' and coalesce((j.value->>'count')::integer,0)=0)),'[]'::jsonb) else src.blockers end,
    src.negative_requirements,case when src.family_code in ('FEATURE_FLAGS','I18N_FORMATS','STATES','TRANSITIONS') then src.test_obligations||jsonb_build_array('Reject NOT_APPLICABLE when only absence/empty collections are observed') else src.test_obligations end,
    '{}'::jsonb,jsonb_build_object('component_id',46,'execution_id',gen_random_uuid()::text,'parent_run_id',v_parent,'parent_assessment_id',src.id,'execution_mode','INDEPENDENT_CURATOR','contract_revision','5.12','remediation_revision','V512_SEMANTIC_COHERENCE_PROPOSAL_SEPARATION_20260822','direct_source_readback',true),repeat('0',64),'PENDING','[]'::jsonb,'{}'::jsonb,null,null,null,'[]'::jsonb,'[]'::jsonb,repeat('0',64)
  from programacion.input_family_assessments src where src.run_id=v_parent order by src.family_code;
  if (select count(*) from programacion.input_family_assessments where run_id=v_new)<>47 then raise exception 'V512_SCREEN56_CURATOR_CARDINALITY_MISMATCH'; end if;

  insert into programacion.input_gap_proposals(run_id,assessment_id,family_code,gap_code,proposal_kind,proposed_payload,canonical_target,source_refs,evidence_refs,confidence,stage_impact,contradictions_checked,status,curator_identity,curator_execution_id,curator_sha256)
  select v_new,cur.id,cur.family_code,'APPLICABILITY_AUTHORITY_REQUIRED','HUMAN_DECISION_REQUIRED',case cur.family_code when 'FEATURE_FLAGS' then '{"proposed_completion":"Define an explicit canonical applicability rule for FEATURE_FLAGS on B2B-AUTH-006. If excluded, record the exclusion authority; if applicable, bind the governed feature-flag source. Do not infer either outcome from absence."}'::jsonb when 'I18N_FORMATS' then '{"proposed_completion":"Define an explicit canonical applicability rule for I18N/locale on B2B-AUTH-006. If excluded, record why this recovery surface is locale-independent; if applicable, bind canonical locale/format sources."}'::jsonb when 'STATES' then '{"proposed_completion":"Decide whether recovery OTP lifecycle outcomes are modeled as canonical screen/domain states. If yes, materialize the state set; if no, add an explicit exclusion rule. An empty state set alone is not authority."}'::jsonb when 'TRANSITIONS' then '{"proposed_completion":"After STATES applicability is resolved, explicitly define the transition model or a canonical exclusion. Keep transition applicability consistent with the chosen state model."}'::jsonb end,case cur.family_code when 'FEATURE_FLAGS' then '{"target_type":"APPLICABILITY_RULE_OR_DECISION","family_code":"FEATURE_FLAGS","screen_code":"B2B-AUTH-006"}'::jsonb when 'I18N_FORMATS' then '{"target_type":"APPLICABILITY_RULE_OR_DECISION","family_code":"I18N_FORMATS","screen_code":"B2B-AUTH-006"}'::jsonb when 'STATES' then '{"target_type":"STATE_MODEL_OR_EXCLUSION_DECISION","screen_code":"B2B-AUTH-006"}'::jsonb when 'TRANSITIONS' then '{"target_type":"TRANSITION_MODEL_OR_EXCLUSION_DECISION","screen_code":"B2B-AUTH-006","depends_on":"STATES"}'::jsonb end,cur.source_refs,'[{"kind":"EKB_ERROR","code":"GOV-012"},{"kind":"RESEARCH","code":"IGA_2026"}]'::jsonb,0.95,'{"story":"BLOCKED","implementation":"BLOCKED","qa":"BLOCKED","production":"BLOCKED"}'::jsonb,'["CAPABILITY_ABSENCE_IS_NOT_EXCLUSION","EMPTY_COLLECTION_IS_NOT_EXCLUSION","NO_EXPLICIT_CANONICAL_EXCLUSION_OBSERVED"]'::jsonb,'PROPOSED','INPUT_CURATOR:v0.5r1-auth-56-v512-semantic-coherence',cur.curator_evidence->>'execution_id',repeat('0',64)
  from programacion.input_family_assessments cur where cur.run_id=v_new and cur.family_code in ('FEATURE_FLAGS','I18N_FORMATS','STATES','TRANSITIONS');

  update programacion.input_readiness_runs set status='VALIDATING',validator_identity=v_validator_identity,validator_component_id=47 where id=v_new;
  select source_snapshot_sha256 into v_source_sha from programacion.input_readiness_runs where id=v_new;
  for v_assessment in select * from programacion.input_family_assessments where run_id=v_new order by family_code loop
    v_assert:=programacion.fn_input_v58_build_assertions(v_new,v_parent,v_assessment.family_code);
    update programacion.input_family_assessments set validator_outcome='PASS',validator_findings='[]'::jsonb,validator_evidence=jsonb_build_object('component_id',47,'execution_id',gen_random_uuid()::text,'execution_mode','INDEPENDENT_VALIDATOR','contract_revision','5.12','direct_source_readback',true,'source_snapshot_sha256',v_source_sha,'curator_sha256',v_assessment.curator_sha256,'semantic_depth_sha256',v_assessment.semantic_depth_sha256,'validated_curator_execution_id',v_assessment.curator_evidence->>'execution_id','assertions',v_assert),validator_identity=v_validator_identity,validator_assessed_at=now() where id=v_assessment.id;
  end loop;
  for v_proposal in select * from programacion.input_gap_proposals where run_id=v_new order by id loop
    select coalesce(jsonb_agg(jsonb_build_object('source_ref',refs.value,'source_observed_sha256',programacion.fn_v09_sha256_jsonb(programacion.fn_input_resolve_source_ref(refs.value,v_screen,19))) order by refs.ord),'[]'::jsonb) into v_readbacks from jsonb_array_elements(v_proposal.source_refs) with ordinality refs(value,ord);
    update programacion.input_gap_proposals set status='HUMAN_DECISION_REQUIRED',validator_identity=v_validator_identity,validator_outcome='PASS',validator_evidence=jsonb_build_object('direct_source_readback',true,'source_snapshot_sha256',v_source_sha,'source_readbacks',v_readbacks,'proposal_is_canonical',false,'auto_promotion','DENY','validated_gap_semantics',true) where id=v_proposal.id;
  end loop;
  update programacion.input_readiness_runs set status='COMPLETED' where id=v_new;
  if not programacion.fn_input_readiness_run_is_current(v_new) then raise exception 'V512_SCREEN56_SUCCESSOR_NOT_CURRENT:%',v_new; end if;
  if (select count(*) from programacion.input_family_assessments where run_id=v_new and validator_outcome='PASS')<>47 then raise exception 'V512_SCREEN56_VALIDATOR_CARDINALITY_MISMATCH'; end if;
  if (select count(*) from programacion.input_gap_proposals where run_id=v_new and validator_outcome='PASS')<>4 then raise exception 'V512_SCREEN56_PROPOSAL_VALIDATION_CARDINALITY_MISMATCH'; end if;
end;
$do$;