-- LF_GATE_CHECK_OBSERVABILITY_V1
-- Transversal check-level diagnostics for governed LF gates.
-- Extends the existing operation execution/step ledger and lf_ops error catalog; it does not create a parallel workflow or error system.

begin;

insert into lf_ops.errores_catalogo(
  error_code,category,severity,user_title,user_message_template,suggested_action,
  action_label,retryable,log_level,provider_mapping,status
)
select
  'LF-GATE-CHECK-FAILED','QUALITY_GATE','HIGH','Gate check failed',
  'A governed quality-gate check failed. Use the persisted trace and evidence references to diagnose the exact condition.',
  'Inspect the check-level diagnostic, correct the owning defect, and rerun the governed gate.',
  'Inspect diagnostic',true,'ERROR',
  jsonb_build_object('contract','LF_GATE_ERROR_V1','scope','GOVERNED_GATE_CHECK'),
  'VIGENTE'
where not exists (
  select 1 from lf_ops.errores_catalogo where error_code='LF-GATE-CHECK-FAILED'
);

insert into lf_ops.errores_catalogo(
  error_code,category,severity,user_title,user_message_template,suggested_action,
  action_label,retryable,log_level,provider_mapping,status
)
select
  'LF-GATE-CHECK-BLOCKED','QUALITY_GATE','HIGH','Gate check blocked',
  'A governed quality-gate check could not execute or prove its condition. Use the persisted trace and evidence references to identify the missing precondition.',
  'Restore the missing precondition or evidence, then rerun the governed gate.',
  'Inspect blocker',true,'ERROR',
  jsonb_build_object('contract','LF_GATE_ERROR_V1','scope','GOVERNED_GATE_CHECK'),
  'VIGENTE'
where not exists (
  select 1 from lf_ops.errores_catalogo where error_code='LF-GATE-CHECK-BLOCKED'
);

create table if not exists public.lf_operation_gate_check_results (
  id bigint generated by default as identity primary key,
  execution_id text not null references public.lf_operation_execution(execution_id),
  operation_code text not null,
  step_order integer not null,
  step_id text not null,
  gate_id text not null,
  gate_mode text not null check (gate_mode in ('COLLECT_ALL','FAIL_FAST_CRITICAL')),
  attempt_no integer not null default 1 check (attempt_no >= 1),
  check_id text not null,
  check_status text not null check (check_status in ('PASS','FAIL','BLOCKED','SKIPPED')),
  error_id bigint null references lf_ops.errores_catalogo(error_id),
  error_occurrence_id uuid null references lf_ops.errores_ocurrencias(occurrence_id),
  error_class text null,
  condition text not null,
  expected jsonb not null default 'null'::jsonb,
  actual jsonb not null default 'null'::jsonb,
  input_ref text null,
  evidence_ref text not null,
  producer text not null,
  run_id text not null,
  job_id text null,
  source_commit text not null,
  source_path text not null,
  trace_id text not null,
  parent_trace_id text not null,
  rc integer not null,
  downstream_impact jsonb not null default '{}'::jsonb,
  owner text not null,
  next_action text not null,
  batch_sha256 text not null check (batch_sha256 ~ '^[0-9a-f]{64}$'),
  created_by_execution_id text not null,
  observed_at timestamptz not null default clock_timestamp(),
  constraint lf_operation_gate_check_result_error_refs_ck check (
    (check_status in ('PASS','SKIPPED') and error_id is null and error_occurrence_id is null)
    or
    (check_status in ('FAIL','BLOCKED') and error_id is not null and error_occurrence_id is not null)
  ),
  constraint lf_operation_gate_check_results_uk unique(execution_id,step_id,gate_id,attempt_no,check_id)
);

create index if not exists lf_operation_gate_check_results_exec_gate_idx
  on public.lf_operation_gate_check_results(execution_id,step_order,gate_id,attempt_no,id);
create index if not exists lf_operation_gate_check_results_error_idx
  on public.lf_operation_gate_check_results(error_occurrence_id)
  where error_occurrence_id is not null;

a lter table public.lf_operation_gate_check_results enable row level security;

revoke all on table public.lf_operation_gate_check_results from public, anon, authenticated;
grant select,insert on table public.lf_operation_gate_check_results to service_role;
grant usage,select on sequence public.lf_operation_gate_check_results_id_seq to service_role;

create or replace function public.lf_gate_check_reject_pii_v1()
returns trigger
language plpgsql
security invoker
set search_path to 'pg_catalog','public'
as $function$
declare
  payload_text text;
begin
  payload_text := jsonb_build_object(
    'expected',new.expected,
    'actual',new.actual,
    'downstream_impact',new.downstream_impact
  )::text;
  if payload_text ~* '\"(email|phone|document_number|tax_id|full_name|customer_full_name|contact_email|contact_phone|legal_address|token|password|secret)\"[[:space:]]*:' then
    raise exception 'LF_PII_BLOCKED_IN_GATE_TELEMETRY';
  end if;
  return new;
end;
$function$;

revoke execute on function public.lf_gate_check_reject_pii_v1() from public, anon, authenticated;

DROP TRIGGER IF EXISTS trg_lf_operation_gate_check_results_no_pii ON public.lf_operation_gate_check_results;
CREATE TRIGGER trg_lf_operation_gate_check_results_no_pii
BEFORE INSERT OR UPDATE ON public.lf_operation_gate_check_results
FOR EACH ROW EXECUTE FUNCTION public.lf_gate_check_reject_pii_v1();

create or replace function public.lf_record_gate_checks_v1(
  p_execution_id text,
  p_step_id text,
  p_gate_id text,
  p_gate_mode text,
  p_expected_check_ids jsonb,
  p_checks jsonb,
  p_context jsonb,
  p_actor_execution_id text
)
returns jsonb
language plpgsql
security invoker
set search_path to 'pg_catalog','public','lf_ops'
as $function$
declare
  x public.lf_operation_execution%rowtype;
  st public.lf_operation_steps%rowtype;
  step_exec public.lf_operation_execution_steps%rowtype;
  c jsonb;
  expected_ids text[];
  seen_ids text[];
  expected_count integer;
  seen_count integer;
  duplicate_count integer;
  attempt_no integer;
  fail_count integer := 0;
  blocked_count integer := 0;
  skipped_count integer := 0;
  pass_count integer := 0;
  first_stop_pos integer := null;
  check_pos integer := 0;
  expected_pos integer;
  check_status text;
  check_id text;
  error_code text;
  error_row lf_ops.errores_catalogo%rowtype;
  occurrence_id uuid;
  trace_id text;
  parent_trace_id text;
  gate_correlation_id uuid;
  batch_sha text;
  batch_payload jsonb;
  gate_result text;
  environment text;
  run_id text;
  job_id text;
  owner_default text;
  next_action_default text;
  source_commit text;
  source_path text;
  producer text;
  evidence_ref text;
  input_ref text;
  error_class text;
  rc integer;
  downstream_impact jsonb;
  expected_value jsonb;
  actual_value jsonb;
  condition_text text;
  actor_exists boolean;
  existing_count integer;
  existing_batch_count integer;
  step_status_conflict boolean := false;
  remaining_after_fail_fast text[] := array[]::text[];
  summary jsonb;
  error_occurrences jsonb := '[]'::jsonb;
begin
  if btrim(coalesce(p_execution_id,''))=''
     or btrim(coalesce(p_step_id,''))=''
     or btrim(coalesce(p_gate_id,''))=''
     or p_gate_mode not in ('COLLECT_ALL','FAIL_FAST_CRITICAL')
     or p_expected_check_ids is null or jsonb_typeof(p_expected_check_ids)<>'array'
     or p_checks is null or jsonb_typeof(p_checks)<>'array'
     or p_context is null or jsonb_typeof(p_context)<>'object'
     or btrim(coalesce(p_actor_execution_id,''))='' then
    return jsonb_build_object('outcome','BLOCKED','code','LF_GATE_ERROR_V1_INPUT_INVALID','durable',false);
  end if;

  select * into x from public.lf_operation_execution where execution_id=p_execution_id for update;
  if not found then
    return jsonb_build_object('outcome','BLOCKED','code','LF_GATE_ERROR_V1_EXECUTION_NOT_FOUND','durable',false);
  end if;
  if x.status<>'IN_PROGRESS' then
    return jsonb_build_object('outcome','BLOCKED','code','LF_GATE_ERROR_V1_EXECUTION_NOT_IN_PROGRESS','status',x.status,'durable',false);
  end if;

  select exists(select 1 from public.lf_operation_execution where execution_id=p_actor_execution_id) into actor_exists;
  if p_actor_execution_id<>p_execution_id and actor_exists is not true then
    return jsonb_build_object('outcome','BLOCKED','code','LF_GATE_ERROR_V1_ACTOR_NOT_GOVERNED','durable',false);
  end if;

  select * into st from public.lf_operation_steps
  where operation_code=x.operation_code and step_id=p_step_id and active=true;
  if not found then
    return jsonb_build_object('outcome','BLOCKED','code','LF_GATE_ERROR_V1_STEP_NOT_CANONICAL','operation_code',x.operation_code,'step_id',p_step_id,'durable',false);
  end if;

  if jsonb_array_length(p_expected_check_ids)=0 or jsonb_array_length(p_checks)=0 then
    return jsonb_build_object('outcome','BLOCKED','code','LF_GATE_ERROR_V1_EMPTY_CHECK_SET','durable',false);
  end if;

  select array_agg(value order by ord), count(*), count(*)-count(distinct value)
  into expected_ids, expected_count, duplicate_count
  from jsonb_array_elements_text(p_expected_check_ids) with ordinality t(value,ord);
  if duplicate_count<>0 or exists(select 1 from unnest(expected_ids) z where btrim(coalesce(z,''))='') then
    return jsonb_build_object('outcome','BLOCKED','code','LF_GATE_ERROR_V1_EXPECTED_CHECK_IDS_INVALID','durable',false);
  end if;

  select array_agg(v order by ord), count(*), count(*)-count(distinct v)
  into seen_ids, seen_count, duplicate_count
  from (
    select elem->>'check_id' as v, ord
    from jsonb_array_elements(p_checks) with ordinality t(elem,ord)
  ) s;
  if duplicate_count<>0 or exists(select 1 from unnest(seen_ids) z where btrim(coalesce(z,''))='') then
    return jsonb_build_object('outcome','BLOCKED','code','LF_GATE_ERROR_V1_CHECK_IDS_INVALID','durable',false);
  end if;
  if exists(select 1 from unnest(seen_ids) z where not (z=any(expected_ids))) then
    return jsonb_build_object('outcome','BLOCKED','code','LF_GATE_ERROR_V1_UNDECLARED_CHECK','durable',false);
  end if;

  attempt_no:=coalesce(nullif(p_context->>'attempt_no','')::integer,1);
  if attempt_no<1 then
    return jsonb_build_object('outcome','BLOCKED','code','LF_GATE_ERROR_V1_ATTEMPT_INVALID','durable',false);
  end if;

  source_commit:=btrim(coalesce(p_context->>'source_commit',''));
  source_path:=btrim(coalesce(p_context->>'source_path',''));
  run_id:=btrim(coalesce(p_context->>'run_id',p_execution_id));
  job_id:=nullif(btrim(coalesce(p_context->>'job_id','')),'');
  owner_default:=btrim(coalesce(p_context->>'owner',''));
  next_action_default:=btrim(coalesce(p_context->>'next_action',''));
  environment:=upper(btrim(coalesce(p_context->>'environment','CANDIDATE')));
  if source_commit='' or source_path='' or run_id='' or owner_default='' or next_action_default='' then
    return jsonb_build_object('outcome','BLOCKED','code','LF_GATE_ERROR_V1_CONTEXT_INCOMPLETE','durable',false);
  end if;

  batch_payload:=jsonb_build_object(
    'execution_id',p_execution_id,'operation_code',x.operation_code,'step_id',p_step_id,'step_order',st.step_order,
    'gate_id',p_gate_id,'gate_mode',p_gate_mode,'attempt_no',attempt_no,
    'expected_check_ids',p_expected_check_ids,'checks',p_checks,'context',p_context
  );
  batch_sha:=encode(extensions.digest(batch_payload::text,'sha256'),'hex');
  parent_trace_id:=coalesce(nullif(btrim(p_context->>'parent_trace_id'),''),'LF-GATE-'||upper(substr(batch_sha,1,20)));
  gate_correlation_id:=gen_random_uuid();

  select count(*),count(distinct batch_sha256) into existing_count,existing_batch_count
  from public.lf_operation_gate_check_results
  where execution_id=p_execution_id and step_id=p_step_id and gate_id=p_gate_id and attempt_no=attempt_no;
  if existing_count>0 then
    if existing_batch_count=1 and exists(
      select 1 from public.lf_operation_gate_check_results
      where execution_id=p_execution_id and step_id=p_step_id and gate_id=p_gate_id and attempt_no=attempt_no and batch_sha256=batch_sha
    ) then
      return public.lf_gate_check_diagnostic_v1(p_execution_id,p_step_id,p_gate_id,attempt_no)
        || jsonb_build_object('outcome','REPLAY','batch_sha256',batch_sha);
    end if;
    return jsonb_build_object('outcome','BLOCKED','code','LF_GATE_ERROR_V1_ATTEMPT_CONFLICT','durable',true,'attempt_no',attempt_no);
  end if;

  -- Validate each check before any durable write.
  check_pos:=0;
  for c in select value from jsonb_array_elements(p_checks) loop
    check_pos:=check_pos+1;
    check_id:=btrim(coalesce(c->>'check_id',''));
    check_status:=upper(btrim(coalesce(c->>'status','')));
    condition_text:=btrim(coalesce(c->>'condition',''));
    producer:=btrim(coalesce(c->>'producer',''));
    evidence_ref:=btrim(coalesce(c->>'evidence_ref',''));
    input_ref:=nullif(btrim(coalesce(c->>'input_ref','')),'');
    error_class:=nullif(btrim(coalesce(c->>'error_class','')),'');
    if not (c?'expected') or not (c?'actual') or not (c?'rc') then
      return jsonb_build_object('outcome','BLOCKED','code','LF_GATE_ERROR_V1_CHECK_SHAPE_INCOMPLETE','check_id',check_id,'durable',false);
    end if;
    if check_status not in ('PASS','FAIL','BLOCKED','SKIPPED') or condition_text='' or producer='' or evidence_ref='' then
      return jsonb_build_object('outcome','BLOCKED','code','LF_GATE_ERROR_V1_CHECK_METADATA_INVALID','check_id',check_id,'durable',false);
    end if;
    if check_status in ('FAIL','BLOCKED') and error_class is null then
      return jsonb_build_object('outcome','BLOCKED','code','LF_GATE_ERROR_V1_ERROR_CLASS_REQUIRED','check_id',check_id,'durable',false);
    end if;
    if jsonb_typeof(c->'rc')<>'number' then
      return jsonb_build_object('outcome','BLOCKED','code','LF_GATE_ERROR_V1_RC_INVALID','check_id',check_id,'durable',false);
    end if;
  end loop;

  -- Collect-all requires the complete declared set. Fail-fast may stop only on a declared critical failure at the exact stop position.
  if p_gate_mode='COLLECT_ALL' then
    if seen_count<>expected_count or exists(select 1 from unnest(expected_ids) z where not (z=any(seen_ids))) then
      return jsonb_build_object('outcome','BLOCKED','code','LF_GATE_ERROR_V1_COLLECT_ALL_INCOMPLETE','expected_count',expected_count,'seen_count',seen_count,'durable',false);
    end if;
  else
    check_pos:=0;
    for c in select value from jsonb_array_elements(p_checks) loop
      check_pos:=check_pos+1;
      check_status:=upper(c->>'status');
      if check_status in ('FAIL','BLOCKED') and coalesce((c->>'critical')::boolean,false) then
        first_stop_pos:=check_pos;
        exit;
      end if;
    end loop;
    if first_stop_pos is null then
      if seen_count<>expected_count or exists(select 1 from unnest(expected_ids) z where not (z=any(seen_ids))) then
        return jsonb_build_object('outcome','BLOCKED','code','LF_GATE_ERROR_V1_FAIL_FAST_WITHOUT_CRITICAL_STOP_INCOMPLETE','durable',false);
      end if;
    else
      if seen_count<>first_stop_pos then
        return jsonb_build_object('outcome','BLOCKED','code','LF_GATE_ERROR_V1_FAIL_FAST_EXECUTED_AFTER_CRITICAL_FAILURE','stop_position',first_stop_pos,'seen_count',seen_count,'durable',false);
      end if;
      select ord into expected_pos from unnest(expected_ids) with ordinality t(v,ord) where v=(p_checks->(first_stop_pos-1)->>'check_id');
      if expected_pos is distinct from first_stop_pos then
        return jsonb_build_object('outcome','BLOCKED','code','LF_GATE_ERROR_V1_FAIL_FAST_ORDER_MISMATCH','stop_position',first_stop_pos,'expected_position',expected_pos,'durable',false);
      end if;
      if first_stop_pos<expected_count then
        remaining_after_fail_fast:=expected_ids[(first_stop_pos+1):expected_count];
      end if;
    end if;
  end if;

  -- Persist every executed check; failures/blocks additionally reuse lf_ops.errores_ocurrencias.
  check_pos:=0;
  for c in select value from jsonb_array_elements(p_checks) loop
    check_pos:=check_pos+1;
    check_id:=btrim(c->>'check_id');
    check_status:=upper(btrim(c->>'status'));
    condition_text:=btrim(c->>'condition');
    expected_value:=c->'expected';
    actual_value:=c->'actual';
    producer:=btrim(c->>'producer');
    evidence_ref:=btrim(c->>'evidence_ref');
    input_ref:=nullif(btrim(coalesce(c->>'input_ref','')),'');
    error_class:=nullif(btrim(coalesce(c->>'error_class','')),'');
    rc:=(c->>'rc')::integer;
    downstream_impact:=coalesce(c->'downstream_impact',p_context->'downstream_impact','{}'::jsonb);
    trace_id:=lf_ops.new_trace_code();
    occurrence_id:=null;

    if check_status='PASS' then pass_count:=pass_count+1;
    elsif check_status='FAIL' then fail_count:=fail_count+1;
    elsif check_status='BLOCKED' then blocked_count:=blocked_count+1;
    else skipped_count:=skipped_count+1;
    end if;

    if check_status in ('FAIL','BLOCKED') then
      error_code:=case when check_status='FAIL' then 'LF-GATE-CHECK-FAILED' else 'LF-GATE-CHECK-BLOCKED' end;
      select * into error_row from lf_ops.errores_catalogo
      where error_code=error_code and status='VIGENTE'
      order by error_id desc limit 1;
      if not found then raise exception 'LF_GATE_ERROR_V1_ERROR_CATALOG_MISSING:%',error_code; end if;

      insert into lf_ops.errores_ocurrencias(
        trace_code,error_code,error_id,correlation_id,technical_fingerprint,severity,environment,
        payload_redacted,resolution_status,provider_code,occurred_at
      ) values (
        trace_id,error_code,error_row.error_id,gate_correlation_id,
        encode(extensions.digest(batch_sha||':'||check_id||':'||attempt_no::text,'sha256'),'hex'),
        error_row.severity,environment,
        jsonb_build_object(
          'contract','LF_GATE_ERROR_V1','run_id',run_id,'job_id',job_id,
          'execution_id',p_execution_id,'operation_code',x.operation_code,
          'step_id',p_step_id,'step_order',st.step_order,'gate_id',p_gate_id,'check_id',check_id,
          'error_class',error_class,'condition',condition_text,'expected',expected_value,'actual',actual_value,
          'input_ref',input_ref,'evidence_ref',evidence_ref,'producer',producer,
          'source_commit',source_commit,'source_path',source_path,
          'trace_id',trace_id,'parent_trace_id',parent_trace_id,'rc',rc,
          'downstream_impact',downstream_impact,
          'owner',coalesce(nullif(btrim(c->>'owner'),''),owner_default),
          'next_action',coalesce(nullif(btrim(c->>'next_action'),''),next_action_default),
          'attempt_no',attempt_no,'batch_sha256',batch_sha
        ),
        'OPEN','LF_GATE_ERROR_V1',clock_timestamp()
      ) returning lf_ops.errores_ocurrencias.occurrence_id into occurrence_id;

      error_occurrences:=error_occurrences||jsonb_build_array(jsonb_build_object(
        'check_id',check_id,'error_code',error_code,'error_id',error_row.error_id,
        'occurrence_id',occurrence_id,'trace_id',trace_id
      ));
    end if;

    insert into public.lf_operation_gate_check_results(
      execution_id,operation_code,step_order,step_id,gate_id,gate_mode,attempt_no,
      check_id,check_status,error_id,error_occurrence_id,error_class,condition,expected,actual,
      input_ref,evidence_ref,producer,run_id,job_id,source_commit,source_path,trace_id,parent_trace_id,
      rc,downstream_impact,owner,next_action,batch_sha256,created_by_execution_id
    ) values (
      p_execution_id,x.operation_code,st.step_order,p_step_id,p_gate_id,p_gate_mode,attempt_no,
      check_id,check_status,case when occurrence_id is null then null else error_row.error_id end,occurrence_id,error_class,condition_text,expected_value,actual_value,
      input_ref,evidence_ref,producer,run_id,job_id,source_commit,source_path,trace_id,parent_trace_id,
      rc,downstream_impact,coalesce(nullif(btrim(c->>'owner'),''),owner_default),
      coalesce(nullif(btrim(c->>'next_action'),''),next_action_default),batch_sha,p_actor_execution_id
    );
  end loop;

  gate_result:=case when blocked_count>0 or skipped_count>0 then 'BLOCKED' when fail_count>0 then 'FAIL' else 'PASS' end;
  summary:=jsonb_build_object(
    'contract','LF_GATE_ERROR_V1','gate_id',p_gate_id,'gate_mode',p_gate_mode,'attempt_no',attempt_no,
    'gate_result',gate_result,'expected_check_count',expected_count,'executed_check_count',seen_count,
    'pass_count',pass_count,'fail_count',fail_count,'blocked_count',blocked_count,'skipped_count',skipped_count,
    'parent_trace_id',parent_trace_id,'batch_sha256',batch_sha,'error_occurrences',error_occurrences,
    'remaining_after_fail_fast',to_jsonb(remaining_after_fail_fast),
    'diagnostic_ref','supabase://public/lf_operation_gate_check_results/'||p_execution_id||'/'||p_step_id||'/'||p_gate_id||'/attempt/'||attempt_no
  );

  select * into step_exec from public.lf_operation_execution_steps
  where execution_id=p_execution_id and step_order=st.step_order and step_id=p_step_id for update;
  if found then
    step_status_conflict:=gate_result<>'PASS' and step_exec.status in ('PASS','PASS_CLEAN','STEP_PASS_WITH_EVIDENCE','TOP_TIER_PASS');
    update public.lf_operation_execution_steps
    set evidence_payload=coalesce(evidence_payload,'{}'::jsonb)||jsonb_build_object('gate_check_contract_v1',summary),
        updated_by_execution_id=p_actor_execution_id,updated_at=clock_timestamp()
    where execution_id=p_execution_id and step_order=st.step_order and step_id=p_step_id;
  end if;

  return jsonb_build_object(
    'outcome','RECORDED','execution_id',p_execution_id,'operation_code',x.operation_code,
    'step_id',p_step_id,'step_order',st.step_order,'gate_id',p_gate_id,'gate_result',gate_result,
    'step_status_conflict',step_status_conflict,'summary',summary
  );
end;
$function$;

create or replace function public.lf_gate_check_diagnostic_v1(
  p_execution_id text,
  p_step_id text,
  p_gate_id text,
  p_attempt_no integer default 1
)
returns jsonb
language sql
security invoker
set search_path to 'pg_catalog','public'
as $function$
  with r as (
    select * from public.lf_operation_gate_check_results
    where execution_id=p_execution_id and step_id=p_step_id and gate_id=p_gate_id and attempt_no=p_attempt_no
    order by id
  ), agg as (
    select
      count(*) as check_count,
      count(*) filter(where check_status='PASS') as pass_count,
      count(*) filter(where check_status='FAIL') as fail_count,
      count(*) filter(where check_status='BLOCKED') as blocked_count,
      count(*) filter(where check_status='SKIPPED') as skipped_count,
      min(parent_trace_id) as parent_trace_id,
      min(batch_sha256) as batch_sha256,
      min(gate_mode) as gate_mode,
      min(operation_code) as operation_code,
      min(step_order) as step_order
    from r
  )
  select case when agg.check_count=0 then
    jsonb_build_object('outcome','NOT_FOUND','execution_id',p_execution_id,'step_id',p_step_id,'gate_id',p_gate_id,'attempt_no',p_attempt_no)
  else jsonb_build_object(
    'outcome','FOUND','contract','LF_GATE_ERROR_V1','execution_id',p_execution_id,'operation_code',agg.operation_code,
    'step_id',p_step_id,'step_order',agg.step_order,'gate_id',p_gate_id,'gate_mode',agg.gate_mode,'attempt_no',p_attempt_no,
    'gate_result',case when agg.blocked_count>0 or agg.skipped_count>0 then 'BLOCKED' when agg.fail_count>0 then 'FAIL' else 'PASS' end,
    'check_count',agg.check_count,'pass_count',agg.pass_count,'fail_count',agg.fail_count,'blocked_count',agg.blocked_count,'skipped_count',agg.skipped_count,
    'parent_trace_id',agg.parent_trace_id,'batch_sha256',agg.batch_sha256,
    'checks',(select jsonb_agg(jsonb_build_object(
      'check_id',check_id,'status',check_status,'error_id',error_id,'occurrence_id',error_occurrence_id,
      'error_class',error_class,'condition',condition,'expected',expected,'actual',actual,'input_ref',input_ref,
      'evidence_ref',evidence_ref,'producer',producer,'run_id',run_id,'job_id',job_id,
      'source_commit',source_commit,'source_path',source_path,'trace_id',trace_id,'parent_trace_id',parent_trace_id,
      'rc',rc,'downstream_impact',downstream_impact,'owner',owner,'next_action',next_action,'observed_at',observed_at
    ) order by id) from r)
  ) end
  from agg;
$function$;

revoke execute on function public.lf_record_gate_checks_v1(text,text,text,text,jsonb,jsonb,jsonb,text) from public, anon, authenticated;
revoke execute on function public.lf_gate_check_diagnostic_v1(text,text,text,integer) from public, anon, authenticated;
grant execute on function public.lf_record_gate_checks_v1(text,text,text,text,jsonb,jsonb,jsonb,text) to service_role;
grant execute on function public.lf_gate_check_diagnostic_v1(text,text,text,integer) to service_role;

comment on table public.lf_operation_gate_check_results is
  'Check-level ledger under the canonical LF operation execution/step workflow. Failures reuse lf_ops.errores_ocurrencias; this is not a parallel workflow or error system.';
comment on function public.lf_record_gate_checks_v1(text,text,text,text,jsonb,jsonb,jsonb,text) is
  'LF_GATE_ERROR_V1 recorder: COLLECT_ALL persists every declared check; FAIL_FAST_CRITICAL permits early stop only at the declared critical failing check.';

commit;
