begin;

alter table private.lf_repository_governance_bundle_v4
  drop constraint lf_repository_governance_bundle_v4_pkey;

alter table private.lf_repository_governance_bundle_v4
  add column revision_id bigint generated by default as identity;

alter table private.lf_repository_governance_bundle_v4
  add constraint lf_repository_governance_bundle_v4_pkey
  primary key (path, revision_id);

create or replace function public.get_lf_repository_governance_bundle_v4()
returns table(path text, expected_sha256 text, expected_git_blob text, control_kind text)
language sql
stable
security definer
set search_path='pg_catalog','private'
as $function$
  select distinct on (b.path)
         b.path,b.expected_sha256,b.expected_git_blob,b.control_kind
  from private.lf_repository_governance_bundle_v4 b
  where b.active
  order by b.path,b.revision_id desc;
$function$;

insert into private.lf_repository_governance_bundle_v4(
  path,expected_sha256,expected_git_blob,control_kind,active,
  approved_commit_sha,approved_by_execution_id
)
values
(
  '.github/workflows/lf-contract-check.yml',
  'd977c5707addaa4a25714437c0c5eb3f879e29eba0c700d43836afbd3bdba7de',
  '4874bd3c8c07f99d1f57917afd55a6684b01ec7b',
  'SOURCE_WORKFLOW',true,
  'dfb6385e55eb4ee533aa2f982633e8da1cdd22ea',
  'WORK-PR93-POSTMERGE-OIDC-RULESET-20260809'
),
(
  '.github/workflows/lf-github-reconcile-v3.yml',
  '0821aec5d5935f350185f68fddc0ec5d42b5bf024b6f62af8104ed322ee0ebb8',
  '2da6838b1f541facff4c9cad5ca61ebfbfaa12cc',
  'RECONCILIATION_WORKFLOW',true,
  '94d63f70249d0da99413a97c44981a8cc6860d9a',
  'WORK-PR93-POSTMERGE-OIDC-RULESET-20260809'
);

create table private.lf_schema_fingerprint_baseline_v13 (
  object_identity text primary key,
  object_type text not null check (object_type in ('TABLE','VIEW','FUNCTION','TRIGGER','CRON_JOB','ROLE')),
  definition_sha256 text not null check (definition_sha256 ~ '^[0-9a-f]{64}$'),
  definition_snapshot text not null,
  baseline_execution_id text not null,
  baselined_at timestamptz not null default clock_timestamp()
);

create or replace function private.fn_guard_schema_fingerprint_baseline_v13()
returns trigger
language plpgsql
set search_path='pg_catalog'
as $function$
begin
  if current_user<>'postgres' then
    raise exception using errcode='42501',message='schema fingerprint baseline v13 accepts inserts only from governed maintenance';
  end if;
  if tg_op in ('UPDATE','DELETE') then
    raise exception using errcode='55000',message='schema fingerprint baseline v13 is append-only';
  end if;
  return new;
end;
$function$;

revoke all on function private.fn_guard_schema_fingerprint_baseline_v13() from public,anon,authenticated,service_role;

alter table private.lf_schema_fingerprint_baseline_v13 enable row level security;
alter table private.lf_schema_fingerprint_baseline_v13 force row level security;
revoke all on private.lf_schema_fingerprint_baseline_v13 from public,anon,authenticated,service_role;

create policy pol_lf_schema_fingerprint_baseline_v13_postgres
on private.lf_schema_fingerprint_baseline_v13 for all to postgres using (true) with check (true);

create trigger trg_00_guard_lf_schema_fingerprint_baseline_v13
before insert or update or delete on private.lf_schema_fingerprint_baseline_v13
for each row execute function private.fn_guard_schema_fingerprint_baseline_v13();

create or replace view public.v_lf_schema_fingerprint_drift_v13
with (security_invoker=true)
as
select b.object_identity,b.object_type,b.definition_sha256 baseline_sha256,
       encode(extensions.digest(convert_to(private.fn_architecture_object_definition_v3(b.object_type,b.object_identity),'UTF8'),'sha256'),'hex') current_sha256,
       private.fn_architecture_object_definition_v3(b.object_type,b.object_identity)='<missing>' missing,
       encode(extensions.digest(convert_to(private.fn_architecture_object_definition_v3(b.object_type,b.object_identity),'UTF8'),'sha256'),'hex')<>b.definition_sha256 drifted
from private.lf_schema_fingerprint_baseline_v13 b
where b.object_identity not in (
  'public.v_lf_schema_fingerprint_drift_v13',
  'public.v_lf_architecture_closure_v4',
  'public.v_lf_architecture_closure_v5',
  'public.v_lf_architecture_closure_v6',
  'public.v_lf_architecture_closure_current'
);

revoke all on public.v_lf_schema_fingerprint_drift_v13 from anon,authenticated;

insert into private.lf_schema_fingerprint_baseline_v13(
  object_identity,object_type,definition_sha256,definition_snapshot,baseline_execution_id
)
select o.object_identity,o.object_type,
       encode(extensions.digest(convert_to(private.fn_architecture_object_definition_v3(o.object_type,o.object_identity),'UTF8'),'sha256'),'hex'),
       private.fn_architecture_object_definition_v3(o.object_type,o.object_identity),
       'WORK-PR93-BASELINE-V13-20260809'
from (
  select object_identity,object_type from private.lf_schema_fingerprint_baseline_v12
  union
  select 'private.lf_schema_fingerprint_baseline_v13','TABLE'
  union
  select 'private.fn_guard_schema_fingerprint_baseline_v13()','FUNCTION'
  union
  select 'public.v_lf_schema_fingerprint_drift_v13','VIEW'
) o
order by o.object_type,o.object_identity;

do $activate$
declare
  def text;
begin
  select pg_get_viewdef('public.v_lf_architecture_closure_v4'::regclass,true) into def;
  if position('v_lf_schema_fingerprint_drift_v12' in def)=0 then
    raise exception 'closure v4 does not reference v12';
  end if;
  def:=replace(def,'v_lf_schema_fingerprint_drift_v12','v_lf_schema_fingerprint_drift_v13');
  execute 'create or replace view public.v_lf_architecture_closure_v4 as '||def;
end;
$activate$;

do $assertions$
declare
  expected_count bigint;
  observed_count bigint;
  drift_count bigint;
  governance_count bigint;
begin
  select count(*)+3 into expected_count from private.lf_schema_fingerprint_baseline_v12;
  select count(*) into observed_count from private.lf_schema_fingerprint_baseline_v13;
  if observed_count<>expected_count then
    raise exception 'baseline v13 count mismatch expected %, got %',expected_count,observed_count;
  end if;

  select count(*) into drift_count
  from public.v_lf_schema_fingerprint_drift_v13
  where drifted or missing;
  if drift_count<>0 then
    raise exception 'baseline v13 unexpected drift count %',drift_count;
  end if;

  if position('v_lf_schema_fingerprint_drift_v13' in pg_get_viewdef('public.v_lf_architecture_closure_v4'::regclass,true))=0 then
    raise exception 'closure v4 did not switch to baseline v13';
  end if;

  select count(*) into governance_count
  from public.get_lf_repository_governance_bundle_v4();
  if governance_count<>7 then
    raise exception 'governance bundle count mismatch expected 7, got %',governance_count;
  end if;

  if not exists (
    select 1 from public.get_lf_repository_governance_bundle_v4()
    where path='.github/workflows/lf-contract-check.yml'
      and expected_sha256='d977c5707addaa4a25714437c0c5eb3f879e29eba0c700d43836afbd3bdba7de'
      and expected_git_blob='4874bd3c8c07f99d1f57917afd55a6684b01ec7b'
  ) then
    raise exception 'source workflow governance revision missing';
  end if;

  if not exists (
    select 1 from public.get_lf_repository_governance_bundle_v4()
    where path='.github/workflows/lf-github-reconcile-v3.yml'
      and expected_sha256='0821aec5d5935f350185f68fddc0ec5d42b5bf024b6f62af8104ed322ee0ebb8'
      and expected_git_blob='2da6838b1f541facff4c9cad5ca61ebfbfaa12cc'
  ) then
    raise exception 'reconciliation workflow governance revision missing';
  end if;
end;
$assertions$;

commit;

