create table if not exists lf_ops.system_audit_campaigns (
  campaign_id bigint generated by default as identity primary key,
  campaign_code text not null unique,
  title text not null,
  objective text not null,
  status text not null default 'ACTIVE' check (status in ('DRAFT','ACTIVE','PAUSED','COMPLETED','CANCELLED')),
  min_benchmark_cases integer not null default 200 check (min_benchmark_cases >= 200),
  operating_policy jsonb not null default '{}'::jsonb,
  gpt_role text not null default 'BUILDER_REMEDIATOR',
  claude_role text not null default 'INDEPENDENT_AUDITOR',
  human_decisions_deferred boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists lf_ops.system_audit_queue (
  work_id bigint generated by default as identity primary key,
  campaign_id bigint not null references lf_ops.system_audit_campaigns(campaign_id) on delete restrict,
  asset_type text not null,
  asset_code text not null,
  asset_ref jsonb not null default '{}'::jsonb,
  priority integer not null default 100,
  status text not null default 'DISCOVERED' check (status in ('DISCOVERED','BASELINING','GPT_AUDIT','GPT_REMEDIATING','GPT_TESTED','CLAUDE_REVIEW','REOPEN','HUMAN_DECISION','VERIFIED','PROVEN_REJECTED','BLOCKED')),
  current_owner text check (current_owner in ('GPT','CLAUDE','HUMAN') or current_owner is null),
  attempt_count integer not null default 0,
  root_cause_state text not null default 'NOT_STARTED' check (root_cause_state in ('NOT_STARTED','TRACING','HYPOTHESIS','PROVEN','NOT_PROVEN')),
  content_trace_state text not null default 'NOT_STARTED' check (content_trace_state in ('NOT_STARTED','PARTIAL','COMPLETE')),
  champion_state text not null default 'UNASSESSED' check (champion_state in ('UNASSESSED','BASELINE','CANDIDATE','CHAMPION','RUNNER_UP','REJECTED')),
  parent_work_id bigint references lf_ops.system_audit_queue(work_id) on delete restrict,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(campaign_id, asset_type, asset_code)
);

create table if not exists lf_ops.system_audit_runs (
  run_id bigint generated by default as identity primary key,
  campaign_id bigint not null references lf_ops.system_audit_campaigns(campaign_id) on delete restrict,
  work_id bigint references lf_ops.system_audit_queue(work_id) on delete restrict,
  agent text not null check (agent in ('GPT','CLAUDE')),
  external_execution_id text,
  run_status text not null check (run_status in ('PASS','FAIL','PARTIAL','BLOCKED','REOPEN','HUMAN_DECISION','NO_WORK')),
  progress_pct numeric(5,2) not null check (progress_pct >= 0 and progress_pct <= 100),
  scope_summary text not null,
  actual_content_trace jsonb not null default '{}'::jsonb,
  root_cause_analysis jsonb not null default '{}'::jsonb,
  alternatives_analysis jsonb not null default '[]'::jsonb,
  actions_taken jsonb not null default '[]'::jsonb,
  verification jsonb not null default '{}'::jsonb,
  metrics jsonb not null default '{}'::jsonb,
  evidence_refs jsonb not null default '[]'::jsonb,
  handoff jsonb not null default '{}'::jsonb,
  report_md text not null check (length(btrim(report_md)) >= 40),
  compacted boolean not null default false,
  supersedes_run_id bigint references lf_ops.system_audit_runs(run_id) on delete restrict,
  started_at timestamptz not null,
  completed_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  unique(agent, external_execution_id)
);

create table if not exists lf_ops.system_audit_findings (
  finding_id bigint generated by default as identity primary key,
  campaign_id bigint not null references lf_ops.system_audit_campaigns(campaign_id) on delete restrict,
  work_id bigint references lf_ops.system_audit_queue(work_id) on delete restrict,
  source_run_id bigint not null references lf_ops.system_audit_runs(run_id) on delete restrict,
  finding_code text not null,
  finding_class text not null,
  severity text not null check (severity in ('LOW','MEDIUM','HIGH','CRITICAL')),
  symptom text not null,
  first_bad_hop text,
  root_cause_status text not null default 'NOT_PROVEN' check (root_cause_status in ('NOT_PROVEN','PROVEN')),
  root_cause text,
  content_evidence jsonb not null default '{}'::jsonb,
  alternatives jsonb not null default '[]'::jsonb,
  remediation_status text not null default 'OPEN' check (remediation_status in ('OPEN','REMEDIATING','RETEST','VERIFIED','PROVEN_REJECTED','DEFERRED_HUMAN')),
  human_decision_required boolean not null default false,
  status text not null default 'OPEN' check (status in ('OPEN','REOPENED','RESOLVED','ACCEPTED_RISK','PROVEN_REJECTED')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(campaign_id, finding_code)
);

create table if not exists lf_ops.system_audit_messages (
  message_id bigint generated by default as identity primary key,
  campaign_id bigint not null references lf_ops.system_audit_campaigns(campaign_id) on delete restrict,
  work_id bigint references lf_ops.system_audit_queue(work_id) on delete restrict,
  from_agent text not null check (from_agent in ('GPT','CLAUDE','SYSTEM')),
  to_agent text not null check (to_agent in ('GPT','CLAUDE','BOTH')),
  message_type text not null check (message_type in ('HANDOFF','REOPEN','EVIDENCE_REQUEST','EVIDENCE_RESPONSE','AUDIT_RESULT','CONTROL')),
  compact_summary text not null,
  payload jsonb not null default '{}'::jsonb,
  acknowledged_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists lf_ops.system_audit_human_decisions (
  decision_id bigint generated by default as identity primary key,
  campaign_id bigint not null references lf_ops.system_audit_campaigns(campaign_id) on delete restrict,
  work_id bigint references lf_ops.system_audit_queue(work_id) on delete restrict,
  finding_id bigint references lf_ops.system_audit_findings(finding_id) on delete restrict,
  decision_code text not null,
  question text not null,
  options jsonb not null,
  recommendation text,
  risk_if_deferred text,
  status text not null default 'PENDING' check (status in ('PENDING','DECIDED','SUPERSEDED')),
  decision_value jsonb,
  created_at timestamptz not null default now(),
  decided_at timestamptz,
  unique(campaign_id, decision_code)
);

create table if not exists lf_ops.system_audit_premises (
  premise_id bigint generated by default as identity primary key,
  campaign_id bigint not null references lf_ops.system_audit_campaigns(campaign_id) on delete restrict,
  premise_code text not null,
  statement text not null,
  status text not null default 'PROPOSED' check (status in ('PROPOSED','PROVEN','SUPERSEDED','DEPRECATED')),
  scope jsonb not null default '[]'::jsonb,
  evidence_refs jsonb not null default '[]'::jsonb,
  last_validated_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(campaign_id, premise_code)
);

create index if not exists idx_system_audit_queue_next on lf_ops.system_audit_queue(campaign_id, status, priority, work_id);
create index if not exists idx_system_audit_runs_campaign_time on lf_ops.system_audit_runs(campaign_id, completed_at desc);
create index if not exists idx_system_audit_findings_open on lf_ops.system_audit_findings(campaign_id, status, severity);
create index if not exists idx_system_audit_messages_inbox on lf_ops.system_audit_messages(campaign_id, to_agent, acknowledged_at, message_id);
create index if not exists idx_system_audit_decisions_pending on lf_ops.system_audit_human_decisions(campaign_id, status, decision_id);

create or replace view lf_ops.v_system_audit_reports as
select r.run_id, c.campaign_code, r.agent, r.run_status, r.progress_pct, r.scope_summary,
       r.report_md, r.metrics, r.evidence_refs, r.completed_at, q.asset_type, q.asset_code
from lf_ops.system_audit_runs r
join lf_ops.system_audit_campaigns c on c.campaign_id = r.campaign_id
left join lf_ops.system_audit_queue q on q.work_id = r.work_id;

create or replace view lf_ops.v_system_audit_pending_human as
select d.decision_id, c.campaign_code, d.decision_code, d.question, d.options, d.recommendation,
       d.risk_if_deferred, d.created_at, q.asset_type, q.asset_code
from lf_ops.system_audit_human_decisions d
join lf_ops.system_audit_campaigns c on c.campaign_id = d.campaign_id
left join lf_ops.system_audit_queue q on q.work_id = d.work_id
where d.status = 'PENDING';