-- INPUT GOVERNANCE AGENT v0.1
-- Scope: two minimal readiness structures + agent/components/contract registration.
-- No LF rule mutation, no production activation.

insert into programacion.agentes (agente_codigo,nombre,proposito,transversal,estado)
select
  'INPUT_GOVERNANCE_AGENT',
  'Agente de gobernanza de inputs',
  'Curar y validar de forma transversal los inputs funcionales antes de Story Creator y Programming Agent, sin inventar fuentes ni autoaprobar sus propias conclusiones.',
  true,
  'draft'
where not exists (
  select 1 from programacion.agentes where agente_codigo='INPUT_GOVERNANCE_AGENT'
);

insert into programacion.versiones_agente (agente_id,version_codigo,objetivo,estado,notas)
select
  a.id,
  'v0.1-input-readiness-governance',
  'Evaluar el universo canónico de familias de input por pantalla, separar cobertura de readiness, preservar provenance/freshness y exigir validación independiente antes de consumir el resultado en Story Creator.',
  'draft',
  'DISCOVERY_COMPLETE_DESIGN_APPROVED. Reutiliza programacion/transversal/lf_ops/lf_design. No activa producción ni promoción automática. Piloto B2B-AUTH-001 y auditoría independiente todavía requeridos.'
from programacion.agentes a
where a.agente_codigo='INPUT_GOVERNANCE_AGENT'
  and not exists (
    select 1 from programacion.versiones_agente v
    where v.agente_id=a.id and v.version_codigo='v0.1-input-readiness-governance'
  );

insert into programacion.componentes
(version_id,componente_codigo,tipo,nombre,responsabilidad,orden_ejecucion,independencia_requerida,configuracion,estado)
select v.id,'INPUT_CURATOR','curator','Input Curator',
       'Descubrir fuentes canónicas, evaluar aplicabilidad y proponer por familia cobertura, definición, readiness, blockers, negativos, pruebas y provenance sin rellenar gaps por inferencia.',
       1,false,
       jsonb_build_object(
         'source_precedence',jsonb_build_array('lf_ops','lf_design','transversal','programacion'),
         'writes_only_curator_fields',true,
         'self_validation',false,
         'no_invention',true,
         'minimum_sufficient_context',true
       ),'defined'
from programacion.versiones_agente v
join programacion.agentes a on a.id=v.agente_id
where a.agente_codigo='INPUT_GOVERNANCE_AGENT'
  and v.version_codigo='v0.1-input-readiness-governance'
  and not exists (
    select 1 from programacion.componentes c where c.version_id=v.id and c.componente_codigo='INPUT_CURATOR'
  );

insert into programacion.componentes
(version_id,componente_codigo,tipo,nombre,responsabilidad,orden_ejecucion,independencia_requerida,configuracion,estado)
select v.id,'INPUT_VALIDATOR','validator','Input Validator',
       'Intentar invalidar la salida del Curator mediante readback directo, validaciones determinísticas, checks semánticos y evidencia independiente; no puede modificar los campos curatoriales.',
       2,true,
       jsonb_build_object(
         'direct_source_readback_required',true,
         'deterministic_checks_first',true,
         'semantic_validation_required',true,
         'llm_as_sole_gate',false,
         'candidate_as_own_authority',false,
         'writes_only_validator_fields',true
       ),'defined'
from programacion.versiones_agente v
join programacion.agentes a on a.id=v.agente_id
where a.agente_codigo='INPUT_GOVERNANCE_AGENT'
  and v.version_codigo='v0.1-input-readiness-governance'
  and not exists (
    select 1 from programacion.componentes c where c.version_id=v.id and c.componente_codigo='INPUT_VALIDATOR'
  );

create table programacion.input_readiness_runs (
  id bigint generated by default as identity primary key,
  version_id bigint not null references programacion.versiones_agente(id),
  pantalla_id integer not null references lf_ops.pantallas(id),
  universe_rule_id integer not null references lf_ops.reglas(id),
  supersedes_run_id bigint null references programacion.input_readiness_runs(id),
  scope jsonb not null default '{}'::jsonb check (jsonb_typeof(scope)='object'),
  source_snapshot_sha256 text not null check (source_snapshot_sha256 ~ '^[0-9a-f]{64}$'),
  universe_snapshot_sha256 text not null check (universe_snapshot_sha256 ~ '^[0-9a-f]{64}$'),
  family_count integer not null check (family_count > 0),
  status text not null default 'CURATING' check (status in ('CURATING','VALIDATING','COMPLETED','BLOCKED')),
  curator_identity text not null check (length(btrim(curator_identity))>0),
  curator_completed_at timestamptz,
  validator_identity text,
  validator_completed_at timestamptz,
  blocked_reason text,
  created_at timestamptz not null default now(),
  check ((status <> 'VALIDATING') or curator_completed_at is not null),
  check ((status <> 'COMPLETED') or (curator_completed_at is not null and validator_completed_at is not null and validator_identity is not null)),
  check ((status <> 'BLOCKED') or length(btrim(coalesce(blocked_reason,'')))>0)
);

create index idx_input_readiness_runs_screen_created
  on programacion.input_readiness_runs(pantalla_id,created_at desc);
create index idx_input_readiness_runs_status
  on programacion.input_readiness_runs(status);
create index idx_input_readiness_runs_supersedes
  on programacion.input_readiness_runs(supersedes_run_id) where supersedes_run_id is not null;

create table programacion.input_family_assessments (
  id bigint generated by default as identity primary key,
  run_id bigint not null references programacion.input_readiness_runs(id) on delete cascade,
  family_code text not null,
  severity text not null check (severity in ('P0','P1','P2','P3','P4')),
  applicability text not null check (applicability in ('APPLICABLE','NOT_APPLICABLE','UNRESOLVED')),
  coverage_status text not null check (coverage_status in ('COMPLETE','PARTIAL','MISSING','NOT_APPLICABLE','PENDING','BLOCKED')),
  well_defined_status text not null check (well_defined_status in ('COMPLETE','PARTIAL','MISSING','NOT_APPLICABLE','PENDING','BLOCKED')),
  story_ready_status text not null check (story_ready_status in ('READY','NOT_READY','NOT_APPLICABLE','PENDING','BLOCKED')),
  implementation_ready_status text not null check (implementation_ready_status in ('READY','NOT_READY','NOT_APPLICABLE','PENDING','BLOCKED')),
  qa_ready_status text not null check (qa_ready_status in ('READY','NOT_READY','NOT_APPLICABLE','PENDING','BLOCKED')),
  production_ready_status text not null check (production_ready_status in ('READY','NOT_READY','NOT_APPLICABLE','PENDING','BLOCKED')),
  source_refs jsonb not null default '[]'::jsonb check (jsonb_typeof(source_refs)='array'),
  rationale text not null check (length(btrim(rationale))>0),
  blockers jsonb not null default '[]'::jsonb check (jsonb_typeof(blockers)='array'),
  negative_requirements jsonb not null default '[]'::jsonb check (jsonb_typeof(negative_requirements)='array'),
  test_obligations jsonb not null default '[]'::jsonb check (jsonb_typeof(test_obligations)='array'),
  freshness jsonb not null default '{}'::jsonb check (jsonb_typeof(freshness)='object'),
  curator_evidence jsonb not null default '{}'::jsonb check (jsonb_typeof(curator_evidence)='object'),
  curator_sha256 text not null check (curator_sha256 ~ '^[0-9a-f]{64}$'),
  validator_outcome text not null default 'PENDING' check (validator_outcome in ('PENDING','PASS','FAIL','BLOCKED')),
  validator_findings jsonb not null default '[]'::jsonb check (jsonb_typeof(validator_findings)='array'),
  validator_evidence jsonb not null default '{}'::jsonb check (jsonb_typeof(validator_evidence)='object'),
  validator_identity text,
  validator_sha256 text check (validator_sha256 is null or validator_sha256 ~ '^[0-9a-f]{64}$'),
  validator_assessed_at timestamptz,
  created_at timestamptz not null default now(),
  unique(run_id,family_code),
  check ((applicability <> 'NOT_APPLICABLE') or (
    coverage_status='NOT_APPLICABLE' and well_defined_status='NOT_APPLICABLE' and
    story_ready_status='NOT_APPLICABLE' and implementation_ready_status='NOT_APPLICABLE' and
    qa_ready_status='NOT_APPLICABLE' and production_ready_status='NOT_APPLICABLE'
  )),
  check ((validator_outcome='PENDING' and validator_identity is null and validator_assessed_at is null and validator_sha256 is null)
      or (validator_outcome<>'PENDING' and validator_identity is not null and validator_assessed_at is not null and validator_sha256 is not null))
);

create index idx_input_family_assessments_run
  on programacion.input_family_assessments(run_id);
create index idx_input_family_assessments_family
  on programacion.input_family_assessments(family_code);
create index idx_input_family_assessments_validator_outcome
  on programacion.input_family_assessments(validator_outcome);

comment on table programacion.input_readiness_runs is
'Input Governance run bound to a canonical screen, canonical 47-family universe rule and source/universe digests. Completion means validation complete, not that every readiness level is READY.';
comment on table programacion.input_family_assessments is
'One immutable Curator assessment per canonical input family plus an independently writable Validator receipt. Curator fields cannot be updated after insert.';

create or replace function programacion.fn_guard_input_family_assessment_insert()
returns trigger
language plpgsql
security definer
set search_path='pg_catalog','public','programacion','lf_ops'
as $fn$
declare
  v_status text;
  v_families jsonb;
  v_payload jsonb;
begin
  select r.status, q.valor_config->'families'
    into v_status, v_families
  from programacion.input_readiness_runs r
  join lf_ops.reglas q on q.id=r.universe_rule_id
  where r.id=new.run_id;

  if v_status is null then
    raise exception 'INPUT_READINESS_RUN_NOT_FOUND';
  end if;
  if v_status <> 'CURATING' then
    raise exception 'CURATOR_INSERT_CLOSED_FOR_RUN_STATUS_%', v_status;
  end if;
  if jsonb_typeof(v_families) <> 'array' or not (v_families ? new.family_code) then
    raise exception 'FAMILY_NOT_IN_CANONICAL_UNIVERSE:%', new.family_code;
  end if;
  if jsonb_array_length(new.source_refs)=0 then
    raise exception 'SOURCE_REFS_REQUIRED:%', new.family_code;
  end if;
  if new.applicability='UNRESOLVED' and new.story_ready_status='READY' then
    raise exception 'UNRESOLVED_APPLICABILITY_CANNOT_BE_STORY_READY:%', new.family_code;
  end if;
  if new.validator_outcome <> 'PENDING' or new.validator_identity is not null or new.validator_sha256 is not null or new.validator_assessed_at is not null then
    raise exception 'CURATOR_CANNOT_PREVALIDATE:%', new.family_code;
  end if;

  v_payload:=jsonb_build_object(
    'run_id',new.run_id,
    'family_code',new.family_code,
    'severity',new.severity,
    'applicability',new.applicability,
    'coverage_status',new.coverage_status,
    'well_defined_status',new.well_defined_status,
    'story_ready_status',new.story_ready_status,
    'implementation_ready_status',new.implementation_ready_status,
    'qa_ready_status',new.qa_ready_status,
    'production_ready_status',new.production_ready_status,
    'source_refs',new.source_refs,
    'rationale',new.rationale,
    'blockers',new.blockers,
    'negative_requirements',new.negative_requirements,
    'test_obligations',new.test_obligations,
    'freshness',new.freshness,
    'curator_evidence',new.curator_evidence
  );
  new.curator_sha256:=programacion.fn_v09_sha256_jsonb(v_payload);
  return new;
end;$fn$;

create trigger trg_input_family_assessment_insert
before insert on programacion.input_family_assessments
for each row execute function programacion.fn_guard_input_family_assessment_insert();

create or replace function programacion.fn_guard_input_family_assessment_update()
returns trigger
language plpgsql
security definer
set search_path='pg_catalog','public','programacion'
as $fn$
declare
  v_payload jsonb;
begin
  if new.run_id is distinct from old.run_id
     or new.family_code is distinct from old.family_code
     or new.severity is distinct from old.severity
     or new.applicability is distinct from old.applicability
     or new.coverage_status is distinct from old.coverage_status
     or new.well_defined_status is distinct from old.well_defined_status
     or new.story_ready_status is distinct from old.story_ready_status
     or new.implementation_ready_status is distinct from old.implementation_ready_status
     or new.qa_ready_status is distinct from old.qa_ready_status
     or new.production_ready_status is distinct from old.production_ready_status
     or new.source_refs is distinct from old.source_refs
     or new.rationale is distinct from old.rationale
     or new.blockers is distinct from old.blockers
     or new.negative_requirements is distinct from old.negative_requirements
     or new.test_obligations is distinct from old.test_obligations
     or new.freshness is distinct from old.freshness
     or new.curator_evidence is distinct from old.curator_evidence
     or new.curator_sha256 is distinct from old.curator_sha256
     or new.created_at is distinct from old.created_at then
    raise exception 'CURATOR_FIELDS_IMMUTABLE:%', old.family_code;
  end if;

  if old.validator_outcome <> 'PENDING' then
    raise exception 'VALIDATOR_RECEIPT_IMMUTABLE:%', old.family_code;
  end if;
  if new.validator_outcome='PENDING' then
    raise exception 'VALIDATOR_UPDATE_MUST_BE_TERMINAL:%', old.family_code;
  end if;
  if new.validator_identity is null or length(btrim(new.validator_identity))=0 then
    raise exception 'VALIDATOR_IDENTITY_REQUIRED:%', old.family_code;
  end if;
  if new.validator_assessed_at is null then
    new.validator_assessed_at:=now();
  end if;
  if jsonb_typeof(new.validator_evidence)<>'object' or new.validator_evidence='{}'::jsonb then
    raise exception 'VALIDATOR_EVIDENCE_REQUIRED:%', old.family_code;
  end if;

  v_payload:=jsonb_build_object(
    'curator_sha256',old.curator_sha256,
    'validator_outcome',new.validator_outcome,
    'validator_findings',new.validator_findings,
    'validator_evidence',new.validator_evidence,
    'validator_identity',new.validator_identity,
    'validator_assessed_at',new.validator_assessed_at
  );
  new.validator_sha256:=programacion.fn_v09_sha256_jsonb(v_payload);
  return new;
end;$fn$;

create trigger trg_input_family_assessment_update
before update on programacion.input_family_assessments
for each row execute function programacion.fn_guard_input_family_assessment_update();

create or replace function programacion.fn_guard_input_readiness_run()
returns trigger
language plpgsql
security definer
set search_path='pg_catalog','public','programacion','lf_ops'
as $fn$
declare
  v_agent_code text;
  v_rule_code text;
  v_families jsonb;
  v_universe_payload jsonb;
  v_expected_count integer;
  v_assessment_count integer;
  v_pass_count integer;
begin
  if tg_op='INSERT' then
    select a.agente_codigo into v_agent_code
    from programacion.versiones_agente v join programacion.agentes a on a.id=v.agente_id
    where v.id=new.version_id;
    if v_agent_code <> 'INPUT_GOVERNANCE_AGENT' then
      raise exception 'INVALID_INPUT_GOVERNANCE_AGENT_VERSION';
    end if;

    select q.codigo,q.valor_config->'families' into v_rule_code,v_families
    from lf_ops.reglas q where q.id=new.universe_rule_id;
    if v_rule_code <> 'B2B-RULE-STORY-READINESS-001' then
      raise exception 'INVALID_INPUT_FAMILY_UNIVERSE_RULE:%', coalesce(v_rule_code,'NULL');
    end if;
    if jsonb_typeof(v_families)<>'array' then
      raise exception 'INVALID_CANONICAL_FAMILY_UNIVERSE';
    end if;
    v_expected_count:=jsonb_array_length(v_families);
    if new.family_count<>v_expected_count then
      raise exception 'FAMILY_COUNT_MISMATCH expected=% actual=%',v_expected_count,new.family_count;
    end if;
    v_universe_payload:=jsonb_build_object('rule_code',v_rule_code,'families',v_families);
    if new.universe_snapshot_sha256<>programacion.fn_v09_sha256_jsonb(v_universe_payload) then
      raise exception 'UNIVERSE_SNAPSHOT_DIGEST_MISMATCH';
    end if;
    return new;
  end if;

  if new.version_id is distinct from old.version_id
     or new.pantalla_id is distinct from old.pantalla_id
     or new.universe_rule_id is distinct from old.universe_rule_id
     or new.supersedes_run_id is distinct from old.supersedes_run_id
     or new.scope is distinct from old.scope
     or new.source_snapshot_sha256 is distinct from old.source_snapshot_sha256
     or new.universe_snapshot_sha256 is distinct from old.universe_snapshot_sha256
     or new.family_count is distinct from old.family_count
     or new.curator_identity is distinct from old.curator_identity
     or new.created_at is distinct from old.created_at then
    raise exception 'INPUT_READINESS_RUN_IDENTITY_IMMUTABLE';
  end if;

  if old.status in ('COMPLETED','BLOCKED') then
    raise exception 'TERMINAL_INPUT_READINESS_RUN_IMMUTABLE';
  end if;

  if old.status='CURATING' and new.status not in ('CURATING','VALIDATING','BLOCKED') then
    raise exception 'INVALID_RUN_TRANSITION:%->%',old.status,new.status;
  end if;
  if old.status='VALIDATING' and new.status not in ('VALIDATING','COMPLETED','BLOCKED') then
    raise exception 'INVALID_RUN_TRANSITION:%->%',old.status,new.status;
  end if;

  if new.status='VALIDATING' and old.status<>'VALIDATING' then
    if new.curator_completed_at is null then new.curator_completed_at:=now(); end if;
    select count(*) into v_assessment_count from programacion.input_family_assessments where run_id=old.id;
    if v_assessment_count<>old.family_count then
      raise exception 'CURATOR_UNIVERSE_INCOMPLETE expected=% actual=%',old.family_count,v_assessment_count;
    end if;
  end if;

  if new.status='COMPLETED' then
    if new.validator_identity is null or length(btrim(new.validator_identity))=0 then
      raise exception 'RUN_VALIDATOR_IDENTITY_REQUIRED';
    end if;
    if new.validator_completed_at is null then new.validator_completed_at:=now(); end if;
    select count(*), count(*) filter(where validator_outcome='PASS')
      into v_assessment_count,v_pass_count
    from programacion.input_family_assessments where run_id=old.id;
    if v_assessment_count<>old.family_count or v_pass_count<>old.family_count then
      raise exception 'VALIDATOR_UNIVERSE_NOT_FULL_PASS expected=% assessed=% pass=%',old.family_count,v_assessment_count,v_pass_count;
    end if;
  end if;

  return new;
end;$fn$;

create trigger trg_input_readiness_run_insert
before insert on programacion.input_readiness_runs
for each row execute function programacion.fn_guard_input_readiness_run();
create trigger trg_input_readiness_run_update
before update on programacion.input_readiness_runs
for each row execute function programacion.fn_guard_input_readiness_run();

alter table programacion.input_readiness_runs enable row level security;
alter table programacion.input_readiness_runs force row level security;
alter table programacion.input_family_assessments enable row level security;
alter table programacion.input_family_assessments force row level security;

revoke all on programacion.input_readiness_runs from public, anon, authenticated, service_role;
revoke all on programacion.input_family_assessments from public, anon, authenticated, service_role;

create policy p_input_readiness_runs_read on programacion.input_readiness_runs
for select to programacion_builder,programacion_verifier,programacion_auditor,programacion_human_authority using (true);
create policy p_input_readiness_runs_builder_insert on programacion.input_readiness_runs
for insert to programacion_builder with check (true);
create policy p_input_readiness_runs_builder_update on programacion.input_readiness_runs
for update to programacion_builder using (true) with check (true);
create policy p_input_readiness_runs_verifier_update on programacion.input_readiness_runs
for update to programacion_verifier using (true) with check (true);

create policy p_input_family_assessments_read on programacion.input_family_assessments
for select to programacion_builder,programacion_verifier,programacion_auditor,programacion_human_authority using (true);
create policy p_input_family_assessments_builder_insert on programacion.input_family_assessments
for insert to programacion_builder with check (true);
create policy p_input_family_assessments_verifier_update on programacion.input_family_assessments
for update to programacion_verifier using (true) with check (true);

grant select,insert on programacion.input_readiness_runs to programacion_builder;
grant update(status,curator_completed_at,blocked_reason) on programacion.input_readiness_runs to programacion_builder;
grant select on programacion.input_readiness_runs to programacion_verifier,programacion_auditor,programacion_human_authority;
grant update(status,validator_identity,validator_completed_at,blocked_reason) on programacion.input_readiness_runs to programacion_verifier;
grant usage on sequence programacion.input_readiness_runs_id_seq to programacion_builder;

grant select,insert on programacion.input_family_assessments to programacion_builder;
grant select on programacion.input_family_assessments to programacion_verifier,programacion_auditor,programacion_human_authority;
grant update(validator_outcome,validator_findings,validator_evidence,validator_identity,validator_sha256,validator_assessed_at)
  on programacion.input_family_assessments to programacion_verifier;
grant usage on sequence programacion.input_family_assessments_id_seq to programacion_builder;

insert into programacion.contratos
(version_id,contrato_codigo,tipo,nombre,descripcion,productor_componente_id,consumidor_componente_id,especificacion,fail_closed,estado)
select
  v.id,
  'INPUT_READINESS_CONTRACT',
  'governance',
  'Input Readiness Contract',
  'Contrato fail-closed para convertir fuentes canónicas de una pantalla en una evaluación validada de las familias de input, separando cobertura de readiness y Curator de Validator.',
  validator.id,
  null,
  jsonb_build_object(
    'schema_version',1,
    'canonical_universe_rule','B2B-RULE-STORY-READINESS-001',
    'family_universe_source','lf_ops.reglas.valor_config.families',
    'source_precedence',jsonb_build_array('lf_ops','lf_design','transversal','programacion'),
    'statuses',jsonb_build_array('COMPLETE','PARTIAL','MISSING','NOT_APPLICABLE','PENDING','BLOCKED'),
    'readiness_levels',jsonb_build_array('coverage','well_defined','story_ready','implementation_ready','qa_ready','production_ready'),
    'story_ready_rule','NO_APPLICABLE_P0_OPEN',
    'curator_fields_immutable_after_insert',true,
    'validator_independence_required',true,
    'candidate_as_own_authority','DENY',
    'llm_as_sole_gate','DENY',
    'direct_source_readback_required',true,
    'not_applicable_requires_reason',true,
    'source_refs_required_per_family',true,
    'negative_tests',jsonb_build_array(
      'MISSING_SOURCE','CONTRADICTORY_SOURCE','BROKEN_ID','INVENTED_URL','TIMEOUT_WITHOUT_SOURCE',
      'UNJUSTIFIED_NOT_APPLICABLE','STALE_EVIDENCE','HISTORICAL_PASS_OVERRIDES_NEWER_FAILURE',
      'SELF_AUTHORITY','AMBIGUOUS_INPUT','UNTESTABLE_REQUIREMENT','SEMANTIC_DUPLICATION'
    ),
    'data_placement',jsonb_build_object(
      'runs','programacion.input_readiness_runs',
      'family_assessments','programacion.input_family_assessments',
      'reuse',jsonb_build_array('programacion.contratos','programacion.provenance_receipts','programacion.retrieval_runs','programacion.retrieval_items','programacion.traceability_graphs','programacion.test_contracts','programacion.human_decisions','transversal.*')
    ),
    'consumer','STORY_CREATOR',
    'auto_promotion',false,
    'production_activation',false
  ),
  true,
  'defined'
from programacion.versiones_agente v
join programacion.agentes a on a.id=v.agente_id
join programacion.componentes validator on validator.version_id=v.id and validator.componente_codigo='INPUT_VALIDATOR'
where a.agente_codigo='INPUT_GOVERNANCE_AGENT'
  and v.version_codigo='v0.1-input-readiness-governance'
  and not exists (
    select 1 from programacion.contratos c where c.version_id=v.id and c.contrato_codigo='INPUT_READINESS_CONTRACT'
  );