-- STRATEGY_CLOSE transversal governance. CLOSE != SUPERSEDE. Source-first; no Strategy is closed by this migration.
DO $pre$ DECLARE c int; d text; BEGIN
 IF EXISTS(select 1 from public.lf_operation_registry where operation_code='CIERRE_ESTRATEGIA_LF') THEN raise exception 'LF_STRATEGY_CLOSE_OPERATION_EXISTS'; END IF;
 IF EXISTS(select 1 from public.lf_router_action_registry where asset_type='STRATEGY' and action_code='STRATEGY_CLOSE') THEN raise exception 'LF_STRATEGY_CLOSE_ROUTE_EXISTS'; END IF;
 SELECT count(*) INTO c FROM public.lf_activos WHERE codigo_activo IN ('POL-LF-OPERATION-LIFECYCLE','POL-LF-POLICY-CONSUMPTION','POL-LF-SOURCE-RESOLUTION','POL-LF-STATE-MODEL');
 IF c<>4 THEN raise exception 'LF_STRATEGY_CLOSE_POLICY_GAP:%',c; END IF;
 SELECT pg_get_functiondef('public.lf_router_resolve_v1(text,text,text,text,text)'::regprocedure) INTO d;
 IF strpos(d,$x$elsif v_req ~ '(^| )(policy|politica|regla)( |$)' then v_type_hint := 'REGLA';$x$)=0 OR strpos(d,$x$if v_req ~ '(^| )(consulta|consultar|estado|metadata|existe)( |$)' then v_action:='ASSET_INSPECTION';$x$)=0 THEN raise exception 'LF_STRATEGY_CLOSE_ROUTER_SOURCE_DRIFT'; END IF;
END $pre$;

INSERT INTO public.lf_operation_execution(execution_id,operation_code,target_type,target_code,status,manifest,created_by_execution_id,updated_by_execution_id)
VALUES('EXEC-BOOTSTRAP-CIERRE-ESTRATEGIA-LF-20260914-001','VULNERABILITY_COVERAGE_REPAIR_LF','OPERATION_PROTOCOL_REPAIR','CIERRE_ESTRATEGIA_LF','IN_PROGRESS','{"governance_bootstrap":true,"bootstrap_operation_code":"CIERRE_ESTRATEGIA_LF","bootstrap_status_ceiling":"SANDBOX_ACTIVE","production_allowed":false,"runtime_activation":false,"strategy_mutation_during_migration":false}'::jsonb,'EXEC-BOOTSTRAP-CIERRE-ESTRATEGIA-LF-20260914-001','EXEC-BOOTSTRAP-CIERRE-ESTRATEGIA-LF-20260914-001');

INSERT INTO public.lf_operation_registry(operation_code,version,status,source_model,source_repo,source_paths,notes,operation_family,operation_domain,operation_type,applies_to_asset_type,created_by_execution_id)
VALUES('CIERRE_ESTRATEGIA_LF','v0.1','SANDBOX_ACTIVE','SUPABASE_STRUCTURED_OPERATION','cristhianlujan/claude-persona-lf-patch','["supabase/migrations/20260914020000_lf_strategy_close_transversal_v1.sql","public.lf_strategy_close_write_v1","public.v_lf_strategy_latest","public.lf_router_resolve_v1"]'::jsonb,'Terminal governed Strategy close; exact currentness, zero executable work, explicit backlog/risk disposition, immutable receipt, read-only event stream. No supersede/runtime/production promotion.','STRATEGY_GOVERNANCE','STRATEGY_LIFECYCLE','CLOSE_PROTOCOL','STRATEGY','EXEC-BOOTSTRAP-CIERRE-ESTRATEGIA-LF-20260914-001');

INSERT INTO public.lf_operation_contracts(operation_code,contract_code,contract_path,required_before_write,allowed,blocked,required_after_write,status,created_by_execution_id)
VALUES('CIERRE_ESTRATEGIA_LF','CONTRACT-CIERRE-ESTRATEGIA-LF-v0.1','supabase/migrations/20260914020000_lf_strategy_close_transversal_v1.sql','["exact_snapshot","revision_bound","zero_safe_work","zero_open_executable_chains","backlog_disposition","risk_disposition","no_supersede","execution_bound"]'::jsonb,'{"dispositions":["TERMINAL_COMPLETE","TERMINAL_BLOCKED"],"terminal":{"runtime_state":"NO_HABILITADO","impact_policy":"BLOQUEADO","visibility":"READ_ONLY_INTERNAL"},"top_level_status_preserved":true,"idempotent_same_execution":true}'::jsonb,'["SUPERSEDE","status_rewrite","archive_mutation","runtime_enable","impact_enable","stale_revision","cross_strategy_write","implicit_backlog_drop","implicit_risk_drop"]'::jsonb,'["close_receipt","status_CLOSED_projection","terminal_fields","history_preserved","idempotency","execution_trace"]'::jsonb,'ACTIVE_ENFORCEMENT','EXEC-BOOTSTRAP-CIERRE-ESTRATEGIA-LF-20260914-001');

WITH s(o,id,e,k,n,j,r) AS (VALUES
(0,'init_execution','Bind durable execution.','["execution_id","target_code"]'::jsonb,'router','JUDGE-CIERRE-ESTRATEGIA-LF-v0.1','GPT_RUNTIME_WITH_SUPABASE_CONTEXT'),
(10,'router','Resolve ACT-0001 Strategy close route.','["router_state","action","operation_code"]'::jsonb,'resolve_baseline','JUDGE-CIERRE-ESTRATEGIA-LF-v0.1','public.lf_router_resolve_v1'),
(20,'resolve_baseline','Resolve one snapshot and freeze full-row revision.','["snapshot_id","snapshot_code","revision_sha256","baseline_status","baseline_backlog","baseline_risks"]'::jsonb,'eligibility','JUDGE-CIERRE-ESTRATEGIA-LF-v0.1','public.lf_strategy_snapshot_revision_sha256_v1'),
(30,'eligibility','Prove close eligibility and explicit disposition.','["disposition","reason_code","safe_work_remaining_count","open_executable_causal_chains","backlog_disposition_map","risk_disposition_map","no_supersede_requested"]'::jsonb,'prewrite','JUDGE-CIERRE-ESTRATEGIA-LF-SEMANTIC-v1','GPT_RUNTIME_WITH_SUPABASE_CONTEXT'),
(40,'prewrite','Rebind execution and exact current revision immediately before write.','["execution_id","snapshot_id","bound_revision_sha256","currentness_state"]'::jsonb,'write','JUDGE-CIERRE-ESTRATEGIA-LF-PREWRITE-v1','GPT_RUNTIME_WITH_SUPABASE_CONTEXT'),
(50,'write','Execute bounded atomic close writer only.','["write_receipt","before_revision_sha256","after_revision_sha256","changed_paths"]'::jsonb,'readback','JUDGE-CIERRE-ESTRATEGIA-LF-v0.1','public.lf_strategy_close_write_v1'),
(60,'readback','Read terminal snapshot and lifecycle projection independently.','["strategy_close_status","runtime_state","impact_policy","visibility","latest_status","history_preserved"]'::jsonb,'semantic_regression','JUDGE-CIERRE-ESTRATEGIA-LF-v0.1','public.v_lf_strategy_latest'),
(70,'semantic_regression','Reject false completion, stale, supersede and cross-strategy cases.','["semantic_result","false_complete_blocked","stale_blocked","supersede_blocked","cross_strategy_blocked","idempotency_result"]'::jsonb,'report','JUDGE-CIERRE-ESTRATEGIA-LF-SEMANTIC-v1','GPT_RUNTIME_WITH_SUPABASE_CONTEXT'),
(80,'report','Emit durable close receipt after all gates pass.','["result","snapshot_id","close_receipt","evidence_refs","open_blockers"]'::jsonb,null,'JUDGE-CIERRE-ESTRATEGIA-LF-v0.1','GPT_RUNTIME_WITH_SUPABASE_CONTEXT')),
i AS (INSERT INTO public.lf_operation_steps(operation_code,step_order,step_id,required,evidence_required,source_path,active,execution_order,created_by_execution_id)
 SELECT 'CIERRE_ESTRATEGIA_LF',o,id,true,array_to_string(ARRAY(SELECT jsonb_array_elements_text(k)),','),'supabase://public/lf_operation_step_contracts/CIERRE_ESTRATEGIA_LF/'||id,true,o,'EXEC-BOOTSTRAP-CIERRE-ESTRATEGIA-LF-20260914-001' FROM s RETURNING 1)
INSERT INTO public.lf_operation_step_contracts(operation_code,step_id,step_order,execution_order,contract_code,purpose,input_required,resolver_ref,output_payload,pass_condition,block_condition,blocking_code,mini_judge_code,required_evidence_keys,next_if_pass,next_if_blocked,status,notes,fail_condition,created_by_execution_id)
SELECT 'CIERRE_ESTRATEGIA_LF',id,o,o,'CONTRACT-CIERRE-ESTRATEGIA-LF-v0.1',e,'[]'::jsonb,r,k,'{"required_evidence_present":true,"fail_closed":true}'::jsonb,'{"missing_required_evidence":true,"wrong_target":true}'::jsonb,'BLOCKED_CIERRE_ESTRATEGIA_LF_'||upper(id),j,k,n,'RETURN_TO_ROUTER','ACTIVE_ENFORCEMENT','CLOSE distinct from SUPERSEDE.','{}'::jsonb,'EXEC-BOOTSTRAP-CIERRE-ESTRATEGIA-LF-20260914-001' FROM s;

INSERT INTO public.lf_operation_judges(operation_code,judge_code,judge_path,pass_if,fail_if,result_values,status,created_by_execution_id) VALUES
('CIERRE_ESTRATEGIA_LF','JUDGE-CIERRE-ESTRATEGIA-LF-v0.1','supabase://CIERRE_ESTRATEGIA_LF/general','{"required_evidence_present":true}'::jsonb,'{"missing_required_evidence":true,"wrong_target":true}'::jsonb,'["STEP_PASS_WITH_EVIDENCE","RETURN_TO_ROUTER","BLOCKED_STEP_NOT_CLEAN"]'::jsonb,'ACTIVE_ENFORCEMENT','EXEC-BOOTSTRAP-CIERRE-ESTRATEGIA-LF-20260914-001'),
('CIERRE_ESTRATEGIA_LF','JUDGE-CIERRE-ESTRATEGIA-LF-PREWRITE-v1','supabase://CIERRE_ESTRATEGIA_LF/prewrite','{"execution_bound":true,"revision_sha_match":true,"safe_work":0,"open_chains":0}'::jsonb,'{"stale_revision":true,"binding_mismatch":true}'::jsonb,'["STEP_PASS_WITH_EVIDENCE","RETURN_TO_ROUTER","BLOCKED_STEP_NOT_CLEAN"]'::jsonb,'ACTIVE_ENFORCEMENT','EXEC-BOOTSTRAP-CIERRE-ESTRATEGIA-LF-20260914-001'),
('CIERRE_ESTRATEGIA_LF','JUDGE-CIERRE-ESTRATEGIA-LF-SEMANTIC-v1','supabase://CIERRE_ESTRATEGIA_LF/semantic','{"backlog_explicit":true,"risks_explicit":true,"no_supersede":true,"false_complete":false}'::jsonb,'{"implicit_drop":true,"supersede":true,"false_complete":true}'::jsonb,'["STEP_PASS_WITH_EVIDENCE","RETURN_TO_ROUTER","BLOCKED_STEP_NOT_CLEAN"]'::jsonb,'ACTIVE_ENFORCEMENT','EXEC-BOOTSTRAP-CIERRE-ESTRATEGIA-LF-20260914-001');

WITH s(o,id,k,j) AS (VALUES
(0,'init_execution','["execution_id","target_code"]'::jsonb,'JUDGE-CIERRE-ESTRATEGIA-LF-v0.1'),(10,'router','["router_state","action","operation_code"]'::jsonb,'JUDGE-CIERRE-ESTRATEGIA-LF-v0.1'),(20,'resolve_baseline','["snapshot_id","snapshot_code","revision_sha256","baseline_status","baseline_backlog","baseline_risks"]'::jsonb,'JUDGE-CIERRE-ESTRATEGIA-LF-v0.1'),(30,'eligibility','["disposition","reason_code","safe_work_remaining_count","open_executable_causal_chains","backlog_disposition_map","risk_disposition_map","no_supersede_requested"]'::jsonb,'JUDGE-CIERRE-ESTRATEGIA-LF-SEMANTIC-v1'),(40,'prewrite','["execution_id","snapshot_id","bound_revision_sha256","currentness_state"]'::jsonb,'JUDGE-CIERRE-ESTRATEGIA-LF-PREWRITE-v1'),(50,'write','["write_receipt","before_revision_sha256","after_revision_sha256","changed_paths"]'::jsonb,'JUDGE-CIERRE-ESTRATEGIA-LF-v0.1'),(60,'readback','["strategy_close_status","runtime_state","impact_policy","visibility","latest_status","history_preserved"]'::jsonb,'JUDGE-CIERRE-ESTRATEGIA-LF-v0.1'),(70,'semantic_regression','["semantic_result","false_complete_blocked","stale_blocked","supersede_blocked","cross_strategy_blocked","idempotency_result"]'::jsonb,'JUDGE-CIERRE-ESTRATEGIA-LF-SEMANTIC-v1'),(80,'report','["result","snapshot_id","close_receipt","evidence_refs","open_blockers"]'::jsonb,'JUDGE-CIERRE-ESTRATEGIA-LF-v0.1'))
INSERT INTO public.lf_operation_step_judge_bindings(operation_code,step_order,step_id,judge_code,clean_result_value,blocked_result_value,return_result_value,required_evidence_keys,status,created_by_execution_id)
SELECT 'CIERRE_ESTRATEGIA_LF',o,id,j,'STEP_PASS_WITH_EVIDENCE','BLOCKED_STEP_NOT_CLEAN','RETURN_TO_ROUTER',k,'ACTIVE_ENFORCEMENT','EXEC-BOOTSTRAP-CIERRE-ESTRATEGIA-LF-20260914-001' FROM s;

INSERT INTO public.lf_operation_policy_bindings(operation_code,policy_code,policy_role,required,distribution_modes,binding_status,created_by_execution_id) VALUES
('CIERRE_ESTRATEGIA_LF','POL-LF-OPERATION-LIFECYCLE','GOVERNANCE_LIFECYCLE',true,ARRAY['ROUTER','DIRECT'],'ACTIVE','EXEC-BOOTSTRAP-CIERRE-ESTRATEGIA-LF-20260914-001'),('CIERRE_ESTRATEGIA_LF','POL-LF-POLICY-CONSUMPTION','POLICY_CONSUMPTION',true,ARRAY['ROUTER','DIRECT'],'ACTIVE','EXEC-BOOTSTRAP-CIERRE-ESTRATEGIA-LF-20260914-001'),('CIERRE_ESTRATEGIA_LF','POL-LF-SOURCE-RESOLUTION','SOURCE_RESOLUTION',true,ARRAY['ROUTER','DIRECT'],'ACTIVE','EXEC-BOOTSTRAP-CIERRE-ESTRATEGIA-LF-20260914-001'),('CIERRE_ESTRATEGIA_LF','POL-LF-STATE-MODEL','STATE_MODEL',true,ARRAY['ROUTER','DIRECT'],'ACTIVE','EXEC-BOOTSTRAP-CIERRE-ESTRATEGIA-LF-20260914-001');

INSERT INTO public.lf_router_action_registry(asset_type,action_code,operation_code,operation_resolution,requires_existing_target,requires_missing_target,write_allowed,status,notes,created_by_execution_id)
VALUES('STRATEGY','STRATEGY_CLOSE','CIERRE_ESTRATEGIA_LF','STATIC',false,false,true,'ACTIVE','Exact Strategy snapshot resolved inside operation; Router master-asset existence is not authoritative.','EXEC-BOOTSTRAP-CIERRE-ESTRATEGIA-LF-20260914-001');

DO $patch$ DECLARE d text; n text; a text:=$x$    elsif v_req ~ '(^| )(policy|politica|regla)( |$)' then v_type_hint := 'REGLA';
    elsif v_req ~ '(^| )(doc|documento)( |$)' then v_type_hint := 'DOC';$x$; b text:=$x$    elsif v_req ~ '(^| )(policy|politica|regla)( |$)' then v_type_hint := 'REGLA';
    elsif v_req ~ '(^| )(estrategia|strategy)( |$)' then v_type_hint := 'STRATEGY';
    elsif v_req ~ '(^| )(doc|documento)( |$)' then v_type_hint := 'DOC';$x$; c text:=$x$    if v_req ~ '(^| )(consulta|consultar|estado|metadata|existe)( |$)' then v_action:='ASSET_INSPECTION';
    elsif v_type_hint='PERFIL' and v_req ~$x$; e text:=$x$    if v_req ~ '(^| )(consulta|consultar|estado|metadata|existe)( |$)' then v_action:='ASSET_INSPECTION';
    elsif v_type_hint='STRATEGY' and v_req ~ '(^| )(cierra|cerrar|cierre|finaliza|finalizar)( |$)' then v_action:='STRATEGY_CLOSE';
    elsif v_type_hint='PERFIL' and v_req ~$x$; BEGIN SELECT pg_get_functiondef('public.lf_router_resolve_v1(text,text,text,text,text)'::regprocedure) INTO d; IF strpos(d,a)=0 OR strpos(d,c)=0 THEN raise exception 'LF_STRATEGY_CLOSE_ROUTER_SOURCE_DRIFT'; END IF; n:=replace(replace(d,a,b),c,e); EXECUTE n; END $patch$;

CREATE OR REPLACE FUNCTION public.lf_strategy_snapshot_revision_sha256_v1(p_snapshot_id bigint) RETURNS text LANGUAGE sql STABLE SECURITY INVOKER SET search_path=pg_catalog,public,extensions AS $$ SELECT encode(extensions.digest(to_jsonb(s)::text,'sha256'),'hex') FROM public.lf_strategy_snapshots s WHERE s.id=p_snapshot_id $$;
REVOKE ALL ON FUNCTION public.lf_strategy_snapshot_revision_sha256_v1(bigint) FROM PUBLIC,anon,authenticated; GRANT EXECUTE ON FUNCTION public.lf_strategy_snapshot_revision_sha256_v1(bigint) TO service_role;

CREATE OR REPLACE FUNCTION public.lf_strategy_close_write_v1(p_execution_id text,p_snapshot_id bigint,p_expected_revision_sha256 text,p_reason text,p_disposition text,p_evidence jsonb) RETURNS jsonb LANGUAGE plpgsql SECURITY INVOKER SET search_path=pg_catalog,public,extensions AS $f$
DECLARE x public.lf_operation_execution%rowtype; s public.lf_strategy_snapshots%rowtype; a public.lf_strategy_snapshots%rowtype; bh text; ah text; cl jsonb; nowv timestamptz:=clock_timestamp(); sw int; oc int;
BEGIN
 IF btrim(coalesce(p_execution_id,''))='' OR p_snapshot_id IS NULL OR p_expected_revision_sha256 !~ '^[0-9a-f]{64}$' OR btrim(coalesce(p_reason,''))='' OR p_disposition NOT IN ('TERMINAL_COMPLETE','TERMINAL_BLOCKED') OR jsonb_typeof(p_evidence)<>'object' THEN raise exception 'LF_STRATEGY_CLOSE_INPUT_INVALID'; END IF;
 SELECT * INTO x FROM public.lf_operation_execution WHERE execution_id=p_execution_id; IF NOT FOUND OR x.operation_code<>'CIERRE_ESTRATEGIA_LF' OR x.status<>'IN_PROGRESS' OR x.target_type<>'STRATEGY' THEN raise exception 'LF_STRATEGY_CLOSE_EXECUTION_BINDING_MISMATCH'; END IF;
 SELECT * INTO s FROM public.lf_strategy_snapshots WHERE id=p_snapshot_id FOR UPDATE; IF NOT FOUND OR x.target_code<>s.snapshot_code THEN raise exception 'LF_STRATEGY_CLOSE_TARGET_MISMATCH'; END IF;
 IF coalesce(s.metadata->'strategy_close'->>'status','')='CLOSED' THEN IF s.metadata->'strategy_close'->>'execution_id'=p_execution_id THEN RETURN jsonb_build_object('result','ALREADY_CLOSED_IDEMPOTENT','snapshot_id',s.id,'close_receipt',s.metadata->'strategy_close'); END IF; raise exception 'LF_STRATEGY_CLOSE_ALREADY_CLOSED'; END IF;
 bh:=encode(extensions.digest(to_jsonb(s)::text,'sha256'),'hex'); IF bh<>p_expected_revision_sha256 THEN raise exception 'LF_STRATEGY_CLOSE_STALE_REVISION'; END IF;
 IF coalesce(p_evidence->>'safe_work_remaining_count','') !~ '^[0-9]+$' OR coalesce(p_evidence->>'open_executable_causal_chains','') !~ '^[0-9]+$' THEN raise exception 'LF_STRATEGY_CLOSE_ELIGIBILITY_COUNTS_REQUIRED'; END IF; sw:=(p_evidence->>'safe_work_remaining_count')::int; oc:=(p_evidence->>'open_executable_causal_chains')::int;
 IF sw<>0 OR oc<>0 OR coalesce((p_evidence->>'no_supersede_requested')::boolean,false) IS NOT TRUE OR jsonb_typeof(p_evidence->'backlog_disposition_map')<>'object' OR jsonb_typeof(p_evidence->'risk_disposition_map')<>'object' THEN raise exception 'LF_STRATEGY_CLOSE_NOT_ELIGIBLE'; END IF;
 IF p_evidence ? 'open_blockers' AND jsonb_typeof(p_evidence->'open_blockers')<>'array' THEN raise exception 'LF_STRATEGY_CLOSE_BLOCKERS_INVALID'; END IF;
 IF p_disposition='TERMINAL_COMPLETE' AND jsonb_array_length(coalesce(p_evidence->'open_blockers','[]'::jsonb))>0 THEN raise exception 'LF_STRATEGY_CLOSE_FALSE_COMPLETE'; END IF;
 IF p_disposition='TERMINAL_BLOCKED' AND jsonb_array_length(coalesce(p_evidence->'open_blockers','[]'::jsonb))=0 THEN raise exception 'LF_STRATEGY_CLOSE_BLOCKED_REQUIRES_BLOCKER'; END IF;
 cl:=jsonb_build_object('status','CLOSED','disposition',p_disposition,'reason_code',p_reason,'execution_id',p_execution_id,'closed_at',nowv,'safe_work_remaining_count',sw,'open_executable_causal_chains',oc,'open_blockers',coalesce(p_evidence->'open_blockers','[]'::jsonb),'backlog_disposition_map',p_evidence->'backlog_disposition_map','risk_disposition_map',p_evidence->'risk_disposition_map','baseline_revision_sha256',bh,'superseded',false);
 UPDATE public.lf_strategy_snapshots SET metadata=jsonb_set(coalesce(metadata,'{}'::jsonb),'{strategy_close}',cl,true),evidence_refs=coalesce(evidence_refs,'[]'::jsonb)||jsonb_build_array(jsonb_build_object('type','STRATEGY_CLOSE','execution_id',p_execution_id,'refs',coalesce(p_evidence->'evidence_refs','[]'::jsonb))),change_log=coalesce(change_log,'[]'::jsonb)||jsonb_build_array(jsonb_build_object('change_type','STRATEGY_CLOSE','execution_id',p_execution_id,'closed_at',nowv,'reason_code',p_reason,'disposition',p_disposition,'superseded',false)),runtime_state='NO_HABILITADO',impact_policy='BLOQUEADO',visibility='READ_ONLY_INTERNAL',updated_at=nowv,updated_by_execution_id=p_execution_id WHERE id=s.id RETURNING * INTO a;
 ah:=encode(extensions.digest(to_jsonb(a)::text,'sha256'),'hex'); IF a.status IS DISTINCT FROM s.status OR a.archived_at IS DISTINCT FROM s.archived_at OR a.archived_reason IS DISTINCT FROM s.archived_reason OR a.runtime_state<>'NO_HABILITADO' OR a.impact_policy<>'BLOQUEADO' OR a.visibility<>'READ_ONLY_INTERNAL' THEN raise exception 'LF_STRATEGY_CLOSE_POSTWRITE_INVARIANT'; END IF;
 RETURN jsonb_build_object('result','STRATEGY_CLOSED_WITH_EVIDENCE','snapshot_id',a.id,'snapshot_code',a.snapshot_code,'close_receipt',a.metadata->'strategy_close','before_revision_sha256',bh,'after_revision_sha256',ah,'changed_paths',jsonb_build_array('metadata.strategy_close','evidence_refs.append','change_log.append','runtime_state','impact_policy','visibility','updated_at','updated_by_execution_id'));
END $f$;
REVOKE ALL ON FUNCTION public.lf_strategy_close_write_v1(text,bigint,text,text,text,jsonb) FROM PUBLIC,anon,authenticated; GRANT EXECUTE ON FUNCTION public.lf_strategy_close_write_v1(text,bigint,text,text,text,jsonb) TO service_role;

CREATE OR REPLACE FUNCTION public.fn_lf_strategy_closed_immutable_v1() RETURNS trigger LANGUAGE plpgsql SECURITY INVOKER SET search_path=pg_catalog,public AS $$ BEGIN IF coalesce(OLD.metadata->'strategy_close'->>'status','')='CLOSED' THEN raise exception 'LF_STRATEGY_CLOSED_READ_ONLY:%',OLD.snapshot_code USING errcode='23514'; END IF; IF TG_OP='DELETE' THEN RETURN OLD; END IF; RETURN NEW; END $$;
REVOKE ALL ON FUNCTION public.fn_lf_strategy_closed_immutable_v1() FROM PUBLIC,anon,authenticated;
CREATE TRIGGER trg_lf_strategy_closed_immutable_v1 BEFORE UPDATE OR DELETE ON public.lf_strategy_snapshots FOR EACH ROW EXECUTE FUNCTION public.fn_lf_strategy_closed_immutable_v1();

CREATE OR REPLACE FUNCTION private.fn_lf_strategy_closed_event_stream_guard_v1() RETURNS trigger LANGUAGE plpgsql SECURITY INVOKER SET search_path=pg_catalog,public,private AS $$ BEGIN IF NEW.entidad_tipo='STRATEGY_SNAPSHOT' AND EXISTS(select 1 from public.lf_strategy_snapshots s where s.snapshot_code=NEW.entidad_codigo and coalesce(s.metadata->'strategy_close'->>'status','')='CLOSED') THEN raise exception 'LF_STRATEGY_CLOSED_EVENT_STREAM_READ_ONLY:%',NEW.entidad_codigo USING errcode='23514'; END IF; RETURN NEW; END $$;
REVOKE ALL ON FUNCTION private.fn_lf_strategy_closed_event_stream_guard_v1() FROM PUBLIC,anon,authenticated;
CREATE TRIGGER trg_00_lf_strategy_closed_event_stream_guard_v1 BEFORE INSERT ON public.lf_eventos FOR EACH ROW EXECUTE FUNCTION private.fn_lf_strategy_closed_event_stream_guard_v1();

CREATE OR REPLACE VIEW public.v_lf_strategy_latest WITH (security_invoker=true) AS WITH c AS (
 SELECT id,created_at,evento_tipo,entidad_codigo,snapshot_code,family,version,status,project_code,front_code,canonical_store,descripcion,severidad,origen,payload FROM public.v_lf_strategy_events WHERE snapshot_code IS NOT NULL
 UNION ALL SELECT -s.id,s.updated_at,'STRATEGY_CLOSED',s.snapshot_code,s.snapshot_code,s.snapshot_family,s.version,'CLOSED',s.project_code,s.front_code,'lf_strategy_snapshots','Governed terminal Strategy close','INFO','EXECUTION:'||coalesce(s.metadata->'strategy_close'->>'execution_id','UNKNOWN'),jsonb_build_object('snapshot_id',s.id,'snapshot_code',s.snapshot_code,'family',s.snapshot_family,'version',s.version,'status','CLOSED','project_code',s.project_code,'front_code',s.front_code,'mode','TERMINAL_READ_ONLY','canonical_store','lf_strategy_snapshots','strategy_close',s.metadata->'strategy_close') FROM public.lf_strategy_snapshots s WHERE coalesce(s.metadata->'strategy_close'->>'status','')='CLOSED')
SELECT DISTINCT ON(snapshot_code) id,created_at,evento_tipo,entidad_codigo,snapshot_code,family,version,status,project_code,front_code,canonical_store,descripcion,severidad,origen,payload FROM c ORDER BY snapshot_code,created_at DESC,id DESC;

DO $post$ DECLARE c int; r jsonb; d text; BEGIN
 SELECT count(*) INTO c FROM public.lf_operation_steps WHERE operation_code='CIERRE_ESTRATEGIA_LF' AND required AND active; IF c<>9 THEN raise exception 'LF_STRATEGY_CLOSE_STEP_COUNT:%',c; END IF;
 SELECT count(*) INTO c FROM public.lf_operation_step_contracts WHERE operation_code='CIERRE_ESTRATEGIA_LF' AND status='ACTIVE_ENFORCEMENT'; IF c<>9 THEN raise exception 'LF_STRATEGY_CLOSE_CONTRACT_COUNT:%',c; END IF;
 SELECT count(*) INTO c FROM public.lf_operation_step_judge_bindings WHERE operation_code='CIERRE_ESTRATEGIA_LF' AND status='ACTIVE_ENFORCEMENT'; IF c<>9 THEN raise exception 'LF_STRATEGY_CLOSE_BINDING_COUNT:%',c; END IF;
 SELECT count(*) INTO c FROM public.lf_operation_policy_bindings WHERE operation_code='CIERRE_ESTRATEGIA_LF' AND required AND binding_status='ACTIVE'; IF c<>4 THEN raise exception 'LF_STRATEGY_CLOSE_POLICY_COUNT:%',c; END IF;
 r:=public.lf_router_resolve_v1('cerrar estrategia gobernada',null,'STRATEGY_CLOSE','STRATEGY','ROUTER'); IF r->>'status'<>'READY_TO_EXECUTE' OR r->>'operation_code'<>'CIERRE_ESTRATEGIA_LF' THEN raise exception 'LF_STRATEGY_CLOSE_EXPLICIT_ROUTE_FAIL:%',r; END IF;
 r:=public.lf_router_resolve_v1('cerrar estrategia S26',null,null,null,'ROUTER'); IF r->>'status'<>'READY_TO_EXECUTE' OR r->>'action_code'<>'STRATEGY_CLOSE' OR r->>'operation_code'<>'CIERRE_ESTRATEGIA_LF' THEN raise exception 'LF_STRATEGY_CLOSE_NATURAL_ROUTE_FAIL:%',r; END IF;
 SELECT pg_get_viewdef('public.v_lf_strategy_latest'::regclass,true) INTO d; IF strpos(d,'STRATEGY_CLOSED')=0 OR strpos(d,'strategy_close')=0 THEN raise exception 'LF_STRATEGY_CLOSE_VIEW_FAIL'; END IF;
END $post$;

UPDATE public.lf_operation_execution SET status='COMPLETED',completed_at=now(),updated_at=now(),updated_by_execution_id='EXEC-BOOTSTRAP-CIERRE-ESTRATEGIA-LF-20260914-001',manifest=manifest||'{"result":"STRATEGY_CLOSE_TRANSVERSAL_REGISTERED_SOURCE_FIRST","router_action":"STRATEGY_CLOSE","operation_status":"SANDBOX_ACTIVE","strategy_mutation_during_migration":false,"close_distinct_from_supersede":true}'::jsonb WHERE execution_id='EXEC-BOOTSTRAP-CIERRE-ESTRATEGIA-LF-20260914-001';