-- IG_CURATOR_VALIDATOR_REFACTOR_V2 · M7.3 / PAULO-052
-- Reconcile contract 5.13 negative_tests into executable cases in the existing INPUT_GOVERNANCE_REGRESSION suite.
-- R16 Git-first. No Validator runtime change. No N-14 change. No second suite/test engine.
-- ASSURANCE_EVALUATOR remains governance-gated; catalog/obligation is the oracle contract.

BEGIN;

DO $m7_3_preflight$
DECLARE
  v_contract_id bigint;
  v_revision text;
  v_negative_count integer;
  v_existing integer;
  v_dep_count integer;
BEGIN
  SELECT id, especificacion->>'contract_revision',
         jsonb_array_length(especificacion->'negative_tests')
    INTO v_contract_id, v_revision, v_negative_count
  FROM programacion.contratos
  WHERE contrato_codigo='INPUT_READINESS_CONTRACT'
  ORDER BY id DESC
  LIMIT 1;

  IF v_contract_id IS NULL OR v_revision<>'5.13' OR v_negative_count<>91 THEN
    RAISE EXCEPTION 'M7_3_CONTRACT_PREFLIGHT_FAILED:id=% revision=% negatives=%',
      v_contract_id,v_revision,v_negative_count;
  END IF;

  SELECT count(*) INTO v_dep_count
  FROM programacion.engineering_work_items
  WHERE work_code IN ('PAULO-016','PAULO-109')
    AND status='DONE';
  IF v_dep_count<>2 THEN
    RAISE EXCEPTION 'M7_3_DEPENDENCY_NOT_DONE:observed=%',v_dep_count;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM public.lf_test_suites
    WHERE suite_code='INPUT_GOVERNANCE_REGRESSION'
      AND metadata->'m7_0_q_taxonomy'->>'version'='Q_TAXONOMY_V1'
  ) THEN
    RAISE EXCEPTION 'M7_3_EXISTING_SUITE_OR_Q_TAXONOMY_MISSING';
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM public.lf_capability_current
    WHERE capability_code='ASSURANCE_EVALUATOR' AND version='1.0.0'
  ) THEN
    RAISE EXCEPTION 'M7_3_ASSURANCE_EVALUATOR_CURRENT_MISSING';
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM public.lf_assurance_claim_catalog
    WHERE claim_code='INPUT_GOVERNANCE_CONTRACT_5_13_ASSURANCE_V1'
      AND version=1
  ) THEN
    RAISE EXCEPTION 'M7_3_ASSURANCE_CLAIM_MISSING';
  END IF;

  SELECT count(*) INTO v_existing
  FROM public.lf_test_suite_cases
  WHERE suite_code='INPUT_GOVERNANCE_REGRESSION'
    AND metadata->>'unit_code'='M7.3';
  IF v_existing<>0 THEN
    RAISE EXCEPTION 'M7_3_PREEXISTING_CASES:observed=%',v_existing;
  END IF;
END
$m7_3_preflight$;

WITH
latest_contract AS (
  SELECT id AS contract_id, especificacion->'negative_tests' AS negatives
  FROM programacion.contratos
  WHERE contrato_codigo='INPUT_READINESS_CONTRACT'
  ORDER BY id DESC
  LIMIT 1
),
mapping(ord,negative_test,q_class,dimension,property,obligation_code,expected_decision,claim_scope) AS (
  VALUES
(1,'MISSING_SOURCE','Q1','STRUCTURAL','SOURCE_REFS_REQUIRED_PER_FAMILY','IG-C5_13-SOURCE_REFS_REQUIRED_PER_FAMILY','REJECT_MUTATION_FAIL_CLOSED','STRUCTURAL_ONLY_NOT_SEMANTIC_OR_READINESS'),
(2,'CONTRADICTORY_SOURCE','Q3','SEMANTIC','SOURCE_PRECEDENCE','IG-C5_13-SOURCE_PRECEDENCE','REJECT_MUTATION_FAIL_CLOSED','SEMANTIC_CORRECTNESS_REQUIRES_GOVERNED_EVIDENCE'),
(3,'BROKEN_ID','Q1','STRUCTURAL','SOURCE_REF_CONTRACT','IG-C5_13-SOURCE_REF_CONTRACT','REJECT_MUTATION_FAIL_CLOSED','STRUCTURAL_ONLY_NOT_SEMANTIC_OR_READINESS'),
(4,'INVENTED_URL','Q6','ADVERSARIAL_FALSE_PASS','SOURCE_REF_CONTRACT','IG-C5_13-SOURCE_REF_CONTRACT','REJECT_MUTATION_FAIL_CLOSED','ADVERSARIAL_FALSE_PASS_RESISTANCE'),
(5,'TIMEOUT_WITHOUT_SOURCE','Q6','ADVERSARIAL_FALSE_PASS','DIRECT_SOURCE_READBACK_REQUIRED','IG-C5_13-DIRECT_SOURCE_READBACK_REQUIRED','REJECT_MUTATION_FAIL_CLOSED','ADVERSARIAL_FALSE_PASS_RESISTANCE'),
(6,'UNJUSTIFIED_NOT_APPLICABLE','Q5','READINESS','NOT_APPLICABLE_REQUIRES_REASON','IG-C5_13-NOT_APPLICABLE_REQUIRES_REASON','REJECT_MUTATION_FAIL_CLOSED','READINESS_POLICY_NOT_SEMANTIC_EQUIVALENCE'),
(7,'STALE_EVIDENCE','Q7','CURRENTNESS_LINEAGE_REPLAY','FRESHNESS_GATE','IG-C5_13-FRESHNESS_GATE','REJECT_MUTATION_FAIL_CLOSED','CURRENTNESS_LINEAGE_REPLAY_NOT_HISTORICAL_PASS'),
(8,'HISTORICAL_PASS_OVERRIDES_NEWER_FAILURE','Q7','CURRENTNESS_LINEAGE_REPLAY','REVISION_LINEAGE','IG-C5_13-REVISION_LINEAGE','REJECT_MUTATION_FAIL_CLOSED','CURRENTNESS_LINEAGE_REPLAY_NOT_HISTORICAL_PASS'),
(9,'SELF_AUTHORITY','Q6','ADVERSARIAL_FALSE_PASS','CANDIDATE_AS_OWN_AUTHORITY','IG-C5_13-CANDIDATE_AS_OWN_AUTHORITY','REJECT_MUTATION_FAIL_CLOSED','ADVERSARIAL_FALSE_PASS_RESISTANCE'),
(10,'AMBIGUOUS_INPUT','Q3','SEMANTIC','SEMANTIC_FAIL_CLOSED','IG-C5_13-SEMANTIC_FAIL_CLOSED','REJECT_MUTATION_FAIL_CLOSED','SEMANTIC_CORRECTNESS_REQUIRES_GOVERNED_EVIDENCE'),
(11,'UNTESTABLE_REQUIREMENT','Q3','SEMANTIC','ASSERTION_CONTRACT','IG-C5_13-ASSERTION_CONTRACT','REJECT_MUTATION_FAIL_CLOSED','SEMANTIC_CORRECTNESS_REQUIRES_GOVERNED_EVIDENCE'),
(12,'SEMANTIC_DUPLICATION','Q4','CROSS_FAMILY_COHERENCE','SEMANTIC_COHERENCE_CONTRACT','IG-C5_13-SEMANTIC_COHERENCE_CONTRACT','REJECT_MUTATION_FAIL_CLOSED','CROSS_FAMILY_SEMANTIC_COHERENCE_REQUIRES_GOVERNED_EVIDENCE'),
(13,'MISSING_COMPONENT_BINDING','Q1','STRUCTURAL','VALIDATOR_COMPONENT_BINDING','IG-C5_13-VALIDATOR_COMPONENT_BINDING','REJECT_MUTATION_FAIL_CLOSED','STRUCTURAL_ONLY_NOT_SEMANTIC_OR_READINESS'),
(14,'BROKEN_COMPONENT_REF','Q1','STRUCTURAL','VALIDATOR_COMPONENT_BINDING','IG-C5_13-VALIDATOR_COMPONENT_BINDING','REJECT_MUTATION_FAIL_CLOSED','STRUCTURAL_ONLY_NOT_SEMANTIC_OR_READINESS'),
(15,'AMBIGUOUS_DESIGN_REF','Q3','SEMANTIC','DESIGN_SYSTEM_READINESS','IG-C5_13-DESIGN_SYSTEM_READINESS','REJECT_MUTATION_FAIL_CLOSED','SEMANTIC_CORRECTNESS_REQUIRES_GOVERNED_EVIDENCE'),
(16,'GENERIC_RULE_AS_IMPLEMENTATION_READY','Q5','READINESS','STAGE_AUTHORITY_POLICY','IG-C5_13-STAGE_AUTHORITY_POLICY','REJECT_MUTATION_FAIL_CLOSED','READINESS_POLICY_NOT_SEMANTIC_EQUIVALENCE'),
(17,'APPLICABLE_WITH_NOT_APPLICABLE_STATUS','Q5','READINESS','APPLICABILITY_STATUS_INVARIANTS','IG-C5_13-APPLICABILITY_STATUS_INVARIANTS','REJECT_MUTATION_FAIL_CLOSED','READINESS_POLICY_NOT_SEMANTIC_EQUIVALENCE'),
(18,'NOT_APPLICABLE_WITH_NON_NA_STATUS','Q5','READINESS','APPLICABILITY_STATUS_INVARIANTS','IG-C5_13-APPLICABILITY_STATUS_INVARIANTS','REJECT_MUTATION_FAIL_CLOSED','READINESS_POLICY_NOT_SEMANTIC_EQUIVALENCE'),
(19,'COMPONENT_ID_PRESENT_BUT_SEMANTIC_BINDING_PENDING','Q3','SEMANTIC','SEMANTIC_COMPONENT_SUFFICIENCY','IG-C5_13-SEMANTIC_COMPONENT_SUFFICIENCY','REJECT_MUTATION_FAIL_CLOSED','SEMANTIC_CORRECTNESS_REQUIRES_GOVERNED_EVIDENCE'),
(20,'SCREEN_APPLICABILITY_WITHOUT_SOURCE_GROUNDING','Q3','SEMANTIC','APPLICABILITY_SOURCE_GROUNDING','IG-C5_13-APPLICABILITY_SOURCE_GROUNDING','REJECT_MUTATION_FAIL_CLOSED','SEMANTIC_CORRECTNESS_REQUIRES_GOVERNED_EVIDENCE'),
(21,'DESCRIPTIVE_API_RULE_AS_IMPLEMENTATION_READY_WITHOUT_RESOLVABLE_SCHEMA','Q3','SEMANTIC','API_DATA_CONTRACT_READINESS','IG-C5_13-API_DATA_CONTRACT_READINESS','REJECT_MUTATION_FAIL_CLOSED','SEMANTIC_CORRECTNESS_REQUIRES_GOVERNED_EVIDENCE'),
(22,'IMPLEMENTATION_READY_WHILE_STORY_NOT_READY','Q5','READINESS','READINESS_STAGE_HIERARCHY','IG-C5_13-READINESS_STAGE_HIERARCHY','REJECT_MUTATION_FAIL_CLOSED','READINESS_POLICY_NOT_SEMANTIC_EQUIVALENCE'),
(23,'QA_READY_WHILE_IMPLEMENTATION_NOT_READY','Q5','READINESS','READINESS_STAGE_HIERARCHY','IG-C5_13-READINESS_STAGE_HIERARCHY','REJECT_MUTATION_FAIL_CLOSED','READINESS_POLICY_NOT_SEMANTIC_EQUIVALENCE'),
(24,'PRODUCTION_READY_WHILE_QA_NOT_READY','Q5','READINESS','READINESS_STAGE_HIERARCHY','IG-C5_13-READINESS_STAGE_HIERARCHY','REJECT_MUTATION_FAIL_CLOSED','READINESS_POLICY_NOT_SEMANTIC_EQUIVALENCE'),
(25,'UNRESOLVED_SEVERITY','Q5','READINESS','DETERMINISTIC_STAGE_SUMMARY','IG-C5_13-DETERMINISTIC_STAGE_SUMMARY','REJECT_MUTATION_FAIL_CLOSED','READINESS_POLICY_NOT_SEMANTIC_EQUIVALENCE'),
(26,'STORY_OPEN_WITH_NON_P0','Q5','READINESS','STORY_READY_RULE','IG-C5_13-STORY_READY_RULE','REJECT_MUTATION_FAIL_CLOSED','READINESS_POLICY_NOT_SEMANTIC_EQUIVALENCE'),
(27,'IMPLEMENTATION_READY_WITH_INCOMPLETE_COVERAGE','Q5','READINESS','STAGE_BOUNDARY_CONTRACT','IG-C5_13-STAGE_BOUNDARY_CONTRACT','REJECT_MUTATION_FAIL_CLOSED','READINESS_POLICY_NOT_SEMANTIC_EQUIVALENCE'),
(28,'NOT_APPLICABLE_BY_ABSENCE_ONLY','Q5','READINESS','NOT_APPLICABLE_POSITIVE_AUTHORITY_CONTRACT','IG-C5_13-NOT_APPLICABLE_POSITIVE_AUTHORITY_CONTRACT','REJECT_MUTATION_FAIL_CLOSED','READINESS_POLICY_NOT_SEMANTIC_EQUIVALENCE'),
(29,'SCREEN_SCOPED_REF_WITHOUT_ID','Q1','STRUCTURAL','SCREEN_GRAPH_SCOPING','IG-C5_13-SCREEN_GRAPH_SCOPING','REJECT_MUTATION_FAIL_CLOSED','STRUCTURAL_ONLY_NOT_SEMANTIC_OR_READINESS'),
(30,'CONTRACT_REVISION_DRIFT','Q7','CURRENTNESS_LINEAGE_REPLAY','CONTRACT_REVISION','IG-C5_13-CONTRACT_REVISION','REJECT_MUTATION_FAIL_CLOSED','CURRENTNESS_LINEAGE_REPLAY_NOT_HISTORICAL_PASS'),
(31,'REVERSIBLE_CURRENTNESS','Q7','CURRENTNESS_LINEAGE_REPLAY','FRESHNESS_GATE','IG-C5_13-FRESHNESS_GATE','REJECT_MUTATION_FAIL_CLOSED','CURRENTNESS_LINEAGE_REPLAY_NOT_HISTORICAL_PASS'),
(32,'DECLARED_STORAGE_VISUAL_MISSING','Q3','SEMANTIC','DESIGN_SYSTEM_READINESS','IG-C5_13-DESIGN_SYSTEM_READINESS','REJECT_MUTATION_FAIL_CLOSED','SEMANTIC_CORRECTNESS_REQUIRES_GOVERNED_EVIDENCE'),
(33,'HEALTH_PASS_WITH_STORY_OPEN','Q6','ADVERSARIAL_FALSE_PASS','STORY_READY_RULE','IG-C5_13-STORY_READY_RULE','REJECT_MUTATION_FAIL_CLOSED','ADVERSARIAL_FALSE_PASS_RESISTANCE'),
(34,'DESIGN_READY_WITHOUT_NON_FIELD_ELEMENT_INVENTORY','Q3','SEMANTIC','DESIGN_SYSTEM_READINESS','IG-C5_13-DESIGN_SYSTEM_READINESS','REJECT_MUTATION_FAIL_CLOSED','SEMANTIC_CORRECTNESS_REQUIRES_GOVERNED_EVIDENCE'),
(35,'CURATOR_VALIDATOR_SAME_EXECUTION_ID','Q6','ADVERSARIAL_FALSE_PASS','VALIDATOR_IDENTITY_MUST_DIFFER_FROM_CURATOR','IG-C5_13-VALIDATOR_IDENTITY_MUST_DIFFER_FROM_CURATOR','REJECT_MUTATION_FAIL_CLOSED','ADVERSARIAL_FALSE_PASS_RESISTANCE'),
(36,'ASSERTION_STORED_RESULT_MISMATCH','Q7','CURRENTNESS_LINEAGE_REPLAY','ASSERTION_TRUTH_EVALUATED','IG-C5_13-ASSERTION_TRUTH_EVALUATED','REJECT_MUTATION_FAIL_CLOSED','CURRENTNESS_LINEAGE_REPLAY_NOT_HISTORICAL_PASS'),
(37,'ASSERTION_STORED_SOURCE_SHA_MISMATCH','Q7','CURRENTNESS_LINEAGE_REPLAY','SOURCE_SNAPSHOT_BINDING','IG-C5_13-SOURCE_SNAPSHOT_BINDING','REJECT_MUTATION_FAIL_CLOSED','CURRENTNESS_LINEAGE_REPLAY_NOT_HISTORICAL_PASS'),
(38,'FAMILY_COMPLETE_WITH_INCOMPLETE_SUBJECT','Q4','CROSS_FAMILY_COHERENCE','SEMANTIC_COHERENCE_CONTRACT','IG-C5_13-SEMANTIC_COHERENCE_CONTRACT','REJECT_MUTATION_FAIL_CLOSED','CROSS_FAMILY_SEMANTIC_COHERENCE_REQUIRES_GOVERNED_EVIDENCE'),
(39,'FAMILY_WELL_DEFINED_WITH_INCOMPLETE_SUBJECT','Q4','CROSS_FAMILY_COHERENCE','SEMANTIC_COHERENCE_CONTRACT','IG-C5_13-SEMANTIC_COHERENCE_CONTRACT','REJECT_MUTATION_FAIL_CLOSED','CROSS_FAMILY_SEMANTIC_COHERENCE_REQUIRES_GOVERNED_EVIDENCE'),
(40,'SECURITY_COMPLETE_WITH_UNRESOLVED_THREAT','Q4','CROSS_FAMILY_COHERENCE','SEMANTIC_DEPTH_CONTRACT','IG-C5_13-SEMANTIC_DEPTH_CONTRACT','REJECT_MUTATION_FAIL_CLOSED','CROSS_FAMILY_SEMANTIC_COHERENCE_REQUIRES_GOVERNED_EVIDENCE'),
(41,'SECURITY_THREAT_OMITTED','Q3','SEMANTIC','SEMANTIC_DEPTH_CONTRACT','IG-C5_13-SEMANTIC_DEPTH_CONTRACT','REJECT_MUTATION_FAIL_CLOSED','SEMANTIC_CORRECTNESS_REQUIRES_GOVERNED_EVIDENCE'),
(42,'SEMANTIC_DEPTH_MUTATION_AFTER_CURATOR','Q7','CURRENTNESS_LINEAGE_REPLAY','CURATOR_FIELDS_IMMUTABLE_AFTER_INSERT','IG-C5_13-CURATOR_FIELDS_IMMUTABLE_AFTER_INSERT','REJECT_MUTATION_FAIL_CLOSED','CURRENTNESS_LINEAGE_REPLAY_NOT_HISTORICAL_PASS'),
(43,'VALIDATOR_SEMANTIC_DEPTH_HASH_MISMATCH','Q7','CURRENTNESS_LINEAGE_REPLAY','SOURCE_SNAPSHOT_BINDING','IG-C5_13-SOURCE_SNAPSHOT_BINDING','REJECT_MUTATION_FAIL_CLOSED','CURRENTNESS_LINEAGE_REPLAY_NOT_HISTORICAL_PASS'),
(44,'LATER_STAGE_GAP_BLOCKS_EARLIER_STAGE','Q5','READINESS','STAGE_BOUNDARY_CONTRACT','IG-C5_13-STAGE_BOUNDARY_CONTRACT','REJECT_MUTATION_FAIL_CLOSED','READINESS_POLICY_NOT_SEMANTIC_EQUIVALENCE'),
(45,'BROWSER_PLATFORM_QA_GAP_AS_STORY_BLOCKER','Q5','READINESS','STAGE_BOUNDARY_CONTRACT','IG-C5_13-STAGE_BOUNDARY_CONTRACT','REJECT_MUTATION_FAIL_CLOSED','READINESS_POLICY_NOT_SEMANTIC_EQUIVALENCE'),
(46,'THREAT_PROFILE_FROM_ABSENCE','Q4','CROSS_FAMILY_COHERENCE','SEMANTIC_COHERENCE_CONTRACT','IG-C5_13-SEMANTIC_COHERENCE_CONTRACT','REJECT_MUTATION_FAIL_CLOSED','CROSS_FAMILY_SEMANTIC_COHERENCE_REQUIRES_GOVERNED_EVIDENCE'),
(47,'THREAT_NA_WITHOUT_PROFILE_AUTHORITY','Q5','READINESS','NOT_APPLICABLE_POSITIVE_AUTHORITY_CONTRACT','IG-C5_13-NOT_APPLICABLE_POSITIVE_AUTHORITY_CONTRACT','REJECT_MUTATION_FAIL_CLOSED','READINESS_POLICY_NOT_SEMANTIC_EQUIVALENCE'),
(48,'LOGIN_THREATS_APPLIED_TO_PASSWORD_UPDATE','Q4','CROSS_FAMILY_COHERENCE','SEMANTIC_COHERENCE_CONTRACT','IG-C5_13-SEMANTIC_COHERENCE_CONTRACT','REJECT_MUTATION_FAIL_CLOSED','CROSS_FAMILY_SEMANTIC_COHERENCE_REQUIRES_GOVERNED_EVIDENCE'),
(49,'PLACEHOLDER_REQUIRED_FOR_QR_DISPLAY','Q3','SEMANTIC','SEMANTIC_COMPONENT_SUFFICIENCY','IG-C5_13-SEMANTIC_COMPONENT_SUFFICIENCY','REJECT_MUTATION_FAIL_CLOSED','SEMANTIC_CORRECTNESS_REQUIRES_GOVERNED_EVIDENCE'),
(50,'OTP_PIN_TREATED_AS_GENERIC_TEXT_INPUT','Q3','SEMANTIC','SEMANTIC_COMPONENT_SUFFICIENCY','IG-C5_13-SEMANTIC_COMPONENT_SUFFICIENCY','REJECT_MUTATION_FAIL_CLOSED','SEMANTIC_CORRECTNESS_REQUIRES_GOVERNED_EVIDENCE'),
(51,'UNKNOWN_SECURITY_CAPABILITY_SELF_NA','Q6','ADVERSARIAL_FALSE_PASS','GOVERNANCE_AUTHORITY_POLICY','IG-C5_13-GOVERNANCE_AUTHORITY_POLICY','REJECT_MUTATION_FAIL_CLOSED','ADVERSARIAL_FALSE_PASS_RESISTANCE'),
(52,'ANALYTICS_GAP_AS_STORY_P0','Q5','READINESS','STAGE_BOUNDARY_CONTRACT','IG-C5_13-STAGE_BOUNDARY_CONTRACT','REJECT_MUTATION_FAIL_CLOSED','READINESS_POLICY_NOT_SEMANTIC_EQUIVALENCE'),
(53,'FORCED_COLORS_GAP_AS_STORY_P0','Q5','READINESS','STAGE_BOUNDARY_CONTRACT','IG-C5_13-STAGE_BOUNDARY_CONTRACT','REJECT_MUTATION_FAIL_CLOSED','READINESS_POLICY_NOT_SEMANTIC_EQUIVALENCE'),
(54,'IDEMPOTENCY_GAP_AS_STORY_P0','Q5','READINESS','STAGE_BOUNDARY_CONTRACT','IG-C5_13-STAGE_BOUNDARY_CONTRACT','REJECT_MUTATION_FAIL_CLOSED','READINESS_POLICY_NOT_SEMANTIC_EQUIVALENCE'),
(55,'REDUCED_MOTION_GAP_AS_STORY_P0','Q5','READINESS','STAGE_BOUNDARY_CONTRACT','IG-C5_13-STAGE_BOUNDARY_CONTRACT','REJECT_MUTATION_FAIL_CLOSED','READINESS_POLICY_NOT_SEMANTIC_EQUIVALENCE'),
(56,'TEST_CONTRACT_GAP_AS_STORY_P0','Q5','READINESS','STAGE_BOUNDARY_CONTRACT','IG-C5_13-STAGE_BOUNDARY_CONTRACT','REJECT_MUTATION_FAIL_CLOSED','READINESS_POLICY_NOT_SEMANTIC_EQUIVALENCE'),
(57,'THEME_GAP_AS_STORY_P0','Q5','READINESS','STAGE_BOUNDARY_CONTRACT','IG-C5_13-STAGE_BOUNDARY_CONTRACT','REJECT_MUTATION_FAIL_CLOSED','READINESS_POLICY_NOT_SEMANTIC_EQUIVALENCE'),
(58,'LATER_STAGE_GAP_SEVERITY_LAUNDERED_TO_P0','Q6','ADVERSARIAL_FALSE_PASS','STAGE_BOUNDARY_CONTRACT','IG-C5_13-STAGE_BOUNDARY_CONTRACT','REJECT_MUTATION_FAIL_CLOSED','ADVERSARIAL_FALSE_PASS_RESISTANCE'),
(59,'CURATOR_REINTRODUCES_P0_FOR_IMPLEMENTATION_GAP','Q5','READINESS','STAGE_AUTHORITY_POLICY','IG-C5_13-STAGE_AUTHORITY_POLICY','REJECT_MUTATION_FAIL_CLOSED','READINESS_POLICY_NOT_SEMANTIC_EQUIVALENCE'),
(60,'CURATOR_REINTRODUCES_P0_FOR_QA_GAP','Q5','READINESS','STAGE_AUTHORITY_POLICY','IG-C5_13-STAGE_AUTHORITY_POLICY','REJECT_MUTATION_FAIL_CLOSED','READINESS_POLICY_NOT_SEMANTIC_EQUIVALENCE'),
(61,'QA_GAP_BLOCKS_IMPLEMENTATION','Q5','READINESS','READINESS_STAGE_HIERARCHY','IG-C5_13-READINESS_STAGE_HIERARCHY','REJECT_MUTATION_FAIL_CLOSED','READINESS_POLICY_NOT_SEMANTIC_EQUIVALENCE'),
(62,'STAGE_SEVERITY_MISMATCH','Q5','READINESS','DETERMINISTIC_STAGE_SUMMARY','IG-C5_13-DETERMINISTIC_STAGE_SUMMARY','REJECT_MUTATION_FAIL_CLOSED','READINESS_POLICY_NOT_SEMANTIC_EQUIVALENCE'),
(63,'RECOVERY_OTP_CLASSIFIED_AS_MFA','Q4','CROSS_FAMILY_COHERENCE','SEMANTIC_COHERENCE_CONTRACT','IG-C5_13-SEMANTIC_COHERENCE_CONTRACT','REJECT_MUTATION_FAIL_CLOSED','CROSS_FAMILY_SEMANTIC_COHERENCE_REQUIRES_GOVERNED_EVIDENCE'),
(64,'RECOVERY_OTP_CREATES_OPERATIONAL_SESSION','Q4','CROSS_FAMILY_COHERENCE','SEMANTIC_COHERENCE_CONTRACT','IG-C5_13-SEMANTIC_COHERENCE_CONTRACT','REJECT_MUTATION_FAIL_CLOSED','CROSS_FAMILY_SEMANTIC_COHERENCE_REQUIRES_GOVERNED_EVIDENCE'),
(65,'RECOVERY_OTP_CREDENTIAL_STUFFING_APPLICABLE','Q4','CROSS_FAMILY_COHERENCE','SEMANTIC_COHERENCE_CONTRACT','IG-C5_13-SEMANTIC_COHERENCE_CONTRACT','REJECT_MUTATION_FAIL_CLOSED','CROSS_FAMILY_SEMANTIC_COHERENCE_REQUIRES_GOVERNED_EVIDENCE'),
(66,'RECOVERY_OTP_REPLAY_OMITTED','Q4','CROSS_FAMILY_COHERENCE','SEMANTIC_DEPTH_CONTRACT','IG-C5_13-SEMANTIC_DEPTH_CONTRACT','REJECT_MUTATION_FAIL_CLOSED','CROSS_FAMILY_SEMANTIC_COHERENCE_REQUIRES_GOVERNED_EVIDENCE'),
(67,'POSITIVE_RULE_ASSERTION_WITH_COVERAGE_MISSING','Q6','ADVERSARIAL_FALSE_PASS','ASSERTION_RELEVANCE_POLICY','IG-C5_13-ASSERTION_RELEVANCE_POLICY','REJECT_MUTATION_FAIL_CLOSED','ADVERSARIAL_FALSE_PASS_RESISTANCE'),
(68,'POSITIVE_RULE_ASSERTION_WITH_FALSE_MISSING_BLOCKER','Q6','ADVERSARIAL_FALSE_PASS','ASSERTION_TRUTH_EVALUATED','IG-C5_13-ASSERTION_TRUTH_EVALUATED','REJECT_MUTATION_FAIL_CLOSED','ADVERSARIAL_FALSE_PASS_RESISTANCE'),
(69,'NA_WITH_CAPABILITY_ABSENCE_PLUS_EMPTY_RULE_SET','Q5','READINESS','NOT_APPLICABLE_POSITIVE_AUTHORITY_CONTRACT','IG-C5_13-NOT_APPLICABLE_POSITIVE_AUTHORITY_CONTRACT','REJECT_MUTATION_FAIL_CLOSED','READINESS_POLICY_NOT_SEMANTIC_EQUIVALENCE'),
(70,'NA_WITH_EMPTY_STATE_SET','Q5','READINESS','NOT_APPLICABLE_POSITIVE_AUTHORITY_CONTRACT','IG-C5_13-NOT_APPLICABLE_POSITIVE_AUTHORITY_CONTRACT','REJECT_MUTATION_FAIL_CLOSED','READINESS_POLICY_NOT_SEMANTIC_EQUIVALENCE'),
(71,'NA_WITH_EXPLICIT_AUTH_EXCLUSION_ACCEPTED','Q5','READINESS','NOT_APPLICABLE_POSITIVE_AUTHORITY_CONTRACT','IG-C5_13-NOT_APPLICABLE_POSITIVE_AUTHORITY_CONTRACT','ACCEPT_NA_WITH_EXPLICIT_AUTHORITY','READINESS_POLICY_NOT_SEMANTIC_EQUIVALENCE'),
(72,'OTP_SOURCE_EXISTS_BUT_MFA_OTP_SSO_NA','Q4','CROSS_FAMILY_COHERENCE','APPLICABILITY_SOURCE_GROUNDING','IG-C5_13-APPLICABILITY_SOURCE_GROUNDING','ACCEPT_NA_WITH_EXPLICIT_SEMANTIC_EXCLUSION','CROSS_FAMILY_SEMANTIC_COHERENCE_REQUIRES_GOVERNED_EVIDENCE'),
(73,'PROPOSAL_WITHOUT_REQUIRED_EVIDENCE','Q6','ADVERSARIAL_FALSE_PASS','PROPOSAL_CONTRACT','IG-C5_13-PROPOSAL_CONTRACT','REJECT_MUTATION_FAIL_CLOSED','ADVERSARIAL_FALSE_PASS_RESISTANCE'),
(74,'PROPOSAL_USED_AS_CANONICAL_SOURCE','Q6','ADVERSARIAL_FALSE_PASS','CANON_VS_PROPOSAL_SEPARATION','IG-C5_13-CANON_VS_PROPOSAL_SEPARATION','REJECT_MUTATION_FAIL_CLOSED','ADVERSARIAL_FALSE_PASS_RESISTANCE'),
(75,'CURATOR_SELF_VALIDATES_PROPOSAL','Q6','ADVERSARIAL_FALSE_PASS','VALIDATOR_INDEPENDENCE_REQUIRED','IG-C5_13-VALIDATOR_INDEPENDENCE_REQUIRED','REJECT_MUTATION_FAIL_CLOSED','ADVERSARIAL_FALSE_PASS_RESISTANCE'),
(76,'PROPOSAL_STALE_SOURCE_WITHOUT_REVALIDATION','Q7','CURRENTNESS_LINEAGE_REPLAY','FRESHNESS_GATE','IG-C5_13-FRESHNESS_GATE','REJECT_MUTATION_FAIL_CLOSED','CURRENTNESS_LINEAGE_REPLAY_NOT_HISTORICAL_PASS'),
(77,'RESEARCH_PROPOSAL_SILENTLY_PROMOTED','Q6','ADVERSARIAL_FALSE_PASS','AUTO_PROMOTION','IG-C5_13-AUTO_PROMOTION','REJECT_MUTATION_FAIL_CLOSED','ADVERSARIAL_FALSE_PASS_RESISTANCE'),
(78,'CANONICAL_VALUE_ORIGINATES_ONLY_FROM_PROPOSAL','Q6','ADVERSARIAL_FALSE_PASS','CANON_VS_PROPOSAL_SEPARATION','IG-C5_13-CANON_VS_PROPOSAL_SEPARATION','REJECT_MUTATION_FAIL_CLOSED','ADVERSARIAL_FALSE_PASS_RESISTANCE'),
(79,'V512_SEMANTIC_DEPTH_GUARD_ACTIVE','Q8','END_TO_END_RELEASE_ASSURANCE','SEMANTIC_DEPTH_CONTRACT','IG-C5_13-SEMANTIC_DEPTH_CONTRACT','REJECT_MUTATION_FAIL_CLOSED','END_TO_END_RELEASE_ASSURANCE_REQUIRES_GOVERNED_EVIDENCE'),
(80,'V512_STAGE_BOUNDARY_GUARD_ACTIVE','Q8','END_TO_END_RELEASE_ASSURANCE','STAGE_BOUNDARY_CONTRACT','IG-C5_13-STAGE_BOUNDARY_CONTRACT','REJECT_MUTATION_FAIL_CLOSED','END_TO_END_RELEASE_ASSURANCE_REQUIRES_GOVERNED_EVIDENCE'),
(81,'SOURCE_PRESENCE_DOES_NOT_EQUAL_SUFFICIENCY','Q3','SEMANTIC','SEMANTIC_COMPONENT_SUFFICIENCY','IG-C5_13-SEMANTIC_COMPONENT_SUFFICIENCY','REJECT_MUTATION_FAIL_CLOSED','SEMANTIC_CORRECTNESS_REQUIRES_GOVERNED_EVIDENCE'),
(82,'PERMISSIONS_DIRECT_RULE_EXCLUSION_RELEVANT','Q4','CROSS_FAMILY_COHERENCE','SEMANTIC_COHERENCE_CONTRACT','IG-C5_13-SEMANTIC_COHERENCE_CONTRACT','REJECT_MUTATION_FAIL_CLOSED','CROSS_FAMILY_SEMANTIC_COHERENCE_REQUIRES_GOVERNED_EVIDENCE'),
(83,'PERMISSIONS_GRAPH_RULES_BROAD_PATH_REJECTED','Q3','SEMANTIC','SCREEN_GRAPH_CONTRACT','IG-C5_13-SCREEN_GRAPH_CONTRACT','REJECT_MUTATION_FAIL_CLOSED','SEMANTIC_CORRECTNESS_REQUIRES_GOVERNED_EVIDENCE'),
(84,'PERMISSIONS_EXCLUSION_RULE_MUST_BE_DECLARED_SOURCE','Q1','STRUCTURAL','SOURCE_REFS_REQUIRED_PER_FAMILY','IG-C5_13-SOURCE_REFS_REQUIRED_PER_FAMILY','REJECT_MUTATION_FAIL_CLOSED','STRUCTURAL_ONLY_NOT_SEMANTIC_OR_READINESS'),
(85,'CONTRACT_STAGE_UNRESOLVED','Q5','READINESS','FAMILY_STAGE_REQUIREMENTS','IG-C5_13-FAMILY_STAGE_REQUIREMENTS','REJECT_MUTATION_FAIL_CLOSED','READINESS_POLICY_NOT_SEMANTIC_EQUIVALENCE'),
(86,'MISSING_FAMILY_STAGE_IMPLICITLY_DEFAULTS_TO_STORY','Q5','READINESS','FAMILY_STAGE_REQUIREMENTS','IG-C5_13-FAMILY_STAGE_REQUIREMENTS','REJECT_MUTATION_FAIL_CLOSED','READINESS_POLICY_NOT_SEMANTIC_EQUIVALENCE'),
(87,'PARAMETER_VALUE_MISSING_AS_STORY_BLOCKER_WHEN_STRUCTURAL_RULE_EXISTS','Q5','READINESS','PARAMETERIZATION_CONTRACT','IG-C5_13-PARAMETERIZATION_CONTRACT','REJECT_MUTATION_FAIL_CLOSED','READINESS_POLICY_NOT_SEMANTIC_EQUIVALENCE'),
(88,'PROVISIONAL_VALUE_SILENTLY_CANONICALIZED','Q7','CURRENTNESS_LINEAGE_REPLAY','CANON_VS_PROPOSAL_SEPARATION','IG-C5_13-CANON_VS_PROPOSAL_SEPARATION','REJECT_MUTATION_FAIL_CLOSED','CURRENTNESS_LINEAGE_REPLAY_NOT_HISTORICAL_PASS'),
(89,'INDUSTRY_GUIDANCE_MISLABELED_AS_INTERNATIONAL_STANDARD','Q6','ADVERSARIAL_FALSE_PASS','GOVERNANCE_AUTHORITY_POLICY','IG-C5_13-GOVERNANCE_AUTHORITY_POLICY','REJECT_MUTATION_FAIL_CLOSED','ADVERSARIAL_FALSE_PASS_RESISTANCE'),
(90,'HARDCODED_CONFIGURABLE_THRESHOLD','Q3','SEMANTIC','PARAMETERIZATION_CONTRACT','IG-C5_13-PARAMETERIZATION_CONTRACT','REJECT_MUTATION_FAIL_CLOSED','SEMANTIC_CORRECTNESS_REQUIRES_GOVERNED_EVIDENCE'),
(91,'PARAMETER_VALUE_CHANGED_WITHOUT_PROVENANCE_REFRESH','Q7','CURRENTNESS_LINEAGE_REPLAY','REVISION_LINEAGE','IG-C5_13-REVISION_LINEAGE','REJECT_MUTATION_FAIL_CLOSED','CURRENTNESS_LINEAGE_REPLAY_NOT_HISTORICAL_PASS')
),
contract_list AS (
  SELECT lc.contract_id, x.ord::integer AS ord, x.t AS negative_test
  FROM latest_contract lc,
       jsonb_array_elements_text(lc.negatives) WITH ORDINALITY AS x(t,ord)
)
INSERT INTO public.lf_test_suite_cases (
  suite_code,test_code,test_order,story_code,rule_codes,title,test_type,execution_mode,severity,
  preconditions,input_payload,expected_output,prohibited_output,status,metadata,
  created_at,updated_at,created_by_execution_id,updated_by_execution_id
)
SELECT
  'INPUT_GOVERNANCE_REGRESSION',
  'M7_3_NEG_'||lpad(m.ord::text,3,'0')||'_'||m.negative_test,
  7300+m.ord,
  NULL,
  ARRAY[m.obligation_code]::text[],
  'M7.3 negative #'||lpad(m.ord::text,3,'0')||' — '||replace(m.negative_test,'_',' '),
  'NEGATIVE',
  'AUTOMATED',
  'HIGH',
  jsonb_build_object(
    'contract_revision','5.13',
    'contract_negative_ordinal',m.ord,
    'oracle_capability','ASSURANCE_EVALUATOR@1.0.0',
    'oracle_call_contract','lf-assurance-evaluator-call-contract/v1',
    'required_entry','ORCHESTRATOR -> dispatch receipt -> guarded bind -> activation gate -> evaluator',
    'exact_active_subject_binding_required',true,
    'runtime_mutation_required',false
  ),
  jsonb_build_object(
    'schema_version','IG_NEGATIVE_FIXTURE_V1',
    'fixture_kind','CONTRACT_NEGATIVE_MUTATION',
    'negative_test',m.negative_test,
    'mutation_code',m.negative_test,
    'contract_revision','5.13',
    'obligation_code',m.obligation_code,
    'synthetic_fixture',true,
    'side_effects',false
  ),
  jsonb_build_object(
    'decision',m.expected_decision,
    'must_not','PASS_WITHOUT_GOVERNED_ORACLE_EVIDENCE'
  ),
  jsonb_build_object(
    'false_pass',true,
    'semantic_pass_from_name_similarity',true,
    'historical_pass_as_current_authority',true
  ),
  'CANDIDATO',
  jsonb_build_object(
    'unit_code','M7.3',
    'work_code','PAULO-052',
    'm7_3_state','EXECUTABLE',
    'contract_negative_test',m.negative_test,
    'contract_ordinal',m.ord,
    'contract_revision','5.13',
    'q_class',m.q_class,
    'dimension',m.dimension,
    'property',m.property,
    'oracle','ASSURANCE_EVALUATOR@1.0.0',
    'oracle_obligation_code',m.obligation_code,
    'oracle_authority','public.lf_assurance_obligation_catalog',
    'expected',m.expected_decision,
    'claim_scope',m.claim_scope,
    'parity_equals_correctness',false,
    'structural_equals_semantic',false,
    'semantic_equals_readiness',false,
    'oracle_activation_state','DEFERRED_BY_GOVERNANCE',
    'equivalence_key',m.obligation_code,
    'dedup_strategy','SHARED_ORACLE_DISTINCT_CONTRACT_TRACE',
    'fixture_locator','public.lf_test_suite_cases.input_payload',
    'evidence',jsonb_build_object(
      'contract_locator','supabase://programacion.contratos/'||cl.contract_id||'#5.13/negative_tests/'||m.ord,
      'oracle_locator','supabase://public.lf_assurance_obligation_catalog/'||m.obligation_code||'@1',
      'call_contract','github://cristhianlujan/claude-persona-lf-patch@3f275d5f2bc114afe46ef94672cc34d57f33ebf2/sandbox/lf_contract_gate_test/assurance_evaluator_boundary/assurance_evaluator_call_contract_v1.json',
      'git_catalog_source','supabase/migrations/20261004063000_ig_cv_m7_3_negative_tests_executable_v1.sql',
      'name_similarity_coverage_forbidden',true
    )
  ),
  now(),now(),'CHATGPT-IG-CV-M7-3-20261004','CHATGPT-IG-CV-M7-3-20261004'
FROM mapping m
JOIN contract_list cl
  ON cl.ord=m.ord AND cl.negative_test=m.negative_test
JOIN public.lf_assurance_obligation_catalog o
  ON o.obligation_code=m.obligation_code
 AND o.version=1
 AND o.claim_code='INPUT_GOVERNANCE_CONTRACT_5_13_ASSURANCE_V1'
 AND o.required=true;

UPDATE public.lf_test_suites
SET metadata = coalesce(metadata,'{}'::jsonb) || jsonb_build_object(
      'm7_3_negative_contract',jsonb_build_object(
        'version','M7_3_NEGATIVE_CONTRACT_V1',
        'unit_code','M7.3',
        'work_code','PAULO-052',
        'contract_revision','5.13',
        'contract_negative_count',91,
        'reconciliation_policy','ONE_CONTRACT_NEGATIVE_ONE_TRACEABLE_CASE',
        'state_policy','EXECUTABLE_OR_EXPLICIT_NA',
        'planned_executable_count',91,
        'planned_na_count',0,
        'oracle','ASSURANCE_EVALUATOR@1.0.0',
        'oracle_authority','public.lf_assurance_obligation_catalog',
        'oracle_execution_activation','DEFERRED_BY_GOVERNANCE',
        'no_parallel_suite',true,
        'no_parallel_test_engine',true,
        'name_similarity_coverage_forbidden',true,
        'dedup_policy','SHARED_ORACLE_DISTINCT_CONTRACT_TRACE',
        'q_distribution',jsonb_build_object(
          'Q1',6,'Q3',15,'Q4',12,'Q5',30,'Q6',15,'Q7',11,'Q8',2
        )
      )
    ),
    updated_at=now(),
    updated_by_execution_id='CHATGPT-IG-CV-M7-3-20261004'
WHERE suite_code='INPUT_GOVERNANCE_REGRESSION';

DO $m7_3_negative_incomplete_probe$
DECLARE
  v_probe jsonb := jsonb_build_object(
    'fixture',jsonb_build_object('negative_test','INCOMPLETE_PROBE'),
    'expected','REJECT_MUTATION_FAIL_CLOSED'
  );
  v_accepted boolean;
BEGIN
  v_accepted :=
      v_probe ? 'fixture'
  AND nullif(v_probe->>'expected','') IS NOT NULL
  AND nullif(v_probe->>'oracle','') IS NOT NULL
  AND nullif(v_probe->>'q_class','') IS NOT NULL;

  IF v_accepted THEN
    RAISE EXCEPTION 'M7_3_INCOMPLETE_CASE_FALSE_ACCEPT';
  END IF;
END
$m7_3_negative_incomplete_probe$;

DO $m7_3_readback$
DECLARE
  v_total integer;
  v_exec integer;
  v_na integer;
  v_incomplete integer;
  v_contract_match integer;
  v_dup integer;
  v_invalid_q integer;
BEGIN
  SELECT
    count(*),
    count(*) FILTER (WHERE metadata->>'m7_3_state'='EXECUTABLE'),
    count(*) FILTER (WHERE metadata->>'m7_3_state'='N/A'),
    count(*) FILTER (
      WHERE input_payload IS NULL
         OR expected_output IS NULL
         OR nullif(metadata->>'oracle','') IS NULL
         OR nullif(metadata->>'oracle_obligation_code','') IS NULL
         OR nullif(metadata->>'q_class','') IS NULL
         OR nullif(metadata->>'dimension','') IS NULL
         OR nullif(metadata->>'property','') IS NULL
         OR NOT (metadata ? 'evidence')
         OR metadata->'evidence' IS NULL
         OR metadata->'evidence'='null'::jsonb
         OR (
           metadata->>'m7_3_state'='N/A'
           AND (
             nullif(metadata->>'na_reason','') IS NULL
             OR nullif(metadata->>'na_authority','') IS NULL
           )
         )
    ),
    count(*) FILTER (
      WHERE metadata->>'q_class' NOT IN ('Q0','Q1','Q2','Q3','Q4','Q5','Q6','Q7','Q8')
    )
  INTO v_total,v_exec,v_na,v_incomplete,v_invalid_q
  FROM public.lf_test_suite_cases
  WHERE suite_code='INPUT_GOVERNANCE_REGRESSION'
    AND metadata->>'unit_code'='M7.3';

  SELECT count(*) INTO v_contract_match
  FROM programacion.contratos c,
       jsonb_array_elements_text(c.especificacion->'negative_tests') WITH ORDINALITY AS x(t,ord)
  JOIN public.lf_test_suite_cases sc
    ON sc.suite_code='INPUT_GOVERNANCE_REGRESSION'
   AND sc.metadata->>'unit_code'='M7.3'
   AND (sc.metadata->>'contract_ordinal')::integer=x.ord
   AND sc.metadata->>'contract_negative_test'=x.t
  WHERE c.id=(SELECT max(id) FROM programacion.contratos WHERE contrato_codigo='INPUT_READINESS_CONTRACT');

  SELECT count(*) INTO v_dup
  FROM (
    SELECT metadata->>'contract_negative_test'
    FROM public.lf_test_suite_cases
    WHERE suite_code='INPUT_GOVERNANCE_REGRESSION'
      AND metadata->>'unit_code'='M7.3'
    GROUP BY metadata->>'contract_negative_test'
    HAVING count(*)<>1
  ) d;

  IF v_total<>91 OR v_exec+v_na<>91 OR v_exec<>91 OR v_na<>0
     OR v_incomplete<>0 OR v_contract_match<>91 OR v_dup<>0 OR v_invalid_q<>0 THEN
    RAISE EXCEPTION
      'M7_3_READBACK_FAILED:total=% exec=% na=% incomplete=% contract_match=% dup=% invalid_q=%',
      v_total,v_exec,v_na,v_incomplete,v_contract_match,v_dup,v_invalid_q;
  END IF;
END
$m7_3_readback$;

COMMIT;
