-- IG M7.10 FIXTURES. Git-first; only public.lf_test_suite_cases. Synthetic data definitions only; NO runtime invocation.
-- Fixtures are self-contained, test-only, disposable via rollback; do not insert lf_ops screens or fake provenance receipts.
-- E2E results require separate run receipts; registering CANDIDATO cases does not attest success.
INSERT INTO public.lf_test_suite_cases
  (suite_code,test_code,test_order,title,test_type,execution_mode,severity,preconditions,input_payload,expected_output,prohibited_output,status,metadata,created_by_execution_id)
VALUES
('INPUT_GOVERNANCE_REGRESSION','M7_10_SOURCE_STALE_SUCCESS',730010,'Fuente cambia y dispara SOURCE_STALE_RECURATE sin reutilizar run histórico','DETERMINISTIC','AUTOMATED','HIGH','[{"type":"FIXTURE_ONLY","requires":"SANDBOX_OR_ROLLBACK"},{"type":"PRODUCER_RECEIPTS","policy":"APPLICABLE_ONLY"}]'::jsonb,'{"test_code":"M7_10_SOURCE_STALE_SUCCESS","suite_code":"INPUT_GOVERNANCE_REGRESSION","test_order":730010,"title":"Fuente cambia y dispara SOURCE_STALE_RECURATE sin reutilizar run histórico","fixture_id":"ig-m7-10-source_stale-v1","fixture_version":"1.0.0","mode":"SOURCE_STALE","screen":{"screen_fixture_key":"IG_E2E_SANDBOX_SCREEN","is_synthetic":true,"layout":{"sections":["HEADER","BODY"],"controls":["INPUT_DEBT","SUBMIT"]},"identity":{"route":"/ig-fixture/test-only","screen_code":"IG_E2E_SANDBOX_SCREEN"}},"sources":[{"source_ref":"fixture://m7_10/debt/mock-v1","source_kind":"API_DATA_CONTRACT","authority_class":"FIXTURE_ONLY","lifecycle":"CANDIDATE","revision":1,"attributes":{"debt_amount":100,"owner":"mock-debtor"}},{"source_ref":"fixture://m7_10/rules/mock-v1","source_kind":"RULE","authority_class":"FIXTURE_ONLY","lifecycle":"CANDIDATE","revision":1,"attributes":{"threshold":30}}],"rules":[{"code":"IG_M7_10_RULE_01","rule_kind":"VALIDATION","expression":{"op":"GTE","field":"debt_amount","value":30},"expected":true}],"trigger":{"kind":"SOURCE_STALE","change_source_ref":"fixture://m7_10/debt/mock-v1","from_revision":1,"to_revision":2,"simulate_blocked":false,"missing_receipt_kind":null},"expected":{"recuration_mode":"SOURCE_STALE","successor_status":"COMPLETED","predecessor_invalidated_only_after_completed":true,"manifest_reflected_source_change":true},"cleanup":{"mode":"ROLLBACK","prohibit_persistent_screen_data":true,"cleanup_assertion":"NO_RESIDUE"},"history":{"new_fixture_only":true,"historical_run_id":null}}'::jsonb,'{"recuration_mode":"SOURCE_STALE","successor_status":"COMPLETED","predecessor_invalidated_only_after_completed":true,"manifest_reflected_source_change":true}'::jsonb,'{"synthetic_receipts_allowed":false,"production_screen_mutation_allowed":false}'::jsonb,'CANDIDATO','{"fixture_id":"ig-m7-10-source_stale-v1","fixture_version":"1.0.0","unit_code":"M7.10","checkpoint":"FIXTURES","scenario":"SOURCE_STALE","oracle":"M7_10_E2E_OUTCOME","fixtures_only":true,"source_corpus":"M0.7","design_note":"CANDIDATO only. NO E2E execution implied; real E2E run + upstream repair gates required.","cleanup":{"mode":"ROLLBACK","test_data_cleanup_required":true}}'::jsonb,'IG_M7_10_FIXTURES_20261007'),
('INPUT_GOVERNANCE_REGRESSION','M7_10_FULL_RECURATION_SUCCESS',730020,'Recuración FULL sobre fixture propio con fuentes y reglas','DETERMINISTIC','AUTOMATED','HIGH','[{"type":"FIXTURE_ONLY","requires":"SANDBOX_OR_ROLLBACK"},{"type":"PRODUCER_RECEIPTS","policy":"APPLICABLE_ONLY"}]'::jsonb,'{"test_code":"M7_10_FULL_RECURATION_SUCCESS","suite_code":"INPUT_GOVERNANCE_REGRESSION","test_order":730020,"title":"Recuración FULL sobre fixture propio con fuentes y reglas","fixture_id":"ig-m7-10-full-v1","fixture_version":"1.0.0","mode":"FULL","screen":{"screen_fixture_key":"IG_E2E_SANDBOX_SCREEN","is_synthetic":true,"layout":{"sections":["HEADER","BODY"],"controls":["INPUT_DEBT","SUBMIT"]},"identity":{"route":"/ig-fixture/test-only","screen_code":"IG_E2E_SANDBOX_SCREEN"}},"sources":[{"source_ref":"fixture://m7_10/debt/mock-v1","source_kind":"API_DATA_CONTRACT","authority_class":"FIXTURE_ONLY","lifecycle":"CANDIDATE","revision":1,"attributes":{"debt_amount":100,"owner":"mock-debtor"}},{"source_ref":"fixture://m7_10/rules/mock-v1","source_kind":"RULE","authority_class":"FIXTURE_ONLY","lifecycle":"CANDIDATE","revision":1,"attributes":{"threshold":30}}],"rules":[{"code":"IG_M7_10_RULE_01","rule_kind":"VALIDATION","expression":{"op":"GTE","field":"debt_amount","value":30},"expected":true}],"trigger":{"kind":"FULL","change_source_ref":"fixture://m7_10/debt/mock-v1","from_revision":1,"to_revision":2,"simulate_blocked":false,"missing_receipt_kind":null},"expected":{"recuration_mode":"FULL","successor_status":"COMPLETED","predecessor_invalidated_only_after_completed":true,"manifest_reflected_source_change":true},"cleanup":{"mode":"ROLLBACK","prohibit_persistent_screen_data":true,"cleanup_assertion":"NO_RESIDUE"},"history":{"new_fixture_only":true,"historical_run_id":null}}'::jsonb,'{"recuration_mode":"FULL","successor_status":"COMPLETED","predecessor_invalidated_only_after_completed":true,"manifest_reflected_source_change":true}'::jsonb,'{"synthetic_receipts_allowed":false,"production_screen_mutation_allowed":false}'::jsonb,'CANDIDATO','{"fixture_id":"ig-m7-10-full-v1","fixture_version":"1.0.0","unit_code":"M7.10","checkpoint":"FIXTURES","scenario":"FULL","oracle":"M7_10_E2E_OUTCOME","fixtures_only":true,"source_corpus":"M0.7","design_note":"CANDIDATO only. NO E2E execution implied; real E2E run + upstream repair gates required.","cleanup":{"mode":"ROLLBACK","test_data_cleanup_required":true}}'::jsonb,'IG_M7_10_FIXTURES_20261007'),
('INPUT_GOVERNANCE_REGRESSION','M7_10_BLOCKED_SUCCESSOR_PRESERVE',730030,'Sucesor bloqueado conserva vigencia del predecesor','DETERMINISTIC','AUTOMATED','HIGH','[{"type":"FIXTURE_ONLY","requires":"SANDBOX_OR_ROLLBACK"},{"type":"PRODUCER_RECEIPTS","policy":"APPLICABLE_ONLY"}]'::jsonb,'{"test_code":"M7_10_BLOCKED_SUCCESSOR_PRESERVE","suite_code":"INPUT_GOVERNANCE_REGRESSION","test_order":730030,"title":"Sucesor bloqueado conserva vigencia del predecesor","fixture_id":"ig-m7-10-blocked-v1","fixture_version":"1.0.0","mode":"BLOCKED","screen":{"screen_fixture_key":"IG_E2E_SANDBOX_SCREEN","is_synthetic":true,"layout":{"sections":["HEADER","BODY"],"controls":["INPUT_DEBT","SUBMIT"]},"identity":{"route":"/ig-fixture/test-only","screen_code":"IG_E2E_SANDBOX_SCREEN"}},"sources":[{"source_ref":"fixture://m7_10/debt/mock-v1","source_kind":"API_DATA_CONTRACT","authority_class":"FIXTURE_ONLY","lifecycle":"CANDIDATE","revision":1,"attributes":{"debt_amount":100,"owner":"mock-debtor"}},{"source_ref":"fixture://m7_10/rules/mock-v1","source_kind":"RULE","authority_class":"FIXTURE_ONLY","lifecycle":"CANDIDATE","revision":1,"attributes":{"threshold":30}}],"rules":[{"code":"IG_M7_10_RULE_01","rule_kind":"VALIDATION","expression":{"op":"GTE","field":"debt_amount","value":30},"expected":true}],"trigger":{"kind":"BLOCKED","change_source_ref":"fixture://m7_10/debt/mock-v1","from_revision":1,"to_revision":2,"simulate_blocked":true,"missing_receipt_kind":null},"expected":{"successor_status":"BLOCKED","predecessor_remains_current":true,"invalidated_by_blocked":false},"cleanup":{"mode":"ROLLBACK","prohibit_persistent_screen_data":true,"cleanup_assertion":"NO_RESIDUE"},"history":{"new_fixture_only":true,"historical_run_id":null}}'::jsonb,'{"successor_status":"BLOCKED","predecessor_remains_current":true,"invalidated_by_blocked":false}'::jsonb,'{"synthetic_receipts_allowed":false,"production_screen_mutation_allowed":false}'::jsonb,'CANDIDATO','{"fixture_id":"ig-m7-10-blocked-v1","fixture_version":"1.0.0","unit_code":"M7.10","checkpoint":"FIXTURES","scenario":"BLOCKED","oracle":"M7_10_E2E_OUTCOME","fixtures_only":true,"source_corpus":"M0.7","design_note":"CANDIDATO only. NO E2E execution implied; real E2E run + upstream repair gates required.","cleanup":{"mode":"ROLLBACK","test_data_cleanup_required":true}}'::jsonb,'IG_M7_10_FIXTURES_20261007'),
('INPUT_GOVERNANCE_REGRESSION','M7_10_UPSTREAM_RECEIPT_MISSING_FAIL_CLOSED',730040,'Receipt upstream aplicable ausente debe fallar cerrado antes de E2E','DETERMINISTIC','AUTOMATED','HIGH','[{"type":"FIXTURE_ONLY","requires":"SANDBOX_OR_ROLLBACK"},{"type":"PRODUCER_RECEIPTS","policy":"APPLICABLE_ONLY"}]'::jsonb,'{"test_code":"M7_10_UPSTREAM_RECEIPT_MISSING_FAIL_CLOSED","suite_code":"INPUT_GOVERNANCE_REGRESSION","test_order":730040,"title":"Receipt upstream aplicable ausente debe fallar cerrado antes de E2E","fixture_id":"ig-m7-10-upstream_missing-v1","fixture_version":"1.0.0","mode":"UPSTREAM_MISSING","screen":{"screen_fixture_key":"IG_E2E_SANDBOX_SCREEN","is_synthetic":true,"layout":{"sections":["HEADER","BODY"],"controls":["INPUT_DEBT","SUBMIT"]},"identity":{"route":"/ig-fixture/test-only","screen_code":"IG_E2E_SANDBOX_SCREEN"}},"sources":[{"source_ref":"fixture://m7_10/debt/mock-v1","source_kind":"API_DATA_CONTRACT","authority_class":"FIXTURE_ONLY","lifecycle":"CANDIDATE","revision":1,"attributes":{"debt_amount":100,"owner":"mock-debtor"}},{"source_ref":"fixture://m7_10/rules/mock-v1","source_kind":"RULE","authority_class":"FIXTURE_ONLY","lifecycle":"CANDIDATE","revision":1,"attributes":{"threshold":30}}],"rules":[{"code":"IG_M7_10_RULE_01","rule_kind":"VALIDATION","expression":{"op":"GTE","field":"debt_amount","value":30},"expected":true}],"trigger":{"kind":"UPSTREAM_MISSING","change_source_ref":"fixture://m7_10/debt/mock-v1","from_revision":1,"to_revision":2,"simulate_blocked":false,"missing_receipt_kind":"SOURCE"},"expected":{"pretest_gate":"FAIL","e2e_execution_allowed":false,"synthetic_receipt_accepted":false},"cleanup":{"mode":"ROLLBACK","prohibit_persistent_screen_data":true,"cleanup_assertion":"NO_RESIDUE"},"history":{"new_fixture_only":true,"historical_run_id":null}}'::jsonb,'{"pretest_gate":"FAIL","e2e_execution_allowed":false,"synthetic_receipt_accepted":false}'::jsonb,'{"synthetic_receipts_allowed":false,"production_screen_mutation_allowed":false}'::jsonb,'CANDIDATO','{"fixture_id":"ig-m7-10-upstream_missing-v1","fixture_version":"1.0.0","unit_code":"M7.10","checkpoint":"FIXTURES","scenario":"UPSTREAM_MISSING","oracle":"M7_10_E2E_OUTCOME","fixtures_only":true,"source_corpus":"M0.7","design_note":"CANDIDATO only. NO E2E execution implied; real E2E run + upstream repair gates required.","cleanup":{"mode":"ROLLBACK","test_data_cleanup_required":true}}'::jsonb,'IG_M7_10_FIXTURES_20261007')
ON CONFLICT (suite_code,test_code) DO NOTHING;

DO $verify$
DECLARE n int;
BEGIN
  SELECT count(*) INTO n FROM public.lf_test_suite_cases
  WHERE suite_code='INPUT_GOVERNANCE_REGRESSION' AND test_code IN ('M7_10_SOURCE_STALE_SUCCESS','M7_10_FULL_RECURATION_SUCCESS','M7_10_BLOCKED_SUCCESSOR_PRESERVE','M7_10_UPSTREAM_RECEIPT_MISSING_FAIL_CLOSED')
    AND input_payload->'history'->>'new_fixture_only'='true'
    AND input_payload->'screen'->>'is_synthetic'='true'
    AND input_payload->'cleanup'->>'mode'='ROLLBACK'
    AND input_payload->>'fixture_version'='1.0.0';
  IF n<>4 THEN RAISE EXCEPTION 'M7_10_FIXTURE_VALIDATION_MISMATCH expected=4 observed=%',n; END IF;
END;
$verify$;
