create table public.lf_task_mode_catalog (
  task_mode text primary key,
  description text not null,
  allows_new_target boolean not null default false,
  requires_existing_target boolean not null default false,
  mutation_intent boolean not null default false,
  reference_source text not null,
  status text not null default 'ACTIVE' check (status in ('ACTIVE','RETIRED')),
  created_by_execution_id text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (not (allows_new_target and requires_existing_target))
);
alter table public.lf_task_mode_catalog enable row level security;
revoke all on public.lf_task_mode_catalog from public,anon,authenticated;
grant select on public.lf_task_mode_catalog to service_role;

create table public.lf_execution_mode_catalog (
  execution_mode text primary key,
  description text not null,
  allows_partial_input boolean not null default false,
  canonical_write_allowed boolean not null default false,
  runtime_allowed boolean not null default false,
  promotion_allowed boolean not null default false,
  requires_evidence_complete boolean not null default false,
  reference_source text not null,
  status text not null default 'ACTIVE' check (status in ('ACTIVE','RETIRED')),
  created_by_execution_id text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
alter table public.lf_execution_mode_catalog enable row level security;
revoke all on public.lf_execution_mode_catalog from public,anon,authenticated;
grant select on public.lf_execution_mode_catalog to service_role;

create table public.lf_operation_mode_bindings (
  operation_code text not null references public.lf_operation_registry(operation_code) on delete restrict,
  task_mode text not null references public.lf_task_mode_catalog(task_mode) on delete restrict,
  execution_mode text not null references public.lf_execution_mode_catalog(execution_mode) on delete restrict,
  allowed boolean not null default false,
  write_allowed boolean not null default false,
  destination_kind text not null check (destination_kind in ('EXPLORATION_STORE','CANONICAL_CANDIDATE','NO_WRITE')),
  input_completeness text not null check (input_completeness in ('PARTIAL_ALLOWED','COMPLETE_REQUIRED','READ_ONLY')),
  canonical_state text null,
  required_existing_state text null,
  notes text null,
  status text not null default 'ACTIVE' check (status in ('ACTIVE','RETIRED')),
  created_by_execution_id text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key(operation_code,task_mode,execution_mode),
  check (not write_allowed or allowed),
  check ((destination_kind='NO_WRITE' and write_allowed=false) or destination_kind<>'NO_WRITE')
);
alter table public.lf_operation_mode_bindings enable row level security;
revoke all on public.lf_operation_mode_bindings from public,anon,authenticated;
grant select on public.lf_operation_mode_bindings to service_role;

create table public.lf_input_exploration_records (
  exploration_id uuid primary key default gen_random_uuid(),
  asset_type text not null,
  task_mode text not null references public.lf_task_mode_catalog(task_mode) on delete restrict,
  execution_mode text not null references public.lf_execution_mode_catalog(execution_mode) on delete restrict,
  target_code text null,
  source_pantalla_id integer null references lf_ops.pantallas(id) on delete restrict,
  source_context jsonb not null default '{}'::jsonb,
  partial_payload jsonb not null default '{}'::jsonb,
  missing_fields jsonb not null default '[]'::jsonb,
  governance_status text not null default 'OPEN' check (governance_status in ('OPEN','READY_FOR_INPUT_GOVERNANCE','CONSUMED','ARCHIVED')),
  canonical_rule_code text null,
  revision integer not null default 1 check (revision>=1),
  created_by_execution_id text not null,
  updated_by_execution_id text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (jsonb_typeof(source_context)='object'),
  check (jsonb_typeof(partial_payload)='object'),
  check (jsonb_typeof(missing_fields)='array'),
  check (execution_mode='EXPLORATION')
);
create index lf_input_exploration_records_status_idx on public.lf_input_exploration_records(governance_status,asset_type,updated_at desc);
create index lf_input_exploration_records_pantalla_idx on public.lf_input_exploration_records(source_pantalla_id) where source_pantalla_id is not null;
alter table public.lf_input_exploration_records enable row level security;
revoke all on public.lf_input_exploration_records from public,anon,authenticated;
grant select,insert,update on public.lf_input_exploration_records to service_role;

create table public.lf_input_exploration_events (
  event_id bigint generated by default as identity primary key,
  exploration_id uuid not null references public.lf_input_exploration_records(exploration_id) on delete restrict,
  revision integer not null check (revision>=1),
  task_mode text not null references public.lf_task_mode_catalog(task_mode) on delete restrict,
  delta_payload jsonb not null,
  snapshot_payload jsonb not null,
  source_context_delta jsonb not null default '{}'::jsonb,
  governance_status text not null,
  created_by_execution_id text not null,
  created_at timestamptz not null default now(),
  unique(exploration_id,revision),
  check (jsonb_typeof(delta_payload)='object'),
  check (jsonb_typeof(snapshot_payload)='object'),
  check (jsonb_typeof(source_context_delta)='object')
);
alter table public.lf_input_exploration_events enable row level security;
revoke all on public.lf_input_exploration_events from public,anon,authenticated;
grant select,insert on public.lf_input_exploration_events to service_role;
grant usage,select on sequence public.lf_input_exploration_events_event_id_seq to service_role;

insert into public.lf_task_mode_catalog(task_mode,description,allows_new_target,requires_existing_target,mutation_intent,reference_source,created_by_execution_id) values
('CREATE_NEW','Create a new target. Vocabulary observed in UI Architect.',true,false,true,'UI_ARCHITECT','EXEC-ACTUALIZACION-DB-MODE-NORMALIZATION-20260913-001'),
('EVALUATE_EXISTING','Evaluate an existing target without mutating it. Vocabulary observed in UI Architect.',false,true,false,'UI_ARCHITECT','EXEC-ACTUALIZACION-DB-MODE-NORMALIZATION-20260913-001'),
('REMEDIATE_EXISTING','Modify or remediate an existing target. Vocabulary observed in UI Architect.',false,true,true,'UI_ARCHITECT','EXEC-ACTUALIZACION-DB-MODE-NORMALIZATION-20260913-001');

insert into public.lf_execution_mode_catalog(execution_mode,description,allows_partial_input,canonical_write_allowed,runtime_allowed,promotion_allowed,requires_evidence_complete,reference_source,created_by_execution_id) values
('SANDBOX','Non-production execution mode observed in UI Architect.',false,false,false,false,false,'UI_ARCHITECT','EXEC-ACTUALIZACION-DB-MODE-NORMALIZATION-20260913-001'),
('EXPLORATION','LF normalized exploratory mode: partial information may accumulate, but cannot write canonical rules, activate runtime, or promote.',true,false,false,false,false,'LF_NORMALIZATION_FROM_UI_MODE_PATTERN','EXEC-ACTUALIZACION-DB-MODE-NORMALIZATION-20260913-001'),
('GOVERNED','LF normalized governed mode: complete evidence is required before canonical candidate write; no runtime or promotion implied.',false,true,false,false,true,'LF_NORMALIZATION_FROM_UI_MODE_PATTERN','EXEC-ACTUALIZACION-DB-MODE-NORMALIZATION-20260913-001');

insert into public.lf_operation_mode_bindings(operation_code,task_mode,execution_mode,allowed,write_allowed,destination_kind,input_completeness,canonical_state,required_existing_state,notes,created_by_execution_id) values
('CREACION_REGLA_LF','CREATE_NEW','EXPLORATION',true,true,'EXPLORATION_STORE','PARTIAL_ALLOWED',null,null,'Incomplete rule discovery; canonical lf_ops.reglas remains untouched.','EXEC-ACTUALIZACION-DB-MODE-NORMALIZATION-20260913-001'),
('CREACION_REGLA_LF','CREATE_NEW','GOVERNED',true,true,'CANONICAL_CANDIDATE','COMPLETE_REQUIRED','CANDIDATO',null,'Strict canonical rule candidate creation.','EXEC-ACTUALIZACION-DB-MODE-NORMALIZATION-20260913-001'),
('ACTUALIZACION_REGLA_LF','EVALUATE_EXISTING','EXPLORATION',true,false,'NO_WRITE','READ_ONLY',null,null,'Read/evaluate existing exploratory context without mutation.','EXEC-ACTUALIZACION-DB-MODE-NORMALIZATION-20260913-001'),
('ACTUALIZACION_REGLA_LF','REMEDIATE_EXISTING','EXPLORATION',true,true,'EXPLORATION_STORE','PARTIAL_ALLOWED',null,null,'Accumulate partial rule information before governed normalization.','EXEC-ACTUALIZACION-DB-MODE-NORMALIZATION-20260913-001'),
('ACTUALIZACION_REGLA_LF','REMEDIATE_EXISTING','GOVERNED',true,true,'CANONICAL_CANDIDATE','COMPLETE_REQUIRED','CANDIDATO','CANDIDATO','Strict update of an existing canonical rule candidate; VIGENTE remains blocked.','EXEC-ACTUALIZACION-DB-MODE-NORMALIZATION-20260913-001');

create or replace function public.lf_resolve_operation_mode_v1(p_operation_code text,p_task_mode text,p_execution_mode text)
returns jsonb language plpgsql security invoker set search_path=pg_catalog,public as $$
declare v_b public.lf_operation_mode_bindings%rowtype; v_t public.lf_task_mode_catalog%rowtype; v_m public.lf_execution_mode_catalog%rowtype;
begin
 if btrim(coalesce(p_operation_code,''))='' or btrim(coalesce(p_task_mode,''))='' or btrim(coalesce(p_execution_mode,''))='' then return jsonb_build_object('status','BLOCKED','blocking_code','MODE_IDENTITY_MISSING'); end if;
 select * into v_t from public.lf_task_mode_catalog where task_mode=upper(p_task_mode) and status='ACTIVE';
 if not found then return jsonb_build_object('status','BLOCKED','blocking_code','TASK_MODE_NOT_ACTIVE','task_mode',upper(p_task_mode)); end if;
 select * into v_m from public.lf_execution_mode_catalog where execution_mode=upper(p_execution_mode) and status='ACTIVE';
 if not found then return jsonb_build_object('status','BLOCKED','blocking_code','EXECUTION_MODE_NOT_ACTIVE','execution_mode',upper(p_execution_mode)); end if;
 select * into v_b from public.lf_operation_mode_bindings where operation_code=p_operation_code and task_mode=v_t.task_mode and execution_mode=v_m.execution_mode and status='ACTIVE';
 if not found or not v_b.allowed then return jsonb_build_object('status','BLOCKED','blocking_code','OPERATION_MODE_NOT_ALLOWED','operation_code',p_operation_code,'task_mode',v_t.task_mode,'execution_mode',v_m.execution_mode); end if;
 return jsonb_build_object('status','READY','operation_code',v_b.operation_code,'task_mode',v_b.task_mode,'execution_mode',v_b.execution_mode,'write_allowed',v_b.write_allowed,'destination_kind',v_b.destination_kind,'input_completeness',v_b.input_completeness,'canonical_state',v_b.canonical_state,'required_existing_state',v_b.required_existing_state,'allows_partial_input',v_m.allows_partial_input,'canonical_write_allowed',v_m.canonical_write_allowed,'runtime_allowed',v_m.runtime_allowed,'promotion_allowed',v_m.promotion_allowed,'reference_source',v_m.reference_source);
end $$;
revoke all on function public.lf_resolve_operation_mode_v1(text,text,text) from public,anon,authenticated;
grant execute on function public.lf_resolve_operation_mode_v1(text,text,text) to service_role;

create or replace function public.lf_input_exploration_capture_v1(p_execution_id text,p_asset_type text,p_task_mode text,p_partial_payload jsonb,p_exploration_id uuid default null,p_target_code text default null,p_source_pantalla_id integer default null,p_source_context jsonb default '{}'::jsonb,p_mark_ready boolean default false)
returns jsonb language plpgsql security invoker set search_path=pg_catalog,public,lf_ops as $$
declare v_exec public.lf_operation_execution%rowtype; v_mode jsonb; v_rec public.lf_input_exploration_records%rowtype; v_snapshot jsonb; v_context jsonb; v_missing jsonb; v_revision integer; v_status text; v_id uuid;
begin
 if btrim(coalesce(p_execution_id,''))='' or upper(coalesce(p_asset_type,''))<>'REGLA' then raise exception 'LF_EXPLORATION_IDENTITY_INVALID'; end if;
 if p_partial_payload is null or jsonb_typeof(p_partial_payload)<>'object' or p_partial_payload='{}'::jsonb then raise exception 'LF_EXPLORATION_PARTIAL_PAYLOAD_REQUIRED'; end if;
 if p_source_context is null or jsonb_typeof(p_source_context)<>'object' then raise exception 'LF_EXPLORATION_SOURCE_CONTEXT_INVALID'; end if;
 select * into v_exec from public.lf_operation_execution where execution_id=p_execution_id;
 if not found or v_exec.status<>'IN_PROGRESS' or v_exec.target_type<>'REGLA' then raise exception 'LF_EXPLORATION_EXECUTION_INVALID'; end if;
 v_mode:=public.lf_resolve_operation_mode_v1(v_exec.operation_code,upper(p_task_mode),'EXPLORATION');
 if v_mode->>'status'<>'READY' or coalesce((v_mode->>'write_allowed')::boolean,false) is not true or v_mode->>'destination_kind'<>'EXPLORATION_STORE' then raise exception 'LF_EXPLORATION_MODE_WRITE_NOT_ALLOWED:%',coalesce(v_mode->>'blocking_code','NO_WRITE'); end if;
 if p_source_pantalla_id is not null and not exists(select 1 from lf_ops.pantallas where id=p_source_pantalla_id) then raise exception 'LF_EXPLORATION_SCREEN_NOT_FOUND:%',p_source_pantalla_id; end if;
 v_status:=case when coalesce(p_mark_ready,false) then 'READY_FOR_INPUT_GOVERNANCE' else 'OPEN' end;
 if upper(p_task_mode)='CREATE_NEW' then
   if p_exploration_id is not null then raise exception 'LF_EXPLORATION_CREATE_ID_MUST_BE_NULL'; end if;
   v_snapshot:=p_partial_payload; v_context:=p_source_context; v_revision:=1;
   select coalesce(jsonb_agg(k order by ord),'[]'::jsonb) into v_missing from (values (1,'codigo'),(2,'categoria'),(3,'titulo'),(4,'descripcion')) x(ord,k) where nullif(btrim(coalesce(v_snapshot->>k,'')),'') is null;
   insert into public.lf_input_exploration_records(asset_type,task_mode,execution_mode,target_code,source_pantalla_id,source_context,partial_payload,missing_fields,governance_status,revision,created_by_execution_id,updated_by_execution_id)
   values('REGLA','CREATE_NEW','EXPLORATION',coalesce(nullif(btrim(p_target_code),''),nullif(btrim(v_snapshot->>'codigo'),'')),p_source_pantalla_id,v_context,v_snapshot,v_missing,v_status,1,p_execution_id,p_execution_id) returning * into v_rec; v_id:=v_rec.exploration_id;
 else
   if upper(p_task_mode)<>'REMEDIATE_EXISTING' or p_exploration_id is null then raise exception 'LF_EXPLORATION_REMEDIATE_ID_REQUIRED'; end if;
   select * into v_rec from public.lf_input_exploration_records where exploration_id=p_exploration_id for update;
   if not found or v_rec.asset_type<>'REGLA' or v_rec.execution_mode<>'EXPLORATION' or v_rec.governance_status in ('CONSUMED','ARCHIVED') then raise exception 'LF_EXPLORATION_RECORD_NOT_MUTABLE'; end if;
   v_snapshot:=v_rec.partial_payload||p_partial_payload; v_context:=v_rec.source_context||p_source_context; v_revision:=v_rec.revision+1; v_id=v_rec.exploration_id;
   select coalesce(jsonb_agg(k order by ord),'[]'::jsonb) into v_missing from (values (1,'codigo'),(2,'categoria'),(3,'titulo'),(4,'descripcion')) x(ord,k) where nullif(btrim(coalesce(v_snapshot->>k,'')),'') is null;
   update public.lf_input_exploration_records set task_mode='REMEDIATE_EXISTING',target_code=coalesce(nullif(btrim(p_target_code),''),nullif(btrim(v_snapshot->>'codigo'),''),target_code),source_pantalla_id=coalesce(p_source_pantalla_id,source_pantalla_id),source_context=v_context,partial_payload=v_snapshot,missing_fields=v_missing,governance_status=v_status,revision=v_revision,updated_by_execution_id=p_execution_id,updated_at=now() where exploration_id=v_id returning * into v_rec;
 end if;
 insert into public.lf_input_exploration_events(exploration_id,revision,task_mode,delta_payload,snapshot_payload,source_context_delta,governance_status,created_by_execution_id) values(v_id,v_revision,upper(p_task_mode),p_partial_payload,v_snapshot,p_source_context,v_status,p_execution_id);
 return jsonb_build_object('result','EXPLORATION_CAPTURED','exploration_id',v_id,'asset_type','REGLA','task_mode',upper(p_task_mode),'execution_mode','EXPLORATION','governance_status',v_status,'revision',v_revision,'target_code',v_rec.target_code,'source_pantalla_id',v_rec.source_pantalla_id,'partial_payload',v_snapshot,'missing_fields',v_missing,'canonical_write_performed',false,'runtime_activation',false,'promotion',false);
end $$;
revoke all on function public.lf_input_exploration_capture_v1(text,text,text,jsonb,uuid,text,integer,jsonb,boolean) from public,anon,authenticated;
grant execute on function public.lf_input_exploration_capture_v1(text,text,text,jsonb,uuid,text,integer,jsonb,boolean) to service_role;

create view public.v_lf_input_exploration_pending with (security_invoker=true) as
select r.exploration_id,r.asset_type,r.task_mode,r.execution_mode,r.target_code,r.source_pantalla_id,r.source_context,r.partial_payload,r.missing_fields,r.governance_status,r.revision,r.created_by_execution_id,r.updated_by_execution_id,r.created_at,r.updated_at
from public.lf_input_exploration_records r where r.governance_status in ('OPEN','READY_FOR_INPUT_GOVERNANCE');
revoke all on public.v_lf_input_exploration_pending from public,anon,authenticated;
grant select on public.v_lf_input_exploration_pending to service_role;

do $patch$
declare v_def text; v_new text;
 p text := $p$v_expected:=case upper(p_action_code) when 'REGLA_CREATE' then 'CREACION_REGLA_LF' else 'ACTUALIZACION_REGLA_LF' end;
 select * into v_exec$p$;
 r text := $p$v_expected:=case upper(p_action_code) when 'REGLA_CREATE' then 'CREACION_REGLA_LF' else 'ACTUALIZACION_REGLA_LF' end;
 perform 1 from public.lf_operation_mode_bindings b where b.operation_code=v_expected and b.task_mode=case when upper(p_action_code)='REGLA_CREATE' then 'CREATE_NEW' else 'REMEDIATE_EXISTING' end and b.execution_mode='GOVERNED' and b.status='ACTIVE' and b.allowed and b.write_allowed and b.destination_kind='CANONICAL_CANDIDATE' and b.input_completeness='COMPLETE_REQUIRED';
 if not found then raise exception 'LF_REGLA_GOVERNED_MODE_BINDING_MISSING:%',v_expected; end if;
 select * into v_exec$p$;
begin
 select pg_get_functiondef('public.lf_regla_candidate_write_v1(text,text,text,text,text,text,text,jsonb,boolean,text)'::regprocedure) into v_def;
 if strpos(v_def,p)=0 then raise exception 'LF_REGLA_MODE_PATCH_SOURCE_DRIFT'; end if;
 v_new:=replace(v_def,p,r); execute v_new;
end $patch$;

do $post$
declare n int; r jsonb;
begin
 select count(*) into n from public.lf_task_mode_catalog where status='ACTIVE'; if n<>3 then raise exception 'LF_TASK_MODE_COUNT_FAIL:%',n; end if;
 select count(*) into n from public.lf_execution_mode_catalog where status='ACTIVE'; if n<>3 then raise exception 'LF_EXECUTION_MODE_COUNT_FAIL:%',n; end if;
 select count(*) into n from public.lf_operation_mode_bindings where status='ACTIVE'; if n<>5 then raise exception 'LF_OPERATION_MODE_BINDING_COUNT_FAIL:%',n; end if;
 select count(*) into n from pg_class c join pg_namespace ns on ns.oid=c.relnamespace where ns.nspname='public' and c.relname in ('lf_task_mode_catalog','lf_execution_mode_catalog','lf_operation_mode_bindings','lf_input_exploration_records','lf_input_exploration_events') and c.relrowsecurity; if n<>5 then raise exception 'LF_MODE_RLS_COUNT_FAIL:%',n; end if;
 if has_function_privilege('anon','public.lf_resolve_operation_mode_v1(text,text,text)','EXECUTE') or has_function_privilege('authenticated','public.lf_resolve_operation_mode_v1(text,text,text)','EXECUTE') then raise exception 'LF_MODE_RESOLVER_ACL_FAIL'; end if;
 if has_function_privilege('anon','public.lf_input_exploration_capture_v1(text,text,text,jsonb,uuid,text,integer,jsonb,boolean)','EXECUTE') or has_function_privilege('authenticated','public.lf_input_exploration_capture_v1(text,text,text,jsonb,uuid,text,integer,jsonb,boolean)','EXECUTE') then raise exception 'LF_EXPLORATION_CAPTURE_ACL_FAIL'; end if;
 r:=public.lf_resolve_operation_mode_v1('CREACION_REGLA_LF','CREATE_NEW','EXPLORATION'); if r->>'status'<>'READY' or r->>'destination_kind'<>'EXPLORATION_STORE' then raise exception 'LF_MODE_RESOLVE_POST_FAIL:%',r; end if;
 r:=public.lf_resolve_operation_mode_v1('ACTUALIZACION_REGLA_LF','EVALUATE_EXISTING','EXPLORATION'); if r->>'status'<>'READY' or (r->>'write_allowed')::boolean then raise exception 'LF_MODE_EVALUATE_POST_FAIL:%',r; end if;
 if position('LF_REGLA_GOVERNED_MODE_BINDING_MISSING' in pg_get_functiondef('public.lf_regla_candidate_write_v1(text,text,text,text,text,text,text,jsonb,boolean,text)'::regprocedure))=0 then raise exception 'LF_REGLA_GOVERNED_BINDING_PATCH_MISSING'; end if;
end $post$;
