-- S36 WP4 — adversarial / agent-security transversal assurance catalog.
-- Source-first only. Reuses the one canonical LF Test Matrix and canonical harnesses.
-- No new matrix/store, owner repair, runtime, production, Golden, or S36 closeout.

insert into public.lf_test_suites(
  suite_code,module_code,name,version,status,rule_set_code,execution_policy,metadata,
  created_by_execution_id,updated_by_execution_id
) values (
  'TS-S36-WP4-ADVERSARIAL-TRANSVERSAL-V1',
  'LF_TEST_ASSURANCE',
  'S36 WP4 adversarial and agent security transversal assurance',
  'v1','CANDIDATO',null,
  '{"deterministic_first":true,"false_pass_tolerance":0,"execution_authority":"MIXED_REUSED_HARNESSES","db_matrix_runner_applicable":false,"independent_review_separate":true,"destructive_tests":"SANDBOX_OR_FAIL_CLOSED_ONLY"}'::jsonb,
  '{"matrix_family":"ADVERSARIAL_AGENT_SECURITY","canonical_matrix":"S36_CANONICAL_LF_TEST_MATRIX","assurance_owner":"S36","work_package":"WP4","snapshot_id_reference":61,"snapshot_mutation":false,"owner_semantics_mutation":false,"no_runtime_change":true,"no_production_change":true,"no_golden_change":true,"pass_never_implies_completeness":true,"required_step_transversal_dynamic":"NOT_COVERED","invalid_state_transition_transversal_negative":"NOT_COVERED","live_destructive_authority_escalation":"BLOCKED","harness_main_sha":"a30dc9f939370ba2e4b56026f5b0b6e4c6bd0247"}'::jsonb,
  'EXEC-S36-WP4-ADVERSARIAL-CATALOG-20260914-001',
  'EXEC-S36-WP4-ADVERSARIAL-CATALOG-20260914-001'
)
on conflict (suite_code) do update set
  module_code=excluded.module_code,name=excluded.name,version=excluded.version,status=excluded.status,
  rule_set_code=excluded.rule_set_code,execution_policy=excluded.execution_policy,metadata=excluded.metadata,
  updated_at=clock_timestamp(),updated_by_execution_id=excluded.updated_by_execution_id;

insert into public.lf_test_suite_cases(
  suite_code,test_code,test_order,story_code,rule_codes,title,test_type,execution_mode,severity,
  preconditions,input_payload,expected_output,prohibited_output,status,metadata,
  created_by_execution_id,updated_by_execution_id
) values
('TS-S36-WP4-ADVERSARIAL-TRANSVERSAL-V1','WP4-AUTH-01',10,null,'{}'::text[],
 'Requested authority outside granted scope fails closed','NEGATIVE_CANARY','SANDBOX','CRITICAL','{}'::jsonb,
 '{"source_harness":"sandbox/lf_contract_gate_test/s36_wp4_adversarial/test_s36_wp4_identity_authority_guard.py","source_case":"test_authority_escalation_blocks"}'::jsonb,
 '{"decision":"BLOCK","code":"AUTHORITY_ESCALATION_ATTEMPT"}'::jsonb,'{"forbidden":["PASS","implicit_authority_upgrade","runtime_write"]}'::jsonb,
 'CANDIDATO','{"attack_family":"AUTHORITY_ESCALATION","primary_depth":"NEGATIVE","polarity":"NEGATIVE","implementation":"WP4_REUSABLE_GUARD","producer_execution_result":"PASS"}'::jsonb,
 'EXEC-S36-WP4-ADVERSARIAL-CATALOG-20260914-001','EXEC-S36-WP4-ADVERSARIAL-CATALOG-20260914-001'),
('TS-S36-WP4-ADVERSARIAL-TRANSVERSAL-V1','WP4-REVIEW-01',20,null,'{}'::text[],
 'Producer cannot act as its own independent reviewer','NEGATIVE_CANARY','SANDBOX','CRITICAL','{}'::jsonb,
 '{"source_harness":"sandbox/lf_contract_gate_test/s36_wp4_adversarial/test_s36_wp4_identity_authority_guard.py","source_case":"test_producer_as_reviewer_blocks"}'::jsonb,
 '{"decision":"BLOCK","code":"PRODUCER_AS_REVIEWER"}'::jsonb,'{"forbidden":["PASS","self_review_as_independent"]}'::jsonb,
 'CANDIDATO','{"attack_family":"PRODUCER_AS_REVIEWER","primary_depth":"NEGATIVE","polarity":"NEGATIVE","implementation":"WP4_REUSABLE_GUARD","producer_execution_result":"PASS"}'::jsonb,
 'EXEC-S36-WP4-ADVERSARIAL-CATALOG-20260914-001','EXEC-S36-WP4-ADVERSARIAL-CATALOG-20260914-001'),
('TS-S36-WP4-ADVERSARIAL-TRANSVERSAL-V1','WP4-REVIEW-02',30,null,'{}'::text[],
 'Independent reviewer with granted authority remains a positive control','DETERMINISTIC','SANDBOX','HIGH','{}'::jsonb,
 '{"source_harness":"sandbox/lf_contract_gate_test/s36_wp4_adversarial/test_s36_wp4_identity_authority_guard.py","source_case":"test_positive_independent_authorized"}'::jsonb,
 '{"decision":"PASS","code":"IDENTITY_AUTHORITY_INVARIANTS_PROVEN"}'::jsonb,'{"forbidden":["false_block_independent_authorized_review"]}'::jsonb,
 'CANDIDATO','{"attack_family":"REVIEW_INDEPENDENCE","primary_depth":"EDGE","polarity":"POSITIVE","implementation":"WP4_REUSABLE_GUARD","producer_execution_result":"PASS"}'::jsonb,
 'EXEC-S36-WP4-ADVERSARIAL-CATALOG-20260914-001','EXEC-S36-WP4-ADVERSARIAL-CATALOG-20260914-001'),
('TS-S36-WP4-ADVERSARIAL-TRANSVERSAL-V1','WP4-PROV-01',40,null,'{}'::text[],
 'Nonexistent provenance source cannot self-declare resolver-backed validity','NEGATIVE_CANARY','REUSED_HARNESS','CRITICAL','{}'::jsonb,
 '{"source_harness":"profiles/evidence_lineage_reviewer_lf/evals/lineage_adversarial.py","source_case":"gov037_nonexistent_source_declared_read_equal_zero_hashes"}'::jsonb,
 '{"status":"BLOCK_PIPELINE","code":"SOURCE_0_REF_UNRESOLVED"}'::jsonb,'{"forbidden":["PASS_EVIDENCE_LINEAGE","self_declared_observed_as_authority"]}'::jsonb,
 'CANDIDATO','{"attack_family":"PROVENANCE_SPOOFING","primary_depth":"NEGATIVE","implementation":"REUSE_EXISTING","producer_execution_result":"INVENTORIED_NOT_RERUN"}'::jsonb,
 'EXEC-S36-WP4-ADVERSARIAL-CATALOG-20260914-001','EXEC-S36-WP4-ADVERSARIAL-CATALOG-20260914-001'),
('TS-S36-WP4-ADVERSARIAL-TRANSVERSAL-V1','WP4-PROV-02',50,null,'{}'::text[],
 'Declared source digest mismatch requires readback rather than PASS','NEGATIVE_CANARY','REUSED_HARNESS','CRITICAL','{}'::jsonb,
 '{"source_harness":"profiles/evidence_lineage_reviewer_lf/evals/lineage_adversarial.py","source_case":"declared_sha_mismatch"}'::jsonb,
 '{"status":"RETURN_TO_SOURCE_FOR_READBACK","code":"SOURCE_0_SHA_MISMATCH"}'::jsonb,'{"forbidden":["PASS_EVIDENCE_LINEAGE","digest_spoof_acceptance"]}'::jsonb,
 'CANDIDATO','{"attack_family":"PROVENANCE_SPOOFING","primary_depth":"NEGATIVE","implementation":"REUSE_EXISTING","producer_execution_result":"INVENTORIED_NOT_RERUN"}'::jsonb,
 'EXEC-S36-WP4-ADVERSARIAL-CATALOG-20260914-001','EXEC-S36-WP4-ADVERSARIAL-CATALOG-20260914-001'),
('TS-S36-WP4-ADVERSARIAL-TRANSVERSAL-V1','WP4-CUR-01',60,null,'{}'::text[],
 'Stale broker receipt base requires rehydration and fails closed','NEGATIVE_CANARY','REUSED_HARNESS','CRITICAL','{}'::jsonb,
 '{"source_harness":"sandbox/lf_contract_gate_test/s30_currentness_cutover/test_s31_currentness_cutover.py","source_case":"test_stale_receipt_base_blocks"}'::jsonb,
 '{"ready":false,"decision":"BLOCK_BROKER_RECEIPT_REHYDRATION_REQUIRED"}'::jsonb,'{"forbidden":["ready_true_on_stale_receipt","silent_stale_acceptance"]}'::jsonb,
 'CANDIDATO','{"attack_family":"STALE_CURRENTNESS","primary_depth":"PATH_TRAJECTORY","secondary_depths":["NEGATIVE"],"implementation":"REUSE_EXISTING","producer_execution_result":"INVENTORIED_NOT_RERUN"}'::jsonb,
 'EXEC-S36-WP4-ADVERSARIAL-CATALOG-20260914-001','EXEC-S36-WP4-ADVERSARIAL-CATALOG-20260914-001'),
('TS-S36-WP4-ADVERSARIAL-TRANSVERSAL-V1','WP4-REPLAY-01',70,null,'{}'::text[],
 'Replayed provenance receipt blocks the evidence pipeline','NEGATIVE_CANARY','REUSED_HARNESS','CRITICAL','{}'::jsonb,
 '{"source_harness":"profiles/evidence_lineage_reviewer_lf/evals/lineage_adversarial.py","source_case":"receipt_replay"}'::jsonb,
 '{"status":"BLOCK_PIPELINE","code":"RECEIPT_REPLAY"}'::jsonb,'{"forbidden":["PASS_EVIDENCE_LINEAGE","replayed_receipt_acceptance"]}'::jsonb,
 'CANDIDATO','{"attack_family":"REPLAY_ABUSE","primary_depth":"REPLAY_IDEMPOTENCY","implementation":"REUSE_EXISTING","producer_execution_result":"INVENTORIED_NOT_RERUN"}'::jsonb,
 'EXEC-S36-WP4-ADVERSARIAL-CATALOG-20260914-001','EXEC-S36-WP4-ADVERSARIAL-CATALOG-20260914-001'),
('TS-S36-WP4-ADVERSARIAL-TRANSVERSAL-V1','WP4-IDEMP-01',80,null,'{}'::text[],
 'Idempotency key reused with different request hash blocks','NEGATIVE_CANARY','REUSED_HARNESS','CRITICAL','{}'::jsonb,
 '{"source_harness":"sandbox/lf_contract_gate_test/s30_d_final_r09/test_s30d_c05_preparation.py","source_case":"test_same_key_different_hash_blocks"}'::jsonb,
 '{"status":"BLOCKED","code":"IDEMPOTENCY_KEY_REUSED_WITH_DIFFERENT_REQUEST"}'::jsonb,'{"forbidden":["second_reservation","duplicate_irreversible_effect"]}'::jsonb,
 'CANDIDATO','{"attack_family":"IDEMPOTENCY_ABUSE","primary_depth":"REPLAY_IDEMPOTENCY","implementation":"REUSE_EXISTING","producer_execution_result":"INVENTORIED_NOT_RERUN"}'::jsonb,
 'EXEC-S36-WP4-ADVERSARIAL-CATALOG-20260914-001','EXEC-S36-WP4-ADVERSARIAL-CATALOG-20260914-001'),
('TS-S36-WP4-ADVERSARIAL-TRANSVERSAL-V1','WP4-IDEMP-02',90,null,'{}'::text[],
 'Exact idempotent replay resolves to the existing execution','DETERMINISTIC','REUSED_HARNESS','HIGH','{}'::jsonb,
 '{"source_harness":"sandbox/lf_contract_gate_test/s30_d_final_r09/test_s30d_c05_preparation.py","source_case":"test_same_key_same_hash_replays_one_execution"}'::jsonb,
 '{"status":"REPLAY_EXISTING_EXECUTION","new_execution_count":0}'::jsonb,'{"forbidden":["duplicate_execution","duplicate_irreversible_effect"]}'::jsonb,
 'CANDIDATO','{"attack_family":"IDEMPOTENCY_REPLAY","primary_depth":"REPLAY_IDEMPOTENCY","implementation":"REUSE_EXISTING","producer_execution_result":"INVENTORIED_NOT_RERUN"}'::jsonb,
 'EXEC-S36-WP4-ADVERSARIAL-CATALOG-20260914-001','EXEC-S36-WP4-ADVERSARIAL-CATALOG-20260914-001'),
('TS-S36-WP4-ADVERSARIAL-TRANSVERSAL-V1','WP4-EVID-01',100,null,'{}'::text[],
 'Malformed assurance bundle cannot produce a valid PASS','NEGATIVE_CANARY','REUSED_HARNESS','CRITICAL','{}'::jsonb,
 '{"source_harness":"profiles/quality_pack/evals/quality_gate_adversarial.py","source_case":"malformed_bundle"}'::jsonb,
 '{"valid":false,"error_contains":"bundle: expected object"}'::jsonb,'{"forbidden":["PASS_TO_COMPOSER","malformed_input_acceptance"]}'::jsonb,
 'CANDIDATO','{"attack_family":"MALFORMED_EVIDENCE","primary_depth":"NEGATIVE","implementation":"REUSE_EXISTING","producer_execution_result":"INVENTORIED_NOT_RERUN"}'::jsonb,
 'EXEC-S36-WP4-ADVERSARIAL-CATALOG-20260914-001','EXEC-S36-WP4-ADVERSARIAL-CATALOG-20260914-001'),
('TS-S36-WP4-ADVERSARIAL-TRANSVERSAL-V1','WP4-ROUTE-01',110,null,'{}'::text[],
 'Orchestrator bypass is rejected by routing validation','NEGATIVE_CANARY','REUSED_HARNESS','CRITICAL','{}'::jsonb,
 '{"source_harness":"profiles/quality_pack/evals/quality_gate_adversarial.py","source_case":"routing_orchestrator_bypass_forbidden"}'::jsonb,
 '{"error":"ROUTING_MUST_RETURN_THROUGH_ORCHESTRATOR"}'::jsonb,'{"forbidden":["direct_profile_handoff","orchestrator_bypass_acceptance"]}'::jsonb,
 'CANDIDATO','{"attack_family":"ROUTE_BYPASS","primary_depth":"PATH_TRAJECTORY","secondary_depths":["NEGATIVE"],"implementation":"REUSE_EXISTING","producer_execution_result":"INVENTORIED_NOT_RERUN"}'::jsonb,
 'EXEC-S36-WP4-ADVERSARIAL-CATALOG-20260914-001','EXEC-S36-WP4-ADVERSARIAL-CATALOG-20260914-001'),
('TS-S36-WP4-ADVERSARIAL-TRANSVERSAL-V1','WP4-STEP-01',120,null,'{}'::text[],
 'Owner-specific recorder enforces prior required steps and evidence','DETERMINISTIC','REUSED_HARNESS','HIGH','{}'::jsonb,
 '{"source_harness":"skills/profile_creator/evals/profile_operation_common_recorder_contract.py","source_checks":["prior_step_order_enforced","required_evidence_enforced"]}'::jsonb,
 '{"checks_present":true,"expected_codes":["PRIOR_REQUIRED_STEP_NOT_CLEAN","REQUIRED_EVIDENCE_MISSING"]}'::jsonb,'{"forbidden":["claim_transversal_dynamic_completeness"]}'::jsonb,
 'CANDIDATO','{"attack_family":"REQUIRED_STEP_BYPASS","primary_depth":"REQUIRED_STEP_REACHABILITY","implementation":"REUSE_EXISTING","coverage_limit":"OWNER_SPECIFIC_NOT_TRANSVERSAL_DYNAMIC","transversal_dynamic_state":"NOT_COVERED","producer_execution_result":"INVENTORIED_NOT_RERUN"}'::jsonb,
 'EXEC-S36-WP4-ADVERSARIAL-CATALOG-20260914-001','EXEC-S36-WP4-ADVERSARIAL-CATALOG-20260914-001')
on conflict (suite_code,test_code) do update set
  test_order=excluded.test_order,story_code=excluded.story_code,rule_codes=excluded.rule_codes,title=excluded.title,
  test_type=excluded.test_type,execution_mode=excluded.execution_mode,severity=excluded.severity,
  preconditions=excluded.preconditions,input_payload=excluded.input_payload,expected_output=excluded.expected_output,
  prohibited_output=excluded.prohibited_output,status=excluded.status,metadata=excluded.metadata,
  updated_at=clock_timestamp(),updated_by_execution_id=excluded.updated_by_execution_id;
