-- LF_CARD_CONTENT_SUPABASE_NATIVE_V1
-- Supabase is the sole Card content and operational authority.
-- Removes Google Drive/Docs from the live Card binding. Historical operation evidence remains immutable elsewhere.

create table if not exists public.lf_card_content_versions (
  id bigint generated by default as identity primary key,
  card_code text not null references public.lf_activos(codigo_activo) on update cascade on delete restrict,
  content_version text not null,
  content_text text not null,
  content_sha256 text not null,
  content_chars integer not null,
  content_format text not null default 'LF_CARD_CANONICAL_TEXT_V1',
  status text not null default 'CURRENT',
  supersedes_id bigint null references public.lf_card_content_versions(id) on delete restrict,
  created_at timestamptz not null default now(),
  retired_at timestamptz null,
  created_by_execution_id text not null,
  retired_by_execution_id text null,
  metadata jsonb not null default '{}'::jsonb,
  constraint lf_card_content_versions_status_chk check (status in ('CURRENT','RETIRED')),
  constraint lf_card_content_versions_sha_chk check (content_sha256 ~ '^[0-9a-f]{64}$'),
  constraint lf_card_content_versions_chars_chk check (content_chars >= 0),
  constraint lf_card_content_versions_content_integrity_chk check (
    content_chars = length(content_text)
    and content_sha256 = encode(extensions.digest(content_text,'sha256'),'hex')
  ),
  constraint lf_card_content_versions_retired_consistency_chk check (
    (status='CURRENT' and retired_at is null and retired_by_execution_id is null)
    or
    (status='RETIRED' and retired_at is not null and retired_by_execution_id is not null)
  )
);

create unique index if not exists lf_card_content_versions_card_version_uq
  on public.lf_card_content_versions(card_code,content_version);
create unique index if not exists lf_card_content_versions_one_current_uq
  on public.lf_card_content_versions(card_code) where status='CURRENT';
create index if not exists lf_card_content_versions_card_created_idx
  on public.lf_card_content_versions(card_code,created_at desc);

alter table public.lf_card_content_versions enable row level security;
revoke all on table public.lf_card_content_versions from public,anon,authenticated;
grant select,insert,update on table public.lf_card_content_versions to service_role;
grant usage,select on sequence public.lf_card_content_versions_id_seq to service_role;

insert into public.lf_card_content_versions(
  card_code,content_version,content_text,content_sha256,content_chars,status,created_by_execution_id,metadata
)
select
  'CARD-CAND-DASHBOARD-CLIENTE-LECTOR-LF-001',
  'v0.1-supabase-native.1',
  E'CARD_CANDIDATA_DASHBOARD_CLIENTE_LECTOR_LF_001\nTipo: Card candidata de aprendizaje / criterio reutilizable UI-dashboard\nProblema detectado: Un dashboard puede verse ordenado o visualmente atractivo, pero no necesariamente ayudar al cliente a decidir.\nRegla candidata: Todo dashboard ejecutivo LF debe diseñarse desde la mente del cliente lector antes que desde la estructura interna del sistema.\nCriterios mínimos: qué está pasando; qué significa para el cliente; qué se recomienda; cómo hacerlo; qué beneficio se espera; qué meta o rango aplica; qué decisión debe tomar; qué checkpoint cierra el ciclo.\nVeredicto de prueba origen: VISUAL_EVIDENCE_READY_CLIENT_READER_PASS\nRestricción: Este bloque no oficializa producción, no habilita runtime, no habilita impacto automático y no declara APROBADO / IMPACTADO / VERIFICADO / CERRADO.',
  '0401cea0e645f7910676839855e336ecdc1248bfc8cf388e7abe157992e19dab',
  833,
  'CURRENT',
  'EXEC-CARD-UPDATE-I7-REMEDIATION-20260913-001',
  jsonb_build_object(
    'migration_reason','REMOVE_EXTERNAL_CARD_CARRIER_DEPENDENCY',
    'canonical_source','SUPABASE',
    'legacy_content_integrity_verified',true,
    'legacy_content_sha256','0401cea0e645f7910676839855e336ecdc1248bfc8cf388e7abe157992e19dab',
    'legacy_content_chars',833
  )
where not exists (
  select 1 from public.lf_card_content_versions
  where card_code='CARD-CAND-DASHBOARD-CLIENTE-LECTOR-LF-001' and status='CURRENT'
);

do $migrate$
declare
  v_content public.lf_card_content_versions%rowtype;
  v_rows integer;
begin
  select * into strict v_content
  from public.lf_card_content_versions
  where card_code='CARD-CAND-DASHBOARD-CLIENTE-LECTOR-LF-001' and status='CURRENT';

  if v_content.content_sha256 is distinct from '0401cea0e645f7910676839855e336ecdc1248bfc8cf388e7abe157992e19dab'
     or v_content.content_chars is distinct from 833 then
    raise exception 'CARD_SUPABASE_NATIVE_CONTENT_INTEGRITY_MISMATCH';
  end if;

  update public.lf_activos
  set formato_nativo='SUPABASE_CARD_CONTENT_V1',
      ruta_esperada='supabase://public/lf_card_content_versions/CARD-CAND-DASHBOARD-CLIENTE-LECTOR-LF-001/CURRENT',
      ultima_revision=v_content.content_version,
      metadata=(metadata - 'storage_refs' - 'carrier_binding_v1')
        || jsonb_build_object(
          'source_governance',
            coalesce(metadata->'source_governance','{}'::jsonb)
            - 'drive_role' - 'external_storage_is_authority' - 'carrier_integrity_currentness_reads_allowed'
            || jsonb_build_object(
              'operational_authority','SUPABASE',
              'operational_source_ref','supabase://public/lf_activos/CARD-CAND-DASHBOARD-CLIENTE-LECTOR-LF-001',
              'content_authority','SUPABASE',
              'content_source_ref','supabase://public/lf_card_content_versions/CARD-CAND-DASHBOARD-CLIENTE-LECTOR-LF-001/CURRENT',
              'external_card_carriers_allowed',false
            ),
          'carrier_binding_v1',jsonb_build_object(
            'binding_schema','LF_CARRIER_BINDING_V1',
            'binding_status','CURRENT',
            'carrier_type','SUPABASE_NATIVE_CARD_CONTENT',
            'carrier_role','CANONICAL_CONTENT_AUTHORITY',
            'carrier_authority',true,
            'carrier_write_allowed',false,
            'carrier_ref','supabase://public/lf_card_content_versions/'||v_content.id,
            'content_row_id',v_content.id,
            'content_version',v_content.content_version,
            'content_sha256',v_content.content_sha256,
            'content_chars',v_content.content_chars,
            'content_format',v_content.content_format,
            'operational_authority_ref','supabase://public/lf_activos/CARD-CAND-DASHBOARD-CLIENTE-LECTOR-LF-001',
            'source_policy_code','POL-LF-SOURCE-RESOLUTION',
            'source_policy_version','v1.4-transversal-supabase-authority-visual-support',
            'source_policy_sha','5fab0c7fec2d7cc88fa13a54db8dfd15c8b7e008b381364f69c707a3675aae46',
            'binding_execution_id','EXEC-CARD-UPDATE-I7-REMEDIATION-20260913-001',
            'observed_at',now()
          )
        ),
      updated_by_execution_id='EXEC-CARD-UPDATE-I7-REMEDIATION-20260913-001'
  where codigo_activo='CARD-CAND-DASHBOARD-CLIENTE-LECTOR-LF-001'
    and tipo_activo='CARD'
    and archived_at is null;
  get diagnostics v_rows=row_count;
  if v_rows<>1 then raise exception 'CARD_SUPABASE_NATIVE_ASSET_UPDATE_NOT_EXACT rows=%',v_rows; end if;
end;
$migrate$;
