-- PROFILE_OPERATION_COMMON_RECORDER_V1
-- MIGRATION DESIGN MARKER / INTENTIONALLY NON-EXECUTABLE / NOT APPLIED
-- Canonical executable source remains:
-- skills/profile_creator/contracts/profile_operation_common_recorder_v1.sql
--
-- Q3 design: durable BLOCKED evidence after truthful execution+step+binding identity resolution.
-- Missing required evidence is represented with explicit null placeholders in BLOCKED snapshots only;
-- evidence audits MUST require non-null values and MUST NOT use key-presence alone as proof.
--
-- This marker intentionally contains NO DDL and NO psql include directive.
-- Before any live materialization, the canonical function body must be copied inline into a separately
-- reviewed migration, exact-head CI must be green, rollback tests must pass, and live deployment must
-- receive explicit authorization. Keeping this file inert prevents accidental partial deployment.
