DO $pre$ DECLARE v text; BEGIN SELECT max(version) INTO v FROM supabase_migrations.schema_migrations; IF v IS DISTINCT FROM '20260914063835' THEN RAISE EXCEPTION 'S30_MATRIX_LEDGER_DRIFT:%',v; END IF; END $pre$;

INSERT INTO public.lf_test_suites(suite_code,module_code,name,version,status,execution_policy,metadata,created_by_execution_id)
VALUES
 ('TS-STRATEGY-OP-CREATE-V1','STRATEGY_GOVERNANCE','Strategy Creation Operation Qualification Matrix','v1','CANDIDATO','{"deterministic_first":true,"false_pass_tolerance":0,"exact_revision":true}'::jsonb,'{"matrix_family":"OPERATION_QUALIFICATION","operation_code":"CREACION_ESTRATEGIA_LF"}'::jsonb,'EXEC-S30-STRATEGY-QUALIFICATION-FRAMEWORK-20260914-001'),
 ('TS-STRATEGY-OP-UPDATE-V1','STRATEGY_GOVERNANCE','Strategy Update Operation Qualification Matrix','v1','CANDIDATO','{"deterministic_first":true,"false_pass_tolerance":0,"exact_revision":true}'::jsonb,'{"matrix_family":"OPERATION_QUALIFICATION","operation_code":"ACTUALIZACION_ESTRATEGIA_LF"}'::jsonb,'EXEC-S30-STRATEGY-QUALIFICATION-FRAMEWORK-20260914-001'),
 ('TS-STRATEGY-OP-EXECUTE-V1','STRATEGY_GOVERNANCE','Strategy Execution Operation Qualification Matrix','v1','CANDIDATO','{"deterministic_first":true,"false_pass_tolerance":0,"exact_revision":true}'::jsonb,'{"matrix_family":"OPERATION_QUALIFICATION","operation_code":"EJECUCION_ESTRATEGIA_LF"}'::jsonb,'EXEC-S30-STRATEGY-QUALIFICATION-FRAMEWORK-20260914-001'),
 ('TS-STRATEGY-OP-CLOSE-V1','STRATEGY_GOVERNANCE','Strategy Close Operation Qualification Matrix','v1','CANDIDATO','{"deterministic_first":true,"false_pass_tolerance":0,"exact_revision":true}'::jsonb,'{"matrix_family":"OPERATION_QUALIFICATION","operation_code":"CIERRE_ESTRATEGIA_LF"}'::jsonb,'EXEC-S30-STRATEGY-QUALIFICATION-FRAMEWORK-20260914-001'),
 ('TS-STRATEGY-BASE-V1','STRATEGY_GOVERNANCE','Strategy Revision Base Qualification Matrix','v1','CANDIDATO','{"deterministic_first":true,"false_pass_tolerance":0,"exact_revision":true,"base_required":true}'::jsonb,'{"matrix_family":"STRATEGY_REVISION_QUALIFICATION"}'::jsonb,'EXEC-S30-STRATEGY-QUALIFICATION-FRAMEWORK-20260914-001'),
 ('TS-STRATEGY-WRITE-SAFETY-V1','STRATEGY_GOVERNANCE','Strategy Write Safety Conditional Pack','v1','CANDIDATO','{"conditional":true,"false_pass_tolerance":0}'::jsonb,'{"characteristic":"WRITES_DATA"}'::jsonb,'EXEC-S30-STRATEGY-QUALIFICATION-FRAMEWORK-20260914-001'),
 ('TS-STRATEGY-EFFECT-GUARD-V1','STRATEGY_GOVERNANCE','Strategy Business Effect Guard Conditional Pack','v1','CANDIDATO','{"conditional":true,"false_pass_tolerance":0}'::jsonb,'{"characteristic":"BUSINESS_EFFECTS"}'::jsonb,'EXEC-S30-STRATEGY-QUALIFICATION-FRAMEWORK-20260914-001'),
 ('TS-STRATEGY-INTEGRATION-V1','STRATEGY_GOVERNANCE','Strategy External Integration Conditional Pack','v1','CANDIDATO','{"conditional":true,"false_pass_tolerance":0}'::jsonb,'{"characteristic":"EXTERNAL_INTEGRATION"}'::jsonb,'EXEC-S30-STRATEGY-QUALIFICATION-FRAMEWORK-20260914-001'),
 ('TS-STRATEGY-SCHEDULER-V1','STRATEGY_GOVERNANCE','Strategy Scheduler Conditional Pack','v1','CANDIDATO','{"conditional":true,"false_pass_tolerance":0}'::jsonb,'{"characteristic":"SCHEDULER"}'::jsonb,'EXEC-S30-STRATEGY-QUALIFICATION-FRAMEWORK-20260914-001'),
 ('TS-STRATEGY-FINANCIAL-V1','STRATEGY_GOVERNANCE','Strategy Financial Decision Conditional Pack','v1','CANDIDATO','{"conditional":true,"false_pass_tolerance":0,"independent_review":true}'::jsonb,'{"characteristic":"FINANCIAL_DECISION"}'::jsonb,'EXEC-S30-STRATEGY-QUALIFICATION-FRAMEWORK-20260914-001'),
 ('TS-STRATEGY-MODEL-HOLDOUT-V1','STRATEGY_GOVERNANCE','Strategy Model Holdout Conditional Pack','v1','CANDIDATO','{"conditional":true,"false_pass_tolerance":0,"independent_review":true}'::jsonb,'{"characteristic":"USES_MODEL"}'::jsonb,'EXEC-S30-STRATEGY-QUALIFICATION-FRAMEWORK-20260914-001'),
 ('TS-STRATEGY-RUNTIME-V1','STRATEGY_GOVERNANCE','Strategy Runtime Change Conditional Pack','v1','CANDIDATO','{"conditional":true,"false_pass_tolerance":0}'::jsonb,'{"characteristic":"RUNTIME_CHANGE"}'::jsonb,'EXEC-S30-STRATEGY-QUALIFICATION-FRAMEWORK-20260914-001'),
 ('TS-STRATEGY-HIGH-RISK-V1','STRATEGY_GOVERNANCE','Strategy High Risk Independent Review Pack','v1','CANDIDATO','{"conditional":true,"false_pass_tolerance":0,"independent_review":true}'::jsonb,'{"characteristic":"HIGH_RISK"}'::jsonb,'EXEC-S30-STRATEGY-QUALIFICATION-FRAMEWORK-20260914-001');

INSERT INTO public.lf_test_suite_cases(suite_code,test_code,test_order,title,test_type,execution_mode,severity,input_payload,expected_output,status,created_by_execution_id)
VALUES
 ('TS-STRATEGY-OP-CREATE-V1','C01',10,'Operation state is catalog-bound','DETERMINISTIC','AUTOMATED','CRITICAL','{"probe_code":"OP_REGISTRY_STATE_VALID"}','{"passed":true}','CANDIDATO','EXEC-S30-STRATEGY-QUALIFICATION-FRAMEWORK-20260914-001'),
 ('TS-STRATEGY-OP-CREATE-V1','C02',20,'Router action is active','DETERMINISTIC','AUTOMATED','CRITICAL','{"probe_code":"ROUTER_ACTIVE"}','{"passed":true}','CANDIDATO','EXEC-S30-STRATEGY-QUALIFICATION-FRAMEWORK-20260914-001'),
 ('TS-STRATEGY-OP-CREATE-V1','C03',30,'Active contract exists','DETERMINISTIC','AUTOMATED','CRITICAL','{"probe_code":"ACTIVE_CONTRACT_PRESENT"}','{"passed":true}','CANDIDATO','EXEC-S30-STRATEGY-QUALIFICATION-FRAMEWORK-20260914-001'),
 ('TS-STRATEGY-OP-CREATE-V1','C04',40,'Active steps exist','DETERMINISTIC','AUTOMATED','CRITICAL','{"probe_code":"ACTIVE_STEPS_PRESENT"}','{"passed":true}','CANDIDATO','EXEC-S30-STRATEGY-QUALIFICATION-FRAMEWORK-20260914-001'),
 ('TS-STRATEGY-OP-CREATE-V1','C05',50,'All active steps have active judges','DETERMINISTIC','AUTOMATED','CRITICAL','{"probe_code":"ALL_ACTIVE_STEPS_JUDGED"}','{"passed":true}','CANDIDATO','EXEC-S30-STRATEGY-QUALIFICATION-FRAMEWORK-20260914-001'),
 ('TS-STRATEGY-OP-CREATE-V1','C06',60,'Creator includes strategy classification step','DETERMINISTIC','AUTOMATED','CRITICAL','{"probe_code":"STEP_PRESENT","step_id":"strategy_classification"}','{"passed":true}','CANDIDATO','EXEC-S30-STRATEGY-QUALIFICATION-FRAMEWORK-20260914-001'),
 ('TS-STRATEGY-OP-CREATE-V1','C07',70,'Strategy initial lifecycle is table-driven','DETERMINISTIC','AUTOMATED','CRITICAL','{"probe_code":"INITIAL_LIFECYCLE_TABLE_DRIVEN","entity_type":"STRATEGY_LIFECYCLE","table_name":"lf_strategy_snapshots"}','{"passed":true}','CANDIDATO','EXEC-S30-STRATEGY-QUALIFICATION-FRAMEWORK-20260914-001'),
 ('TS-STRATEGY-OP-CREATE-V1','C08',80,'Qualification binding is registered','DETERMINISTIC','AUTOMATED','CRITICAL','{"probe_code":"QUALIFICATION_BINDING_PRESENT"}','{"passed":true}','CANDIDATO','EXEC-S30-STRATEGY-QUALIFICATION-FRAMEWORK-20260914-001'),
 ('TS-STRATEGY-OP-CREATE-V1','C09',90,'Natural Router request resolves canonical create action','DETERMINISTIC','AUTOMATED','HIGH','{"probe_code":"ROUTER_NATURAL_ACTION","request":"crear estrategia","expected_action":"STRATEGY_CREATE"}','{"passed":true}','CANDIDATO','EXEC-S30-STRATEGY-QUALIFICATION-FRAMEWORK-20260914-001'),

 ('TS-STRATEGY-OP-UPDATE-V1','U01',10,'Operation state is catalog-bound','DETERMINISTIC','AUTOMATED','CRITICAL','{"probe_code":"OP_REGISTRY_STATE_VALID"}','{"passed":true}','CANDIDATO','EXEC-S30-STRATEGY-QUALIFICATION-FRAMEWORK-20260914-001'),
 ('TS-STRATEGY-OP-UPDATE-V1','U02',20,'Router action is active','DETERMINISTIC','AUTOMATED','CRITICAL','{"probe_code":"ROUTER_ACTIVE"}','{"passed":true}','CANDIDATO','EXEC-S30-STRATEGY-QUALIFICATION-FRAMEWORK-20260914-001'),
 ('TS-STRATEGY-OP-UPDATE-V1','U03',30,'Active contract exists','DETERMINISTIC','AUTOMATED','CRITICAL','{"probe_code":"ACTIVE_CONTRACT_PRESENT"}','{"passed":true}','CANDIDATO','EXEC-S30-STRATEGY-QUALIFICATION-FRAMEWORK-20260914-001'),
 ('TS-STRATEGY-OP-UPDATE-V1','U04',40,'Active steps exist','DETERMINISTIC','AUTOMATED','CRITICAL','{"probe_code":"ACTIVE_STEPS_PRESENT"}','{"passed":true}','CANDIDATO','EXEC-S30-STRATEGY-QUALIFICATION-FRAMEWORK-20260914-001'),
 ('TS-STRATEGY-OP-UPDATE-V1','U05',50,'All active steps have active judges','DETERMINISTIC','AUTOMATED','CRITICAL','{"probe_code":"ALL_ACTIVE_STEPS_JUDGED"}','{"passed":true}','CANDIDATO','EXEC-S30-STRATEGY-QUALIFICATION-FRAMEWORK-20260914-001'),
 ('TS-STRATEGY-OP-UPDATE-V1','U06',60,'Update writer resolves lifecycle through transition table','DETERMINISTIC','AUTOMATED','CRITICAL','{"probe_code":"FUNCTION_TABLE_DRIVEN","function_signature":"lf_strategy_update_write_v1(text,bigint,text,jsonb)"}','{"passed":true}','CANDIDATO','EXEC-S30-STRATEGY-QUALIFICATION-FRAMEWORK-20260914-001'),
 ('TS-STRATEGY-OP-UPDATE-V1','U07',70,'Material update invalidates qualification','DETERMINISTIC','AUTOMATED','CRITICAL','{"probe_code":"TRIGGER_PRESENT","trigger_name":"trg_lf_strategy_invalidate_qualification_v1","table_name":"lf_strategy_snapshots"}','{"passed":true}','CANDIDATO','EXEC-S30-STRATEGY-QUALIFICATION-FRAMEWORK-20260914-001'),
 ('TS-STRATEGY-OP-UPDATE-V1','U08',80,'Qualification binding is registered','DETERMINISTIC','AUTOMATED','CRITICAL','{"probe_code":"QUALIFICATION_BINDING_PRESENT"}','{"passed":true}','CANDIDATO','EXEC-S30-STRATEGY-QUALIFICATION-FRAMEWORK-20260914-001'),
 ('TS-STRATEGY-OP-UPDATE-V1','U09',90,'Natural Router request resolves canonical update action','DETERMINISTIC','AUTOMATED','HIGH','{"probe_code":"ROUTER_NATURAL_ACTION","request":"actualizar estrategia","expected_action":"STRATEGY_UPDATE"}','{"passed":true}','CANDIDATO','EXEC-S30-STRATEGY-QUALIFICATION-FRAMEWORK-20260914-001'),
 ('TS-STRATEGY-OP-UPDATE-V1','U10',100,'Legacy lifecycle fields are non-authoritative','DETERMINISTIC','AUTOMATED','HIGH','{"probe_code":"OP_CONTRACT_BOOL","key":"legacy_state_fields_authoritative","expected":false}','{"passed":true}','CANDIDATO','EXEC-S30-STRATEGY-QUALIFICATION-FRAMEWORK-20260914-001'),

 ('TS-STRATEGY-OP-EXECUTE-V1','E01',10,'Operation state is catalog-bound','DETERMINISTIC','AUTOMATED','CRITICAL','{"probe_code":"OP_REGISTRY_STATE_VALID"}','{"passed":true}','CANDIDATO','EXEC-S30-STRATEGY-QUALIFICATION-FRAMEWORK-20260914-001'),
 ('TS-STRATEGY-OP-EXECUTE-V1','E02',20,'Router action is active','DETERMINISTIC','AUTOMATED','CRITICAL','{"probe_code":"ROUTER_ACTIVE"}','{"passed":true}','CANDIDATO','EXEC-S30-STRATEGY-QUALIFICATION-FRAMEWORK-20260914-001'),
 ('TS-STRATEGY-OP-EXECUTE-V1','E03',30,'Active contract exists','DETERMINISTIC','AUTOMATED','CRITICAL','{"probe_code":"ACTIVE_CONTRACT_PRESENT"}','{"passed":true}','CANDIDATO','EXEC-S30-STRATEGY-QUALIFICATION-FRAMEWORK-20260914-001'),
 ('TS-STRATEGY-OP-EXECUTE-V1','E04',40,'Active steps exist','DETERMINISTIC','AUTOMATED','CRITICAL','{"probe_code":"ACTIVE_STEPS_PRESENT"}','{"passed":true}','CANDIDATO','EXEC-S30-STRATEGY-QUALIFICATION-FRAMEWORK-20260914-001'),
 ('TS-STRATEGY-OP-EXECUTE-V1','E05',50,'All active steps have active judges','DETERMINISTIC','AUTOMATED','CRITICAL','{"probe_code":"ALL_ACTIVE_STEPS_JUDGED"}','{"passed":true}','CANDIDATO','EXEC-S30-STRATEGY-QUALIFICATION-FRAMEWORK-20260914-001'),
 ('TS-STRATEGY-OP-EXECUTE-V1','E06',60,'Execution transition is table-driven','DETERMINISTIC','AUTOMATED','CRITICAL','{"probe_code":"FUNCTION_TABLE_DRIVEN","function_signature":"lf_strategy_lifecycle_from_execution_step_v1()"}','{"passed":true}','CANDIDATO','EXEC-S30-STRATEGY-QUALIFICATION-FRAMEWORK-20260914-001'),
 ('TS-STRATEGY-OP-EXECUTE-V1','E07',70,'Qualification binding is registered','DETERMINISTIC','AUTOMATED','CRITICAL','{"probe_code":"QUALIFICATION_BINDING_PRESENT"}','{"passed":true}','CANDIDATO','EXEC-S30-STRATEGY-QUALIFICATION-FRAMEWORK-20260914-001'),
 ('TS-STRATEGY-OP-EXECUTE-V1','E08',80,'Business effect dispatch is governed and allowed','DETERMINISTIC','AUTOMATED','CRITICAL','{"probe_code":"OP_CONTRACT_BOOL","key":"business_effect_dispatch_allowed","expected":true}','{"passed":true}','CANDIDATO','EXEC-S30-STRATEGY-QUALIFICATION-FRAMEWORK-20260914-001'),
 ('TS-STRATEGY-OP-EXECUTE-V1','E09',90,'Direct business write remains forbidden','DETERMINISTIC','AUTOMATED','CRITICAL','{"probe_code":"OP_CONTRACT_BOOL","key":"direct_business_write_allowed","expected":false}','{"passed":true}','CANDIDATO','EXEC-S30-STRATEGY-QUALIFICATION-FRAMEWORK-20260914-001'),
 ('TS-STRATEGY-OP-EXECUTE-V1','E10',100,'Scheduler remains disabled','DETERMINISTIC','AUTOMATED','HIGH','{"probe_code":"OP_CONTRACT_BOOL","key":"scheduler_activation","expected":false}','{"passed":true}','CANDIDATO','EXEC-S30-STRATEGY-QUALIFICATION-FRAMEWORK-20260914-001'),
 ('TS-STRATEGY-OP-EXECUTE-V1','E11',110,'Orchestrator remains disabled','DETERMINISTIC','AUTOMATED','HIGH','{"probe_code":"OP_CONTRACT_BOOL","key":"orchestrator_activation","expected":false}','{"passed":true}','CANDIDATO','EXEC-S30-STRATEGY-QUALIFICATION-FRAMEWORK-20260914-001'),

 ('TS-STRATEGY-OP-CLOSE-V1','L01',10,'Operation state is catalog-bound','DETERMINISTIC','AUTOMATED','CRITICAL','{"probe_code":"OP_REGISTRY_STATE_VALID"}','{"passed":true}','CANDIDATO','EXEC-S30-STRATEGY-QUALIFICATION-FRAMEWORK-20260914-001'),
 ('TS-STRATEGY-OP-CLOSE-V1','L02',20,'Router action is active','DETERMINISTIC','AUTOMATED','CRITICAL','{"probe_code":"ROUTER_ACTIVE"}','{"passed":true}','CANDIDATO','EXEC-S30-STRATEGY-QUALIFICATION-FRAMEWORK-20260914-001'),
 ('TS-STRATEGY-OP-CLOSE-V1','L03',30,'Active contract exists','DETERMINISTIC','AUTOMATED','CRITICAL','{"probe_code":"ACTIVE_CONTRACT_PRESENT"}','{"passed":true}','CANDIDATO','EXEC-S30-STRATEGY-QUALIFICATION-FRAMEWORK-20260914-001'),
 ('TS-STRATEGY-OP-CLOSE-V1','L04',40,'Active steps exist','DETERMINISTIC','AUTOMATED','CRITICAL','{"probe_code":"ACTIVE_STEPS_PRESENT"}','{"passed":true}','CANDIDATO','EXEC-S30-STRATEGY-QUALIFICATION-FRAMEWORK-20260914-001'),
 ('TS-STRATEGY-OP-CLOSE-V1','L05',50,'All active steps have active judges','DETERMINISTIC','AUTOMATED','CRITICAL','{"probe_code":"ALL_ACTIVE_STEPS_JUDGED"}','{"passed":true}','CANDIDATO','EXEC-S30-STRATEGY-QUALIFICATION-FRAMEWORK-20260914-001'),
 ('TS-STRATEGY-OP-CLOSE-V1','L06',60,'Close writer resolves target lifecycle through transition table','DETERMINISTIC','AUTOMATED','CRITICAL','{"probe_code":"FUNCTION_TABLE_DRIVEN","function_signature":"lf_strategy_close_write_v1(text,bigint,text,text,text,jsonb)"}','{"passed":true}','CANDIDATO','EXEC-S30-STRATEGY-QUALIFICATION-FRAMEWORK-20260914-001'),
 ('TS-STRATEGY-OP-CLOSE-V1','L07',70,'Terminal immutability uses catalog terminal flag','DETERMINISTIC','AUTOMATED','CRITICAL','{"probe_code":"FUNCTION_TERMINAL_HELPER","function_signature":"fn_lf_strategy_closed_immutable_v1()"}','{"passed":true}','CANDIDATO','EXEC-S30-STRATEGY-QUALIFICATION-FRAMEWORK-20260914-001'),
 ('TS-STRATEGY-OP-CLOSE-V1','L08',80,'Qualification binding is registered','DETERMINISTIC','AUTOMATED','CRITICAL','{"probe_code":"QUALIFICATION_BINDING_PRESENT"}','{"passed":true}','CANDIDATO','EXEC-S30-STRATEGY-QUALIFICATION-FRAMEWORK-20260914-001'),
 ('TS-STRATEGY-OP-CLOSE-V1','L09',90,'Natural Router request resolves canonical close action','DETERMINISTIC','AUTOMATED','HIGH','{"probe_code":"ROUTER_NATURAL_ACTION","request":"cerrar estrategia","expected_action":"STRATEGY_CLOSE"}','{"passed":true}','CANDIDATO','EXEC-S30-STRATEGY-QUALIFICATION-FRAMEWORK-20260914-001'),

 ('TS-STRATEGY-BASE-V1','S01',10,'Lifecycle state exists in canonical catalog','DETERMINISTIC','AUTOMATED','CRITICAL','{"probe_code":"STRATEGY_STATE_CATALOG_VALID"}','{"passed":true}','CANDIDATO','EXEC-S30-STRATEGY-QUALIFICATION-FRAMEWORK-20260914-001'),
 ('TS-STRATEGY-BASE-V1','S02',20,'Strategy is not terminal','DETERMINISTIC','AUTOMATED','CRITICAL','{"probe_code":"STRATEGY_NOT_TERMINAL"}','{"passed":true}','CANDIDATO','EXEC-S30-STRATEGY-QUALIFICATION-FRAMEWORK-20260914-001'),
 ('TS-STRATEGY-BASE-V1','S03',30,'Exact revision fingerprint matches','DETERMINISTIC','AUTOMATED','CRITICAL','{"probe_code":"STRATEGY_REVISION_MATCH"}','{"passed":true}','CANDIDATO','EXEC-S30-STRATEGY-QUALIFICATION-FRAMEWORK-20260914-001'),
 ('TS-STRATEGY-BASE-V1','S04',40,'All risk characteristics are explicitly classified','DETERMINISTIC','AUTOMATED','CRITICAL','{"probe_code":"STRATEGY_CHARACTERISTICS_COMPLETE"}','{"passed":true}','CANDIDATO','EXEC-S30-STRATEGY-QUALIFICATION-FRAMEWORK-20260914-001'),
 ('TS-STRATEGY-BASE-V1','S05',50,'Every enabled characteristic has a conditional test binding','DETERMINISTIC','AUTOMATED','CRITICAL','{"probe_code":"STRATEGY_CONDITIONAL_BINDINGS_RESOLVED"}','{"passed":true}','CANDIDATO','EXEC-S30-STRATEGY-QUALIFICATION-FRAMEWORK-20260914-001'),
 ('TS-STRATEGY-BASE-V1','S06',60,'Strategy executor is operational','DETERMINISTIC','AUTOMATED','CRITICAL','{"probe_code":"EXECUTOR_OPERATIONAL"}','{"passed":true}','CANDIDATO','EXEC-S30-STRATEGY-QUALIFICATION-FRAMEWORK-20260914-001'),
 ('TS-STRATEGY-BASE-V1','S07',70,'Current policy-set fingerprint is present','DETERMINISTIC','AUTOMATED','HIGH','{"probe_code":"STRATEGY_POLICY_FINGERPRINT_PRESENT"}','{"passed":true}','CANDIDATO','EXEC-S30-STRATEGY-QUALIFICATION-FRAMEWORK-20260914-001'),
 ('TS-STRATEGY-BASE-V1','S08',80,'Code and version are unique','DETERMINISTIC','AUTOMATED','CRITICAL','{"probe_code":"STRATEGY_UNIQUE_CODE_VERSION"}','{"passed":true}','CANDIDATO','EXEC-S30-STRATEGY-QUALIFICATION-FRAMEWORK-20260914-001'),
 ('TS-STRATEGY-BASE-V1','S09',90,'Current lifecycle admits governed execution action','DETERMINISTIC','AUTOMATED','CRITICAL','{"probe_code":"STRATEGY_START_TRANSITION_PRESENT"}','{"passed":true}','CANDIDATO','EXEC-S30-STRATEGY-QUALIFICATION-FRAMEWORK-20260914-001'),
 ('TS-STRATEGY-BASE-V1','S10',100,'Snapshot is current for its strategy code','DETERMINISTIC','AUTOMATED','CRITICAL','{"probe_code":"STRATEGY_CURRENT_VERSION"}','{"passed":true}','CANDIDATO','EXEC-S30-STRATEGY-QUALIFICATION-FRAMEWORK-20260914-001');

INSERT INTO public.lf_test_suite_cases(suite_code,test_code,test_order,title,test_type,execution_mode,severity,input_payload,expected_output,status,created_by_execution_id)
SELECT s.suite_code,'A01',10,'Characteristic assurance declaration is materialized','DETERMINISTIC','AUTOMATED','CRITICAL',jsonb_build_object('probe_code','STRATEGY_ASSURANCE_DECLARATION','assurance_key',s.assurance_key),'{"passed":true}'::jsonb,'CANDIDATO','EXEC-S30-STRATEGY-QUALIFICATION-FRAMEWORK-20260914-001'
FROM (VALUES
 ('TS-STRATEGY-WRITE-SAFETY-V1','writes_data'),('TS-STRATEGY-EFFECT-GUARD-V1','business_effects'),('TS-STRATEGY-INTEGRATION-V1','external_integration'),('TS-STRATEGY-SCHEDULER-V1','scheduler'),('TS-STRATEGY-FINANCIAL-V1','financial_decision'),('TS-STRATEGY-MODEL-HOLDOUT-V1','uses_model'),('TS-STRATEGY-RUNTIME-V1','runtime_change'),('TS-STRATEGY-HIGH-RISK-V1','high_risk')
) s(suite_code,assurance_key);
INSERT INTO public.lf_test_suite_cases(suite_code,test_code,test_order,title,test_type,execution_mode,severity,input_payload,expected_output,status,created_by_execution_id)
SELECT s.suite_code,'A02',20,'Characteristic assurance includes evidence receipts','DETERMINISTIC','AUTOMATED','CRITICAL',jsonb_build_object('probe_code','STRATEGY_ASSURANCE_EVIDENCE','assurance_key',s.assurance_key),'{"passed":true}'::jsonb,'CANDIDATO','EXEC-S30-STRATEGY-QUALIFICATION-FRAMEWORK-20260914-001'
FROM (VALUES
 ('TS-STRATEGY-WRITE-SAFETY-V1','writes_data'),('TS-STRATEGY-EFFECT-GUARD-V1','business_effects'),('TS-STRATEGY-INTEGRATION-V1','external_integration'),('TS-STRATEGY-SCHEDULER-V1','scheduler'),('TS-STRATEGY-FINANCIAL-V1','financial_decision'),('TS-STRATEGY-MODEL-HOLDOUT-V1','uses_model'),('TS-STRATEGY-RUNTIME-V1','runtime_change'),('TS-STRATEGY-HIGH-RISK-V1','high_risk')
) s(suite_code,assurance_key);
INSERT INTO public.lf_test_suite_cases(suite_code,test_code,test_order,title,test_type,execution_mode,severity,input_payload,expected_output,status,created_by_execution_id)
VALUES
 ('TS-STRATEGY-FINANCIAL-V1','A03',30,'Independent financial-risk review','SEMANTIC','INDEPENDENT_REVIEW','CRITICAL','{"probe_code":"INDEPENDENT_REVIEW"}','{"verdict":"PASS"}','CANDIDATO','EXEC-S30-STRATEGY-QUALIFICATION-FRAMEWORK-20260914-001'),
 ('TS-STRATEGY-MODEL-HOLDOUT-V1','A03',30,'Independent model holdout review','SEMANTIC','INDEPENDENT_REVIEW','CRITICAL','{"probe_code":"INDEPENDENT_REVIEW"}','{"verdict":"PASS"}','CANDIDATO','EXEC-S30-STRATEGY-QUALIFICATION-FRAMEWORK-20260914-001'),
 ('TS-STRATEGY-HIGH-RISK-V1','A03',30,'Independent high-risk review','SEMANTIC','INDEPENDENT_REVIEW','CRITICAL','{"probe_code":"INDEPENDENT_REVIEW"}','{"verdict":"PASS"}','CANDIDATO','EXEC-S30-STRATEGY-QUALIFICATION-FRAMEWORK-20260914-001');

INSERT INTO public.lf_test_requirement_bindings(binding_code,subject_type,subject_code,characteristic_code,suite_code,required,min_pass_rate,false_pass_tolerance,independent_review_required,rollback_required,currentness_mode,activation_condition,effective_from,status,created_by_execution_id)
VALUES
 ('BIND-OP-STRATEGY-CREATE-V1','OPERATION','CREACION_ESTRATEGIA_LF',NULL,'TS-STRATEGY-OP-CREATE-V1',true,1,0,false,true,'EXACT_REVISION','{"type":"ALWAYS"}'::jsonb,'9999-12-31'::timestamptz,'PENDING','EXEC-S30-STRATEGY-QUALIFICATION-FRAMEWORK-20260914-001'),
 ('BIND-OP-STRATEGY-UPDATE-V1','OPERATION','ACTUALIZACION_ESTRATEGIA_LF',NULL,'TS-STRATEGY-OP-UPDATE-V1',true,1,0,false,true,'EXACT_REVISION','{"type":"ALWAYS"}'::jsonb,'9999-12-31'::timestamptz,'PENDING','EXEC-S30-STRATEGY-QUALIFICATION-FRAMEWORK-20260914-001'),
 ('BIND-OP-STRATEGY-EXECUTE-V1','OPERATION','EJECUCION_ESTRATEGIA_LF',NULL,'TS-STRATEGY-OP-EXECUTE-V1',true,1,0,false,true,'EXACT_REVISION','{"type":"ALWAYS"}'::jsonb,'9999-12-31'::timestamptz,'PENDING','EXEC-S30-STRATEGY-QUALIFICATION-FRAMEWORK-20260914-001'),
 ('BIND-OP-STRATEGY-CLOSE-V1','OPERATION','CIERRE_ESTRATEGIA_LF',NULL,'TS-STRATEGY-OP-CLOSE-V1',true,1,0,false,true,'EXACT_REVISION','{"type":"ALWAYS"}'::jsonb,'9999-12-31'::timestamptz,'PENDING','EXEC-S30-STRATEGY-QUALIFICATION-FRAMEWORK-20260914-001'),
 ('BIND-STRATEGY-BASE-V1','STRATEGY','*',NULL,'TS-STRATEGY-BASE-V1',true,1,0,false,true,'EXACT_REVISION','{"type":"ALWAYS"}'::jsonb,'9999-12-31'::timestamptz,'PENDING','EXEC-S30-STRATEGY-QUALIFICATION-FRAMEWORK-20260914-001'),
 ('BIND-STRATEGY-WRITES-DATA-V1','STRATEGY','*','WRITES_DATA','TS-STRATEGY-WRITE-SAFETY-V1',true,1,0,false,true,'EXACT_REVISION','{"type":"CHARACTERISTIC_TRUE","characteristic_code":"WRITES_DATA"}'::jsonb,'9999-12-31'::timestamptz,'PENDING','EXEC-S30-STRATEGY-QUALIFICATION-FRAMEWORK-20260914-001'),
 ('BIND-STRATEGY-BUSINESS-EFFECTS-V1','STRATEGY','*','BUSINESS_EFFECTS','TS-STRATEGY-EFFECT-GUARD-V1',true,1,0,false,true,'EXACT_REVISION','{"type":"CHARACTERISTIC_TRUE","characteristic_code":"BUSINESS_EFFECTS"}'::jsonb,'9999-12-31'::timestamptz,'PENDING','EXEC-S30-STRATEGY-QUALIFICATION-FRAMEWORK-20260914-001'),
 ('BIND-STRATEGY-EXTERNAL-INTEGRATION-V1','STRATEGY','*','EXTERNAL_INTEGRATION','TS-STRATEGY-INTEGRATION-V1',true,1,0,false,true,'EXACT_REVISION','{"type":"CHARACTERISTIC_TRUE","characteristic_code":"EXTERNAL_INTEGRATION"}'::jsonb,'9999-12-31'::timestamptz,'PENDING','EXEC-S30-STRATEGY-QUALIFICATION-FRAMEWORK-20260914-001'),
 ('BIND-STRATEGY-SCHEDULER-V1','STRATEGY','*','SCHEDULER','TS-STRATEGY-SCHEDULER-V1',true,1,0,false,true,'EXACT_REVISION','{"type":"CHARACTERISTIC_TRUE","characteristic_code":"SCHEDULER"}'::jsonb,'9999-12-31'::timestamptz,'PENDING','EXEC-S30-STRATEGY-QUALIFICATION-FRAMEWORK-20260914-001'),
 ('BIND-STRATEGY-FINANCIAL-V1','STRATEGY','*','FINANCIAL_DECISION','TS-STRATEGY-FINANCIAL-V1',true,1,0,true,true,'EXACT_REVISION','{"type":"CHARACTERISTIC_TRUE","characteristic_code":"FINANCIAL_DECISION"}'::jsonb,'9999-12-31'::timestamptz,'PENDING','EXEC-S30-STRATEGY-QUALIFICATION-FRAMEWORK-20260914-001'),
 ('BIND-STRATEGY-MODEL-V1','STRATEGY','*','USES_MODEL','TS-STRATEGY-MODEL-HOLDOUT-V1',true,1,0,true,true,'EXACT_REVISION','{"type":"CHARACTERISTIC_TRUE","characteristic_code":"USES_MODEL"}'::jsonb,'9999-12-31'::timestamptz,'PENDING','EXEC-S30-STRATEGY-QUALIFICATION-FRAMEWORK-20260914-001'),
 ('BIND-STRATEGY-RUNTIME-V1','STRATEGY','*','RUNTIME_CHANGE','TS-STRATEGY-RUNTIME-V1',true,1,0,false,true,'EXACT_REVISION','{"type":"CHARACTERISTIC_TRUE","characteristic_code":"RUNTIME_CHANGE"}'::jsonb,'9999-12-31'::timestamptz,'PENDING','EXEC-S30-STRATEGY-QUALIFICATION-FRAMEWORK-20260914-001'),
 ('BIND-STRATEGY-HIGH-RISK-V1','STRATEGY','*','HIGH_RISK','TS-STRATEGY-HIGH-RISK-V1',true,1,0,true,true,'EXACT_REVISION','{"type":"CHARACTERISTIC_TRUE","characteristic_code":"HIGH_RISK"}'::jsonb,'9999-12-31'::timestamptz,'PENDING','EXEC-S30-STRATEGY-QUALIFICATION-FRAMEWORK-20260914-001');

CREATE OR REPLACE FUNCTION public.lf_eval_strategy_matrix_probe_v1(p_probe jsonb,p_subject_type text,p_subject_code text,p_revision_sha256 text)
RETURNS jsonb LANGUAGE plpgsql STABLE SET search_path TO 'pg_catalog','public' AS $fn$
DECLARE pc text:=p_probe->>'probe_code'; ok boolean:=false; actual jsonb:='{}'::jsonb; cnt int; sid bigint; def text; rp jsonb; expb boolean; actb boolean; st text;
BEGIN
 IF p_subject_type='STRATEGY' THEN SELECT id INTO sid FROM public.lf_strategy_snapshots WHERE snapshot_code=p_subject_code ORDER BY id DESC LIMIT 1; END IF;
 CASE pc
 WHEN 'OP_REGISTRY_STATE_VALID' THEN SELECT EXISTS(SELECT 1 FROM public.lf_operation_registry r JOIN lf_ops.estados_catalogo s ON s.state_code=r.lifecycle_state_code AND s.entity_type='OPERATION_LIFECYCLE' AND s.status='VIGENTE' WHERE r.operation_code=p_subject_code) INTO ok;
 WHEN 'ROUTER_ACTIVE' THEN SELECT EXISTS(SELECT 1 FROM public.lf_router_action_registry WHERE operation_code=p_subject_code AND status='ACTIVE') INTO ok;
 WHEN 'ACTIVE_CONTRACT_PRESENT' THEN SELECT EXISTS(SELECT 1 FROM public.lf_operation_contracts WHERE operation_code=p_subject_code AND status IN ('ACTIVE_ENFORCEMENT','ACTIVE','ACTIVO')) INTO ok;
 WHEN 'ACTIVE_STEPS_PRESENT' THEN SELECT EXISTS(SELECT 1 FROM public.lf_operation_step_contracts WHERE operation_code=p_subject_code AND status IN ('ACTIVE_ENFORCEMENT','ACTIVE','ACTIVO')) INTO ok;
 WHEN 'ALL_ACTIVE_STEPS_JUDGED' THEN SELECT NOT EXISTS(SELECT 1 FROM public.lf_operation_step_contracts s WHERE s.operation_code=p_subject_code AND s.status IN ('ACTIVE_ENFORCEMENT','ACTIVE','ACTIVO') AND (s.mini_judge_code IS NULL OR NOT EXISTS(SELECT 1 FROM public.lf_operation_judges j WHERE j.operation_code=p_subject_code AND j.judge_code=s.mini_judge_code AND j.status IN ('ACTIVE_ENFORCEMENT','ACTIVE','ACTIVO')))) INTO ok;
 WHEN 'STEP_PRESENT' THEN SELECT EXISTS(SELECT 1 FROM public.lf_operation_step_contracts WHERE operation_code=p_subject_code AND step_id=p_probe->>'step_id' AND status IN ('ACTIVE_ENFORCEMENT','ACTIVE','ACTIVO')) INTO ok;
 WHEN 'INITIAL_LIFECYCLE_TABLE_DRIVEN' THEN SELECT count(*) INTO cnt FROM information_schema.columns WHERE table_schema='public' AND table_name=p_probe->>'table_name' AND column_name='lifecycle_state_code' AND column_default IS NULL; ok:=(cnt=1 AND public.lf_lifecycle_initial_state_v1(p_probe->>'entity_type') IS NOT NULL AND EXISTS(SELECT 1 FROM pg_trigger t JOIN pg_class c ON c.oid=t.tgrelid JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='public' AND c.relname=p_probe->>'table_name' AND t.tgname LIKE '%initial_lifecycle%' AND NOT t.tgisinternal));
 WHEN 'QUALIFICATION_BINDING_PRESENT' THEN SELECT EXISTS(SELECT 1 FROM public.lf_test_requirement_bindings WHERE subject_type='OPERATION' AND subject_code=p_subject_code AND status IN ('PENDING','ACTIVE')) INTO ok;
 WHEN 'ROUTER_NATURAL_ACTION' THEN rp:=public.lf_router_resolve_v1(p_probe->>'request',NULL,NULL,'STRATEGY','ROUTER'); ok:=(rp->>'action_code'=p_probe->>'expected_action'); actual:=rp;
 WHEN 'FUNCTION_TABLE_DRIVEN' THEN SELECT pg_get_functiondef(to_regprocedure('public.'||(p_probe->>'function_signature'))) INTO def; ok:=(def IS NOT NULL AND strpos(def,'lf_lifecycle_resolve_transition_v1')>0 AND def NOT LIKE '%''STRATEGY_PLANNED''%' AND def NOT LIKE '%''STRATEGY_ACTIVE''%' AND def NOT LIKE '%''STRATEGY_CLOSED''%' AND def NOT LIKE '%''STRATEGY_SUPERSEDED''%');
 WHEN 'FUNCTION_TERMINAL_HELPER' THEN SELECT pg_get_functiondef(to_regprocedure('public.'||(p_probe->>'function_signature'))) INTO def; ok:=(def IS NOT NULL AND strpos(def,'lf_lifecycle_state_is_terminal_v1')>0);
 WHEN 'TRIGGER_PRESENT' THEN SELECT EXISTS(SELECT 1 FROM pg_trigger t JOIN pg_class c ON c.oid=t.tgrelid JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='public' AND c.relname=p_probe->>'table_name' AND t.tgname=p_probe->>'trigger_name' AND NOT t.tgisinternal) INTO ok;
 WHEN 'OP_CONTRACT_BOOL' THEN expb:=(p_probe->>'expected')::boolean; SELECT (c.allowed->>(p_probe->>'key'))::boolean INTO actb FROM public.lf_operation_contracts c WHERE c.operation_code=p_subject_code AND c.status='ACTIVE_ENFORCEMENT' ORDER BY c.updated_at DESC LIMIT 1; ok:=(actb IS NOT DISTINCT FROM expb); actual:=jsonb_build_object('actual',actb,'expected',expb);
 WHEN 'STRATEGY_STATE_CATALOG_VALID' THEN SELECT EXISTS(SELECT 1 FROM public.lf_strategy_snapshots s JOIN lf_ops.estados_catalogo e ON e.state_code=s.lifecycle_state_code AND e.entity_type='STRATEGY_LIFECYCLE' AND e.status='VIGENTE' WHERE s.id=sid) INTO ok;
 WHEN 'STRATEGY_NOT_TERMINAL' THEN SELECT NOT public.lf_lifecycle_state_is_terminal_v1('STRATEGY_LIFECYCLE',lifecycle_state_code) INTO ok FROM public.lf_strategy_snapshots WHERE id=sid;
 WHEN 'STRATEGY_REVISION_MATCH' THEN ok:=(public.lf_strategy_revision_sha256_v1(sid)=p_revision_sha256); actual:=jsonb_build_object('actual_revision',public.lf_strategy_revision_sha256_v1(sid),'expected_revision',p_revision_sha256);
 WHEN 'STRATEGY_CHARACTERISTICS_COMPLETE' THEN SELECT NOT EXISTS(SELECT 1 FROM public.lf_strategy_test_characteristic_catalog k WHERE k.status='ACTIVE' AND NOT EXISTS(SELECT 1 FROM public.lf_strategy_test_characteristics c WHERE c.snapshot_id=sid AND c.characteristic_code=k.characteristic_code AND c.enabled IS NOT NULL)) INTO ok;
 WHEN 'STRATEGY_CONDITIONAL_BINDINGS_RESOLVED' THEN SELECT NOT EXISTS(SELECT 1 FROM public.lf_strategy_test_characteristics c WHERE c.snapshot_id=sid AND c.enabled IS TRUE AND NOT EXISTS(SELECT 1 FROM public.lf_test_requirement_bindings b WHERE b.subject_type='STRATEGY' AND b.subject_code='*' AND b.characteristic_code=c.characteristic_code AND b.status IN ('PENDING','ACTIVE'))) INTO ok;
 WHEN 'EXECUTOR_OPERATIONAL' THEN SELECT lifecycle_state_code INTO st FROM public.lf_operation_registry WHERE operation_code='EJECUCION_ESTRATEGIA_LF'; ok:=(st=public.lf_lifecycle_action_target_state_v1('OPERATION_LIFECYCLE','PROMOTE_OPERATION'));
 WHEN 'STRATEGY_POLICY_FINGERPRINT_PRESENT' THEN SELECT coalesce(metadata->>'policy_set_fingerprint','')<>'' INTO ok FROM public.lf_strategy_snapshots WHERE id=sid;
 WHEN 'STRATEGY_UNIQUE_CODE_VERSION' THEN SELECT count(*)=1 INTO ok FROM public.lf_strategy_snapshots s JOIN public.lf_strategy_snapshots x ON x.snapshot_code=s.snapshot_code AND x.version=s.version WHERE s.id=sid;
 WHEN 'STRATEGY_START_TRANSITION_PRESENT' THEN BEGIN PERFORM public.lf_lifecycle_transition_spec_v1('STRATEGY_LIFECYCLE',(SELECT lifecycle_state_code FROM public.lf_strategy_snapshots WHERE id=sid),'START_EXECUTION'); ok:=true; EXCEPTION WHEN OTHERS THEN ok:=false; END;
 WHEN 'STRATEGY_CURRENT_VERSION' THEN SELECT id=(SELECT max(id) FROM public.lf_strategy_snapshots x WHERE x.snapshot_code=s.snapshot_code) INTO ok FROM public.lf_strategy_snapshots s WHERE s.id=sid;
 WHEN 'STRATEGY_ASSURANCE_DECLARATION' THEN SELECT jsonb_typeof(metadata->'test_assurance'->(p_probe->>'assurance_key'))='object' INTO ok FROM public.lf_strategy_snapshots WHERE id=sid;
 WHEN 'STRATEGY_ASSURANCE_EVIDENCE' THEN SELECT jsonb_typeof(metadata->'test_assurance'->(p_probe->>'assurance_key')->'evidence_refs')='array' AND jsonb_array_length(metadata->'test_assurance'->(p_probe->>'assurance_key')->'evidence_refs')>0 INTO ok FROM public.lf_strategy_snapshots WHERE id=sid;
 ELSE ok:=false; actual:=jsonb_build_object('error','UNKNOWN_PROBE_CODE','probe_code',pc);
 END CASE;
 RETURN jsonb_build_object('passed',coalesce(ok,false),'probe_code',pc,'actual',actual);
END $fn$;

CREATE OR REPLACE FUNCTION public.lf_run_strategy_matrix_suite_v1(p_suite_code text,p_subject_type text,p_subject_code text,p_revision_sha256 text,p_execution_id text)
RETURNS jsonb LANGUAGE plpgsql SET search_path TO 'pg_catalog','public' AS $fn$
DECLARE sr uuid; c public.lf_test_suite_cases%rowtype; ev jsonb; st text; passed int:=0; failed int:=0; reviews int:=0; total int:=0; startv timestamptz:=clock_timestamp();
BEGIN
 IF NOT EXISTS(SELECT 1 FROM public.lf_test_suites WHERE suite_code=p_suite_code) THEN RAISE EXCEPTION 'LF_MATRIX_SUITE_MISSING:%',p_suite_code; END IF;
 INSERT INTO public.lf_test_suite_runs(suite_code,execution_id,environment,application_version,rule_set_version,executor_type,executor_name,status,started_at,manifest,metadata,created_by_execution_id)
 VALUES(p_suite_code,p_execution_id,'SUPABASE_LIVE','S30_STRATEGY_QUALIFICATION_V1','S30-QM-v1','DETERMINISTIC_DB','lf_run_strategy_matrix_suite_v1','IN_PROGRESS',startv,jsonb_build_object('subject_type',p_subject_type,'subject_code',p_subject_code,'revision_sha256',p_revision_sha256),jsonb_build_object('subject_type',p_subject_type,'subject_code',p_subject_code,'revision_sha256',p_revision_sha256),p_execution_id) RETURNING suite_run_id INTO sr;
 FOR c IN SELECT * FROM public.lf_test_suite_cases WHERE suite_code=p_suite_code AND status='CANDIDATO' ORDER BY test_order LOOP
   total:=total+1;
   IF c.execution_mode='INDEPENDENT_REVIEW' THEN st:='REVIEW_REQUIRED'; reviews:=reviews+1; ev:=jsonb_build_object('passed',false,'review_required',true,'probe_code',c.input_payload->>'probe_code');
   ELSE ev:=public.lf_eval_strategy_matrix_probe_v1(c.input_payload,p_subject_type,p_subject_code,p_revision_sha256); IF coalesce((ev->>'passed')::boolean,false) THEN st:='PASS'; passed:=passed+1; ELSE st:='FAIL'; failed:=failed+1; END IF; END IF;
   INSERT INTO public.lf_test_runs(suite_run_id,suite_code,test_code,execution_id,operation_code,environment,application_version,rule_set_version,executor_type,executor_name,status,input_payload,expected_output,actual_output,severity,started_at,completed_at,duration_ms,evidence_payload,metadata,created_by_execution_id)
   VALUES(sr,p_suite_code,c.test_code,p_execution_id,CASE WHEN p_subject_type='OPERATION' THEN p_subject_code ELSE NULL END,'SUPABASE_LIVE','S30_STRATEGY_QUALIFICATION_V1','S30-QM-v1','DETERMINISTIC_DB','lf_run_strategy_matrix_suite_v1',st,c.input_payload,c.expected_output,ev,c.severity,clock_timestamp(),clock_timestamp(),0,ev,jsonb_build_object('subject_type',p_subject_type,'subject_code',p_subject_code,'revision_sha256',p_revision_sha256),p_execution_id);
 END LOOP;
 UPDATE public.lf_test_suite_runs SET status=CASE WHEN failed>0 THEN 'FAILED' WHEN reviews>0 THEN 'REVIEW_REQUIRED' ELSE 'PASSED' END,completed_at=clock_timestamp(),duration_ms=(extract(epoch from (clock_timestamp()-startv))*1000)::bigint,tests_total=total,tests_passed=passed,tests_failed=failed,tests_blocked=0,tests_review_required=reviews,updated_at=clock_timestamp(),updated_by_execution_id=p_execution_id WHERE suite_run_id=sr;
 RETURN jsonb_build_object('suite_run_id',sr,'suite_code',p_suite_code,'status',CASE WHEN failed>0 THEN 'FAILED' WHEN reviews>0 THEN 'REVIEW_REQUIRED' ELSE 'PASSED' END,'tests_total',total,'tests_passed',passed,'tests_failed',failed,'tests_review_required',reviews);
END $fn$;

CREATE OR REPLACE FUNCTION public.lf_run_operation_qualification_v1(p_operation_code text,p_execution_id text)
RETURNS jsonb LANGUAGE plpgsql SET search_path TO 'pg_catalog','public','extensions' AS $fn$
DECLARE rev text; qid uuid; qstate text; b public.lf_test_requirement_bindings%rowtype; rr jsonb; ids uuid[]:='{}'::uuid[]; any_fail boolean:=false; any_review boolean:=false; fp text;
BEGIN
 rev:=public.lf_operation_revision_sha256_v1(p_operation_code);
 SELECT encode(extensions.digest(convert_to(coalesce(string_agg(binding_code||':'||suite_code||':'||currentness_mode||':'||min_pass_rate::text||':'||false_pass_tolerance::text||':'||independent_review_required::text,'|' ORDER BY binding_code),''),'UTF8'),'sha256'),'hex') INTO fp FROM public.lf_test_requirement_bindings WHERE subject_type='OPERATION' AND subject_code=p_operation_code AND status IN ('PENDING','ACTIVE') AND required;
 INSERT INTO public.lf_qualification_receipts(subject_type,subject_code,subject_ref,revision_sha256,lifecycle_state_code,suite_set_fingerprint,created_by_execution_id) VALUES('OPERATION',p_operation_code,'supabase://public/lf_operation_registry/'||p_operation_code,rev,NULL,fp,p_execution_id) RETURNING qualification_id INTO qid;
 qstate:=public.lf_lifecycle_resolve_transition_v1('QUALIFICATION_LIFECYCLE',public.lf_lifecycle_initial_state_v1('QUALIFICATION_LIFECYCLE'),'START_QUALIFICATION'); UPDATE public.lf_qualification_receipts SET lifecycle_state_code=qstate,updated_by_execution_id=p_execution_id WHERE qualification_id=qid;
 FOR b IN SELECT * FROM public.lf_test_requirement_bindings WHERE subject_type='OPERATION' AND subject_code=p_operation_code AND status IN ('PENDING','ACTIVE') AND required ORDER BY binding_code LOOP rr:=public.lf_run_strategy_matrix_suite_v1(b.suite_code,'OPERATION',p_operation_code,rev,p_execution_id); ids:=array_append(ids,(rr->>'suite_run_id')::uuid); IF rr->>'status'='FAILED' THEN any_fail:=true; ELSIF rr->>'status'='REVIEW_REQUIRED' THEN any_review:=true; END IF; END LOOP;
 UPDATE public.lf_qualification_receipts SET suite_run_ids=ids,updated_at=clock_timestamp(),updated_by_execution_id=p_execution_id WHERE qualification_id=qid;
 IF any_fail THEN UPDATE public.lf_qualification_receipts SET lifecycle_state_code=public.lf_lifecycle_resolve_transition_v1('QUALIFICATION_LIFECYCLE',lifecycle_state_code,'FAIL_QUALIFICATION'),findings=findings||jsonb_build_array(jsonb_build_object('type','MATRIX_FAILED')),updated_at=clock_timestamp(),updated_by_execution_id=p_execution_id WHERE qualification_id=qid;
 ELSIF NOT any_review THEN UPDATE public.lf_qualification_receipts SET lifecycle_state_code=public.lf_lifecycle_resolve_transition_v1('QUALIFICATION_LIFECYCLE',lifecycle_state_code,'PASS_QUALIFICATION'),qualified_at=clock_timestamp(),updated_at=clock_timestamp(),updated_by_execution_id=p_execution_id WHERE qualification_id=qid; END IF;
 RETURN (SELECT jsonb_build_object('qualification_id',qualification_id,'subject_code',subject_code,'revision_sha256',revision_sha256,'lifecycle_state_code',lifecycle_state_code,'suite_run_ids',suite_run_ids,'suite_set_fingerprint',suite_set_fingerprint) FROM public.lf_qualification_receipts WHERE qualification_id=qid);
END $fn$;

CREATE OR REPLACE FUNCTION public.lf_run_strategy_qualification_v1(p_snapshot_id bigint,p_execution_id text)
RETURNS jsonb LANGUAGE plpgsql SET search_path TO 'pg_catalog','public','extensions' AS $fn$
DECLARE s public.lf_strategy_snapshots%rowtype; rev text; cf text; qid uuid; qstate text; b public.lf_test_requirement_bindings%rowtype; rr jsonb; ids uuid[]:='{}'::uuid[]; any_fail boolean:=false; any_review boolean:=false; fp text;
BEGIN
 SELECT * INTO s FROM public.lf_strategy_snapshots WHERE id=p_snapshot_id; IF NOT FOUND THEN RAISE EXCEPTION 'LF_STRATEGY_QUALIFICATION_TARGET_MISSING:%',p_snapshot_id; END IF;
 rev:=public.lf_strategy_revision_sha256_v1(p_snapshot_id); cf:=public.lf_strategy_classification_fingerprint_v1(p_snapshot_id);
 SELECT encode(extensions.digest(convert_to(coalesce(string_agg(b.binding_code||':'||b.suite_code||':'||b.currentness_mode||':'||b.min_pass_rate::text||':'||b.false_pass_tolerance::text||':'||b.independent_review_required::text,'|' ORDER BY b.binding_code),''),'UTF8'),'sha256'),'hex') INTO fp FROM public.lf_test_requirement_bindings b WHERE b.subject_type='STRATEGY' AND (b.subject_code='*' OR b.subject_code=s.snapshot_code) AND b.status IN ('PENDING','ACTIVE') AND b.required AND public.lf_test_requirement_applies_v1(b.binding_code,'STRATEGY',s.snapshot_code);
 INSERT INTO public.lf_qualification_receipts(subject_type,subject_code,subject_ref,revision_sha256,classification_fingerprint,lifecycle_state_code,suite_set_fingerprint,created_by_execution_id) VALUES('STRATEGY',s.snapshot_code,format('supabase://public/lf_strategy_snapshots/%s',s.id),rev,cf,NULL,fp,p_execution_id) RETURNING qualification_id INTO qid;
 qstate:=public.lf_lifecycle_resolve_transition_v1('QUALIFICATION_LIFECYCLE',public.lf_lifecycle_initial_state_v1('QUALIFICATION_LIFECYCLE'),'START_QUALIFICATION'); UPDATE public.lf_qualification_receipts SET lifecycle_state_code=qstate,updated_by_execution_id=p_execution_id WHERE qualification_id=qid;
 FOR b IN SELECT * FROM public.lf_test_requirement_bindings b WHERE b.subject_type='STRATEGY' AND (b.subject_code='*' OR b.subject_code=s.snapshot_code) AND b.status IN ('PENDING','ACTIVE') AND b.required AND public.lf_test_requirement_applies_v1(b.binding_code,'STRATEGY',s.snapshot_code) ORDER BY b.binding_code LOOP rr:=public.lf_run_strategy_matrix_suite_v1(b.suite_code,'STRATEGY',s.snapshot_code,rev,p_execution_id); ids:=array_append(ids,(rr->>'suite_run_id')::uuid); IF rr->>'status'='FAILED' THEN any_fail:=true; ELSIF rr->>'status'='REVIEW_REQUIRED' THEN any_review:=true; END IF; END LOOP;
 UPDATE public.lf_qualification_receipts SET suite_run_ids=ids,updated_at=clock_timestamp(),updated_by_execution_id=p_execution_id WHERE qualification_id=qid;
 IF any_fail THEN UPDATE public.lf_qualification_receipts SET lifecycle_state_code=public.lf_lifecycle_resolve_transition_v1('QUALIFICATION_LIFECYCLE',lifecycle_state_code,'FAIL_QUALIFICATION'),findings=findings||jsonb_build_array(jsonb_build_object('type','MATRIX_FAILED')),updated_at=clock_timestamp(),updated_by_execution_id=p_execution_id WHERE qualification_id=qid;
 ELSIF NOT any_review THEN UPDATE public.lf_qualification_receipts SET lifecycle_state_code=public.lf_lifecycle_resolve_transition_v1('QUALIFICATION_LIFECYCLE',lifecycle_state_code,'PASS_QUALIFICATION'),qualified_at=clock_timestamp(),updated_at=clock_timestamp(),updated_by_execution_id=p_execution_id WHERE qualification_id=qid; END IF;
 RETURN (SELECT jsonb_build_object('qualification_id',qualification_id,'subject_code',subject_code,'revision_sha256',revision_sha256,'classification_fingerprint',classification_fingerprint,'lifecycle_state_code',lifecycle_state_code,'suite_run_ids',suite_run_ids,'suite_set_fingerprint',suite_set_fingerprint) FROM public.lf_qualification_receipts WHERE qualification_id=qid);
END $fn$;

CREATE OR REPLACE FUNCTION public.lf_set_strategy_test_characteristic_v1(p_snapshot_id bigint,p_characteristic_code text,p_enabled boolean,p_evidence jsonb,p_execution_id text)
RETURNS jsonb LANGUAGE plpgsql SET search_path TO 'pg_catalog','public' AS $fn$
DECLARE x public.lf_operation_execution%rowtype; s public.lf_strategy_snapshots%rowtype;
BEGIN
 IF p_enabled IS NULL OR jsonb_typeof(coalesce(p_evidence,'{}'::jsonb))<>'object' THEN RAISE EXCEPTION 'LF_STRATEGY_CHARACTERISTIC_INPUT_INVALID'; END IF;
 SELECT * INTO x FROM public.lf_operation_execution WHERE execution_id=p_execution_id; IF NOT FOUND OR x.operation_code NOT IN ('CREACION_ESTRATEGIA_LF','ACTUALIZACION_ESTRATEGIA_LF','ACTUALIZACION_DB_LF') OR x.status<>'IN_PROGRESS' THEN RAISE EXCEPTION 'LF_STRATEGY_CHARACTERISTIC_EXECUTION_BINDING_INVALID'; END IF;
 SELECT * INTO s FROM public.lf_strategy_snapshots WHERE id=p_snapshot_id; IF NOT FOUND OR public.lf_lifecycle_state_is_terminal_v1('STRATEGY_LIFECYCLE',s.lifecycle_state_code) THEN RAISE EXCEPTION 'LF_STRATEGY_CHARACTERISTIC_TARGET_INVALID'; END IF;
 UPDATE public.lf_strategy_test_characteristics SET enabled=p_enabled,evidence_payload=p_evidence,classified_at=clock_timestamp(),updated_at=clock_timestamp(),updated_by_execution_id=p_execution_id WHERE snapshot_id=p_snapshot_id AND characteristic_code=p_characteristic_code;
 IF NOT FOUND THEN RAISE EXCEPTION 'LF_STRATEGY_CHARACTERISTIC_CODE_INVALID:%',p_characteristic_code; END IF;
 RETURN jsonb_build_object('snapshot_id',p_snapshot_id,'characteristic_code',p_characteristic_code,'enabled',p_enabled,'classification_fingerprint',public.lf_strategy_classification_fingerprint_v1(p_snapshot_id));
END $fn$;

DO $post$ DECLARE c int; BEGIN SELECT count(*) INTO c FROM public.lf_test_suites WHERE suite_code LIKE 'TS-STRATEGY-%-V1' OR suite_code='TS-STRATEGY-BASE-V1'; IF c<13 THEN RAISE EXCEPTION 'S30_MATRIX_SUITE_COUNT:%',c; END IF; SELECT count(*) INTO c FROM public.lf_test_requirement_bindings WHERE status='PENDING'; IF c<>13 THEN RAISE EXCEPTION 'S30_MATRIX_BINDING_COUNT:%',c; END IF; SELECT count(*) INTO c FROM public.lf_test_suite_cases WHERE suite_code IN ('TS-STRATEGY-OP-CREATE-V1','TS-STRATEGY-OP-UPDATE-V1','TS-STRATEGY-OP-EXECUTE-V1','TS-STRATEGY-OP-CLOSE-V1','TS-STRATEGY-BASE-V1'); IF c<>49 THEN RAISE EXCEPTION 'S30_MATRIX_CORE_CASE_COUNT:%',c; END IF; END $post$;