create table if not exists lf_ops.pantalla_elementos (
  element_id bigint generated by default as identity primary key,
  pantalla_id integer not null references lf_ops.pantallas(id) on delete restrict,
  element_code text not null,
  element_role text not null,
  context_key text,
  component_token_id bigint references lf_design.component_tokens(component_token_id) on delete restrict,
  semantic_binding_status text not null default 'MISSING' check (semantic_binding_status in ('RESOLVED_ID','PENDING_SEMANTIC_COMPONENT','MISSING','NOT_APPLICABLE')),
  required_for_implementation boolean not null default true,
  source_refs jsonb not null default '[]'::jsonb check (jsonb_typeof(source_refs)='array'),
  status text not null default 'CANDIDATO',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(pantalla_id,element_code),
  check (btrim(element_code)<>'' and btrim(element_role)<>'')
);

comment on table lf_ops.pantalla_elementos is 'Inventario explícito de elementos UI no-campo por pantalla. No duplica campos_pantallas; cubre CTA, links, títulos, mensajes, iconos, imágenes, decoración y otros elementos visuales con binding semántico a lf_design.';

create index if not exists idx_pantalla_elementos_pantalla on lf_ops.pantalla_elementos(pantalla_id);
create index if not exists idx_pantalla_elementos_component on lf_ops.pantalla_elementos(component_token_id) where component_token_id is not null;

create or replace function programacion.fn_input_design_binding_graph_v2(p_pantalla_id integer)
returns jsonb
language plpgsql
security definer
set search_path to 'pg_catalog','programacion','lf_ops','lf_design'
as $$
declare
  v_design_system_id bigint; v_design_rule_count integer; v_screen jsonb; v_fields jsonb; v_variants jsonb; v_elements jsonb;
  v_field_count integer; v_field_bound integer; v_field_semantic_pending integer; v_variant_count integer; v_variant_bound integer;
  v_element_count integer; v_element_required integer; v_element_bound integer; v_element_semantic_pending integer; v_integrity_failures integer;
begin
  select to_jsonb(p) into v_screen from lf_ops.pantallas p where p.id=p_pantalla_id;
  if v_screen is null then raise exception 'DESIGN_BINDING_SCREEN_NOT_FOUND:%',p_pantalla_id; end if;

  select count(distinct (r.valor_config->>'design_system_id')),max((r.valor_config->>'design_system_id')::bigint)
    into v_design_rule_count,v_design_system_id
  from lf_ops.reglas_pantallas rp join lf_ops.reglas r on r.id=rp.regla_id
  where rp.pantalla_id=p_pantalla_id and r.codigo='B2B-RULE-DESIGN-001' and coalesce(r.valor_config->>'design_system_id','')~'^[0-9]+$';
  if v_design_rule_count<>1 or v_design_system_id is null then raise exception 'DESIGN_SYSTEM_ID_UNRESOLVED_OR_CONFLICT:%',p_pantalla_id; end if;

  select count(*),count(*) filter(where cp.component_token_id is not null),count(*) filter(where coalesce(cp.nota,'')~*'PENDING_VISUAL_COMPONENT'),
         coalesce(jsonb_agg(jsonb_build_object(
           'screen_field_link_id',cp.id,'field_id',c.id,'field_code',c.codigo,'context_key',cp.context_key,
           'component_token_id',cp.component_token_id,'component_token_code',cp.component_token_code,'source_note',cp.nota,
           'semantic_binding_pending',coalesce(cp.nota,'')~*'PENDING_VISUAL_COMPONENT',
           'binding_status',case when cp.component_token_id is null then 'MISSING' when coalesce(cp.nota,'')~*'PENDING_VISUAL_COMPONENT' then 'PENDING_SEMANTIC_COMPONENT' else 'RESOLVED_ID' end,
           'component_receipt',case when cp.component_token_id is null then null else programacion.fn_input_component_binding_receipt(cp.component_token_id,v_design_system_id) end
         ) order by cp.orden_visual,cp.id),'[]'::jsonb)
    into v_field_count,v_field_bound,v_field_semantic_pending,v_fields
  from lf_ops.campos_pantallas cp join lf_ops.campos c on c.id=cp.campo_id where cp.pantalla_id=p_pantalla_id;

  select count(*),count(*) filter(where pv.layout_component_token_id is not null),
         coalesce(jsonb_agg(jsonb_build_object(
           'variant_id',pv.variant_id,'variant_code',pv.variant_code,'responsive_token_id',pv.responsive_token_id,'theme_binding_id',pv.theme_binding_id,
           'layout_component_token_id',pv.layout_component_token_id,'layout_component_token_code',pv.layout_component_token_code,'source_decision_id',pv.source_decision_id,
           'binding_status',case when pv.layout_component_token_id is null then 'MISSING' else 'RESOLVED_ID' end,
           'layout_component_receipt',case when pv.layout_component_token_id is null then null else programacion.fn_input_component_binding_receipt(pv.layout_component_token_id,v_design_system_id) end
         ) order by pv.variant_id),'[]'::jsonb)
    into v_variant_count,v_variant_bound,v_variants
  from lf_ops.pantalla_variantes pv where pv.pantalla_id=p_pantalla_id;

  select count(*),count(*) filter(where pe.required_for_implementation),count(*) filter(where pe.component_token_id is not null),
         count(*) filter(where pe.semantic_binding_status='PENDING_SEMANTIC_COMPONENT'),
         coalesce(jsonb_agg(jsonb_build_object(
           'element_id',pe.element_id,'element_code',pe.element_code,'element_role',pe.element_role,'context_key',pe.context_key,
           'required_for_implementation',pe.required_for_implementation,'semantic_binding_status',pe.semantic_binding_status,'component_token_id',pe.component_token_id,
           'status',pe.status,'source_refs',pe.source_refs,
           'component_receipt',case when pe.component_token_id is null then null else programacion.fn_input_component_binding_receipt(pe.component_token_id,v_design_system_id) end
         ) order by pe.element_id),'[]'::jsonb)
    into v_element_count,v_element_required,v_element_bound,v_element_semantic_pending,v_elements
  from lf_ops.pantalla_elementos pe where pe.pantalla_id=p_pantalla_id and pe.status<>'DEPRECATED';

  select coalesce(sum(x.failures),0)::integer into v_integrity_failures
  from (
    select case when cp.component_token_id is null then 0 else ((programacion.fn_input_component_binding_receipt(cp.component_token_id,v_design_system_id)->>'unresolved_expected_ref_count')::integer+(programacion.fn_input_component_binding_receipt(cp.component_token_id,v_design_system_id)->>'ambiguous_expected_ref_count')::integer) end failures
      from lf_ops.campos_pantallas cp where cp.pantalla_id=p_pantalla_id
    union all
    select case when pv.layout_component_token_id is null then 0 else ((programacion.fn_input_component_binding_receipt(pv.layout_component_token_id,v_design_system_id)->>'unresolved_expected_ref_count')::integer+(programacion.fn_input_component_binding_receipt(pv.layout_component_token_id,v_design_system_id)->>'ambiguous_expected_ref_count')::integer) end
      from lf_ops.pantalla_variantes pv where pv.pantalla_id=p_pantalla_id
    union all
    select case when pe.component_token_id is null then 0 else ((programacion.fn_input_component_binding_receipt(pe.component_token_id,v_design_system_id)->>'unresolved_expected_ref_count')::integer+(programacion.fn_input_component_binding_receipt(pe.component_token_id,v_design_system_id)->>'ambiguous_expected_ref_count')::integer) end
      from lf_ops.pantalla_elementos pe where pe.pantalla_id=p_pantalla_id and pe.status<>'DEPRECATED'
  ) x;

  return jsonb_build_object(
    'graph_contract','DESIGN_BINDING_GRAPH_V3','pantalla_id',p_pantalla_id,'screen_code',v_screen->>'codigo','design_system_id',v_design_system_id,
    'fields',v_fields,'variants',v_variants,'elements',v_elements,
    'summary',jsonb_build_object(
      'field_count',v_field_count,'field_component_binding_count',v_field_bound,'field_component_missing_count',v_field_count-v_field_bound,'field_semantic_component_pending_count',v_field_semantic_pending,
      'variant_count',v_variant_count,'variant_layout_binding_count',v_variant_bound,'variant_layout_missing_count',v_variant_count-v_variant_bound,
      'element_inventory_count',v_element_count,'element_required_count',v_element_required,'element_component_binding_count',v_element_bound,
      'element_required_missing_component_count',(select count(*) from lf_ops.pantalla_elementos pe where pe.pantalla_id=p_pantalla_id and pe.status<>'DEPRECATED' and pe.required_for_implementation and (pe.component_token_id is null or pe.semantic_binding_status<>'RESOLVED_ID')),
      'element_semantic_component_pending_count',v_element_semantic_pending,'referential_integrity_failure_count',v_integrity_failures
    )
  );
end;
$$;

create or replace function programacion.fn_input_design_readiness_v2(p_pantalla_id integer)
returns jsonb
language plpgsql
security definer
set search_path to 'pg_catalog','programacion','lf_ops','lf_design'
as $$
declare
  v_graph jsonb; v_summary jsonb; v_design_system_id bigint; v_design_status text;
  v_missing_fields integer; v_semantic_pending integer; v_missing_layouts integer; v_ref_failures integer; v_nonprod_components integer; v_missing_supabase_visual integer;
  v_element_count integer; v_element_missing integer; v_element_pending integer;
  v_coverage text:='COMPLETE'; v_well text:='COMPLETE'; v_story text:='READY'; v_impl text:='READY'; v_qa text:='READY'; v_prod text:='READY'; v_blockers jsonb:='[]'::jsonb;
begin
  begin v_graph:=programacion.fn_input_design_binding_graph_v2(p_pantalla_id);
  exception when others then return jsonb_build_object('coverage_status','MISSING','well_defined_status','BLOCKED','story_ready_status','BLOCKED','implementation_ready_status','BLOCKED','qa_ready_status','BLOCKED','production_ready_status','BLOCKED','blockers',jsonb_build_array(jsonb_build_object('code','DESIGN_AUTHORITY_UNRESOLVED','detail',sqlerrm)),'binding_graph',null); end;
  v_summary:=v_graph->'summary'; v_design_system_id:=(v_graph->>'design_system_id')::bigint;
  select status into v_design_status from lf_design.design_systems where design_system_id=v_design_system_id;
  if v_design_status is null then v_coverage:='MISSING';v_well:='BLOCKED';v_story:='BLOCKED';v_impl:='BLOCKED';v_qa:='BLOCKED';v_prod:='BLOCKED';v_blockers:=v_blockers||jsonb_build_array(jsonb_build_object('code','DESIGN_SYSTEM_NOT_FOUND','design_system_id',v_design_system_id)); end if;

  v_missing_fields:=coalesce((v_summary->>'field_component_missing_count')::integer,0); v_semantic_pending:=coalesce((v_summary->>'field_semantic_component_pending_count')::integer,0);
  v_missing_layouts:=coalesce((v_summary->>'variant_layout_missing_count')::integer,0); v_ref_failures:=coalesce((v_summary->>'referential_integrity_failure_count')::integer,0);
  v_element_count:=coalesce((v_summary->>'element_inventory_count')::integer,0); v_element_missing:=coalesce((v_summary->>'element_required_missing_component_count')::integer,0); v_element_pending:=coalesce((v_summary->>'element_semantic_component_pending_count')::integer,0);

  if v_missing_fields>0 then v_well:='PARTIAL';v_impl:='NOT_READY';v_qa:='BLOCKED';v_prod:='BLOCKED';v_blockers:=v_blockers||jsonb_build_array(jsonb_build_object('code','SCREEN_FIELD_COMPONENT_BINDING_MISSING','count',v_missing_fields)); end if;
  if v_semantic_pending>0 then v_well:='PARTIAL';v_impl:='NOT_READY';v_qa:='BLOCKED';v_prod:='BLOCKED';v_blockers:=v_blockers||jsonb_build_array(jsonb_build_object('code','SCREEN_FIELD_SEMANTIC_COMPONENT_PENDING','count',v_semantic_pending)); end if;
  if v_missing_layouts>0 then v_well:='PARTIAL';v_impl:='NOT_READY';v_qa:='BLOCKED';v_prod:='BLOCKED';v_blockers:=v_blockers||jsonb_build_array(jsonb_build_object('code','SCREEN_VARIANT_LAYOUT_BINDING_MISSING','count',v_missing_layouts)); end if;
  if v_element_count=0 then v_well:='PARTIAL';v_impl:='NOT_READY';v_qa:='BLOCKED';v_prod:='BLOCKED';v_blockers:=v_blockers||jsonb_build_array(jsonb_build_object('code','SCREEN_ELEMENT_INVENTORY_MISSING','count',0)); end if;
  if v_element_missing>0 then v_well:='PARTIAL';v_impl:='NOT_READY';v_qa:='BLOCKED';v_prod:='BLOCKED';v_blockers:=v_blockers||jsonb_build_array(jsonb_build_object('code','SCREEN_ELEMENT_COMPONENT_BINDING_MISSING','count',v_element_missing)); end if;
  if v_element_pending>0 then v_well:='PARTIAL';v_impl:='NOT_READY';v_qa:='BLOCKED';v_prod:='BLOCKED';v_blockers:=v_blockers||jsonb_build_array(jsonb_build_object('code','SCREEN_ELEMENT_SEMANTIC_COMPONENT_PENDING','count',v_element_pending)); end if;
  if v_ref_failures>0 then v_well:='BLOCKED';v_impl:='BLOCKED';v_qa:='BLOCKED';v_prod:='BLOCKED';v_blockers:=v_blockers||jsonb_build_array(jsonb_build_object('code','DESIGN_REFERENCE_INTEGRITY_FAILURE','count',v_ref_failures)); end if;

  select count(*) into v_nonprod_components from (
    select distinct (f#>>'{component_receipt,component,component_token_id}')::bigint component_token_id from jsonb_array_elements(v_graph->'fields') f where f#>>'{component_receipt,component,component_token_id}' is not null
    union select distinct (v#>>'{layout_component_receipt,component,component_token_id}')::bigint from jsonb_array_elements(v_graph->'variants') v where v#>>'{layout_component_receipt,component,component_token_id}' is not null
    union select distinct (e#>>'{component_receipt,component,component_token_id}')::bigint from jsonb_array_elements(v_graph->'elements') e where e#>>'{component_receipt,component,component_token_id}' is not null
  ) q join lf_design.component_tokens ct using(component_token_id) where ct.status<>'VIGENTE';
  if v_design_status<>'VIGENTE' or v_nonprod_components>0 then if v_prod='READY' then v_prod:='NOT_READY'; end if;v_blockers:=v_blockers||jsonb_build_array(jsonb_build_object('code','DESIGN_SOURCE_NOT_PRODUCTION_STATUS','design_system_status',v_design_status,'non_vigente_component_count',v_nonprod_components)); end if;

  select count(*) into v_missing_supabase_visual from lf_ops.pantalla_artefactos a where a.pantalla_id=p_pantalla_id and a.is_current=true and a.storage_provider='SUPABASE_STORAGE' and (a.storage_bucket is null or a.storage_object_path is null or not exists(select 1 from storage.objects o where o.bucket_id=a.storage_bucket and o.name=a.storage_object_path));
  if v_missing_supabase_visual>0 then v_qa:='BLOCKED';v_prod:='BLOCKED';v_blockers:=v_blockers||jsonb_build_array(jsonb_build_object('code','CURRENT_SUPABASE_VISUAL_ARTIFACT_NOT_PHYSICALLY_RESOLVABLE','count',v_missing_supabase_visual)); end if;

  return jsonb_build_object('coverage_status',v_coverage,'well_defined_status',v_well,'story_ready_status',v_story,'implementation_ready_status',v_impl,'qa_ready_status',v_qa,'production_ready_status',v_prod,
    'blockers',v_blockers,'binding_graph',v_graph,
    'policy',jsonb_build_object('generic_design_rule_alone_is_implementation_ready',false,'component_id_alone_is_semantic_binding_sufficient',false,'explicit_pending_visual_component_blocks_implementation',true,'candidate_visual_may_guide_candidate_implementation',true,'candidate_visual_is_production_ready',false,'declared_supabase_visual_must_exist_for_qa',true,'non_field_element_inventory_required',true));
end;
$$;

update programacion.contratos c
set especificacion=jsonb_set(c.especificacion,'{semantic_fail_closed,non_field_element_inventory_required}','true'::jsonb,true)
where c.version_id=19 and c.contrato_codigo='INPUT_READINESS_CONTRACT' and c.especificacion->>'contract_revision'='5.6';

update programacion.contratos c
set especificacion=jsonb_set(c.especificacion,'{negative_tests}',coalesce(c.especificacion->'negative_tests','[]'::jsonb)||jsonb_build_array('DESIGN_READY_WITHOUT_NON_FIELD_ELEMENT_INVENTORY'),true)
where c.version_id=19 and c.contrato_codigo='INPUT_READINESS_CONTRACT' and c.especificacion->>'contract_revision'='5.6';