-- DB-SPACE / PR-OBS-1 — durable DB size observability.
-- Owner-approved pilot 2 for the migration merge train.
-- Scope:
--   * daily durable pg_database_size snapshot;
--   * private growth view;
--   * active internal alert definition at 450 MiB;
--   * no external notification provider is invented.

do $obs_pre$
begin
  if to_regclass('private.lf_db_size_snapshots_v1') is not null then
    raise exception 'BLOCK_OBS1_SNAPSHOT_TABLE_ALREADY_EXISTS';
  end if;
  if to_regclass('private.v_lf_db_size_growth_v1') is not null then
    raise exception 'BLOCK_OBS1_GROWTH_VIEW_ALREADY_EXISTS';
  end if;
  if to_regprocedure('private.fn_capture_db_size_snapshot_v1()') is not null then
    raise exception 'BLOCK_OBS1_CAPTURE_FUNCTION_ALREADY_EXISTS';
  end if;
  if exists (
    select 1 from lf_ops.observabilidad_alertas
    where alert_code='ALERT-DB-SIZE-450MB'
  ) then
    raise exception 'BLOCK_OBS1_ALERT_ALREADY_EXISTS';
  end if;
  if exists (
    select 1 from cron.job
    where jobname='lf-db-size-snapshot-v1'
  ) then
    raise exception 'BLOCK_OBS1_CRON_ALREADY_EXISTS';
  end if;
end
$obs_pre$;

create temporary table _lf_obs1_cron_before
on commit drop
as
select jobid,jobname,schedule,active,command
from cron.job;

create table private.lf_db_size_snapshots_v1 (
  snapshot_id bigint generated by default as identity primary key,
  captured_at timestamptz not null default clock_timestamp(),
  db_size_bytes bigint not null check (db_size_bytes > 0),
  threshold_bytes bigint not null default 471859200
    check (threshold_bytes = 471859200),
  alert_triggered boolean generated always as (db_size_bytes >= threshold_bytes) stored,
  source_metric text not null default 'pg_database_size'
    check (source_metric = 'pg_database_size')
);

revoke all on table private.lf_db_size_snapshots_v1
from public, anon, authenticated;

grant select on table private.lf_db_size_snapshots_v1 to service_role;

create or replace function private.fn_capture_db_size_snapshot_v1()
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, private
as $function$
declare
  v_id bigint;
  v_size bigint;
  v_threshold constant bigint := 471859200;
begin
  v_size := pg_database_size(current_database());

  insert into private.lf_db_size_snapshots_v1(
    db_size_bytes,
    threshold_bytes
  )
  values (
    v_size,
    v_threshold
  )
  returning snapshot_id into v_id;

  return jsonb_build_object(
    'schema_version','lf-db-size-snapshot/v1',
    'snapshot_id',v_id,
    'db_size_bytes',v_size,
    'threshold_bytes',v_threshold,
    'threshold_mib',450,
    'alert_triggered',v_size >= v_threshold
  );
end;
$function$;

revoke all on function private.fn_capture_db_size_snapshot_v1()
from public, anon, authenticated;

grant execute on function private.fn_capture_db_size_snapshot_v1()
to service_role;

create view private.v_lf_db_size_growth_v1
with (security_invoker=true)
as
with ordered as (
  select
    snapshot_id,
    captured_at,
    db_size_bytes,
    threshold_bytes,
    alert_triggered,
    lag(db_size_bytes) over (
      order by captured_at,snapshot_id
    ) as previous_db_size_bytes
  from private.lf_db_size_snapshots_v1
)
select
  snapshot_id,
  captured_at,
  db_size_bytes,
  previous_db_size_bytes,
  db_size_bytes - previous_db_size_bytes as growth_bytes,
  case
    when previous_db_size_bytes is null or previous_db_size_bytes = 0 then null
    else round(
      100.0 * (db_size_bytes - previous_db_size_bytes)::numeric
      / previous_db_size_bytes::numeric,
      2
    )
  end as growth_pct,
  threshold_bytes,
  alert_triggered
from ordered;

revoke all on private.v_lf_db_size_growth_v1
from public, anon, authenticated;

grant select on private.v_lf_db_size_growth_v1
to service_role;

insert into lf_ops.observabilidad_alertas(
  alert_code,
  provider_code,
  condition_name,
  severity,
  metric_name,
  threshold_config,
  notification_channel,
  enabled,
  status,
  source_decision_id
)
values (
  'ALERT-DB-SIZE-450MB',
  null,
  'Database size at or above 450 MiB',
  'HIGH',
  'database_size_bytes',
  jsonb_build_object(
    'operator','>=',
    'bytes',471859200,
    'mib',450,
    'source','pg_database_size',
    'delivery','DB_INTERNAL_ONLY'
  ),
  null,
  true,
  'VIGENTE',
  'DB-SPACE-OBS-1'
);

select private.fn_capture_db_size_snapshot_v1();

do $obs_cron$
declare
  v_jobid bigint;
  v_before_count bigint;
  v_after_count bigint;
begin
  select count(*) into v_before_count from _lf_obs1_cron_before;

  select cron.schedule(
    'lf-db-size-snapshot-v1',
    '53 8 * * *',
    $cron$select private.fn_capture_db_size_snapshot_v1();$cron$
  ) into v_jobid;

  if v_jobid is null then
    raise exception 'BLOCK_OBS1_CRON_NO_JOBID';
  end if;

  if not exists (
    select 1
    from cron.job
    where jobid=v_jobid
      and jobname='lf-db-size-snapshot-v1'
      and schedule='53 8 * * *'
      and active is true
      and command='select private.fn_capture_db_size_snapshot_v1();'
  ) then
    raise exception 'BLOCK_OBS1_CRON_READBACK_MISMATCH';
  end if;

  if exists (
    select 1
    from _lf_obs1_cron_before b
    left join cron.job j using(jobid)
    where j.jobid is null
       or j.jobname is distinct from b.jobname
       or j.schedule is distinct from b.schedule
       or j.active is distinct from b.active
       or j.command is distinct from b.command
  ) then
    raise exception 'BLOCK_OBS1_EXISTING_CRON_DRIFT';
  end if;

  select count(*) into v_after_count from cron.job;
  if v_after_count <> v_before_count + 1 then
    raise exception 'BLOCK_OBS1_CRON_COUNT_DELTA expected=% observed=%',v_before_count+1,v_after_count;
  end if;

  if not exists (
    select 1
    from lf_ops.observabilidad_alertas
    where alert_code='ALERT-DB-SIZE-450MB'
      and severity='HIGH'
      and metric_name='database_size_bytes'
      and enabled is true
      and status='VIGENTE'
      and threshold_config->>'bytes'='471859200'
  ) then
    raise exception 'BLOCK_OBS1_ALERT_READBACK_MISMATCH';
  end if;

  if not exists (
    select 1
    from private.lf_db_size_snapshots_v1
    where threshold_bytes=471859200
  ) then
    raise exception 'BLOCK_OBS1_INITIAL_SNAPSHOT_MISSING';
  end if;
end
$obs_cron$;

comment on table private.lf_db_size_snapshots_v1 is
'DB-SPACE OBS-1 daily pg_database_size snapshots. Threshold 450 MiB.';

comment on view private.v_lf_db_size_growth_v1 is
'DB-SPACE OBS-1 growth history and 450 MiB threshold state. Internal/service_role only.';
