DO $pre$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM public.lf_operation_execution WHERE execution_id='EXEC-S30-LF-ASSURANCE-METHOD-V1-BASELINE-20260916-001' AND operation_code='ACTUALIZACION_ESTRATEGIA_LF' AND target_type='STRATEGY' AND target_code='LF_OPERATING_CONSTITUTION_POLICY_AUTONOMOUS_OPERATIONS_20260906' AND status='IN_PROGRESS') THEN RAISE EXCEPTION 'LF_ASSURANCE_S30_GOVERNED_EXECUTION_MISSING'; END IF;
  IF EXISTS (SELECT 1 FROM public.lf_assurance_evaluations) THEN RAISE EXCEPTION 'LF_ASSURANCE_PRODUCTIVE_EVALUATION_ALREADY_EXISTS'; END IF;
END $pre$;

-- Re-version existing obligations to give current material rows canonical provenance while preserving append-only history.
INSERT INTO public.lf_assurance_obligation_catalog
(obligation_code,version,claim_code,claim_version,requirement_ref,implementation_ref,condition_ref,verification_method,positive_test_ref,negative_test_ref,adversarial_test_ref,structural_coverage_mode,evidence_contract,failure_taxonomy_code,required,status,source_ref,created_by_execution_id)
SELECT obligation_code,2,claim_code,claim_version,requirement_ref,implementation_ref,condition_ref,verification_method,positive_test_ref,negative_test_ref,adversarial_test_ref,structural_coverage_mode,evidence_contract,failure_taxonomy_code,required,'CANDIDATO',
'github://cristhianlujan/claude-persona-lf-patch/supabase/source_plans/s30_assurance_method_v1_workflow_router_completion.sql','EXEC-S30-LF-ASSURANCE-METHOD-V1-BASELINE-20260916-001'
FROM public.lf_assurance_obligation_catalog
WHERE version=1 AND obligation_code IN ('WF-DIAG-TEST-IDENTITY-V1','WF-DIAG-ASSERTION-V1','WF-DIAG-DURABLE-V1','ROUTER-EXEC-BIND-V1','ROUTER-OP-BIND-V1','ROUTER-TARGET-BIND-V1','ROUTER-FRESHNESS-V1','ROUTER-REPLAY-V1','ROUTER-ZERO-EFFECT-V1')
ON CONFLICT (obligation_code,version) DO NOTHING;

INSERT INTO public.lf_assurance_obligation_catalog
(obligation_code,version,claim_code,claim_version,requirement_ref,implementation_ref,condition_ref,verification_method,positive_test_ref,negative_test_ref,adversarial_test_ref,structural_coverage_mode,evidence_contract,failure_taxonomy_code,required,status,source_ref,created_by_execution_id)
VALUES
('WF-DIAG-EXPECTED-ACTUAL-V1',1,'WF_DIAGNOSTIC_COMPLETE_V1',1,'expected/actual','github://.github/workflows/validate-lf-packs.yml#validate-lf-packs','assertion/gate failure => expected and actual values independently recoverable','TEST','github://validate-lf-packs/expected-actual-present','github://validate-lf-packs/expected-or-actual-missing','github://validate-lf-packs/ambiguous-shared-rc','CONDITION','{"required_fields":["expected","actual","operator_or_condition","assertion_or_error"],"durable_evidence_required":true}'::jsonb,'EVIDENCE_WEAK',true,'CANDIDATO','github://cristhianlujan/claude-persona-lf-patch/supabase/source_plans/s30_assurance_method_v1_workflow_router_completion.sql','EXEC-S30-LF-ASSURANCE-METHOD-V1-BASELINE-20260916-001'),
('WF-DIAG-CORRELATION-V1',1,'WF_DIAGNOSTIC_COMPLETE_V1',1,'correlation','github://.github/workflows/validate-lf-packs.yml#validate-lf-packs','failure evidence => workflow run/job/step/source/test/evidence share one correlation chain','TEST','github://validate-lf-packs/correlation-chain-valid','github://validate-lf-packs/orphan-artifact','github://validate-lf-packs/cross-run-artifact-reuse','MC_DC_LIKE','{"required_fields":["workflow_run_id","job_id","step","source_sha","test_case_or_check_id","durable_ref","correlation_id"],"cross_run_reuse_forbidden":true}'::jsonb,'TRACEABILITY_BROKEN',true,'CANDIDATO','github://cristhianlujan/claude-persona-lf-patch/supabase/source_plans/s30_assurance_method_v1_workflow_router_completion.sql','EXEC-S30-LF-ASSURANCE-METHOD-V1-BASELINE-20260916-001'),
('WF-DIAG-OWNER-REPAIR-RESUME-V1',1,'WF_DIAGNOSTIC_COMPLETE_V1',1,'owner/repair/resume','github://.github/workflows/validate-lf-packs.yml#validate-lf-packs','localized failure => exact owner, repair target and resume checkpoint are durable','DEMONSTRATION','github://validate-lf-packs/owner-repair-resume-present','github://validate-lf-packs/owner-or-resume-missing','github://validate-lf-packs/wrong-owner-routing','CONDITION','{"required_fields":["owner","repair_target","first_bad_step","resume_checkpoint","rerun_scope"],"full_restart_not_default":true}'::jsonb,'OBSERVABILITY_GAP',true,'CANDIDATO','github://cristhianlujan/claude-persona-lf-patch/supabase/source_plans/s30_assurance_method_v1_workflow_router_completion.sql','EXEC-S30-LF-ASSURANCE-METHOD-V1-BASELINE-20260916-001'),
('ROUTER-REVISION-BIND-V1',1,'STRATEGY_ROUTER_AUTHENTIC_V1',1,'revision binding','supabase://public/lf_router_resolve_v1','route receipt binds exact material subject/operation revision consumed at effect boundary','TEST','supabase://router-assurance/exact-revision','supabase://router-assurance/wrong-revision','supabase://router-assurance/revision-substitution','MC_DC_LIKE','{"required_fields":["receipt_revision","expected_revision","current_revision"],"expected_actual_required":true,"zero_effect_on_fail":true}'::jsonb,'CURRENTNESS_GAP',true,'CANDIDATO','github://cristhianlujan/claude-persona-lf-patch/supabase/source_plans/s30_assurance_method_v1_workflow_router_completion.sql','EXEC-S30-LF-ASSURANCE-METHOD-V1-BASELINE-20260916-001'),
('ROUTER-PRODUCER-AUTHORITY-V1',1,'STRATEGY_ROUTER_AUTHENTIC_V1',1,'producer authority','supabase://public/lf_router_resolve_v1','route trust is accepted only when produced by canonical ACT-0001/Router authority','TEST','supabase://router-assurance/canonical-producer','supabase://router-assurance/caller-declared-trust','supabase://router-assurance/forged-producer','MC_DC_LIKE','{"required_fields":["producer_ref","authority_ref","route_receipt"],"caller_assertions_not_authority":true,"zero_effect_on_fail":true}'::jsonb,'EVIDENCE_NOT_INDEPENDENT',true,'CANDIDATO','github://cristhianlujan/claude-persona-lf-patch/supabase/source_plans/s30_assurance_method_v1_workflow_router_completion.sql','EXEC-S30-LF-ASSURANCE-METHOD-V1-BASELINE-20260916-001'),
('ROUTER-SPOOF-RESISTANCE-V1',1,'STRATEGY_ROUTER_AUTHENTIC_V1',1,'spoof resistance','supabase://public/lf_router_resolve_v1','plausible caller-supplied route fields cannot substitute canonical producer receipt','TEST','supabase://router-assurance/canonical-receipt','supabase://router-assurance/fabricated-route-fields','supabase://router-assurance/forged-trust-payload','MC_DC_LIKE','{"required_fields":["canonical_receipt_ref","producer_ref","trust_validation"],"zero_effect_on_fail":true}'::jsonb,'TRACEABILITY_BROKEN',true,'CANDIDATO','github://cristhianlujan/claude-persona-lf-patch/supabase/source_plans/s30_assurance_method_v1_workflow_router_completion.sql','EXEC-S30-LF-ASSURANCE-METHOD-V1-BASELINE-20260916-001'),
('ROUTER-TOCTOU-RESISTANCE-V1',1,'STRATEGY_ROUTER_AUTHENTIC_V1',1,'TOCTOU resistance','supabase://public/lf_router_resolve_v1','target/currentness is revalidated immediately before material effect','TEST','supabase://router-assurance/unchanged-before-effect','supabase://router-assurance/changed-before-effect','supabase://router-assurance/concurrent-change-window','MC_DC_LIKE','{"required_fields":["route_observed_revision","pre_effect_revision","pre_effect_check_at"],"zero_effect_on_fail":true}'::jsonb,'CURRENTNESS_GAP',true,'CANDIDATO','github://cristhianlujan/claude-persona-lf-patch/supabase/source_plans/s30_assurance_method_v1_workflow_router_completion.sql','EXEC-S30-LF-ASSURANCE-METHOD-V1-BASELINE-20260916-001')
ON CONFLICT (obligation_code,version) DO NOTHING;

-- Current defeater provenance and explicit mechanisms for the newly materialized obligations.
INSERT INTO public.lf_assurance_defeater_catalog
(defeater_code,version,claim_code,claim_version,obligation_code,defeater_class,description,required_counterevidence,zero_effect_required,status,source_ref,created_by_execution_id)
SELECT defeater_code,2,claim_code,claim_version,
 CASE defeater_code WHEN 'ROUTER-D-SPOOF-V1' THEN 'ROUTER-SPOOF-RESISTANCE-V1' WHEN 'ROUTER-D-TOCTOU-V1' THEN 'ROUTER-TOCTOU-RESISTANCE-V1' ELSE obligation_code END,
 defeater_class,description,required_counterevidence,zero_effect_required,'CANDIDATO',
 'github://cristhianlujan/claude-persona-lf-patch/supabase/source_plans/s30_assurance_method_v1_workflow_router_completion.sql','EXEC-S30-LF-ASSURANCE-METHOD-V1-BASELINE-20260916-001'
FROM public.lf_assurance_defeater_catalog
WHERE version=1 AND defeater_code IN ('WF-D-STDOUT-LOSS-V1','ROUTER-D-WRONG-EXEC-V1','ROUTER-D-WRONG-TARGET-V1','ROUTER-D-STALE-V1','ROUTER-D-REPLAY-V1','ROUTER-D-SPOOF-V1','ROUTER-D-TOCTOU-V1')
ON CONFLICT (defeater_code,version) DO NOTHING;

INSERT INTO public.lf_assurance_defeater_catalog
(defeater_code,version,claim_code,claim_version,obligation_code,defeater_class,description,required_counterevidence,zero_effect_required,status,source_ref,created_by_execution_id)
VALUES
('WF-D-EXPECTED-ACTUAL-MISSING-V1',1,'WF_DIAGNOSTIC_COMPLETE_V1',1,'WF-DIAG-EXPECTED-ACTUAL-V1','EVIDENCE_WEAK','Failure identifies a check but not the expected/actual condition.','{"test_ref":"github://validate-lf-packs/expected-or-actual-missing"}'::jsonb,false,'CANDIDATO','github://cristhianlujan/claude-persona-lf-patch/supabase/source_plans/s30_assurance_method_v1_workflow_router_completion.sql','EXEC-S30-LF-ASSURANCE-METHOD-V1-BASELINE-20260916-001'),
('WF-D-CORRELATION-BROKEN-V1',1,'WF_DIAGNOSTIC_COMPLETE_V1',1,'WF-DIAG-CORRELATION-V1','TRACEABILITY_BROKEN','Evidence from another run/source can be mistaken for the failing test evidence.','{"test_ref":"github://validate-lf-packs/cross-run-artifact-reuse"}'::jsonb,false,'CANDIDATO','github://cristhianlujan/claude-persona-lf-patch/supabase/source_plans/s30_assurance_method_v1_workflow_router_completion.sql','EXEC-S30-LF-ASSURANCE-METHOD-V1-BASELINE-20260916-001'),
('WF-D-OWNER-RESUME-MISSING-V1',1,'WF_DIAGNOSTIC_COMPLETE_V1',1,'WF-DIAG-OWNER-REPAIR-RESUME-V1','OBSERVABILITY_GAP','Failure is localized but lacks durable owner/repair/resume information.','{"test_ref":"github://validate-lf-packs/owner-or-resume-missing"}'::jsonb,false,'CANDIDATO','github://cristhianlujan/claude-persona-lf-patch/supabase/source_plans/s30_assurance_method_v1_workflow_router_completion.sql','EXEC-S30-LF-ASSURANCE-METHOD-V1-BASELINE-20260916-001'),
('ROUTER-D-WRONG-OP-V1',1,'STRATEGY_ROUTER_AUTHENTIC_V1',1,'ROUTER-OP-BIND-V1','WRONG_OPERATION','A receipt from another operation is accepted.','{"test_ref":"supabase://router-assurance/other-operation"}'::jsonb,true,'CANDIDATO','github://cristhianlujan/claude-persona-lf-patch/supabase/source_plans/s30_assurance_method_v1_workflow_router_completion.sql','EXEC-S30-LF-ASSURANCE-METHOD-V1-BASELINE-20260916-001'),
('ROUTER-D-WRONG-REVISION-V1',1,'STRATEGY_ROUTER_AUTHENTIC_V1',1,'ROUTER-REVISION-BIND-V1','WRONG_REVISION','A receipt for another material revision is accepted.','{"test_ref":"supabase://router-assurance/wrong-revision"}'::jsonb,true,'CANDIDATO','github://cristhianlujan/claude-persona-lf-patch/supabase/source_plans/s30_assurance_method_v1_workflow_router_completion.sql','EXEC-S30-LF-ASSURANCE-METHOD-V1-BASELINE-20260916-001'),
('ROUTER-D-PRODUCER-AUTHORITY-V1',1,'STRATEGY_ROUTER_AUTHENTIC_V1',1,'ROUTER-PRODUCER-AUTHORITY-V1','SPOOF','A non-authoritative producer is accepted as Router authority.','{"test_ref":"supabase://router-assurance/forged-producer"}'::jsonb,true,'CANDIDATO','github://cristhianlujan/claude-persona-lf-patch/supabase/source_plans/s30_assurance_method_v1_workflow_router_completion.sql','EXEC-S30-LF-ASSURANCE-METHOD-V1-BASELINE-20260916-001')
ON CONFLICT (defeater_code,version) DO NOTHING;