
update public.lf_error_knowledge
set
  ultima_vez=now(),
  updated_at=now(),
  evidencia=concat_ws(E'\n',nullif(evidencia,''),
    '2026-10-05 expanded probes: n=3 [CURRENTNESS_AUTHORITY,TYPED_EVIDENCE_REGISTRY,CONTROL_EQUIVALENCE_JUDGE] -> BLOCK_TRANSVERSAL_CAPABILITY_HANDLER_MISSING; n=5 [CURRENTNESS_AUTHORITY,TYPED_EVIDENCE_REGISTRY,MIGRATION_SOURCE_PARITY,INDEPENDENT_ASSURANCE,CONTROL_EQUIVALENCE_JUDGE] -> same block; n=8 [CURRENTNESS_AUTHORITY,TYPED_EVIDENCE_REGISTRY,MIGRATION_SOURCE_PARITY,INDEPENDENT_ASSURANCE,REVERSIBLE_CANDIDATE_VERIFICATION,SAFE_CHANGE_ADMISSION,TARGETED_EVIDENCE_ACQUISITION,CONTROL_EQUIVALENCE_JUDGE] -> same block with declared_count=8. Arrays preserved exactly; no truncation. M3.9 restored to CONTROL_EQUIVALENCE_JUDGE only.'
  )
where codigo='ENGINEERING-TRANSVERSAL-MULTI-CAPABILITY-001';
