-- INV-9.5a — external repository/Edge baseline synchronization primitives v1.
-- Git-first / EXACT_VERSION_SOURCE_FIRST.
-- This migration is source-only in this PR. Do not apply before independent audit.
--
-- Separation of responsibility:
--   baseline sync mutates object identity/baseline only;
--   inventory.fn_apply_external_currentness_observation_v1 remains the sole writer
--   of currentness/currentness_source/observed_at/observed_main_sha/source_traceability_state.
--
-- Approval:
--   large/risky deltas are created as REQUIRES_APPROVAL and are approved by
--   workflow_dispatch using the exact sync_key. Approval records GitHub actor/run
--   identity in lf_eventos before finalize.
--
-- Storage:
--   thresholds and capacity are governed by lf_ops.reglas. Missing/invalid config
--   fails closed. Capacity is checked at begin and again immediately before finalize.

do $preflight$
begin
  if exists (
    select 1 from lf_ops.reglas
    where codigo='EXTERNAL-BASELINE-SYNC-POLICY-001'
  ) then
    raise exception 'INV_9_5A_POLICY_ALREADY_EXISTS';
  end if;

  if to_regclass('inventory.baseline_sync_runs') is not null
     or to_regclass('inventory.baseline_sync_items') is not null then
    raise exception 'INV_9_5A_SYNC_TABLE_ALREADY_EXISTS';
  end if;

  if pg_catalog.to_regprocedure('public.lf_external_baseline_sync_policy_v1()') is not null
     or pg_catalog.to_regprocedure('inventory.fn_begin_external_baseline_sync_v1(text,text,integer,integer,integer,integer,integer,integer,integer)') is not null
     or pg_catalog.to_regprocedure('inventory.fn_stage_external_baseline_batch_v1(text,integer,jsonb)') is not null
     or pg_catalog.to_regprocedure('inventory.fn_approve_external_baseline_sync_v1(text,text,bigint,text)') is not null
     or pg_catalog.to_regprocedure('inventory.fn_finalize_external_baseline_sync_v1(text)') is not null then
    raise exception 'INV_9_5A_FUNCTION_ALREADY_EXISTS';
  end if;

  if pg_catalog.to_regprocedure(
    'private.fn_lf_event_contract_assessment_v3(text,text,text,text,jsonb,text)'
  ) is null then
    raise exception 'INV_9_5A_EVENT_VALIDATOR_MISSING';
  end if;
end
$preflight$;

insert into lf_ops.reglas(
  codigo,categoria,titulo,descripcion,razon,valor_config,
  es_transversal,estado,origen,pendiente_decision,pendiente_detalle,created_by
)
values(
  'EXTERNAL-BASELINE-SYNC-POLICY-001',
  'GOVERNANCE',
  'Política de sincronización gobernada de baseline externo repo/edge',
  'Define umbrales, aprobación, lotes y capacidad para reconciliar inventory.objects con GitHub main y Supabase Edge runtime sin mezclar baseline con currentness.',
  'La reconciliación automática debe ser fail-closed, acotada por capacidad, preservar MISSING como histórico y exigir aprobación humana para deltas grandes o Edge runtime sin fuente.',
  jsonb_build_object(
    'schema_version','lf-external-baseline-sync-policy/v1',
    'fail_closed',true,
    'batch_size',100,
    'missing_confirmation_runs',2,
    'runtime_without_source_requires_approval',true,
    'allowed_approval_actors',jsonb_build_array('paulozterra','cristhianlujan'),
    'repo',jsonb_build_object(
      'max_changes_abs',100,
      'max_change_pct',0.05,
      'max_deactivations_abs',10,
      'max_deactivation_pct',0.005
    ),
    'edge',jsonb_build_object(
      'max_changes_abs',5,
      'max_deactivations_abs',1
    ),
    'storage',jsonb_build_object(
      'db_capacity_bytes',524288000,
      'safety_margin_bytes',20971520,
      'repo_new_projected_bytes',12288,
      'edge_new_projected_bytes',8192,
      'staging_item_projected_bytes',1024
    )
  ),
  true,
  'VIGENTE',
  'OWNER_AUTHORIZED_INV_9_5A_20261002',
  false,
  null,
  'CHATGPT-INV-9.5A-20261002'
);

create table inventory.baseline_sync_runs(
  sync_id bigint generated by default as identity primary key,
  sync_key text not null unique,
  observed_main_sha text not null,
  report_sha256 text not null,
  status text not null,
  expected_repo_new integer not null,
  expected_repo_stale integer not null,
  expected_repo_missing integer not null,
  expected_edge_new integer not null,
  expected_edge_stale integer not null,
  expected_edge_missing integer not null,
  runtime_without_source_count integer not null default 0,
  expected_item_count integer not null,
  staged_item_count integer not null default 0,
  requires_approval boolean not null,
  approval_reasons jsonb not null default '[]'::jsonb,
  config_rule_id integer not null,
  config_updated_at timestamptz not null,
  config_sha256 text not null,
  config_snapshot jsonb not null,
  db_size_at_begin bigint not null,
  projected_baseline_growth_bytes bigint not null,
  projected_staging_growth_bytes bigint not null,
  created_at timestamptz not null default clock_timestamp(),
  approved_at timestamptz,
  approved_by_actor text,
  approval_github_run_id bigint,
  approval_workflow_sha text,
  approval_event_id bigint,
  finalized_at timestamptz,
  snapshot_id bigint,
  constraint baseline_sync_runs_key_ck check (sync_key ~ '^[0-9a-f]{64}$'),
  constraint baseline_sync_runs_main_sha_ck check (observed_main_sha ~ '^[0-9a-f]{40}$'),
  constraint baseline_sync_runs_report_sha_ck check (report_sha256 ~ '^[0-9a-f]{64}$'),
  constraint baseline_sync_runs_config_sha_ck check (config_sha256 ~ '^[0-9a-f]{64}$'),
  constraint baseline_sync_runs_status_ck check (
    status in ('STAGING','REQUIRES_APPROVAL','APPROVED','COMPLETED')
  ),
  constraint baseline_sync_runs_counts_ck check (
    expected_repo_new>=0 and expected_repo_stale>=0 and expected_repo_missing>=0
    and expected_edge_new>=0 and expected_edge_stale>=0 and expected_edge_missing>=0
    and runtime_without_source_count>=0 and expected_item_count>0
    and staged_item_count>=0 and staged_item_count<=expected_item_count
  ),
  constraint baseline_sync_runs_expected_total_ck check (
    expected_item_count =
      expected_repo_new+expected_repo_stale+expected_repo_missing+
      expected_edge_new+expected_edge_stale+expected_edge_missing
  ),
  constraint baseline_sync_runs_projection_ck check (
    db_size_at_begin>=0
    and projected_baseline_growth_bytes>=0
    and projected_staging_growth_bytes>=0
  )
);

create index baseline_sync_runs_status_idx
  on inventory.baseline_sync_runs(status,created_at);

create table inventory.baseline_sync_items(
  sync_id bigint not null
    references inventory.baseline_sync_runs(sync_id) on delete cascade,
  source_kind text not null,
  object_key text not null,
  state text not null,
  definition_sha256 text,
  source_version text,
  git_blob text,
  verify_jwt boolean,
  source_state text,
  byte_size bigint,
  extension text,
  batch_no integer not null,
  created_at timestamptz not null default clock_timestamp(),
  primary key(sync_id,source_kind,object_key),
  constraint baseline_sync_items_source_ck check (source_kind in ('REPO','EDGE')),
  constraint baseline_sync_items_state_ck check (state in ('NEW','STALE','MISSING')),
  constraint baseline_sync_items_batch_ck check (batch_no>0),
  constraint baseline_sync_items_bytes_ck check (byte_size is null or byte_size>=0)
);

create index baseline_sync_items_batch_idx
  on inventory.baseline_sync_items(sync_id,batch_no);

revoke all on inventory.baseline_sync_runs from public,anon,authenticated,service_role;
revoke all on inventory.baseline_sync_items from public,anon,authenticated,service_role;

create function public.lf_external_baseline_sync_policy_v1()
returns jsonb
language plpgsql
stable
security definer
set search_path = pg_catalog, pg_temp
as $function$
declare
  v_count integer;
  v_rule record;
  v_cfg jsonb;
begin
  select count(*) into v_count
  from lf_ops.reglas
  where codigo='EXTERNAL-BASELINE-SYNC-POLICY-001';

  if v_count<>1 then
    raise exception 'BASELINE_POLICY_CARDINALITY_MISMATCH expected=1 actual=%',v_count;
  end if;

  select id,codigo,estado,valor_config,updated_at
  into v_rule
  from lf_ops.reglas
  where codigo='EXTERNAL-BASELINE-SYNC-POLICY-001';

  if v_rule.estado<>'VIGENTE' then
    raise exception 'BASELINE_POLICY_NOT_VIGENTE actual=%',v_rule.estado;
  end if;

  v_cfg := v_rule.valor_config;

  if v_cfg is null
     or jsonb_typeof(v_cfg)<>'object'
     or v_cfg->>'schema_version'<>'lf-external-baseline-sync-policy/v1'
     or coalesce((v_cfg->>'fail_closed')::boolean,false) is not true
     or coalesce((v_cfg->>'batch_size')::integer,0) not between 1 and 500
     or coalesce((v_cfg->>'missing_confirmation_runs')::integer,0)<>2
     or coalesce((v_cfg->>'runtime_without_source_requires_approval')::boolean,false) is not true
     or jsonb_typeof(v_cfg->'allowed_approval_actors')<>'array'
     or jsonb_array_length(v_cfg->'allowed_approval_actors')<1
     or coalesce((v_cfg#>>'{repo,max_changes_abs}')::integer,-1)<0
     or coalesce((v_cfg#>>'{repo,max_change_pct}')::numeric,-1)<0
     or coalesce((v_cfg#>>'{repo,max_change_pct}')::numeric,2)>1
     or coalesce((v_cfg#>>'{repo,max_deactivations_abs}')::integer,-1)<0
     or coalesce((v_cfg#>>'{repo,max_deactivation_pct}')::numeric,-1)<0
     or coalesce((v_cfg#>>'{repo,max_deactivation_pct}')::numeric,2)>1
     or coalesce((v_cfg#>>'{edge,max_changes_abs}')::integer,-1)<0
     or coalesce((v_cfg#>>'{edge,max_deactivations_abs}')::integer,-1)<0
     or coalesce((v_cfg#>>'{storage,db_capacity_bytes}')::bigint,0)<=0
     or coalesce((v_cfg#>>'{storage,safety_margin_bytes}')::bigint,0)<=0
     or coalesce((v_cfg#>>'{storage,repo_new_projected_bytes}')::bigint,0)<=0
     or coalesce((v_cfg#>>'{storage,edge_new_projected_bytes}')::bigint,0)<=0
     or coalesce((v_cfg#>>'{storage,staging_item_projected_bytes}')::bigint,0)<=0
     or (v_cfg#>>'{storage,safety_margin_bytes}')::bigint >=
        (v_cfg#>>'{storage,db_capacity_bytes}')::bigint
     or exists (
       select 1
       from jsonb_array_elements_text(v_cfg->'allowed_approval_actors') a(value)
       where btrim(value)=''
     ) then
    raise exception 'BASELINE_POLICY_INVALID';
  end if;

  return jsonb_build_object(
    'schema_version','lf-external-baseline-sync-policy-reader/v1',
    'rule_id',v_rule.id,
    'codigo',v_rule.codigo,
    'estado',v_rule.estado,
    'valor_config',v_cfg,
    'updated_at',v_rule.updated_at,
    'observed_at',clock_timestamp()
  );
end
$function$;

alter function public.lf_external_baseline_sync_policy_v1() owner to postgres;
revoke all on function public.lf_external_baseline_sync_policy_v1()
  from public,anon,authenticated;
grant execute on function public.lf_external_baseline_sync_policy_v1()
  to service_role;

create function inventory.fn_begin_external_baseline_sync_v1(
  p_observed_main_sha text,
  p_report_sha256 text,
  p_expected_repo_new integer,
  p_expected_repo_stale integer,
  p_expected_repo_missing integer,
  p_expected_edge_new integer,
  p_expected_edge_stale integer,
  p_expected_edge_missing integer,
  p_runtime_without_source_count integer
)
returns table(
  sync_id bigint,
  sync_key text,
  sync_state text,
  requires_approval boolean,
  approval_reasons jsonb,
  batch_size integer,
  expected_item_count integer,
  projected_growth_bytes bigint
)
language plpgsql
security invoker
set search_path = inventory, pg_catalog, extensions
as $function$
declare
  v_policy jsonb;
  v_cfg jsonb;
  v_rule_id integer;
  v_rule_updated_at timestamptz;
  v_config_sha text;
  v_key text;
  v_expected integer;
  v_repo_active integer;
  v_edge_active integer;
  v_repo_changes integer;
  v_edge_changes integer;
  v_reasons jsonb := '[]'::jsonb;
  v_requires boolean;
  v_state text;
  v_db_size bigint;
  v_capacity bigint;
  v_safety bigint;
  v_project_baseline bigint;
  v_project_staging bigint;
  v_batch_size integer;
  v_existing inventory.baseline_sync_runs%rowtype;
  v_inserted inventory.baseline_sync_runs%rowtype;
begin
  if coalesce(p_observed_main_sha,'') !~ '^[0-9a-f]{40}$'
     or coalesce(p_report_sha256,'') !~ '^[0-9a-f]{64}$' then
    raise exception 'BASELINE_SYNC_IDENTITY_INVALID';
  end if;

  if p_expected_repo_new<0 or p_expected_repo_stale<0 or p_expected_repo_missing<0
     or p_expected_edge_new<0 or p_expected_edge_stale<0 or p_expected_edge_missing<0
     or p_runtime_without_source_count<0 then
    raise exception 'BASELINE_SYNC_COUNT_INVALID';
  end if;

  v_expected :=
    p_expected_repo_new+p_expected_repo_stale+p_expected_repo_missing+
    p_expected_edge_new+p_expected_edge_stale+p_expected_edge_missing;

  if v_expected<=0 then
    raise exception 'BASELINE_EMPTY_DELTA';
  end if;

  v_policy := public.lf_external_baseline_sync_policy_v1();
  v_cfg := v_policy->'valor_config';
  v_rule_id := (v_policy->>'rule_id')::integer;
  v_rule_updated_at := (v_policy->>'updated_at')::timestamptz;
  v_config_sha := encode(digest(convert_to(v_cfg::text,'UTF8'),'sha256'),'hex');
  v_key := encode(
    digest(convert_to(p_observed_main_sha||':'||p_report_sha256,'UTF8'),'sha256'),
    'hex'
  );

  select * into v_existing
  from inventory.baseline_sync_runs r
  where r.sync_key=v_key;

  if found then
    if v_existing.observed_main_sha<>p_observed_main_sha
       or v_existing.report_sha256<>p_report_sha256
       or v_existing.expected_repo_new<>p_expected_repo_new
       or v_existing.expected_repo_stale<>p_expected_repo_stale
       or v_existing.expected_repo_missing<>p_expected_repo_missing
       or v_existing.expected_edge_new<>p_expected_edge_new
       or v_existing.expected_edge_stale<>p_expected_edge_stale
       or v_existing.expected_edge_missing<>p_expected_edge_missing
       or v_existing.runtime_without_source_count<>p_runtime_without_source_count then
      raise exception 'BASELINE_SYNC_KEY_CONFLICT';
    end if;

    return query
    select v_existing.sync_id,v_existing.sync_key,v_existing.status,
           v_existing.requires_approval,v_existing.approval_reasons,
           (v_existing.config_snapshot->>'batch_size')::integer,
           v_existing.expected_item_count,
           v_existing.projected_baseline_growth_bytes+
             v_existing.projected_staging_growth_bytes;
    return;
  end if;

  select count(*) filter(where active and object_ref like 'repo://%'),
         count(*) filter(where active and object_ref like 'edge://%')
    into v_repo_active,v_edge_active
  from inventory.objects;

  v_repo_changes := p_expected_repo_new+p_expected_repo_stale;
  v_edge_changes := p_expected_edge_new+p_expected_edge_stale;

  if v_repo_changes > (v_cfg#>>'{repo,max_changes_abs}')::integer then
    v_reasons := v_reasons||jsonb_build_array('REPO_CHANGE_ABS');
  end if;
  if v_repo_active=0 and v_repo_changes>0 then
    v_reasons := v_reasons||jsonb_build_array('REPO_CHANGE_PCT');
  elsif v_repo_active>0
    and (v_repo_changes::numeric/v_repo_active::numeric) >
        (v_cfg#>>'{repo,max_change_pct}')::numeric then
    v_reasons := v_reasons||jsonb_build_array('REPO_CHANGE_PCT');
  end if;
  if v_edge_changes > (v_cfg#>>'{edge,max_changes_abs}')::integer then
    v_reasons := v_reasons||jsonb_build_array('EDGE_CHANGE_ABS');
  end if;
  if p_expected_repo_missing > (v_cfg#>>'{repo,max_deactivations_abs}')::integer then
    v_reasons := v_reasons||jsonb_build_array('REPO_DEACTIVATION_ABS');
  end if;
  if v_repo_active=0 and p_expected_repo_missing>0 then
    v_reasons := v_reasons||jsonb_build_array('REPO_DEACTIVATION_PCT');
  elsif v_repo_active>0
    and (p_expected_repo_missing::numeric/v_repo_active::numeric) >
        (v_cfg#>>'{repo,max_deactivation_pct}')::numeric then
    v_reasons := v_reasons||jsonb_build_array('REPO_DEACTIVATION_PCT');
  end if;
  if p_expected_edge_missing > (v_cfg#>>'{edge,max_deactivations_abs}')::integer then
    v_reasons := v_reasons||jsonb_build_array('EDGE_DEACTIVATION_ABS');
  end if;
  if p_runtime_without_source_count>0
     and (v_cfg->>'runtime_without_source_requires_approval')::boolean then
    v_reasons := v_reasons||jsonb_build_array('RUNTIME_WITHOUT_SOURCE');
  end if;

  v_requires := jsonb_array_length(v_reasons)>0;
  v_state := case when v_requires then 'REQUIRES_APPROVAL' else 'STAGING' end;

  v_batch_size := (v_cfg->>'batch_size')::integer;
  v_capacity := (v_cfg#>>'{storage,db_capacity_bytes}')::bigint;
  v_safety := (v_cfg#>>'{storage,safety_margin_bytes}')::bigint;
  v_project_baseline :=
    p_expected_repo_new*(v_cfg#>>'{storage,repo_new_projected_bytes}')::bigint+
    p_expected_edge_new*(v_cfg#>>'{storage,edge_new_projected_bytes}')::bigint;
  v_project_staging :=
    v_expected*(v_cfg#>>'{storage,staging_item_projected_bytes}')::bigint;
  v_db_size := pg_database_size(current_database());

  if v_db_size+v_project_baseline+v_project_staging+v_safety > v_capacity then
    raise exception
      'BASELINE_STORAGE_CAPACITY_EXCEEDED db=% baseline_growth=% staging_growth=% safety=% capacity=%',
      v_db_size,v_project_baseline,v_project_staging,v_safety,v_capacity;
  end if;

  insert into inventory.baseline_sync_runs(
    sync_key,observed_main_sha,report_sha256,status,
    expected_repo_new,expected_repo_stale,expected_repo_missing,
    expected_edge_new,expected_edge_stale,expected_edge_missing,
    runtime_without_source_count,expected_item_count,
    requires_approval,approval_reasons,
    config_rule_id,config_updated_at,config_sha256,config_snapshot,
    db_size_at_begin,projected_baseline_growth_bytes,projected_staging_growth_bytes
  )
  values(
    v_key,p_observed_main_sha,p_report_sha256,v_state,
    p_expected_repo_new,p_expected_repo_stale,p_expected_repo_missing,
    p_expected_edge_new,p_expected_edge_stale,p_expected_edge_missing,
    p_runtime_without_source_count,v_expected,
    v_requires,v_reasons,
    v_rule_id,v_rule_updated_at,v_config_sha,v_cfg,
    v_db_size,v_project_baseline,v_project_staging
  )
  returning * into v_inserted;

  return query
  select v_inserted.sync_id,v_inserted.sync_key,v_inserted.status,
         v_inserted.requires_approval,v_inserted.approval_reasons,
         v_batch_size,v_inserted.expected_item_count,
         v_project_baseline+v_project_staging;
end
$function$;

create function inventory.fn_stage_external_baseline_batch_v1(
  p_sync_key text,
  p_batch_no integer,
  p_items jsonb
)
returns table(
  sync_id bigint,
  sync_key text,
  sync_state text,
  staged_item_count integer,
  expected_item_count integer
)
language plpgsql
security invoker
set search_path = inventory, pg_catalog
as $function$
declare
  v_run inventory.baseline_sync_runs%rowtype;
  v_batch_size integer;
  v_count integer;
  v_total integer;
begin
  if coalesce(p_sync_key,'') !~ '^[0-9a-f]{64}$'
     or p_batch_no is null or p_batch_no<=0
     or jsonb_typeof(p_items) is distinct from 'array' then
    raise exception 'BASELINE_STAGE_REQUEST_INVALID';
  end if;

  select * into v_run
  from inventory.baseline_sync_runs
  where baseline_sync_runs.sync_key=p_sync_key
  for update;

  if not found then
    raise exception 'BASELINE_SYNC_NOT_FOUND';
  end if;
  if v_run.status not in ('STAGING','REQUIRES_APPROVAL') then
    raise exception 'BASELINE_STAGE_STATE_INVALID state=%',v_run.status;
  end if;

  v_batch_size := (v_run.config_snapshot->>'batch_size')::integer;
  v_count := jsonb_array_length(p_items);
  if v_count<1 or v_count>v_batch_size then
    raise exception 'BASELINE_STAGE_BATCH_SIZE_INVALID count=% max=%',v_count,v_batch_size;
  end if;

  if (
    select count(*)<>count(distinct (x.source_kind||chr(31)||x.object_key))
    from jsonb_to_recordset(p_items) as x(
      source_kind text,object_key text,state text,definition_sha256 text,
      source_version text,git_blob text,verify_jwt boolean,source_state text,
      bytes bigint,extension text
    )
  ) then
    raise exception 'BASELINE_STAGE_DUPLICATE_ITEM';
  end if;

  if exists (
    select 1
    from jsonb_to_recordset(p_items) as x(
      source_kind text,object_key text,state text,definition_sha256 text,
      source_version text,git_blob text,verify_jwt boolean,source_state text,
      bytes bigint,extension text
    )
    where x.source_kind not in ('REPO','EDGE')
       or coalesce(x.object_key,'')=''
       or x.state not in ('NEW','STALE','MISSING')
       or (
         x.source_kind='REPO' and x.state in ('NEW','STALE')
         and (
           coalesce(x.definition_sha256,'') !~ '^[0-9a-f]{64}$'
           or coalesce(x.source_version,'') !~ '^[0-9a-f]{40}$'
           or coalesce(x.git_blob,'') !~ '^[0-9a-f]{40}$'
           or x.bytes is null or x.bytes<0
         )
       )
       or (
         x.source_kind='EDGE' and x.state in ('NEW','STALE')
         and (
           coalesce(x.definition_sha256,'') !~ '^[0-9a-f]{64}$'
           or coalesce(btrim(x.source_version),'')=''
           or coalesce(x.source_state,'') not in ('SOURCE_PRESENT','RUNTIME_WITHOUT_SOURCE')
         )
       )
  ) then
    raise exception 'BASELINE_STAGE_ITEM_INVALID';
  end if;

  if exists (
    select 1
    from jsonb_to_recordset(p_items) as x(
      source_kind text,object_key text,state text,definition_sha256 text,
      source_version text,git_blob text,verify_jwt boolean,source_state text,
      bytes bigint,extension text
    )
    left join inventory.objects o
      on o.object_ref=case
        when x.source_kind='REPO' then 'repo://'||x.object_key
        else 'edge://'||x.object_key
      end
    where x.state='STALE'
      and (o.object_id is null or not o.active)
  ) then
    raise exception 'BASELINE_STALE_TARGET_NOT_ACTIVE';
  end if;

  if exists (
    select 1
    from jsonb_to_recordset(p_items) as x(
      source_kind text,object_key text,state text,definition_sha256 text,
      source_version text,git_blob text,verify_jwt boolean,source_state text,
      bytes bigint,extension text
    )
    left join inventory.objects o
      on o.object_ref=case
        when x.source_kind='REPO' then 'repo://'||x.object_key
        else 'edge://'||x.object_key
      end
    where x.state='MISSING'
      and (
        o.object_id is null
        or not o.active
        or o.currentness is distinct from 'MISSING'
        or o.observed_at is null
        or o.observed_at>=v_run.created_at
      )
  ) then
    raise exception 'BASELINE_MISSING_CONFIRMATION_REQUIRED';
  end if;

  if exists (
    select 1
    from jsonb_to_recordset(p_items) as x(
      source_kind text,object_key text,state text,definition_sha256 text,
      source_version text,git_blob text,verify_jwt boolean,source_state text,
      bytes bigint,extension text
    )
    join inventory.baseline_sync_items i
      on i.sync_id=v_run.sync_id
     and i.source_kind=x.source_kind
     and i.object_key=x.object_key
    where i.state is distinct from x.state
       or i.definition_sha256 is distinct from x.definition_sha256
       or i.source_version is distinct from x.source_version
       or i.git_blob is distinct from x.git_blob
       or i.verify_jwt is distinct from x.verify_jwt
       or i.source_state is distinct from x.source_state
       or i.byte_size is distinct from x.bytes
       or i.extension is distinct from x.extension
       or i.batch_no<>p_batch_no
  ) then
    raise exception 'BASELINE_STAGE_REPLAY_MISMATCH';
  end if;

  insert into inventory.baseline_sync_items(
    sync_id,source_kind,object_key,state,definition_sha256,source_version,
    git_blob,verify_jwt,source_state,byte_size,extension,batch_no
  )
  select
    v_run.sync_id,x.source_kind,x.object_key,x.state,x.definition_sha256,
    x.source_version,x.git_blob,x.verify_jwt,x.source_state,x.bytes,x.extension,
    p_batch_no
  from jsonb_to_recordset(p_items) as x(
    source_kind text,object_key text,state text,definition_sha256 text,
    source_version text,git_blob text,verify_jwt boolean,source_state text,
    bytes bigint,extension text
  )
  on conflict on constraint baseline_sync_items_pkey do nothing;

  select count(*) into v_total
  from inventory.baseline_sync_items
  where baseline_sync_items.sync_id=v_run.sync_id;

  if v_total>v_run.expected_item_count then
    raise exception 'BASELINE_STAGE_COUNT_EXCEEDED expected=% actual=%',
      v_run.expected_item_count,v_total;
  end if;

  update inventory.baseline_sync_runs
  set staged_item_count=v_total
  where baseline_sync_runs.sync_id=v_run.sync_id;

  return query
  select v_run.sync_id,v_run.sync_key,v_run.status,v_total,v_run.expected_item_count;
end
$function$;

create function inventory.fn_approve_external_baseline_sync_v1(
  p_sync_key text,
  p_actor text,
  p_github_run_id bigint,
  p_workflow_sha text
)
returns table(
  sync_id bigint,
  sync_key text,
  sync_state text,
  approval_event_id bigint
)
language plpgsql
security invoker
set search_path = inventory, pg_catalog, extensions
as $function$
declare
  v_run inventory.baseline_sync_runs%rowtype;
  v_policy jsonb;
  v_cfg jsonb;
  v_config_sha text;
  v_event_payload jsonb;
  v_event_description text;
  v_execution_id text;
  v_assessment text;
  v_event_id bigint;
begin
  select * into v_run
  from inventory.baseline_sync_runs
  where baseline_sync_runs.sync_key=p_sync_key
  for update;

  if not found then
    raise exception 'BASELINE_SYNC_NOT_FOUND';
  end if;

  if v_run.status='APPROVED' then
    if lower(v_run.approved_by_actor)=lower(p_actor)
       and v_run.approval_github_run_id=p_github_run_id
       and v_run.approval_workflow_sha=p_workflow_sha then
      return query
      select v_run.sync_id,v_run.sync_key,v_run.status,v_run.approval_event_id;
      return;
    end if;
    raise exception 'BASELINE_APPROVAL_REPLAY_MISMATCH';
  end if;

  if v_run.status<>'REQUIRES_APPROVAL' then
    raise exception 'BASELINE_APPROVAL_STATE_INVALID state=%',v_run.status;
  end if;
  if v_run.staged_item_count<>v_run.expected_item_count then
    raise exception 'BASELINE_APPROVAL_STAGING_INCOMPLETE expected=% actual=%',
      v_run.expected_item_count,v_run.staged_item_count;
  end if;
  if coalesce(p_actor,'')='' or p_github_run_id is null or p_github_run_id<=0
     or coalesce(p_workflow_sha,'') !~ '^[0-9a-f]{40}$' then
    raise exception 'BASELINE_APPROVAL_IDENTITY_INVALID';
  end if;

  v_policy := public.lf_external_baseline_sync_policy_v1();
  v_cfg := v_policy->'valor_config';
  v_config_sha := encode(digest(convert_to(v_cfg::text,'UTF8'),'sha256'),'hex');

  if v_config_sha<>v_run.config_sha256 then
    raise exception 'BASELINE_POLICY_CHANGED';
  end if;

  if not exists (
    select 1
    from jsonb_array_elements_text(v_cfg->'allowed_approval_actors') a(value)
    where lower(value)=lower(p_actor)
  ) then
    raise exception 'BASELINE_APPROVAL_ACTOR_NOT_ALLOWED actor=%',p_actor;
  end if;

  v_execution_id :=
    'BASELINE-APPROVAL-'||substr(v_run.sync_key,1,16)||'-'||p_github_run_id::text;
  v_event_description :=
    'Aprobación gobernada del delta de baseline externo para sync_key '||
    v_run.sync_key||' mediante workflow_dispatch.';
  v_event_payload := jsonb_build_object(
    'evidence_schema_version','operational-event/v2',
    'execution_id',v_execution_id,
    'producer','EXTERNAL_BASELINE_SYNC_APPROVAL_V1',
    'purpose','Registrar aprobación humana de un delta de baseline que excede las guardas automáticas.',
    'occurred_at',clock_timestamp(),
    'acceptance_declared',false,
    'production_authorized',false,
    'runtime_or_deploy_touched',false,
    'sync_key',v_run.sync_key,
    'observed_main_sha',v_run.observed_main_sha,
    'report_sha256',v_run.report_sha256,
    'approval_actor',p_actor,
    'github_run_id',p_github_run_id,
    'workflow_sha',p_workflow_sha,
    'approval_reasons',v_run.approval_reasons
  );

  v_assessment := private.fn_lf_event_contract_assessment_v3(
    'REMEDIACION_GOBERNANZA',
    'INVENTORY',
    'EXTERNAL_BASELINE_SYNC_APPROVAL',
    v_event_description,
    v_event_payload,
    v_execution_id
  );
  if v_assessment<>'CONFORMING' then
    raise exception 'BASELINE_APPROVAL_EVENT_NONCONFORMING assessment=%',v_assessment;
  end if;

  insert into public.lf_eventos(
    evento_tipo,entidad_tipo,entidad_codigo,descripcion,severidad,payload,
    origen,created_by_execution_id
  )
  values(
    'REMEDIACION_GOBERNANZA',
    'INVENTORY',
    'EXTERNAL_BASELINE_SYNC_APPROVAL',
    v_event_description,
    'INFO',
    v_event_payload,
    'EXTERNAL_BASELINE_SYNC_APPROVAL_V1',
    v_execution_id
  )
  returning id into v_event_id;

  update inventory.baseline_sync_runs
  set status='APPROVED',
      approved_at=clock_timestamp(),
      approved_by_actor=p_actor,
      approval_github_run_id=p_github_run_id,
      approval_workflow_sha=p_workflow_sha,
      approval_event_id=v_event_id
  where baseline_sync_runs.sync_id=v_run.sync_id
  returning * into v_run;

  return query
  select v_run.sync_id,v_run.sync_key,v_run.status,v_run.approval_event_id;
end
$function$;

create function inventory.fn_finalize_external_baseline_sync_v1(
  p_sync_key text
)
returns table(
  outcome text,
  sync_id bigint,
  sync_key text,
  sync_state text,
  snapshot_id bigint,
  repo_new integer,
  repo_stale integer,
  repo_missing integer,
  edge_new integer,
  edge_stale integer,
  edge_missing integer
)
language plpgsql
security invoker
set search_path = inventory, pg_catalog, extensions
as $function$
declare
  v_run inventory.baseline_sync_runs%rowtype;
  v_policy jsonb;
  v_cfg jsonb;
  v_config_sha text;
  v_db_size bigint;
  v_capacity bigint;
  v_safety bigint;
  v_staged integer;
  v_repo_new integer;
  v_repo_stale integer;
  v_repo_missing integer;
  v_edge_new integer;
  v_edge_stale integer;
  v_edge_missing integer;
  v_runtime_without_source integer;
  v_snapshot_id bigint;
  v_now timestamptz := clock_timestamp();
  v_changed_ids bigint[];
  v_missing_ids bigint[];
begin
  select * into v_run
  from inventory.baseline_sync_runs
  where baseline_sync_runs.sync_key=p_sync_key
  for update;

  if not found then
    raise exception 'BASELINE_SYNC_NOT_FOUND';
  end if;

  if v_run.status='COMPLETED' then
    return query
    select 'ALREADY_COMPLETED',v_run.sync_id,v_run.sync_key,v_run.status,
           v_run.snapshot_id,
           v_run.expected_repo_new,v_run.expected_repo_stale,v_run.expected_repo_missing,
           v_run.expected_edge_new,v_run.expected_edge_stale,v_run.expected_edge_missing;
    return;
  end if;

  if v_run.status='REQUIRES_APPROVAL' then
    raise exception 'BASELINE_APPROVAL_REQUIRED sync_key=%',v_run.sync_key;
  end if;
  if v_run.status not in ('STAGING','APPROVED') then
    raise exception 'BASELINE_FINALIZE_STATE_INVALID state=%',v_run.status;
  end if;
  if v_run.requires_approval and v_run.status<>'APPROVED' then
    raise exception 'BASELINE_APPROVAL_REQUIRED sync_key=%',v_run.sync_key;
  end if;

  v_policy := public.lf_external_baseline_sync_policy_v1();
  v_cfg := v_policy->'valor_config';
  v_config_sha := encode(digest(convert_to(v_cfg::text,'UTF8'),'sha256'),'hex');
  if v_config_sha<>v_run.config_sha256 then
    raise exception 'BASELINE_POLICY_CHANGED';
  end if;

  select count(*),
         count(*) filter(where source_kind='REPO' and state='NEW'),
         count(*) filter(where source_kind='REPO' and state='STALE'),
         count(*) filter(where source_kind='REPO' and state='MISSING'),
         count(*) filter(where source_kind='EDGE' and state='NEW'),
         count(*) filter(where source_kind='EDGE' and state='STALE'),
         count(*) filter(where source_kind='EDGE' and state='MISSING'),
         count(*) filter(where source_kind='EDGE' and source_state='RUNTIME_WITHOUT_SOURCE')
  into v_staged,v_repo_new,v_repo_stale,v_repo_missing,
       v_edge_new,v_edge_stale,v_edge_missing,v_runtime_without_source
  from inventory.baseline_sync_items
  where baseline_sync_items.sync_id=v_run.sync_id;

  if v_staged<>v_run.expected_item_count
     or v_staged<>v_run.staged_item_count
     or v_repo_new<>v_run.expected_repo_new
     or v_repo_stale<>v_run.expected_repo_stale
     or v_repo_missing<>v_run.expected_repo_missing
     or v_edge_new<>v_run.expected_edge_new
     or v_edge_stale<>v_run.expected_edge_stale
     or v_edge_missing<>v_run.expected_edge_missing
     or v_runtime_without_source<>v_run.runtime_without_source_count then
    raise exception 'BASELINE_FINALIZE_DELTA_MISMATCH';
  end if;

  v_db_size := pg_database_size(current_database());
  v_capacity := (v_cfg#>>'{storage,db_capacity_bytes}')::bigint;
  v_safety := (v_cfg#>>'{storage,safety_margin_bytes}')::bigint;
  if v_db_size+v_run.projected_baseline_growth_bytes+v_safety>v_capacity then
    raise exception
      'BASELINE_STORAGE_CAPACITY_EXCEEDED_FINALIZE db=% baseline_growth=% safety=% capacity=%',
      v_db_size,v_run.projected_baseline_growth_bytes,v_safety,v_capacity;
  end if;

  if exists (
    select 1
    from inventory.baseline_sync_items i
    left join inventory.objects o
      on o.object_ref=case when i.source_kind='REPO'
        then 'repo://'||i.object_key else 'edge://'||i.object_key end
    where i.sync_id=v_run.sync_id
      and i.state='STALE'
      and (o.object_id is null or not o.active)
  ) then
    raise exception 'BASELINE_STALE_TARGET_CHANGED';
  end if;

  if exists (
    select 1
    from inventory.baseline_sync_items i
    left join inventory.objects o
      on o.object_ref=case when i.source_kind='REPO'
        then 'repo://'||i.object_key else 'edge://'||i.object_key end
    where i.sync_id=v_run.sync_id
      and i.state='MISSING'
      and (
        o.object_id is null or not o.active
        or o.currentness is distinct from 'MISSING'
        or o.observed_at is null
        or o.observed_at>=v_run.created_at
      )
  ) then
    raise exception 'BASELINE_MISSING_CONFIRMATION_REQUIRED';
  end if;

  insert into inventory.objects(
    object_ref,object_type,schema_name,object_name,parent_object_id,domain,
    source_system,source_of_truth,status,definition_sha256,source_version,
    metadata,first_seen_at,last_seen_at,active,created_at,updated_at
  )
  select
    'repo://'||i.object_key,
    'REPO_FILE',
    null,
    i.object_key,
    null,
    'REPOSITORY',
    'GITHUB_REPO_LIVE_READBACK',
    true,
    'ACTIVE',
    i.definition_sha256,
    i.source_version,
    jsonb_strip_nulls(jsonb_build_object(
      'path',i.object_key,
      'git_blob',i.git_blob,
      'file_last_commit',i.source_version,
      'observed_main_sha',v_run.observed_main_sha,
      'bytes',i.byte_size,
      'extension',i.extension,
      'authority','GITHUB_MAIN_LIVE_READBACK'
    )),
    v_now,v_now,true,v_now,v_now
  from inventory.baseline_sync_items i
  where i.sync_id=v_run.sync_id
    and i.source_kind='REPO'
    and i.state='NEW'
  on conflict(object_ref) do update
  set object_type='REPO_FILE',
      object_name=excluded.object_name,
      domain='REPOSITORY',
      source_system='GITHUB_REPO_LIVE_READBACK',
      source_of_truth=true,
      status='ACTIVE',
      definition_sha256=excluded.definition_sha256,
      source_version=excluded.source_version,
      metadata=inventory.objects.metadata||excluded.metadata,
      last_seen_at=v_now,
      active=true,
      updated_at=v_now;

  update inventory.objects o
  set definition_sha256=i.definition_sha256,
      source_version=i.source_version,
      source_system='GITHUB_REPO_LIVE_READBACK',
      source_of_truth=true,
      metadata=o.metadata||jsonb_strip_nulls(jsonb_build_object(
        'path',i.object_key,
        'git_blob',i.git_blob,
        'file_last_commit',i.source_version,
        'observed_main_sha',v_run.observed_main_sha,
        'bytes',i.byte_size,
        'extension',i.extension,
        'authority','GITHUB_MAIN_LIVE_READBACK'
      )),
      last_seen_at=v_now,
      updated_at=v_now
  from inventory.baseline_sync_items i
  where i.sync_id=v_run.sync_id
    and i.source_kind='REPO'
    and i.state='STALE'
    and o.object_ref='repo://'||i.object_key
    and o.active;

  insert into inventory.objects(
    object_ref,object_type,schema_name,object_name,parent_object_id,domain,
    source_system,source_of_truth,status,definition_sha256,source_version,
    metadata,first_seen_at,last_seen_at,active,created_at,updated_at
  )
  select
    'edge://'||i.object_key,
    'EDGE_FUNCTION_RUNTIME',
    null,
    i.object_key,
    null,
    'EDGE_FUNCTIONS',
    'SUPABASE_EDGE_RUNTIME',
    true,
    'ACTIVE',
    i.definition_sha256,
    i.source_version,
    jsonb_strip_nulls(jsonb_build_object(
      'name',i.object_key,
      'authority','SUPABASE_EDGE_RUNTIME_LIVE_READBACK',
      'runtime_version',i.source_version,
      'verify_jwt',i.verify_jwt,
      'source_state',i.source_state
    )),
    v_now,v_now,true,v_now,v_now
  from inventory.baseline_sync_items i
  where i.sync_id=v_run.sync_id
    and i.source_kind='EDGE'
    and i.state='NEW'
  on conflict(object_ref) do update
  set object_type='EDGE_FUNCTION_RUNTIME',
      object_name=excluded.object_name,
      domain='EDGE_FUNCTIONS',
      source_system='SUPABASE_EDGE_RUNTIME',
      source_of_truth=true,
      status='ACTIVE',
      definition_sha256=excluded.definition_sha256,
      source_version=excluded.source_version,
      metadata=inventory.objects.metadata||excluded.metadata,
      last_seen_at=v_now,
      active=true,
      updated_at=v_now;

  update inventory.objects o
  set definition_sha256=i.definition_sha256,
      source_version=i.source_version,
      source_system='SUPABASE_EDGE_RUNTIME',
      source_of_truth=true,
      metadata=o.metadata||jsonb_strip_nulls(jsonb_build_object(
        'name',i.object_key,
        'authority','SUPABASE_EDGE_RUNTIME_LIVE_READBACK',
        'runtime_version',i.source_version,
        'verify_jwt',i.verify_jwt,
        'source_state',i.source_state
      )),
      last_seen_at=v_now,
      updated_at=v_now
  from inventory.baseline_sync_items i
  where i.sync_id=v_run.sync_id
    and i.source_kind='EDGE'
    and i.state='STALE'
    and o.object_ref='edge://'||i.object_key
    and o.active;

  update inventory.objects o
  set active=false,
      metadata=o.metadata||jsonb_build_object(
        'missing_observed_at',v_now,
        'missing_observed_main_sha',v_run.observed_main_sha,
        'deactivation_reason','MISSING_IN_AUTHORITATIVE_SOURCE'
      ),
      updated_at=v_now
  from inventory.baseline_sync_items i
  where i.sync_id=v_run.sync_id
    and i.state='MISSING'
    and o.object_ref=case when i.source_kind='REPO'
      then 'repo://'||i.object_key else 'edge://'||i.object_key end
    and o.active;

  select array_agg(o.object_id order by o.object_id)
  into v_changed_ids
  from inventory.baseline_sync_items i
  join inventory.objects o
    on o.object_ref=case when i.source_kind='REPO'
      then 'repo://'||i.object_key else 'edge://'||i.object_key end
  where i.sync_id=v_run.sync_id
    and i.state in ('NEW','STALE')
    and o.active;

  select array_agg(o.object_id order by o.object_id)
  into v_missing_ids
  from inventory.baseline_sync_items i
  join inventory.objects o
    on o.object_ref=case when i.source_kind='REPO'
      then 'repo://'||i.object_key else 'edge://'||i.object_key end
  where i.sync_id=v_run.sync_id
    and i.state='MISSING'
    and not o.active;

  if v_changed_ids is not null then
    insert into inventory.search_index(
      object_id,object_ref,object_ref_lc,object_type,schema_name,object_name,
      object_name_lc,tags,tags_lc,column_names,column_names_lc,
      source_system,source_of_truth,status,search_document,refreshed_at,
      currentness,currentness_source,observed_at,observed_main_sha,
      source_traceability_state
    )
    select
      o.object_id,o.object_ref,lower(o.object_ref),o.object_type,o.schema_name,
      o.object_name,lower(o.object_name),
      coalesce(t.tags,'{}'::text[]),coalesce(t.tags_lc,'{}'::text[]),
      coalesce(c.cols,'{}'::text[]),coalesce(c.cols_lc,'{}'::text[]),
      o.source_system,o.source_of_truth,o.status,
      to_tsvector(
        'simple',
        coalesce(o.object_ref,'')||' '||coalesce(o.object_name,'')||' '||
        coalesce(o.schema_name,'')||' '||
        array_to_string(coalesce(t.tags,'{}'::text[]),' ')||' '||
        array_to_string(coalesce(c.cols,'{}'::text[]),' ')
      ),
      v_now,
      o.currentness,o.currentness_source,o.observed_at,o.observed_main_sha,
      o.source_traceability_state
    from inventory.objects o
    left join lateral(
      select array_agg(distinct ot.tag_code order by ot.tag_code) tags,
             array_agg(distinct lower(ot.tag_code) order by lower(ot.tag_code)) tags_lc
      from inventory.object_tags ot
      where ot.object_id=o.object_id
    ) t on true
    left join lateral(
      select array_agg(ic.column_name order by ic.ordinal_position) cols,
             array_agg(lower(ic.column_name) order by ic.ordinal_position) cols_lc
      from inventory.columns ic
      where ic.object_id=o.object_id
    ) c on true
    where o.object_id=any(v_changed_ids)
    on conflict(object_id) do update
    set object_ref=excluded.object_ref,
        object_ref_lc=excluded.object_ref_lc,
        object_type=excluded.object_type,
        schema_name=excluded.schema_name,
        object_name=excluded.object_name,
        object_name_lc=excluded.object_name_lc,
        tags=excluded.tags,
        tags_lc=excluded.tags_lc,
        column_names=excluded.column_names,
        column_names_lc=excluded.column_names_lc,
        source_system=excluded.source_system,
        source_of_truth=excluded.source_of_truth,
        status=excluded.status,
        search_document=excluded.search_document,
        refreshed_at=excluded.refreshed_at,
        currentness=excluded.currentness,
        currentness_source=excluded.currentness_source,
        observed_at=excluded.observed_at,
        observed_main_sha=excluded.observed_main_sha,
        source_traceability_state=excluded.source_traceability_state;
  end if;

  if v_missing_ids is not null then
    delete from inventory.search_index
    where object_id=any(v_missing_ids);
  end if;

  insert into inventory.snapshots(
    snapshot_code,source_system,scope,started_at,completed_at,status,
    object_count,dependency_count,metadata
  )
  values(
    'LF_EXTERNAL_BASELINE_'||v_run.sync_key,
    'EXTERNAL_BASELINE_SYNC_V1',
    'REPO_EDGE_BASELINE',
    v_run.created_at,
    v_now,
    'COMPLETED',
    v_run.expected_item_count,
    null,
    jsonb_strip_nulls(jsonb_build_object(
      'schema_version','lf-external-baseline-sync-snapshot/v1',
      'sync_key',v_run.sync_key,
      'observed_main_sha',v_run.observed_main_sha,
      'report_sha256',v_run.report_sha256,
      'repo_new',v_repo_new,
      'repo_stale',v_repo_stale,
      'repo_missing',v_repo_missing,
      'edge_new',v_edge_new,
      'edge_stale',v_edge_stale,
      'edge_missing',v_edge_missing,
      'requires_approval',v_run.requires_approval,
      'approval_actor',v_run.approved_by_actor,
      'approval_github_run_id',v_run.approval_github_run_id,
      'approval_event_id',v_run.approval_event_id,
      'config_rule_id',v_run.config_rule_id,
      'config_sha256',v_run.config_sha256,
      'db_size_at_begin',v_run.db_size_at_begin,
      'db_size_before_finalize',v_db_size
    ))
  )
  returning inventory.snapshots.snapshot_id into v_snapshot_id;

  update inventory.baseline_sync_runs
  set status='COMPLETED',
      finalized_at=v_now,
      snapshot_id=v_snapshot_id
  where baseline_sync_runs.sync_id=v_run.sync_id
  returning * into v_run;

  return query
  select 'APPLIED',v_run.sync_id,v_run.sync_key,v_run.status,v_snapshot_id,
         v_repo_new,v_repo_stale,v_repo_missing,
         v_edge_new,v_edge_stale,v_edge_missing;
end
$function$;

revoke all on function inventory.fn_begin_external_baseline_sync_v1(
  text,text,integer,integer,integer,integer,integer,integer,integer
) from public,anon,authenticated,service_role;
revoke all on function inventory.fn_stage_external_baseline_batch_v1(
  text,integer,jsonb
) from public,anon,authenticated,service_role;
revoke all on function inventory.fn_approve_external_baseline_sync_v1(
  text,text,bigint,text
) from public,anon,authenticated,service_role;
revoke all on function inventory.fn_finalize_external_baseline_sync_v1(
  text
) from public,anon,authenticated,service_role;

create function public.lf_external_baseline_begin_v1(
  p_observed_main_sha text,
  p_report_sha256 text,
  p_expected_repo_new integer,
  p_expected_repo_stale integer,
  p_expected_repo_missing integer,
  p_expected_edge_new integer,
  p_expected_edge_stale integer,
  p_expected_edge_missing integer,
  p_runtime_without_source_count integer
)
returns table(
  sync_id bigint,sync_key text,sync_state text,requires_approval boolean,
  approval_reasons jsonb,batch_size integer,expected_item_count integer,
  projected_growth_bytes bigint
)
language sql
volatile
security definer
set search_path = pg_catalog, pg_temp
as $function$
  select * from inventory.fn_begin_external_baseline_sync_v1(
    p_observed_main_sha,p_report_sha256,
    p_expected_repo_new,p_expected_repo_stale,p_expected_repo_missing,
    p_expected_edge_new,p_expected_edge_stale,p_expected_edge_missing,
    p_runtime_without_source_count
  );
$function$;

create function public.lf_external_baseline_stage_batch_v1(
  p_sync_key text,
  p_batch_no integer,
  p_items jsonb
)
returns table(
  sync_id bigint,sync_key text,sync_state text,
  staged_item_count integer,expected_item_count integer
)
language sql
volatile
security definer
set search_path = pg_catalog, pg_temp
as $function$
  select * from inventory.fn_stage_external_baseline_batch_v1(
    p_sync_key,p_batch_no,p_items
  );
$function$;

create function public.lf_external_baseline_approve_v1(
  p_sync_key text,
  p_actor text,
  p_github_run_id bigint,
  p_workflow_sha text
)
returns table(
  sync_id bigint,sync_key text,sync_state text,approval_event_id bigint
)
language sql
volatile
security definer
set search_path = pg_catalog, pg_temp
as $function$
  select * from inventory.fn_approve_external_baseline_sync_v1(
    p_sync_key,p_actor,p_github_run_id,p_workflow_sha
  );
$function$;

create function public.lf_external_baseline_finalize_v1(
  p_sync_key text
)
returns table(
  outcome text,sync_id bigint,sync_key text,sync_state text,snapshot_id bigint,
  repo_new integer,repo_stale integer,repo_missing integer,
  edge_new integer,edge_stale integer,edge_missing integer
)
language sql
volatile
security definer
set search_path = pg_catalog, pg_temp
as $function$
  select * from inventory.fn_finalize_external_baseline_sync_v1(p_sync_key);
$function$;

alter function public.lf_external_baseline_begin_v1(
  text,text,integer,integer,integer,integer,integer,integer,integer
) owner to postgres;
alter function public.lf_external_baseline_stage_batch_v1(
  text,integer,jsonb
) owner to postgres;
alter function public.lf_external_baseline_approve_v1(
  text,text,bigint,text
) owner to postgres;
alter function public.lf_external_baseline_finalize_v1(text) owner to postgres;

revoke all on function public.lf_external_baseline_begin_v1(
  text,text,integer,integer,integer,integer,integer,integer,integer
) from public,anon,authenticated;
revoke all on function public.lf_external_baseline_stage_batch_v1(
  text,integer,jsonb
) from public,anon,authenticated;
revoke all on function public.lf_external_baseline_approve_v1(
  text,text,bigint,text
) from public,anon,authenticated;
revoke all on function public.lf_external_baseline_finalize_v1(text)
  from public,anon,authenticated;

grant execute on function public.lf_external_baseline_begin_v1(
  text,text,integer,integer,integer,integer,integer,integer,integer
) to service_role;
grant execute on function public.lf_external_baseline_stage_batch_v1(
  text,integer,jsonb
) to service_role;
grant execute on function public.lf_external_baseline_approve_v1(
  text,text,bigint,text
) to service_role;
grant execute on function public.lf_external_baseline_finalize_v1(text)
  to service_role;

comment on table inventory.baseline_sync_runs is
'INV-9.5a governed external baseline sync runs; currentness is out of scope.';
comment on table inventory.baseline_sync_items is
'INV-9.5a staged delta items only; never stores file contents or full detector reports.';
comment on function public.lf_external_baseline_sync_policy_v1() is
'Governed policy reader for external baseline synchronization. Fail-closed and service_role-only.';
