create or replace function programacion.fn_input_rebind_assertion_specs(p_run_id bigint,p_family_code text,p_specs jsonb)
returns jsonb language plpgsql security definer set search_path=pg_catalog,programacion as $$
declare s jsonb; r jsonb; outj jsonb:='[]'::jsonb;
begin
  for s in select value from jsonb_array_elements(p_specs) loop
    r:=programacion.fn_input_rebind_assertion(p_run_id,p_family_code,s);
    if r->>'result'<>'PASS' then raise exception 'ASSERTION_SPEC_FAILED run=% family=% source=% path=% expected=% actual=%',p_run_id,p_family_code,r->'source_ref',r->'path',r->'expected',r->'actual'; end if;
    outj:=outj||jsonb_build_array(r);
  end loop;
  return outj;
end$$;

create or replace function programacion.fn_input_auth006_build_assertions(p_run_id bigint,p_seed_run_id bigint,p_family_code text)
returns jsonb language plpgsql security definer set search_path=pg_catalog,programacion as $$
declare specs jsonb; olda jsonb; tpl jsonb; reb jsonb; outj jsonb:='[]'::jsonb;
begin
  case p_family_code
    when 'SCREEN_IDENTITY' then specs:=jsonb_build_array(jsonb_build_object('source_ref',jsonb_build_object('kind','SCREEN_CANONICAL_GRAPH','pantalla_id',56),'path',jsonb_build_array('observed','screen_code'),'operator','EQ','expected','B2B-AUTH-006'));
    when 'OBJECTIVE_OUTCOMES' then specs:=jsonb_build_array(jsonb_build_object('source_ref',jsonb_build_object('kind','SCREEN_CANONICAL_GRAPH','pantalla_id',56),'path',jsonb_build_array('observed','canonical_contract','context','screen','objective'),'operator','EQ','expected','Validar la identidad mediante OTP de recuperación y habilitar exclusivamente un contexto PASSWORD_UPDATE_ONLY antes de B2B-AUTH-003.'));
    when 'FIELDS' then specs:=jsonb_build_array(jsonb_build_object('source_ref',jsonb_build_object('kind','SCREEN_CANONICAL_GRAPH','pantalla_id',56),'path',jsonb_build_array('observed','canonical_contract','fields'),'operator','CONTAINS','expected','[{"field_id":306,"field_code":"B2B_FLD_RECOVERY_EMAIL_OTP_CODE","required":true,"sensitive":true,"logs_allowed":false,"analytics_allowed":false,"retention_class":"TRANSIENT","ui":{"context_key":"PASSWORD_RECOVERY_OTP_CODE","component_token_id":40,"component_token_code":"otp_pin"}}]'::jsonb));
    when 'VALIDATIONS' then specs:=jsonb_build_array(jsonb_build_object('source_ref',jsonb_build_object('kind','SCREEN_CANONICAL_GRAPH','pantalla_id',56),'path',jsonb_build_array('observed','canonical_contract','fields'),'operator','CONTAINS','expected','[{"field_id":306,"validations":[{"validation_id":101,"validation_code":"B2B_VAL_RECOVERY_EMAIL_OTP_REQUIRED","blocking":true,"config":{"required":true}},{"validation_id":102,"validation_code":"B2B_VAL_RECOVERY_EMAIL_OTP_POLICY","blocking":true,"config":{"otp_policy_id":2,"relation_key":"otp_policy_id","server_side_validation":"REQUIRED","numeric_thresholds_in_validation":"DENY"}}]}]'::jsonb));
    when 'ACTIONS' then specs:=jsonb_build_array(jsonb_build_object('source_ref',jsonb_build_object('kind','SCREEN_CANONICAL_GRAPH','pantalla_id',56),'path',jsonb_build_array('observed','canonical_contract','rules'),'operator','CONTAINS','expected','[{"rule_code":"B2B-RULE-AUTH-037","config":{"otp_policy_id":2,"verify_screen_id":56,"success_scope":"PASSWORD_UPDATE_ONLY","server_side_generation":"REQUIRED","server_side_verification":"REQUIRED","mfa_satisfaction":"DENY","operational_session_creation":"DENY"}},{"rule_code":"B2B-RULE-AUTH-038","config":{"otp_policy_id":2,"verify_screen_id":56,"hardcoded_expiry":"DENY","hardcoded_resend_countdown":"DENY"}}]'::jsonb));
    when 'ROUTING_NAVIGATION' then specs:=jsonb_build_array(
      jsonb_build_object('source_ref',jsonb_build_object('kind','ROUTE_SET','ids',jsonb_build_array(11)),'path',jsonb_build_array('observed'),'operator','CONTAINS','expected','[{"route_id":11,"route_code":"B2B_ROUTE_AUTH_RECOVERY_VERIFY","pantalla_id":56,"route_pattern":"/b2b/auth/verificar-recuperacion","authentication_required":false}]'::jsonb),
      jsonb_build_object('source_ref',jsonb_build_object('kind','SCREEN_CANONICAL_GRAPH','pantalla_id',56),'path',jsonb_build_array('observed','canonical_contract','rules'),'operator','CONTAINS','expected','[{"rule_code":"B2B-RULE-AUTH-029","config":{"recovery_verify_route_id":11,"recovery_verify_screen_id":56,"password_update_screen_id":53,"client_context_promotion":"DENY","grant_mode":"OPAQUE_ONE_TIME_SERVER_VERIFIED"}}]'::jsonb));
    when 'PROFILES' then specs:=jsonb_build_array(jsonb_build_object('source_ref',jsonb_build_object('kind','SCREEN_CANONICAL_GRAPH','pantalla_id',56),'path',jsonb_build_array('observed','canonical_contract','profiles'),'operator','ARRAY_LENGTH_EQ','expected',0));
    when 'SESSION' then specs:=jsonb_build_array(jsonb_build_object('source_ref',jsonb_build_object('kind','SCREEN_CANONICAL_GRAPH','pantalla_id',56),'path',jsonb_build_array('observed','canonical_contract','rules'),'operator','CONTAINS','expected','[{"rule_code":"B2B-RULE-AUTH-037","config":{"operational_session_creation":"DENY","mfa_satisfaction":"DENY"}},{"rule_code":"B2B-RULE-AUTH-029","config":{"operational_authorization_before_completion":"DENY","client_context_promotion":"DENY"}}]'::jsonb));
    when 'MFA_OTP_SSO' then specs:=jsonb_build_array(jsonb_build_object('source_ref',jsonb_build_object('kind','SCREEN_CANONICAL_GRAPH','pantalla_id',56),'path',jsonb_build_array('observed','canonical_contract','rules'),'operator','CONTAINS','expected','[{"rule_code":"B2B-RULE-AUTH-037","config":{"otp_policy_id":2,"otp_operation_id":5,"delivery_channel":"EMAIL","delivery_provider":"BREVO","server_side_verification":"REQUIRED","mfa_satisfaction":"DENY"}}]'::jsonb));
    when 'PRIVACY_PII' then specs:=jsonb_build_array(
      jsonb_build_object('source_ref',jsonb_build_object('kind','SCREEN_CANONICAL_GRAPH','pantalla_id',56),'path',jsonb_build_array('observed','canonical_contract','fields'),'operator','CONTAINS','expected','[{"field_id":306,"sensitive":true,"logs_allowed":false,"analytics_allowed":false,"masking_rule":"MASK_FULL","retention_class":"TRANSIENT","pii_classification":"SENSITIVE"}]'::jsonb),
      jsonb_build_object('source_ref',jsonb_build_object('kind','SCREEN_CANONICAL_GRAPH','pantalla_id',56),'path',jsonb_build_array('observed','canonical_contract','rules'),'operator','CONTAINS','expected','[{"rule_code":"B2B-RULE-AUTH-037","config":{"otp_value_logs":"DENY","otp_value_analytics":"DENY"}}]'::jsonb));
    when 'ERRORS' then specs:=jsonb_build_array(
      jsonb_build_object('source_ref',jsonb_build_object('kind','SCREEN_CANONICAL_GRAPH','pantalla_id',56),'path',jsonb_build_array('observed','canonical_contract','rules'),'operator','CONTAINS','expected','[{"rule_code":"B2B-RULE-AUTH-029","config":{"invalid_recovery_error_id":39}}]'::jsonb),
      jsonb_build_object('source_ref',jsonb_build_object('kind','ERROR_SET','ids',jsonb_build_array(39)),'path',jsonb_build_array('observed'),'operator','CONTAINS','expected','[{"error_id":39,"error_code":"LF-B2B-AUTH-006","user_title":"Enlace de recuperación no válido","user_message_template":"El enlace de recuperación ya no es válido o venció.","action_label":"Solicitar otro enlace"}]'::jsonb));
    when 'UI_MESSAGES' then specs:=jsonb_build_array(
      jsonb_build_object('source_ref',jsonb_build_object('kind','MESSAGE_SET','ids',jsonb_build_array(17)),'path',jsonb_build_array('observed'),'operator','CONTAINS','expected','[{"message":{"message_id":17,"message_code":"MSG-B2B-AUTH-RECOVERY-REQUESTED","body_template":"Si existe una cuenta asociada a ese correo, recibirás un código de verificación para continuar con la recuperación."},"screen_links":[{"pantalla_id":56,"context_key":"RECOVERY_OTP_ENTRY_NOTICE"}]}]'::jsonb),
      jsonb_build_object('source_ref',jsonb_build_object('kind','SCREEN_CANONICAL_GRAPH','pantalla_id',56),'path',jsonb_build_array('observed','canonical_contract','fields'),'operator','CONTAINS','expected','[{"field_id":306,"validations":[{"validation_id":101,"message":null},{"validation_id":102,"message":null}]}]'::jsonb));
    when 'DEPENDENCIES' then specs:=jsonb_build_array(jsonb_build_object('source_ref',jsonb_build_object('kind','SCREEN_CANONICAL_GRAPH','pantalla_id',56),'path',jsonb_build_array('observed','canonical_contract','context','screen','dependencies'),'operator','CONTAINS','expected','["SEC-B2B-PASSWORD-CREDENTIAL","SEC-B2B-AUTH-PROVIDER-ARCHITECTURE","SEC-B2B-AUTH-FAIL-CLOSED","OTP_POL_B2B_AUTH_EMAIL_BREVO"]'::jsonb));
    when 'RUNTIME_CONFIG' then specs:=jsonb_build_array(jsonb_build_object('source_ref',jsonb_build_object('kind','SCREEN_CANONICAL_GRAPH','pantalla_id',56),'path',jsonb_build_array('observed','canonical_contract','rules'),'operator','CONTAINS','expected','[{"rule_code":"B2B-RULE-AUTH-037","config":{"delivery_provider":"BREVO","delivery_provider_status":"PENDING_CREDENTIALS_IMPLEMENTATION","production_authorized":false,"server_side_generation":"REQUIRED","server_side_verification":"REQUIRED"}}]'::jsonb));
    when 'VISUAL_EVIDENCE' then specs:=jsonb_build_array(jsonb_build_object('source_ref',jsonb_build_object('kind','CURRENT_VISUAL_ARTIFACT','pantalla_id',56),'path',jsonb_build_array('observed'),'operator','CONTAINS','expected','[{"artifact":{"id":14,"pantalla_id":56,"artifact_code":"B2B-AUTH-006-DESKTOP-LIGHT-CANDIDATO-VISUAL-V01","mime_type":"image/png","is_current":true,"storage_provider":"GOOGLE_DRIVE","storage_object_path":"18T1XH6oMavtbECVFu_IstKM8e_GIO38B"}}]'::jsonb));
    else specs:=null;
  end case;
  if specs is not null then return programacion.fn_input_rebind_assertion_specs(p_run_id,p_family_code,specs); end if;
  for olda in select x.value from programacion.input_family_assessments a cross join lateral jsonb_array_elements(a.validator_evidence->'assertions') x(value) where a.run_id=p_seed_run_id and a.family_code=p_family_code loop
    tpl:=olda-'actual'-'result'-'source_observed_sha256'; if tpl->'source_ref' ? 'pantalla_id' then tpl:=jsonb_set(tpl,'{source_ref,pantalla_id}','56'::jsonb,true); end if;
    reb:=programacion.fn_input_rebind_assertion(p_run_id,p_family_code,tpl); if reb->>'result'<>'PASS' then raise exception 'AUTH006_INHERITED_ASSERTION_FAILED family=% source=% path=% expected=% actual=%',p_family_code,reb->'source_ref',reb->'path',reb->'expected',reb->'actual'; end if; outj:=outj||jsonb_build_array(reb);
  end loop;
  if jsonb_array_length(outj)=0 then raise exception 'AUTH006_ASSERTIONS_EMPTY:%',p_family_code; end if;
  return outj;
end$$;

do $$
declare a record; v_run bigint; v_sources jsonb; v_sev text; v_app text; v_cov text; v_well text; v_story text; v_impl text; v_qa text; v_prod text; v_rat text; v_block jsonb; v_cur text; v_val text; v_sha text; v_assert jsonb; v_design_open int; v_security_open int;
begin
  v_cur:='INPUT_CURATOR:v0.5r1-auth006-v511-r14-'||substr(md5(random()::text||clock_timestamp()::text),1,8);
  insert into programacion.input_readiness_runs(version_id,pantalla_id,universe_rule_id,supersedes_run_id,scope,universe_snapshot_sha256,family_count,status,curator_identity,curator_component_id,contract_version)
  select version_id,56,universe_rule_id,null,jsonb_build_object('mode','CANDIDATE_V511_RECOVERY_OTP_CONTEXTUAL','module_code','B2B_AUTENTICACION','screen_code','B2B-AUTH-006','app_shell_code','B2B_APP_SHELL','research_basis','IGA_2026','authority_policy','INDEPENDENT_EKB_FOR_GOVERNANCE','remediation','AUDIT_20260819_R14_AUTH006'),universe_snapshot_sha256,family_count,'CURATING',v_cur,curator_component_id,5 from programacion.input_readiness_runs where id=100 returning id into v_run;
  select count(*) into v_design_open from jsonb_array_elements(programacion.fn_input_subject_depth_expected(56,'DESIGN_SYSTEM')) s where s->>'status' not in ('COMPLETE','NOT_APPLICABLE');
  select count(*) into v_security_open from jsonb_array_elements(programacion.fn_input_security_threat_expected(56)) t where t->>'status' not in ('COMPLETE','NOT_APPLICABLE');
  for a in select * from programacion.input_family_assessments where run_id=100 order by family_code loop
    select coalesce(jsonb_agg(case when x.value ? 'pantalla_id' then jsonb_set(x.value,'{pantalla_id}','56'::jsonb,true) else x.value end),'[]'::jsonb) into v_sources from jsonb_array_elements(a.source_refs) x(value);
    v_sev:=a.severity;v_app:=a.applicability;v_cov:=a.coverage_status;v_well:=a.well_defined_status;v_story:=a.story_ready_status;v_impl:=a.implementation_ready_status;v_qa:=a.qa_ready_status;v_prod:=a.production_ready_status;v_rat:=a.rationale;v_block:=a.blockers;
    if a.family_code='SCREEN_IDENTITY' then v_sev:='P4';v_app:='APPLICABLE';v_cov:='COMPLETE';v_well:='COMPLETE';v_story:='READY';v_impl:='READY';v_qa:='READY';v_prod:='READY';v_rat:='Screen 56 is canonically identified as B2B-AUTH-006 / Verificar recuperación in B2B_AUTENTICACION.';v_block:='[]'::jsonb;
    elsif a.family_code='OBJECTIVE_OUTCOMES' then v_sev:='P4';v_app:='APPLICABLE';v_cov:='COMPLETE';v_well:='COMPLETE';v_story:='READY';v_impl:='READY';v_qa:='READY';v_prod:='READY';v_rat:='Canonical objective explicitly limits successful recovery OTP verification to PASSWORD_UPDATE_ONLY before B2B-AUTH-003.';v_block:='[]'::jsonb;
    elsif a.family_code='FIELDS' then v_sev:='P4';v_app:='APPLICABLE';v_cov:='COMPLETE';v_well:='COMPLETE';v_story:='READY';v_impl:='READY';v_qa:='READY';v_prod:='READY';v_rat:='Field 306 is explicit, sensitive/transient, policy-driven and bound to otp_pin.';v_block:='[]'::jsonb;
    elsif a.family_code='VALIDATIONS' then v_sev:='P4';v_app:='APPLICABLE';v_cov:='COMPLETE';v_well:='COMPLETE';v_story:='READY';v_impl:='READY';v_qa:='READY';v_prod:='READY';v_rat:='Required and OTP-policy validations are explicit; numeric thresholds are delegated to otp_politicas rather than duplicated.';v_block:='[]'::jsonb;
    elsif a.family_code='ACTIONS' then v_sev:='P4';v_app:='APPLICABLE';v_cov:='COMPLETE';v_well:='COMPLETE';v_story:='READY';v_impl:='READY';v_qa:='READY';v_prod:='READY';v_rat:='Verify/resend/success-scope behavior is explicitly defined by AUTH-037/038; implementation dependency is tracked separately in API/RUNTIME.';v_block:='[]'::jsonb;
    elsif a.family_code='ROUTING_NAVIGATION' then v_sev:='P4';v_app:='APPLICABLE';v_cov:='COMPLETE';v_well:='COMPLETE';v_story:='READY';v_impl:='READY';v_qa:='READY';v_prod:='READY';v_sources:=jsonb_build_array(jsonb_build_object('kind','ROUTE_SET','ids',jsonb_build_array(11)),jsonb_build_object('kind','SCREEN_RULE_SET','pantalla_id',56));v_rat:='Route 11 is canonical for recovery verification and AUTH-029 fixes screen56->PASSWORD_UPDATE screen53 while denying client context promotion.';v_block:='[]'::jsonb;
    elsif a.family_code='PROFILES' then v_sev:='P4';v_app:='NOT_APPLICABLE';v_cov:='NOT_APPLICABLE';v_well:='NOT_APPLICABLE';v_story:='NOT_APPLICABLE';v_impl:='NOT_APPLICABLE';v_qa:='NOT_APPLICABLE';v_prod:='NOT_APPLICABLE';v_sources:=jsonb_build_array(jsonb_build_object('kind','SCREEN_RULE_SET','pantalla_id',56));v_rat:='Recovery OTP verification is governed by the one-time recovery context and eligibility rules, not a screen profile matrix; canonical profiles array is empty.';v_block:='[]'::jsonb;
    elsif a.family_code='SESSION' then v_sev:='P4';v_app:='NOT_APPLICABLE';v_cov:='NOT_APPLICABLE';v_well:='NOT_APPLICABLE';v_story:='NOT_APPLICABLE';v_impl:='NOT_APPLICABLE';v_qa:='NOT_APPLICABLE';v_prod:='NOT_APPLICABLE';v_sources:=jsonb_build_array(jsonb_build_object('kind','SCREEN_RULE_SET','pantalla_id',56));v_rat:='Positive authority: AUTH-037 operational_session_creation=DENY and AUTH-029 operational_authorization_before_completion=DENY. Recovery OTP cannot create an operational session.';v_block:='[]'::jsonb;
    elsif a.family_code='MFA_OTP_SSO' then v_sev:='P2';v_app:='APPLICABLE';v_cov:='COMPLETE';v_well:='COMPLETE';v_story:='READY';v_impl:='READY';v_qa:='NOT_READY';v_prod:='NOT_READY';v_sources:=jsonb_build_array(jsonb_build_object('kind','SCREEN_RULE_SET','pantalla_id',56),jsonb_build_object('kind','SECURITY_POLICY_SET','ids',jsonb_build_array(23)));v_rat:='OTP is applicable but explicitly not MFA: AUTH-037 binds OTP policy2/operation5/Brevo and denies MFA satisfaction. Inputs are sufficient to implement; provider credentials/QA remain downstream.';v_block:=jsonb_build_array(jsonb_build_object('code','BREVO_CREDENTIALS_IMPLEMENTATION_QA_PENDING','source_ref','B2B-RULE-AUTH-037'));
    elsif a.family_code='PRIVACY_PII' then v_sev:='P4';v_app:='APPLICABLE';v_cov:='COMPLETE';v_well:='COMPLETE';v_story:='READY';v_impl:='READY';v_qa:='READY';v_prod:='READY';v_rat:='OTP field and AUTH-037 both deny logs/analytics; field is SENSITIVE/TRANSIENT/MASK_FULL.';v_block:='[]'::jsonb;
    elsif a.family_code='ERRORS' then v_sev:='P0';v_app:='APPLICABLE';v_cov:='PARTIAL';v_well:='BLOCKED';v_story:='BLOCKED';v_impl:='BLOCKED';v_qa:='BLOCKED';v_prod:='BLOCKED';v_sources:=jsonb_build_array(jsonb_build_object('kind','SCREEN_RULE_SET','pantalla_id',56),jsonb_build_object('kind','ERROR_SET','ids',jsonb_build_array(39)));v_rat:='AUTH-029 points invalid recovery to error39, but error39 still describes an invalid/expired recovery link and asks for another link, conflicting with the current email OTP code flow.';v_block:=jsonb_build_array(jsonb_build_object('code','RECOVERY_ERROR_COPY_SEMANTIC_CONFLICT','rule','B2B-RULE-AUTH-029','error_id',39,'current_title','Enlace de recuperación no válido','required_decision','Define canonical invalid/expired OTP recovery error copy and action.'));
    elsif a.family_code='UI_MESSAGES' then v_sev:='P1';v_app:='APPLICABLE';v_cov:='PARTIAL';v_well:='PARTIAL';v_story:='READY';v_impl:='NOT_READY';v_qa:='BLOCKED';v_prod:='BLOCKED';v_sources:=jsonb_build_array(jsonb_build_object('kind','SCREEN_RULE_SET','pantalla_id',56),jsonb_build_object('kind','MESSAGE_SET','ids',jsonb_build_array(17)));v_rat:='Message17 correctly introduces code verification, but field validations101/102 have no canonical user messages and the invalid-recovery error copy is conflicting.';v_block:=jsonb_build_array(jsonb_build_object('code','FIELD_VALIDATION_MESSAGES_MISSING','validation_ids',jsonb_build_array(101,102)),jsonb_build_object('code','RECOVERY_ERROR_COPY_CONFLICT','error_id',39));
    elsif a.family_code='DEPENDENCIES' then v_sev:='P4';v_app:='APPLICABLE';v_cov:='COMPLETE';v_well:='COMPLETE';v_story:='READY';v_impl:='READY';v_qa:='READY';v_prod:='READY';v_sources:=jsonb_build_array(jsonb_build_object('kind','SCREEN','pantalla_id',56));v_rat:='Canonical dependencies are explicit: password credential policy, provider architecture/fail-closed and recovery email OTP policy.';v_block:='[]'::jsonb;
    elsif a.family_code='RUNTIME_CONFIG' then v_sev:='P1';v_app:='APPLICABLE';v_cov:='PARTIAL';v_well:='PARTIAL';v_story:='READY';v_impl:='NOT_READY';v_qa:='NOT_READY';v_prod:='NOT_READY';v_sources:=jsonb_build_array(jsonb_build_object('kind','SECURITY_POLICY_SET','ids',jsonb_build_array(23)),jsonb_build_object('kind','SCREEN_RULE_SET','pantalla_id',56));v_rat:='Brevo/provider architecture is identified, but delivery_provider_status remains PENDING_CREDENTIALS_IMPLEMENTATION and production_authorized=false.';v_block:=jsonb_build_array(jsonb_build_object('code','BREVO_PROVIDER_CREDENTIALS_IMPLEMENTATION_PENDING','source_ref','B2B-RULE-AUTH-037'));
    elsif a.family_code='VISUAL_EVIDENCE' then v_sev:='P1';v_app:='APPLICABLE';v_cov:='PARTIAL';v_well:='COMPLETE';v_story:='READY';v_impl:='NOT_READY';v_qa:='BLOCKED';v_prod:='BLOCKED';v_sources:=jsonb_build_array(jsonb_build_object('kind','CURRENT_VISUAL_ARTIFACT','pantalla_id',56));v_rat:='Current Web screenshot artifact14 exists and its Google Drive binary was directly verified, but tablet/app current evidence and governed external-binary resolver coverage are incomplete.';v_block:=jsonb_build_array(jsonb_build_object('code','VISUAL_VARIANT_EVIDENCE_INCOMPLETE','available_variant','DESKTOP_LIGHT','required_followup','TABLET_APP_OR_CANONICAL_VARIANT_EVIDENCE'));
    elsif a.family_code='DESIGN_SYSTEM' then v_sev:='P1';v_app:='APPLICABLE';v_cov:='PARTIAL';v_well:='PARTIAL';v_story:='READY';v_impl:='NOT_READY';v_qa:='BLOCKED';v_prod:='BLOCKED';v_rat:='otp_pin binding is resolvable, but input typography and label typography are missing, all three variant layout bindings are missing, and the field source_note still says semantic component pending.';v_block:=jsonb_build_array(jsonb_build_object('code','DESIGN_SUBJECT_DEPTH_INCOMPLETE','open_subject_count',v_design_open),jsonb_build_object('code','VARIANT_LAYOUT_BINDING_MISSING','count',3),jsonb_build_object('code','FIELD_SEMANTIC_COMPONENT_NOTE_STALE_OR_PENDING','field_id',306),jsonb_build_object('code','SCREEN_ELEMENT_INVENTORY_MISSING','count',0));
    elsif a.family_code='SECURITY' then v_sev:='P1';v_app:='APPLICABLE';v_cov:='PARTIAL';v_well:='PARTIAL';v_story:='READY';v_impl:='NOT_READY';v_qa:='NOT_READY';v_prod:='NOT_READY';v_sources:=jsonb_build_array(jsonb_build_object('kind','SCREEN_RULE_SET','pantalla_id',56),jsonb_build_object('kind','SECURITY_POLICY_SET','ids',jsonb_build_array(23)));v_rat:='RECOVERY_OTP_VERIFY field handling is complete, but the contextual 30-threat matrix still has open/partial/unresolved controls. Recovery OTP explicitly cannot satisfy MFA or create an operational session.';v_block:=jsonb_build_array(jsonb_build_object('code','SECURITY_THREAT_MATRIX_INCOMPLETE','open_or_partial_count',v_security_open,'capability_profile','RECOVERY_OTP_VERIFY'),jsonb_build_object('code','BREVO_PROVIDER_CREDENTIALS_IMPLEMENTATION_PENDING','source_ref','B2B-RULE-AUTH-037'));
    end if;
    insert into programacion.input_family_assessments(run_id,family_code,severity,applicability,coverage_status,well_defined_status,story_ready_status,implementation_ready_status,qa_ready_status,production_ready_status,source_refs,rationale,blockers,negative_requirements,test_obligations,curator_evidence,curator_sha256)
    values(v_run,a.family_code,v_sev,v_app,v_cov,v_well,v_story,v_impl,v_qa,v_prod,v_sources,v_rat,v_block,a.negative_requirements,a.test_obligations,jsonb_build_object('component_id',46,'execution_id',gen_random_uuid()::text,'execution_mode','INDEPENDENT_CURATOR','contract_revision','5.11','seed_criteria_run_id',100,'remediation_revision','AUDIT_20260819_R14_AUTH006','direct_source_readback',true),repeat('0',64));
  end loop;
  v_val:='INPUT_VALIDATOR:v0.5r1-auth006-v511-r14-'||substr(md5(random()::text||clock_timestamp()::text),1,8);
  update programacion.input_readiness_runs set status='VALIDATING',validator_identity=v_val,validator_component_id=47 where id=v_run;
  select source_snapshot_sha256 into v_sha from programacion.input_readiness_runs where id=v_run;
  for a in select * from programacion.input_family_assessments where run_id=v_run order by family_code loop
    v_assert:=programacion.fn_input_auth006_build_assertions(v_run,100,a.family_code);
    update programacion.input_family_assessments set validator_outcome='PASS',validator_findings='[]'::jsonb,validator_identity=v_val,validator_evidence=jsonb_build_object('component_id',47,'execution_id',gen_random_uuid()::text,'validated_curator_execution_id',a.curator_evidence->>'execution_id','execution_mode','INDEPENDENT_VALIDATOR','direct_source_readback',true,'contract_revision','5.11','source_snapshot_sha256',v_sha,'curator_sha256',a.curator_sha256,'semantic_depth_sha256',a.semantic_depth_sha256,'assertions',v_assert) where id=a.id;
  end loop;
  update programacion.input_readiness_runs set status='COMPLETED' where id=v_run;
end$$;

do $$
declare rec record; a record; v_new bigint; v_cur text; v_val text; v_sha text; v_assert jsonb;
begin
 for rec in select * from (values (51,97::bigint),(52,98::bigint),(53,99::bigint),(54,100::bigint),(55,101::bigint)) v(pantalla_id,parent_run_id) loop
  v_cur:='INPUT_CURATOR:v0.5r1-auth-'||rec.pantalla_id||'-v511-r14-'||substr(md5(random()::text||clock_timestamp()::text),1,8);
  insert into programacion.input_readiness_runs(version_id,pantalla_id,universe_rule_id,supersedes_run_id,scope,universe_snapshot_sha256,family_count,status,curator_identity,curator_component_id,contract_version)
  select version_id,pantalla_id,universe_rule_id,id,scope||jsonb_build_object('mode','CANDIDATE_V511_MODULE_SUCCESSOR','parent_run_id',id,'remediation','AUDIT_20260819_R14_MODULE_V511'),universe_snapshot_sha256,family_count,'CURATING',v_cur,curator_component_id,5 from programacion.input_readiness_runs where id=rec.parent_run_id returning id into v_new;
  for a in select * from programacion.input_family_assessments where run_id=rec.parent_run_id order by family_code loop
   insert into programacion.input_family_assessments(run_id,family_code,severity,applicability,coverage_status,well_defined_status,story_ready_status,implementation_ready_status,qa_ready_status,production_ready_status,source_refs,rationale,blockers,negative_requirements,test_obligations,curator_evidence,curator_sha256)
   values(v_new,a.family_code,a.severity,a.applicability,a.coverage_status,a.well_defined_status,a.story_ready_status,a.implementation_ready_status,a.qa_ready_status,a.production_ready_status,a.source_refs,a.rationale||' | V5.11 contract/profile successor readback.',a.blockers,a.negative_requirements,a.test_obligations,jsonb_build_object('component_id',46,'execution_id',gen_random_uuid()::text,'execution_mode','INDEPENDENT_CURATOR','contract_revision','5.11','parent_run_id',rec.parent_run_id,'parent_assessment_id',a.id,'remediation_revision','AUDIT_20260819_R14_MODULE_V511','direct_source_readback',true),repeat('0',64));
  end loop;
  v_val:='INPUT_VALIDATOR:v0.5r1-auth-'||rec.pantalla_id||'-v511-r14-'||substr(md5(random()::text||clock_timestamp()::text),1,8);
  update programacion.input_readiness_runs set status='VALIDATING',validator_identity=v_val,validator_component_id=47 where id=v_new;
  select source_snapshot_sha256 into v_sha from programacion.input_readiness_runs where id=v_new;
  for a in select * from programacion.input_family_assessments where run_id=v_new order by family_code loop
   v_assert:=programacion.fn_input_v58_build_assertions(v_new,rec.parent_run_id,a.family_code);
   update programacion.input_family_assessments set validator_outcome='PASS',validator_findings='[]'::jsonb,validator_identity=v_val,validator_evidence=jsonb_build_object('component_id',47,'execution_id',gen_random_uuid()::text,'validated_curator_execution_id',a.curator_evidence->>'execution_id','execution_mode','INDEPENDENT_VALIDATOR','direct_source_readback',true,'contract_revision','5.11','source_snapshot_sha256',v_sha,'curator_sha256',a.curator_sha256,'semantic_depth_sha256',a.semantic_depth_sha256,'assertions',v_assert) where id=a.id;
  end loop;
  update programacion.input_readiness_runs set status='COMPLETED' where id=v_new;
 end loop;
end$$;