DO $pre$ DECLARE v text; BEGIN
 SELECT max(version) INTO v FROM supabase_migrations.schema_migrations;
 IF v IS DISTINCT FROM '20260914061449' THEN RAISE EXCEPTION 'S30_QUALIFICATION_LEDGER_DRIFT:%',v; END IF;
 IF NOT EXISTS (SELECT 1 FROM public.lf_operation_execution WHERE execution_id='EXEC-S30-STRATEGY-QUALIFICATION-FRAMEWORK-20260914-001' AND operation_code='ACTUALIZACION_DB_LF' AND status='IN_PROGRESS') THEN RAISE EXCEPTION 'S30_QUALIFICATION_EXECUTION_BINDING_INVALID'; END IF;
END $pre$;

INSERT INTO lf_ops.estados_catalogo(state_code,entity_type,state_name,description,is_initial,is_terminal,status,source_decision_id)
SELECT * FROM (VALUES
 ('QUAL_UNQUALIFIED','QUALIFICATION_LIFECYCLE','UNQUALIFIED','No qualification has started for the exact subject revision.',true,false,'VIGENTE','S30-STRATEGY-QUALIFICATION-20260914'),
 ('QUAL_QUALIFYING','QUALIFICATION_LIFECYCLE','QUALIFYING','Qualification is running or awaiting required review.',false,false,'VIGENTE','S30-STRATEGY-QUALIFICATION-20260914'),
 ('QUAL_QUALIFIED','QUALIFICATION_LIFECYCLE','QUALIFIED','All required suites and reviews passed for the exact subject revision.',false,false,'VIGENTE','S30-STRATEGY-QUALIFICATION-20260914'),
 ('QUAL_FAILED','QUALIFICATION_LIFECYCLE','FAILED','At least one required qualification obligation failed.',false,false,'VIGENTE','S30-STRATEGY-QUALIFICATION-20260914'),
 ('QUAL_STALE','QUALIFICATION_LIFECYCLE','STALE','A formerly qualified subject changed or its requirement set changed.',false,false,'VIGENTE','S30-STRATEGY-QUALIFICATION-20260914')
) v(state_code,entity_type,state_name,description,is_initial,is_terminal,status,source_decision_id)
WHERE NOT EXISTS (SELECT 1 FROM lf_ops.estados_catalogo e WHERE e.state_code=v.state_code);

INSERT INTO lf_ops.estados_transiciones(transition_code,entity_type,from_state_code,to_state_code,action_code,requires_comment,requires_idempotency_key,audit_required,condition_config,status,source_decision_id,from_state_id,to_state_id)
SELECT x.transition_code,x.entity_type,x.from_state_code,x.to_state_code,x.action_code,false,true,true,jsonb_build_object('table_driven',true),'VIGENTE','S30-STRATEGY-QUALIFICATION-20260914',f.state_id,t.state_id
FROM (VALUES
 ('TR_QUAL_UNQUALIFIED_QUALIFYING','QUALIFICATION_LIFECYCLE','QUAL_UNQUALIFIED','QUAL_QUALIFYING','START_QUALIFICATION'),
 ('TR_QUAL_QUALIFYING_QUALIFIED','QUALIFICATION_LIFECYCLE','QUAL_QUALIFYING','QUAL_QUALIFIED','PASS_QUALIFICATION'),
 ('TR_QUAL_QUALIFYING_FAILED','QUALIFICATION_LIFECYCLE','QUAL_QUALIFYING','QUAL_FAILED','FAIL_QUALIFICATION'),
 ('TR_QUAL_QUALIFIED_STALE','QUALIFICATION_LIFECYCLE','QUAL_QUALIFIED','QUAL_STALE','INVALIDATE_QUALIFICATION'),
 ('TR_QUAL_FAILED_QUALIFYING','QUALIFICATION_LIFECYCLE','QUAL_FAILED','QUAL_QUALIFYING','RETRY_QUALIFICATION'),
 ('TR_QUAL_STALE_QUALIFYING','QUALIFICATION_LIFECYCLE','QUAL_STALE','QUAL_QUALIFYING','RETRY_QUALIFICATION'),
 ('TR_STRATEGY_PLANNED_UPDATE','STRATEGY_LIFECYCLE','STRATEGY_PLANNED','STRATEGY_PLANNED','UPDATE_STRATEGY'),
 ('TR_STRATEGY_ACTIVE_UPDATE','STRATEGY_LIFECYCLE','STRATEGY_ACTIVE','STRATEGY_ACTIVE','UPDATE_STRATEGY'),
 ('TR_STRATEGY_ACTIVE_EXECUTION','STRATEGY_LIFECYCLE','STRATEGY_ACTIVE','STRATEGY_ACTIVE','START_EXECUTION')
) x(transition_code,entity_type,from_state_code,to_state_code,action_code)
JOIN lf_ops.estados_catalogo f ON f.state_code=x.from_state_code AND f.entity_type=x.entity_type
JOIN lf_ops.estados_catalogo t ON t.state_code=x.to_state_code AND t.entity_type=x.entity_type
ON CONFLICT (entity_type,from_state_code,to_state_code,action_code) DO NOTHING;

CREATE OR REPLACE FUNCTION public.lf_lifecycle_initial_state_v1(p_entity_type text)
RETURNS text LANGUAGE plpgsql STABLE SET search_path TO 'pg_catalog','public' AS $fn$
DECLARE v_count int; v_state text; BEGIN
 SELECT count(*),min(state_code) INTO v_count,v_state FROM lf_ops.estados_catalogo WHERE entity_type=p_entity_type AND status='VIGENTE' AND is_initial;
 IF v_count<>1 THEN RAISE EXCEPTION 'LF_LIFECYCLE_INITIAL_STATE_NOT_UNIQUE:%:%',p_entity_type,v_count; END IF; RETURN v_state;
END $fn$;

CREATE OR REPLACE FUNCTION public.lf_lifecycle_transition_spec_v1(p_entity_type text,p_from_state text,p_action_code text)
RETURNS jsonb LANGUAGE plpgsql STABLE SET search_path TO 'pg_catalog','public' AS $fn$
DECLARE v_count int; v_spec jsonb; BEGIN
 SELECT count(*) INTO v_count FROM lf_ops.estados_transiciones t JOIN lf_ops.estados_catalogo s ON s.state_code=t.to_state_code AND s.entity_type=t.entity_type AND s.status='VIGENTE' WHERE t.entity_type=p_entity_type AND t.from_state_code=p_from_state AND t.action_code=p_action_code AND t.status='VIGENTE';
 IF v_count<>1 THEN RAISE EXCEPTION 'LF_LIFECYCLE_ACTION_TRANSITION_NOT_UNIQUE:%:%:%:%',p_entity_type,p_from_state,p_action_code,v_count; END IF;
 SELECT to_jsonb(t)||jsonb_build_object('target_is_terminal',s.is_terminal) INTO v_spec FROM lf_ops.estados_transiciones t JOIN lf_ops.estados_catalogo s ON s.state_code=t.to_state_code AND s.entity_type=t.entity_type AND s.status='VIGENTE' WHERE t.entity_type=p_entity_type AND t.from_state_code=p_from_state AND t.action_code=p_action_code AND t.status='VIGENTE' LIMIT 1; RETURN v_spec;
END $fn$;
CREATE OR REPLACE FUNCTION public.lf_lifecycle_resolve_transition_v1(p_entity_type text,p_from_state text,p_action_code text)
RETURNS text LANGUAGE sql STABLE SET search_path TO 'pg_catalog','public' AS $fn$ SELECT public.lf_lifecycle_transition_spec_v1(p_entity_type,p_from_state,p_action_code)->>'to_state_code' $fn$;
CREATE OR REPLACE FUNCTION public.lf_lifecycle_action_target_state_v1(p_entity_type text,p_action_code text)
RETURNS text LANGUAGE plpgsql STABLE SET search_path TO 'pg_catalog','public' AS $fn$
DECLARE v_count int; v_state text; BEGIN SELECT count(DISTINCT t.to_state_code),min(t.to_state_code) INTO v_count,v_state FROM lf_ops.estados_transiciones t JOIN lf_ops.estados_catalogo s ON s.state_code=t.to_state_code AND s.entity_type=t.entity_type AND s.status='VIGENTE' WHERE t.entity_type=p_entity_type AND t.action_code=p_action_code AND t.status='VIGENTE'; IF v_count<>1 THEN RAISE EXCEPTION 'LF_LIFECYCLE_ACTION_TARGET_NOT_UNIQUE:%:%:%',p_entity_type,p_action_code,v_count; END IF; RETURN v_state; END $fn$;
CREATE OR REPLACE FUNCTION public.lf_lifecycle_state_is_terminal_v1(p_entity_type text,p_state_code text)
RETURNS boolean LANGUAGE sql STABLE SET search_path TO 'pg_catalog','public' AS $fn$ SELECT coalesce((SELECT is_terminal FROM lf_ops.estados_catalogo WHERE entity_type=p_entity_type AND state_code=p_state_code AND status='VIGENTE'),false) $fn$;

CREATE TABLE public.lf_strategy_test_characteristic_catalog(
 characteristic_code text PRIMARY KEY,description text NOT NULL,status text NOT NULL DEFAULT 'ACTIVE',created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),created_by_execution_id text NOT NULL DEFAULT 'UNKNOWN',updated_by_execution_id text
);
CREATE TABLE public.lf_strategy_test_characteristics(
 snapshot_id bigint NOT NULL REFERENCES public.lf_strategy_snapshots(id) ON UPDATE CASCADE ON DELETE RESTRICT,characteristic_code text NOT NULL REFERENCES public.lf_strategy_test_characteristic_catalog(characteristic_code) ON UPDATE CASCADE ON DELETE RESTRICT,enabled boolean,evidence_payload jsonb NOT NULL DEFAULT '{}'::jsonb,classified_at timestamptz,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),created_by_execution_id text NOT NULL DEFAULT 'UNKNOWN',updated_by_execution_id text,PRIMARY KEY(snapshot_id,characteristic_code)
);
CREATE TABLE public.lf_test_requirement_bindings(
 binding_code text PRIMARY KEY,subject_type text NOT NULL CHECK(subject_type IN ('OPERATION','STRATEGY')),subject_code text NOT NULL,characteristic_code text REFERENCES public.lf_strategy_test_characteristic_catalog(characteristic_code) ON UPDATE CASCADE ON DELETE RESTRICT,suite_code text NOT NULL REFERENCES public.lf_test_suites(suite_code) ON UPDATE CASCADE ON DELETE RESTRICT,required boolean NOT NULL DEFAULT true,min_pass_rate numeric(6,5) NOT NULL DEFAULT 1.0 CHECK(min_pass_rate>=0 AND min_pass_rate<=1),false_pass_tolerance integer NOT NULL DEFAULT 0 CHECK(false_pass_tolerance>=0),independent_review_required boolean NOT NULL DEFAULT false,rollback_required boolean NOT NULL DEFAULT false,currentness_mode text NOT NULL DEFAULT 'EXACT_REVISION',activation_condition jsonb NOT NULL DEFAULT '{"type":"ALWAYS"}'::jsonb,effective_from timestamptz NOT NULL DEFAULT now(),status text NOT NULL DEFAULT 'PENDING',created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),created_by_execution_id text NOT NULL DEFAULT 'UNKNOWN',updated_by_execution_id text
);
CREATE INDEX idx_lf_test_requirement_bindings_subject ON public.lf_test_requirement_bindings(subject_type,subject_code,status,effective_from);
CREATE TABLE public.lf_qualification_receipts(
 qualification_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),subject_type text NOT NULL CHECK(subject_type IN ('OPERATION','STRATEGY')),subject_code text NOT NULL,subject_ref text,revision_sha256 text NOT NULL CHECK(revision_sha256 ~ '^[0-9a-f]{64}$'),classification_fingerprint text,lifecycle_state_code text NOT NULL REFERENCES lf_ops.estados_catalogo(state_code) ON UPDATE RESTRICT ON DELETE RESTRICT,suite_set_fingerprint text NOT NULL,suite_run_ids uuid[] NOT NULL DEFAULT '{}'::uuid[],independent_review_ref jsonb NOT NULL DEFAULT '{}'::jsonb,rollback_receipt jsonb NOT NULL DEFAULT '{}'::jsonb,findings jsonb NOT NULL DEFAULT '[]'::jsonb,qualified_at timestamptz,invalidated_at timestamptz,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),created_by_execution_id text NOT NULL DEFAULT 'UNKNOWN',updated_by_execution_id text
);
CREATE INDEX idx_lf_qualification_receipts_current ON public.lf_qualification_receipts(subject_type,subject_code,revision_sha256,lifecycle_state_code,created_at DESC);

CREATE OR REPLACE FUNCTION public.lf_operation_revision_sha256_v1(p_operation_code text)
RETURNS text LANGUAGE plpgsql STABLE SET search_path TO 'pg_catalog','public','extensions' AS $fn$
DECLARE r public.lf_operation_registry%rowtype; payload jsonb; BEGIN SELECT * INTO r FROM public.lf_operation_registry WHERE operation_code=p_operation_code; IF NOT FOUND THEN RAISE EXCEPTION 'LF_OPERATION_REVISION_TARGET_MISSING:%',p_operation_code; END IF; payload:=jsonb_build_object('registry',to_jsonb(r)-ARRAY['status','lifecycle_state_code','version','notes','created_at','updated_at','created_by_execution_id','updated_by_execution_id'],'contracts',coalesce((SELECT jsonb_agg(to_jsonb(c)-ARRAY['created_at','updated_at','created_by_execution_id','updated_by_execution_id'] ORDER BY c.contract_code) FROM public.lf_operation_contracts c WHERE c.operation_code=p_operation_code AND c.status IN ('ACTIVE_ENFORCEMENT','ACTIVE','ACTIVO')),'[]'::jsonb),'steps',coalesce((SELECT jsonb_agg(to_jsonb(s)-ARRAY['created_at','updated_at','created_by_execution_id','updated_by_execution_id'] ORDER BY coalesce(s.execution_order,s.step_order),s.step_id) FROM public.lf_operation_step_contracts s WHERE s.operation_code=p_operation_code AND s.status IN ('ACTIVE_ENFORCEMENT','ACTIVE','ACTIVO')),'[]'::jsonb),'judges',coalesce((SELECT jsonb_agg(to_jsonb(j)-ARRAY['created_at','updated_at','created_by_execution_id','updated_by_execution_id'] ORDER BY j.judge_code) FROM public.lf_operation_judges j WHERE j.operation_code=p_operation_code AND j.status IN ('ACTIVE_ENFORCEMENT','ACTIVE','ACTIVO')),'[]'::jsonb),'router',coalesce((SELECT jsonb_agg(to_jsonb(a)-ARRAY['created_at','updated_at'] ORDER BY a.asset_type,a.action_code) FROM public.lf_router_action_registry a WHERE a.operation_code=p_operation_code AND a.status='ACTIVE'),'[]'::jsonb)); RETURN encode(extensions.digest(convert_to(payload::text,'UTF8'),'sha256'),'hex'); END $fn$;
CREATE OR REPLACE FUNCTION public.lf_strategy_revision_sha256_from_json_v1(p_row jsonb)
RETURNS text LANGUAGE plpgsql IMMUTABLE SET search_path TO 'pg_catalog','public','extensions' AS $fn$
DECLARE v jsonb; m jsonb; BEGIN v:=coalesce(p_row,'{}'::jsonb)-ARRAY['lifecycle_state_code','evidence_refs','change_log','created_at','updated_at','created_by_execution_id','updated_by_execution_id']; m:=coalesce(v->'metadata','{}'::jsonb)-ARRAY['progress','strategy_close']; v:=jsonb_set(v,'{metadata}',m,true); RETURN encode(extensions.digest(convert_to(v::text,'UTF8'),'sha256'),'hex'); END $fn$;
CREATE OR REPLACE FUNCTION public.lf_strategy_revision_sha256_v1(p_snapshot_id bigint)
RETURNS text LANGUAGE plpgsql STABLE SET search_path TO 'pg_catalog','public' AS $fn$
DECLARE v jsonb; BEGIN SELECT to_jsonb(s) INTO v FROM public.lf_strategy_snapshots s WHERE s.id=p_snapshot_id; IF v IS NULL THEN RAISE EXCEPTION 'LF_STRATEGY_REVISION_TARGET_MISSING:%',p_snapshot_id; END IF; RETURN public.lf_strategy_revision_sha256_from_json_v1(v); END $fn$;
CREATE OR REPLACE FUNCTION public.lf_strategy_classification_fingerprint_v1(p_snapshot_id bigint)
RETURNS text LANGUAGE plpgsql STABLE SET search_path TO 'pg_catalog','public','extensions' AS $fn$
DECLARE v text; BEGIN SELECT string_agg(c.characteristic_code||'='||coalesce(c.enabled::text,'NULL'),'|' ORDER BY c.characteristic_code) INTO v FROM public.lf_strategy_test_characteristics c JOIN public.lf_strategy_test_characteristic_catalog k ON k.characteristic_code=c.characteristic_code AND k.status='ACTIVE' WHERE c.snapshot_id=p_snapshot_id; RETURN encode(extensions.digest(convert_to(coalesce(v,''),'UTF8'),'sha256'),'hex'); END $fn$;
CREATE OR REPLACE FUNCTION public.lf_test_requirement_applies_v1(p_binding_code text,p_subject_type text,p_subject_code text)
RETURNS boolean LANGUAGE plpgsql STABLE SET search_path TO 'pg_catalog','public' AS $fn$
DECLARE b public.lf_test_requirement_bindings%rowtype; typ text; sid bigint; BEGIN SELECT * INTO b FROM public.lf_test_requirement_bindings WHERE binding_code=p_binding_code; IF NOT FOUND OR b.subject_type<>p_subject_type OR (b.subject_code<>'*' AND b.subject_code<>p_subject_code) THEN RETURN false; END IF; typ:=upper(coalesce(b.activation_condition->>'type','ALWAYS')); IF typ='ALWAYS' THEN RETURN true; END IF; IF typ='CHARACTERISTIC_TRUE' AND p_subject_type='STRATEGY' THEN SELECT id INTO sid FROM public.lf_strategy_snapshots WHERE snapshot_code=p_subject_code ORDER BY id DESC LIMIT 1; IF sid IS NULL THEN RETURN false; END IF; RETURN EXISTS(SELECT 1 FROM public.lf_strategy_test_characteristics c WHERE c.snapshot_id=sid AND c.characteristic_code=coalesce(b.characteristic_code,b.activation_condition->>'characteristic_code') AND c.enabled IS TRUE); END IF; RETURN false; END $fn$;
CREATE OR REPLACE FUNCTION public.lf_required_test_suite_fingerprint_v1(p_subject_type text,p_subject_code text)
RETURNS text LANGUAGE plpgsql STABLE SET search_path TO 'pg_catalog','public','extensions' AS $fn$
DECLARE v text; BEGIN SELECT string_agg(b.binding_code||':'||b.suite_code||':'||b.currentness_mode||':'||b.min_pass_rate::text||':'||b.false_pass_tolerance::text||':'||b.independent_review_required::text,'|' ORDER BY b.binding_code) INTO v FROM public.lf_test_requirement_bindings b WHERE b.status='ACTIVE' AND b.required AND b.effective_from<=clock_timestamp() AND b.subject_type=p_subject_type AND (b.subject_code='*' OR b.subject_code=p_subject_code) AND public.lf_test_requirement_applies_v1(b.binding_code,p_subject_type,p_subject_code); RETURN encode(extensions.digest(convert_to(coalesce(v,''),'UTF8'),'sha256'),'hex'); END $fn$;
CREATE OR REPLACE FUNCTION public.lf_qualification_current_v1(p_subject_type text,p_subject_code text,p_revision_sha256 text)
RETURNS boolean LANGUAGE plpgsql STABLE SET search_path TO 'pg_catalog','public' AS $fn$
DECLARE q public.lf_qualification_receipts%rowtype; qs text; fp text; sid bigint; req_count int; BEGIN qs:=public.lf_lifecycle_action_target_state_v1('QUALIFICATION_LIFECYCLE','PASS_QUALIFICATION'); SELECT count(*) INTO req_count FROM public.lf_test_requirement_bindings b WHERE b.status='ACTIVE' AND b.required AND b.effective_from<=clock_timestamp() AND b.subject_type=p_subject_type AND (b.subject_code='*' OR b.subject_code=p_subject_code) AND public.lf_test_requirement_applies_v1(b.binding_code,p_subject_type,p_subject_code); IF req_count=0 THEN RETURN false; END IF; SELECT * INTO q FROM public.lf_qualification_receipts WHERE subject_type=p_subject_type AND subject_code=p_subject_code AND revision_sha256=p_revision_sha256 AND lifecycle_state_code=qs AND invalidated_at IS NULL ORDER BY qualified_at DESC NULLS LAST,created_at DESC LIMIT 1; IF NOT FOUND THEN RETURN false; END IF; fp:=public.lf_required_test_suite_fingerprint_v1(p_subject_type,p_subject_code); IF q.suite_set_fingerprint IS DISTINCT FROM fp THEN RETURN false; END IF; IF p_subject_type='STRATEGY' THEN SELECT id INTO sid FROM public.lf_strategy_snapshots WHERE snapshot_code=p_subject_code ORDER BY id DESC LIMIT 1; IF sid IS NULL OR q.classification_fingerprint IS DISTINCT FROM public.lf_strategy_classification_fingerprint_v1(sid) THEN RETURN false; END IF; END IF; IF EXISTS(SELECT 1 FROM public.lf_test_requirement_bindings b WHERE b.status='ACTIVE' AND b.required AND b.effective_from<=clock_timestamp() AND b.subject_type=p_subject_type AND (b.subject_code='*' OR b.subject_code=p_subject_code) AND public.lf_test_requirement_applies_v1(b.binding_code,p_subject_type,p_subject_code) AND NOT EXISTS(SELECT 1 FROM public.lf_test_suite_runs sr WHERE sr.suite_run_id=ANY(q.suite_run_ids) AND sr.suite_code=b.suite_code AND sr.status='PASSED' AND sr.metadata->>'subject_type'=p_subject_type AND sr.metadata->>'subject_code'=p_subject_code AND sr.metadata->>'revision_sha256'=p_revision_sha256)) THEN RETURN false; END IF; RETURN true; END $fn$;
CREATE OR REPLACE FUNCTION public.lf_qualification_gate_effective_from_v1(p_subject_type text)
RETURNS timestamptz LANGUAGE sql STABLE SET search_path TO 'pg_catalog','public' AS $fn$ SELECT min(effective_from) FROM public.lf_test_requirement_bindings WHERE subject_type=p_subject_type AND status='ACTIVE' AND required $fn$;

CREATE OR REPLACE FUNCTION public.lf_assign_initial_lifecycle_state_v1()
RETURNS trigger LANGUAGE plpgsql SET search_path TO 'pg_catalog','public' AS $fn$
DECLARE v_entity_type text:=TG_ARGV[0]; v_initial text; BEGIN v_initial:=public.lf_lifecycle_initial_state_v1(v_entity_type); IF NEW.lifecycle_state_code IS NULL OR btrim(NEW.lifecycle_state_code)='' THEN NEW.lifecycle_state_code:=v_initial; ELSIF NEW.lifecycle_state_code<>v_initial THEN RAISE EXCEPTION 'LF_LIFECYCLE_INSERT_MUST_START_INITIAL:%:%:%',v_entity_type,NEW.lifecycle_state_code,v_initial; END IF; RETURN NEW; END $fn$;
CREATE OR REPLACE FUNCTION public.lf_enforce_lifecycle_transition_v1()
RETURNS trigger LANGUAGE plpgsql SET search_path TO 'pg_catalog','public' AS $fn$
DECLARE v_entity_type text:=TG_ARGV[0]; v_spec jsonb; v_subject_type text; v_subject_code text; v_revision text; v_new jsonb:=to_jsonb(NEW); BEGIN IF NEW.lifecycle_state_code IS NOT DISTINCT FROM OLD.lifecycle_state_code THEN RETURN NEW; END IF; SELECT to_jsonb(t) INTO v_spec FROM lf_ops.estados_transiciones t WHERE t.entity_type=v_entity_type AND t.from_state_code=OLD.lifecycle_state_code AND t.to_state_code=NEW.lifecycle_state_code AND t.status='VIGENTE'; IF v_spec IS NULL THEN RAISE EXCEPTION 'LF_LIFECYCLE_TRANSITION_NOT_ALLOWED:%:%:%',v_entity_type,OLD.lifecycle_state_code,NEW.lifecycle_state_code; END IF; IF coalesce((v_spec->'condition_config'->>'requires_qualification')::boolean,false) THEN IF v_entity_type='OPERATION_LIFECYCLE' THEN v_subject_type:='OPERATION'; v_subject_code:=v_new->>'operation_code'; v_revision:=public.lf_operation_revision_sha256_v1(v_subject_code); ELSIF v_entity_type='STRATEGY_LIFECYCLE' THEN v_subject_type:='STRATEGY'; v_subject_code:=v_new->>'snapshot_code'; v_revision:=public.lf_strategy_revision_sha256_v1((v_new->>'id')::bigint); ELSE RAISE EXCEPTION 'LF_LIFECYCLE_QUALIFICATION_SCOPE_UNSUPPORTED:%',v_entity_type; END IF; IF NOT public.lf_qualification_current_v1(v_subject_type,v_subject_code,v_revision) THEN RAISE EXCEPTION 'LF_LIFECYCLE_QUALIFICATION_REQUIRED:%:%:%',v_subject_type,v_subject_code,v_revision; END IF; END IF; RETURN NEW; END $fn$;

ALTER TABLE public.lf_operation_registry ALTER COLUMN lifecycle_state_code DROP DEFAULT;
ALTER TABLE public.lf_strategy_snapshots ALTER COLUMN lifecycle_state_code DROP DEFAULT;
DROP TRIGGER IF EXISTS trg_lf_operation_registry_initial_lifecycle_v1 ON public.lf_operation_registry;
CREATE TRIGGER trg_lf_operation_registry_initial_lifecycle_v1 BEFORE INSERT ON public.lf_operation_registry FOR EACH ROW EXECUTE FUNCTION public.lf_assign_initial_lifecycle_state_v1('OPERATION_LIFECYCLE');
DROP TRIGGER IF EXISTS trg_lf_strategy_snapshots_initial_lifecycle_v1 ON public.lf_strategy_snapshots;
CREATE TRIGGER trg_lf_strategy_snapshots_initial_lifecycle_v1 BEFORE INSERT ON public.lf_strategy_snapshots FOR EACH ROW EXECUTE FUNCTION public.lf_assign_initial_lifecycle_state_v1('STRATEGY_LIFECYCLE');
DROP TRIGGER IF EXISTS trg_lf_qualification_receipts_initial_lifecycle_v1 ON public.lf_qualification_receipts;
CREATE TRIGGER trg_lf_qualification_receipts_initial_lifecycle_v1 BEFORE INSERT ON public.lf_qualification_receipts FOR EACH ROW EXECUTE FUNCTION public.lf_assign_initial_lifecycle_state_v1('QUALIFICATION_LIFECYCLE');
DROP TRIGGER IF EXISTS trg_lf_qualification_receipts_lifecycle_transition_v1 ON public.lf_qualification_receipts;
CREATE TRIGGER trg_lf_qualification_receipts_lifecycle_transition_v1 BEFORE UPDATE OF lifecycle_state_code ON public.lf_qualification_receipts FOR EACH ROW EXECUTE FUNCTION public.lf_enforce_lifecycle_transition_v1('QUALIFICATION_LIFECYCLE');

INSERT INTO public.lf_strategy_test_characteristic_catalog(characteristic_code,description,status,created_by_execution_id) VALUES
 ('WRITES_DATA','Strategy may write persistent business or governance data.','ACTIVE','EXEC-S30-STRATEGY-QUALIFICATION-FRAMEWORK-20260914-001'),('BUSINESS_EFFECTS','Strategy may dispatch externally observable business effects.','ACTIVE','EXEC-S30-STRATEGY-QUALIFICATION-FRAMEWORK-20260914-001'),('EXTERNAL_INTEGRATION','Strategy depends on an external system or connector.','ACTIVE','EXEC-S30-STRATEGY-QUALIFICATION-FRAMEWORK-20260914-001'),('SCHEDULER','Strategy includes scheduled or recurring execution.','ACTIVE','EXEC-S30-STRATEGY-QUALIFICATION-FRAMEWORK-20260914-001'),('FINANCIAL_DECISION','Strategy can influence financial or monetary decisions.','ACTIVE','EXEC-S30-STRATEGY-QUALIFICATION-FRAMEWORK-20260914-001'),('USES_MODEL','Strategy requires model-based semantic decisions.','ACTIVE','EXEC-S30-STRATEGY-QUALIFICATION-FRAMEWORK-20260914-001'),('RUNTIME_CHANGE','Strategy can alter runtime enablement or execution mode.','ACTIVE','EXEC-S30-STRATEGY-QUALIFICATION-FRAMEWORK-20260914-001'),('HIGH_RISK','Strategy has high-risk blast radius requiring independent review.','ACTIVE','EXEC-S30-STRATEGY-QUALIFICATION-FRAMEWORK-20260914-001');
CREATE OR REPLACE FUNCTION public.lf_strategy_characteristics_seed_v1() RETURNS trigger LANGUAGE plpgsql SET search_path TO 'pg_catalog','public' AS $fn$ BEGIN INSERT INTO public.lf_strategy_test_characteristics(snapshot_id,characteristic_code,enabled,created_by_execution_id) SELECT NEW.id,c.characteristic_code,NULL,coalesce(NEW.created_by_execution_id,'UNKNOWN') FROM public.lf_strategy_test_characteristic_catalog c WHERE c.status='ACTIVE' ON CONFLICT(snapshot_id,characteristic_code) DO NOTHING; RETURN NEW; END $fn$;
DROP TRIGGER IF EXISTS trg_lf_strategy_characteristics_seed_v1 ON public.lf_strategy_snapshots; CREATE TRIGGER trg_lf_strategy_characteristics_seed_v1 AFTER INSERT ON public.lf_strategy_snapshots FOR EACH ROW EXECUTE FUNCTION public.lf_strategy_characteristics_seed_v1();
INSERT INTO public.lf_strategy_test_characteristics(snapshot_id,characteristic_code,enabled,created_by_execution_id) SELECT s.id,c.characteristic_code,NULL,'EXEC-S30-STRATEGY-QUALIFICATION-FRAMEWORK-20260914-001' FROM public.lf_strategy_snapshots s CROSS JOIN public.lf_strategy_test_characteristic_catalog c WHERE c.status='ACTIVE' ON CONFLICT(snapshot_id,characteristic_code) DO NOTHING;

CREATE OR REPLACE FUNCTION public.lf_strategy_invalidate_qualification_v1() RETURNS trigger LANGUAGE plpgsql SET search_path TO 'pg_catalog','public' AS $fn$
DECLARE old_sha text; new_sha text; qualified_state text; BEGIN old_sha:=public.lf_strategy_revision_sha256_from_json_v1(to_jsonb(OLD)); new_sha:=public.lf_strategy_revision_sha256_from_json_v1(to_jsonb(NEW)); IF old_sha IS NOT DISTINCT FROM new_sha THEN RETURN NEW; END IF; qualified_state:=public.lf_lifecycle_action_target_state_v1('QUALIFICATION_LIFECYCLE','PASS_QUALIFICATION'); UPDATE public.lf_qualification_receipts q SET lifecycle_state_code=public.lf_lifecycle_resolve_transition_v1('QUALIFICATION_LIFECYCLE',q.lifecycle_state_code,'INVALIDATE_QUALIFICATION'),invalidated_at=clock_timestamp(),updated_at=clock_timestamp(),updated_by_execution_id=coalesce(NEW.updated_by_execution_id,'SYSTEM'),findings=q.findings||jsonb_build_array(jsonb_build_object('type','MATERIAL_STRATEGY_REVISION_CHANGED','old_revision_sha256',old_sha,'new_revision_sha256',new_sha)) WHERE q.subject_type='STRATEGY' AND q.subject_code=OLD.snapshot_code AND q.revision_sha256=old_sha AND q.lifecycle_state_code=qualified_state AND q.invalidated_at IS NULL; RETURN NEW; END $fn$;
DROP TRIGGER IF EXISTS trg_lf_strategy_invalidate_qualification_v1 ON public.lf_strategy_snapshots; CREATE TRIGGER trg_lf_strategy_invalidate_qualification_v1 AFTER UPDATE ON public.lf_strategy_snapshots FOR EACH ROW EXECUTE FUNCTION public.lf_strategy_invalidate_qualification_v1();
CREATE OR REPLACE FUNCTION public.lf_strategy_characteristic_invalidate_qualification_v1() RETURNS trigger LANGUAGE plpgsql SET search_path TO 'pg_catalog','public' AS $fn$
DECLARE sc text; rev text; qualified_state text; BEGIN IF NEW.enabled IS NOT DISTINCT FROM OLD.enabled THEN RETURN NEW; END IF; SELECT snapshot_code INTO sc FROM public.lf_strategy_snapshots WHERE id=NEW.snapshot_id; rev:=public.lf_strategy_revision_sha256_v1(NEW.snapshot_id); qualified_state:=public.lf_lifecycle_action_target_state_v1('QUALIFICATION_LIFECYCLE','PASS_QUALIFICATION'); UPDATE public.lf_qualification_receipts q SET lifecycle_state_code=public.lf_lifecycle_resolve_transition_v1('QUALIFICATION_LIFECYCLE',q.lifecycle_state_code,'INVALIDATE_QUALIFICATION'),invalidated_at=clock_timestamp(),updated_at=clock_timestamp(),updated_by_execution_id=coalesce(NEW.updated_by_execution_id,'SYSTEM'),findings=q.findings||jsonb_build_array(jsonb_build_object('type','STRATEGY_TEST_CLASSIFICATION_CHANGED','characteristic_code',NEW.characteristic_code,'enabled',NEW.enabled)) WHERE q.subject_type='STRATEGY' AND q.subject_code=sc AND q.revision_sha256=rev AND q.lifecycle_state_code=qualified_state AND q.invalidated_at IS NULL; RETURN NEW; END $fn$;
DROP TRIGGER IF EXISTS trg_lf_strategy_characteristic_invalidate_qualification_v1 ON public.lf_strategy_test_characteristics; CREATE TRIGGER trg_lf_strategy_characteristic_invalidate_qualification_v1 AFTER UPDATE OF enabled ON public.lf_strategy_test_characteristics FOR EACH ROW EXECUTE FUNCTION public.lf_strategy_characteristic_invalidate_qualification_v1();

DO $post$ DECLARE c int; BEGIN SELECT count(*) INTO c FROM lf_ops.estados_catalogo WHERE entity_type='QUALIFICATION_LIFECYCLE' AND status='VIGENTE'; IF c<>5 THEN RAISE EXCEPTION 'S30_POST_QUAL_STATE_COUNT:%',c; END IF; SELECT count(*) INTO c FROM public.lf_strategy_test_characteristic_catalog WHERE status='ACTIVE'; IF c<>8 THEN RAISE EXCEPTION 'S30_POST_CHARACTERISTIC_COUNT:%',c; END IF; SELECT count(*) INTO c FROM information_schema.columns WHERE table_schema='public' AND table_name IN ('lf_operation_registry','lf_strategy_snapshots') AND column_name='lifecycle_state_code' AND column_default IS NOT NULL; IF c<>0 THEN RAISE EXCEPTION 'S30_POST_LIFECYCLE_DEFAULT_REMAINS:%',c; END IF; END $post$;