-- SADM-PP-L5-022 isolated cutover 11: WAIVER_AUTHORITY_V1.
-- Materializes the dedicated one-use waiver store and promotes the exact guarded capability.
-- Non-production only. No runtime/deploy/production. No reuse of validation exemptions.

create table if not exists private.lf_post_pase_waivers (
  waiver_id bigint generated by default as identity primary key,
  post_pase_execution_id text not null,
  control_id text not null,
  plan_digest text not null check (plan_digest ~ '^[0-9a-f]{64}$'),
  merge_sha text not null check (merge_sha ~ '^[0-9a-f]{40}$'),
  source_revision text not null check (source_revision ~ '^[0-9a-f]{40}$'),
  subject_ref text not null,
  rationale text not null check (length(btrim(rationale)) >= 20),
  approval_authority text not null check (approval_authority = 'LF_GOVERNANCE'),
  approval_event_id bigint not null references public.lf_eventos(id),
  approval_decision text not null check (approval_decision = 'APPROVED'),
  approved_at timestamptz not null,
  expires_at timestamptz not null,
  max_uses integer not null default 1 check (max_uses = 1),
  uses_count integer not null default 0 check (uses_count between 0 and 1),
  active boolean not null default true,
  consumed_at timestamptz,
  consumed_by_execution_id text,
  consumed_by_request_digest text check (consumed_by_request_digest is null or consumed_by_request_digest ~ '^[0-9a-f]{64}$'),
  grant_sha256 text not null check (grant_sha256 ~ '^[0-9a-f]{64}$'),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint lf_post_pase_waivers_expiry_chk check (expires_at > approved_at and expires_at <= approved_at + interval '1 hour'),
  constraint lf_post_pase_waivers_consumption_chk check (
    (uses_count=0 and consumed_at is null and consumed_by_execution_id is null and consumed_by_request_digest is null)
    or
    (uses_count=1 and consumed_at is not null and consumed_by_execution_id is not null and consumed_by_request_digest is not null and active=false)
  )
);

create unique index if not exists lf_post_pase_waivers_exact_scope_active_uk
on private.lf_post_pase_waivers(post_pase_execution_id,control_id,plan_digest,merge_sha,source_revision,subject_ref)
where active;

create or replace function private.lf_post_pase_waiver_readback_v1(
  p_waiver_id bigint,
  p_post_pase_execution_id text,
  p_control_id text,
  p_plan_digest text,
  p_merge_sha text,
  p_source_revision text,
  p_subject_ref text
) returns jsonb
language plpgsql security definer
set search_path=pg_catalog,private,public,extensions
as $fn$
declare r private.lf_post_pase_waivers%rowtype; v_scope jsonb; v_pre jsonb; v_digest text;
begin
  select * into r from private.lf_post_pase_waivers where waiver_id=p_waiver_id;
  if not found then return jsonb_build_object('schema_version','LF_POST_PASE_WAIVER_GRANT_READBACK_V1','authority_layer','WAIVER_AUTHORITY_STORE','decision','WAIVER_GRANT_MISSING','ready',false,'waiver_id',p_waiver_id); end if;
  v_scope:=jsonb_build_object('post_pase_execution_id',p_post_pase_execution_id,'control_id',p_control_id,'plan_digest',p_plan_digest,'merge_sha',p_merge_sha,'source_revision',p_source_revision,'subject_ref',p_subject_ref);
  if (r.post_pase_execution_id,r.control_id,r.plan_digest,r.merge_sha,r.source_revision,r.subject_ref) is distinct from (p_post_pase_execution_id,p_control_id,p_plan_digest,p_merge_sha,p_source_revision,p_subject_ref) then
    return jsonb_build_object('schema_version','LF_POST_PASE_WAIVER_GRANT_READBACK_V1','authority_layer','WAIVER_AUTHORITY_STORE','decision','WAIVER_SCOPE_MISMATCH','ready',false,'waiver_id',p_waiver_id,'scope',v_scope);
  end if;
  v_pre:=jsonb_build_object('schema_version','LF_POST_PASE_WAIVER_GRANT_READBACK_V1','authority_layer','WAIVER_AUTHORITY_STORE','decision',case when r.active and r.uses_count=0 and r.expires_at>clock_timestamp() then 'WAIVER_GRANT_CURRENT' else 'WAIVER_GRANT_NOT_CURRENT' end,'ready',(r.active and r.uses_count=0 and r.expires_at>clock_timestamp()),'waiver_id',r.waiver_id,'scope',v_scope,'approval_authority',r.approval_authority,'approval_decision',r.approval_decision,'approval_event_id',r.approval_event_id,'approved_at',r.approved_at,'expires_at',r.expires_at,'max_uses',r.max_uses,'uses_count',r.uses_count,'active',r.active,'consumed_at',r.consumed_at,'rationale',r.rationale,'grant_sha256',r.grant_sha256);
  v_digest:=encode(extensions.digest(convert_to(v_pre::text,'UTF8'),'sha256'),'hex');
  return v_pre||jsonb_build_object('readback_digest',v_digest);
end $fn$;

create or replace function private.lf_post_pase_waiver_consume_v1(
  p_waiver_id bigint,
  p_post_pase_execution_id text,
  p_control_id text,
  p_plan_digest text,
  p_merge_sha text,
  p_source_revision text,
  p_subject_ref text,
  p_consumer_execution_id text,
  p_request_digest text
) returns jsonb
language plpgsql security definer
set search_path=pg_catalog,private,public,extensions
as $fn$
declare r private.lf_post_pase_waivers%rowtype; v_scope jsonb; v_pre jsonb; v_digest text;
begin
  if p_request_digest !~ '^[0-9a-f]{64}$' or nullif(btrim(p_consumer_execution_id),'') is null then raise exception 'BLOCK_WAIVER_CONSUME_IDENTITY_INVALID'; end if;
  select * into r from private.lf_post_pase_waivers where waiver_id=p_waiver_id for update;
  if not found then return jsonb_build_object('schema_version','LF_POST_PASE_WAIVER_CONSUMPTION_READBACK_V1','authority_layer','WAIVER_AUTHORITY_STORE','decision','WAIVER_MISSING','ready',false,'waiver_id',p_waiver_id); end if;
  v_scope:=jsonb_build_object('post_pase_execution_id',p_post_pase_execution_id,'control_id',p_control_id,'plan_digest',p_plan_digest,'merge_sha',p_merge_sha,'source_revision',p_source_revision,'subject_ref',p_subject_ref);
  if (r.post_pase_execution_id,r.control_id,r.plan_digest,r.merge_sha,r.source_revision,r.subject_ref) is distinct from (p_post_pase_execution_id,p_control_id,p_plan_digest,p_merge_sha,p_source_revision,p_subject_ref) then return jsonb_build_object('schema_version','LF_POST_PASE_WAIVER_CONSUMPTION_READBACK_V1','authority_layer','WAIVER_AUTHORITY_STORE','decision','WAIVER_SCOPE_MISMATCH','ready',false,'waiver_id',p_waiver_id,'scope',v_scope); end if;
  if not r.active or r.uses_count<>0 or r.max_uses<>1 or r.expires_at<=clock_timestamp() then return jsonb_build_object('schema_version','LF_POST_PASE_WAIVER_CONSUMPTION_READBACK_V1','authority_layer','WAIVER_AUTHORITY_STORE','decision','WAIVER_NOT_CONSUMABLE','ready',false,'waiver_id',p_waiver_id,'scope',v_scope,'uses_count',r.uses_count,'max_uses',r.max_uses,'active',r.active); end if;
  update private.lf_post_pase_waivers set uses_count=1,active=false,consumed_at=clock_timestamp(),consumed_by_execution_id=p_consumer_execution_id,consumed_by_request_digest=p_request_digest,updated_at=clock_timestamp() where waiver_id=p_waiver_id returning * into r;
  v_pre:=jsonb_build_object('schema_version','LF_POST_PASE_WAIVER_CONSUMPTION_READBACK_V1','authority_layer','WAIVER_AUTHORITY_STORE','decision','WAIVER_CONSUMED','ready',true,'waiver_id',r.waiver_id,'scope',v_scope,'max_uses',r.max_uses,'uses_count',r.uses_count,'active',r.active,'consumed_at',r.consumed_at,'consumed_by_execution_id',r.consumed_by_execution_id,'consumed_by_request_digest',r.consumed_by_request_digest,'grant_sha256',r.grant_sha256);
  v_digest:=encode(extensions.digest(convert_to(v_pre::text,'UTF8'),'sha256'),'hex');
  return v_pre||jsonb_build_object('readback_digest',v_digest);
end $fn$;

revoke all on table private.lf_post_pase_waivers from public,anon,authenticated;
revoke all on function private.lf_post_pase_waiver_readback_v1(bigint,text,text,text,text,text,text) from public,anon,authenticated;
revoke all on function private.lf_post_pase_waiver_consume_v1(bigint,text,text,text,text,text,text,text,text) from public,anon,authenticated;

insert into public.lf_activos(codigo_activo,nombre_canonico,tipo_activo,subtipo_activo,formato_nativo,estado_original,estado_documental,estado_operativo,impacto_automatico,version,ruta_esperada,owner_name,source_spreadsheet_id,source_spreadsheet_title,source_sheet_name,source_row_number,raw_payload,metadata,migration_batch_id,created_by_execution_id,updated_by_execution_id)
values('WAIVER_AUTHORITY','TRANSVERSAL_POST_PASE_WAIVER_AUTHORITY','CAPABILITY','TRANSVERSAL_ONE_USE_WAIVER_AUTHORITY','GITHUB_CONTRACT','CANDIDATE_READ_ONLY','VIGENTE','ACTIVO','BLOQUEADO','1.0.0','sandbox/lf_contract_gate_test/waiver_authority/README.md','LF_GOVERNANCE','NATIVE_SUPABASE','LF_TRANSVERSAL_CAPABILITY_INVENTORY','WAIVER_AUTHORITY_20261001',1,
jsonb_build_object('solution_code','WAIVER_AUTHORITY_V1','work_code','SADM-PP-L3-018','store','private.lf_post_pase_waivers','readback_function','private.lf_post_pase_waiver_readback_v1','consume_function','private.lf_post_pase_waiver_consume_v1','validation_exemption_store_reused',false,'max_ttl_seconds',3600,'max_uses',1,'cutover_executed',true,'runtime_authorized',false,'production_authorized',false),
jsonb_build_object('schema_version','WAIVER_AUTHORITY_ASSET_METADATA_V1','entry_guard','ORCHESTRATOR_EXECUTION_GUARD_V1','decisions',jsonb_build_array('WAIVER_AUTHORIZED','WAIVER_BLOCKED'),'closure_decision_forbidden',true,'waived_output_forbidden',true,'approval_authority','LF_GOVERNANCE','required_cross_bind',jsonb_build_array('post_pase_execution_id','control_id','plan_digest','merge_sha','source_revision','subject_ref','request_digest'),'registry_cutover_state','ENFORCED'),
'8c1d2f6c-4a1c-4f80-9d3d-018000000001'::uuid,'EXEC-L5-WAIVER-AUTHORITY-CUTOVER-V1-20261001','EXEC-L5-WAIVER-AUTHORITY-CUTOVER-V1-20261001')
on conflict(codigo_activo) do update set estado_documental='VIGENTE',estado_operativo='ACTIVO',version='1.0.0',owner_name='LF_GOVERNANCE',raw_payload=excluded.raw_payload,metadata=excluded.metadata,updated_at=now(),updated_by_execution_id=excluded.updated_by_execution_id;

insert into public.lf_activo_relaciones(codigo_activo,relacionado_codigo,relacion_tipo,valor_original,fuente,migration_batch_id,created_by_execution_id,updated_by_execution_id) values
('WAIVER_AUTHORITY','LF_GOVERNANCE','RELACIONADO_CAPACIDADES','administrative owner and approval authority','sandbox/lf_contract_gate_test/waiver_authority/waiver_authority_contract_v1.json','8c1d2f6c-4a1c-4f80-9d3d-018000000001'::uuid,'EXEC-L5-WAIVER-AUTHORITY-CUTOVER-V1-20261001','EXEC-L5-WAIVER-AUTHORITY-CUTOVER-V1-20261001'),
('WAIVER_AUTHORITY','PLAN_AUTHORITY_DRIFT_GUARD','DEPENDE_DE','plan scope and authorized delta validation','sandbox/lf_contract_gate_test/waiver_authority/waiver_authority_contract_v1.json','8c1d2f6c-4a1c-4f80-9d3d-018000000001'::uuid,'EXEC-L5-WAIVER-AUTHORITY-CUTOVER-V1-20261001','EXEC-L5-WAIVER-AUTHORITY-CUTOVER-V1-20261001'),
('WAIVER_AUTHORITY','CURRENTNESS_AUTHORITY','DEPENDE_DE','source revision currentness','sandbox/lf_contract_gate_test/waiver_authority/waiver_authority_contract_v1.json','8c1d2f6c-4a1c-4f80-9d3d-018000000001'::uuid,'EXEC-L5-WAIVER-AUTHORITY-CUTOVER-V1-20261001','EXEC-L5-WAIVER-AUTHORITY-CUTOVER-V1-20261001') on conflict do nothing;

do $$
declare v_manifest jsonb; v_sha text; v_existing text; v_promote jsonb; v_execution_id constant text:='EXEC-L5-WAIVER-AUTHORITY-CUTOVER-V1-20261001';
begin
  v_manifest:=jsonb_build_object('schema_version','LF_CAPABILITY_MANIFEST_V1','capability_code','WAIVER_AUTHORITY','version','1.0.0','contract',jsonb_build_object('input','LF_WAIVER_AUTHORITY_REQUEST_V1 + PLAN_CURRENTNESS_GRANT_CONSUMPTION_READBACKS','output','LF_WAIVER_AUTHORITY_RECEIPT_V1','authority','EXACT_APPROVED_CURRENT_ONE_USE_WAIVER_ONLY'),'delivery',jsonb_build_object('mode','SUPABASE_STORE_PLUS_VERSIONED_REPOSITORY_EVALUATOR','core','sandbox/lf_contract_gate_test/waiver_authority/waiver_authority_v1.py','store','private.lf_post_pase_waivers'),'installation',jsonb_build_object('required',false,'reinstall_required',false,'package_update_mode','DATABASE_NATIVE_CUTOVER'),'dependencies',jsonb_build_object('capabilities',jsonb_build_array('PLAN_AUTHORITY_DRIFT_GUARD','CURRENTNESS_AUTHORITY'),'governance',jsonb_build_array('LF_GOVERNANCE','ORCHESTRATOR_EXECUTION_GUARD_V1')),'compatibility',jsonb_build_object('unknown_state','FAIL_CLOSED','validation_exemption_semantic_reuse',false,'one_use',true,'max_ttl_seconds',3600,'functional_core_unchanged',true),'migration',jsonb_build_object('mode','DEDICATED_STORE_AND_REGISTRY_CUTOVER','work_code','SADM-PP-L5-022','legacy_retirement',false),'usage',jsonb_build_object('core','sandbox/lf_contract_gate_test/waiver_authority/waiver_authority_v1.py','contract','sandbox/lf_contract_gate_test/waiver_authority/waiver_authority_contract_v1.json','validator','sandbox/lf_contract_gate_test/waiver_authority/test_waiver_authority_v1.py','entrypoint','public.fn_lf_capability_bind_from_orchestrator_v1'),'currentness',jsonb_build_object('authority_ref','github://cristhianlujan/claude-persona-lf-patch@a918c85af086d08a085bab2db5f70cb6b31b62eb','source_revision_immutable',true,'core_blob_sha1','839792277cf71f2a3f3585e2e1f0b21351da533c','test_blob_sha1','397a612f044332b359f251f8d8101948be73a376','terminal_source_event_id',19624));
  v_sha:=encode(extensions.digest(convert_to(v_manifest::text,'UTF8'),'sha256'),'hex');
  insert into public.lf_capability_registry(capability_code,capability_name,capability_kind,owner_scope,status,description,created_by_execution_id,updated_by_execution_id,entry_guard_required,entry_guard_code)
  values('WAIVER_AUTHORITY','Waiver Authority','TRANSVERSAL','LF_GOVERNANCE','ACTIVE','Exact-scope approved current one-use POST-PASE waiver authority with dedicated store and anti-replay consumption.',v_execution_id,v_execution_id,true,'ORCHESTRATOR_EXECUTION_GUARD_V1') on conflict(capability_code) do update set owner_scope='LF_GOVERNANCE',status='ACTIVE',entry_guard_required=true,entry_guard_code='ORCHESTRATOR_EXECUTION_GUARD_V1',updated_at=now(),updated_by_execution_id=v_execution_id;
  select manifest_sha256 into v_existing from public.lf_capability_version_registry where capability_code='WAIVER_AUTHORITY' and version='1.0.0';
  if v_existing is not null and v_existing<>v_sha then raise exception 'WAIVER_AUTHORITY_VERSION_1_0_0_MANIFEST_CONFLICT'; end if;
  insert into public.lf_capability_version_registry(capability_code,version,version_major,version_minor,version_patch,release_state,supersedes_version,manifest,manifest_sha256,source_ref,docs_ref,validator_ref,created_by_execution_id)
  values('WAIVER_AUTHORITY','1.0.0',1,0,0,'RELEASED',null,v_manifest,v_sha,'github://cristhianlujan/claude-persona-lf-patch@a918c85af086d08a085bab2db5f70cb6b31b62eb/sandbox/lf_contract_gate_test/waiver_authority/waiver_authority_v1.py','github://cristhianlujan/claude-persona-lf-patch@a918c85af086d08a085bab2db5f70cb6b31b62eb/sandbox/lf_contract_gate_test/waiver_authority/README.md','github://cristhianlujan/claude-persona-lf-patch@a918c85af086d08a085bab2db5f70cb6b31b62eb/sandbox/lf_contract_gate_test/waiver_authority/test_waiver_authority_v1.py',v_execution_id) on conflict(capability_code,version) do nothing;
  v_promote:=public.fn_lf_capability_promote_v1('WAIVER_AUTHORITY','1.0.0',null,v_execution_id,'L5 isolated WAIVER_AUTHORITY dedicated-store cutover; validation exemptions remain semantically separate.');
  if coalesce((v_promote->>'ready')::boolean,false) is not true then raise exception 'WAIVER_AUTHORITY_CURRENT_POINTER_BLOCKED:%',v_promote::text; end if;
end $$;
