-- LF_GATE_CHECK_OBSERVABILITY_V1
-- Check-level diagnostics under the canonical operation execution/step ledger.
-- Reuses lf_ops.errores_catalogo / lf_ops.errores_ocurrencias; no parallel workflow or error system.

begin;

insert into lf_ops.errores_catalogo(
  error_code,category,severity,user_title,user_message_template,suggested_action,
  action_label,retryable,log_level,provider_mapping,status
)
select 'LF-GATE-CHECK-FAILED','QUALITY_GATE','HIGH','Gate check failed',
       'A governed gate check failed. Inspect its trace and evidence references.',
       'Correct the owning defect and rerun the governed gate.',
       'Inspect diagnostic',true,'ERROR',
       jsonb_build_object('contract','LF_GATE_ERROR_V1'),'VIGENTE'
where not exists(select 1 from lf_ops.errores_catalogo where error_code='LF-GATE-CHECK-FAILED');

insert into lf_ops.errores_catalogo(
  error_code,category,severity,user_title,user_message_template,suggested_action,
  action_label,retryable,log_level,provider_mapping,status
)
select 'LF-GATE-CHECK-BLOCKED','QUALITY_GATE','HIGH','Gate check blocked',
       'A governed gate check could not execute or prove its condition. Inspect its trace and evidence references.',
       'Restore the missing precondition or evidence and rerun the governed gate.',
       'Inspect blocker',true,'ERROR',
       jsonb_build_object('contract','LF_GATE_ERROR_V1'),'VIGENTE'
where not exists(select 1 from lf_ops.errores_catalogo where error_code='LF-GATE-CHECK-BLOCKED');

create table if not exists public.lf_operation_gate_check_results(
  id bigint generated by default as identity primary key,
  execution_id text not null references public.lf_operation_execution(execution_id),
  operation_code text not null,
  step_order integer not null,
  step_id text not null,
  gate_id text not null,
  gate_mode text not null check(gate_mode in ('COLLECT_ALL','FAIL_FAST_CRITICAL')),
  attempt_no integer not null default 1 check(attempt_no>=1),
  check_id text not null,
  check_status text not null check(check_status in ('PASS','FAIL','BLOCKED','SKIPPED')),
  error_id bigint null references lf_ops.errores_catalogo(error_id),
  error_occurrence_id uuid null references lf_ops.errores_ocurrencias(occurrence_id),
  error_class text null,
  check_condition text not null,
  expected jsonb not null default 'null'::jsonb,
  actual jsonb not null default 'null'::jsonb,
  input_ref text null,
  evidence_ref text not null,
  producer text not null,
  run_id text not null,
  job_id text null,
  source_commit text not null,
  source_path text not null,
  trace_id text not null,
  parent_trace_id text not null,
  rc integer not null,
  downstream_impact jsonb not null default '{}'::jsonb,
  owner text not null,
  next_action text not null,
  batch_sha256 text not null check(batch_sha256 ~ '^[0-9a-f]{64}$'),
  created_by_execution_id text not null,
  observed_at timestamptz not null default clock_timestamp(),
  constraint lf_gate_check_error_refs_ck check(
    (check_status in ('PASS','SKIPPED') and error_id is null and error_occurrence_id is null)
    or (check_status in ('FAIL','BLOCKED') and error_id is not null and error_occurrence_id is not null)
  ),
  constraint lf_gate_check_result_uk unique(execution_id,step_id,gate_id,attempt_no,check_id)
);

create index if not exists lf_gate_check_exec_idx
  on public.lf_operation_gate_check_results(execution_id,step_order,gate_id,attempt_no,id);
create index if not exists lf_gate_check_error_idx
  on public.lf_operation_gate_check_results(error_occurrence_id)
  where error_occurrence_id is not null;

alter table public.lf_operation_gate_check_results enable row level security;
revoke all on table public.lf_operation_gate_check_results from public,anon,authenticated;
grant select,insert on table public.lf_operation_gate_check_results to service_role;
grant usage,select on sequence public.lf_operation_gate_check_results_id_seq to service_role;

create or replace function public.lf_gate_check_reject_pii_v1()
returns trigger
language plpgsql
security invoker
set search_path to 'pg_catalog','public'
as $function$
declare v_text text;
begin
  v_text:=jsonb_build_object('expected',new.expected,'actual',new.actual,'downstream_impact',new.downstream_impact)::text;
  if v_text ~* '\"(email|phone|document_number|tax_id|full_name|customer_full_name|contact_email|contact_phone|legal_address|token|password|secret)\"[[:space:]]*:' then
    raise exception 'LF_PII_BLOCKED_IN_GATE_TELEMETRY';
  end if;
  return new;
end;
$function$;
revoke execute on function public.lf_gate_check_reject_pii_v1() from public,anon,authenticated;

drop trigger if exists trg_lf_gate_check_no_pii on public.lf_operation_gate_check_results;
create trigger trg_lf_gate_check_no_pii
before insert or update on public.lf_operation_gate_check_results
for each row execute function public.lf_gate_check_reject_pii_v1();

create or replace function public.lf_gate_check_diagnostic_v1(
  p_execution_id text,p_step_id text,p_gate_id text,p_attempt_no integer default 1
)
returns jsonb
language sql
security invoker
set search_path to 'pg_catalog','public'
as $function$
with r as (
  select * from public.lf_operation_gate_check_results
  where execution_id=p_execution_id and step_id=p_step_id and gate_id=p_gate_id and attempt_no=p_attempt_no
  order by id
), a as (
  select count(*)::int n,
         count(*) filter(where check_status='PASS')::int p,
         count(*) filter(where check_status='FAIL')::int f,
         count(*) filter(where check_status='BLOCKED')::int b,
         count(*) filter(where check_status='SKIPPED')::int s,
         min(operation_code) operation_code,min(step_order) step_order,min(gate_mode) gate_mode,
         min(parent_trace_id) parent_trace_id,min(batch_sha256) batch_sha256
  from r
)
select case when a.n=0 then
  jsonb_build_object('outcome','NOT_FOUND','execution_id',p_execution_id,'step_id',p_step_id,'gate_id',p_gate_id,'attempt_no',p_attempt_no)
else jsonb_build_object(
  'outcome','FOUND','contract','LF_GATE_ERROR_V1','execution_id',p_execution_id,'operation_code',a.operation_code,
  'step_id',p_step_id,'step_order',a.step_order,'gate_id',p_gate_id,'gate_mode',a.gate_mode,'attempt_no',p_attempt_no,
  'gate_result',case when a.b>0 or a.s>0 then 'BLOCKED' when a.f>0 then 'FAIL' else 'PASS' end,
  'check_count',a.n,'pass_count',a.p,'fail_count',a.f,'blocked_count',a.b,'skipped_count',a.s,
  'parent_trace_id',a.parent_trace_id,'batch_sha256',a.batch_sha256,
  'checks',(select jsonb_agg(jsonb_build_object(
    'check_id',check_id,'status',check_status,'error_id',error_id,'occurrence_id',error_occurrence_id,
    'error_class',error_class,'condition',check_condition,'expected',expected,'actual',actual,
    'input_ref',input_ref,'evidence_ref',evidence_ref,'producer',producer,'run_id',run_id,'job_id',job_id,
    'source_commit',source_commit,'source_path',source_path,'trace_id',trace_id,'parent_trace_id',parent_trace_id,
    'rc',rc,'downstream_impact',downstream_impact,'owner',owner,'next_action',next_action,'observed_at',observed_at
  ) order by id) from r)
) end from a;
$function$;

create or replace function public.lf_record_gate_checks_v1(
  p_execution_id text,p_step_id text,p_gate_id text,p_gate_mode text,
  p_expected_check_ids jsonb,p_checks jsonb,p_context jsonb,p_actor_execution_id text
)
returns jsonb
language plpgsql
security invoker
set search_path to 'pg_catalog','public','lf_ops'
as $function$
declare
  v_exec public.lf_operation_execution%rowtype;
  v_step public.lf_operation_steps%rowtype;
  v_step_exec public.lf_operation_execution_steps%rowtype;
  v_check jsonb;
  v_expected text[];
  v_seen text[];
  v_expected_count int;
  v_seen_count int;
  v_duplicates int;
  v_attempt int;
  v_pos int:=0;
  v_stop_pos int:=null;
  v_expected_pos int;
  v_status text;
  v_check_id text;
  v_error_code text;
  v_error lf_ops.errores_catalogo%rowtype;
  v_occurrence uuid;
  v_trace text;
  v_parent_trace text;
  v_corr uuid;
  v_batch_sha text;
  v_batch jsonb;
  v_source_commit text;
  v_source_path text;
  v_run_id text;
  v_job_id text;
  v_owner text;
  v_next_action text;
  v_environment text;
  v_condition text;
  v_producer text;
  v_evidence_ref text;
  v_input_ref text;
  v_error_class text;
  v_rc int;
  v_expected_value jsonb;
  v_actual_value jsonb;
  v_downstream jsonb;
  v_pass int:=0;
  v_fail int:=0;
  v_blocked int:=0;
  v_skipped int:=0;
  v_gate_result text;
  v_existing int;
  v_existing_distinct int;
  v_actor_exists boolean;
  v_conflict boolean:=false;
  v_remaining text[]:=array[]::text[];
  v_errors jsonb:='[]'::jsonb;
  v_summary jsonb;
begin
  if btrim(coalesce(p_execution_id,''))='' or btrim(coalesce(p_step_id,''))='' or btrim(coalesce(p_gate_id,''))=''
     or p_gate_mode not in ('COLLECT_ALL','FAIL_FAST_CRITICAL')
     or p_expected_check_ids is null or jsonb_typeof(p_expected_check_ids)<>'array'
     or p_checks is null or jsonb_typeof(p_checks)<>'array'
     or p_context is null or jsonb_typeof(p_context)<>'object'
     or btrim(coalesce(p_actor_execution_id,''))='' then
    return jsonb_build_object('outcome','BLOCKED','code','LF_GATE_ERROR_V1_INPUT_INVALID','durable',false);
  end if;

  select * into v_exec from public.lf_operation_execution where execution_id=p_execution_id for update;
  if not found then return jsonb_build_object('outcome','BLOCKED','code','LF_GATE_ERROR_V1_EXECUTION_NOT_FOUND','durable',false); end if;
  if v_exec.status<>'IN_PROGRESS' then return jsonb_build_object('outcome','BLOCKED','code','LF_GATE_ERROR_V1_EXECUTION_NOT_IN_PROGRESS','status',v_exec.status,'durable',false); end if;

  select exists(select 1 from public.lf_operation_execution where execution_id=p_actor_execution_id) into v_actor_exists;
  if p_actor_execution_id<>p_execution_id and not v_actor_exists then
    return jsonb_build_object('outcome','BLOCKED','code','LF_GATE_ERROR_V1_ACTOR_NOT_GOVERNED','durable',false);
  end if;

  select * into v_step from public.lf_operation_steps
  where operation_code=v_exec.operation_code and step_id=p_step_id and active=true;
  if not found then return jsonb_build_object('outcome','BLOCKED','code','LF_GATE_ERROR_V1_STEP_NOT_CANONICAL','durable',false); end if;
  if jsonb_array_length(p_expected_check_ids)=0 or jsonb_array_length(p_checks)=0 then
    return jsonb_build_object('outcome','BLOCKED','code','LF_GATE_ERROR_V1_EMPTY_CHECK_SET','durable',false);
  end if;

  select array_agg(value order by ord),count(*)::int,(count(*)-count(distinct value))::int
  into v_expected,v_expected_count,v_duplicates
  from jsonb_array_elements_text(p_expected_check_ids) with ordinality t(value,ord);
  if v_duplicates<>0 or exists(select 1 from unnest(v_expected) q where btrim(coalesce(q,''))='') then
    return jsonb_build_object('outcome','BLOCKED','code','LF_GATE_ERROR_V1_EXPECTED_CHECK_IDS_INVALID','durable',false);
  end if;

  select array_agg(cid order by ord),count(*)::int,(count(*)-count(distinct cid))::int
  into v_seen,v_seen_count,v_duplicates
  from (select elem->>'check_id' cid,ord from jsonb_array_elements(p_checks) with ordinality t(elem,ord)) s;
  if v_duplicates<>0 or exists(select 1 from unnest(v_seen) q where btrim(coalesce(q,''))='') then
    return jsonb_build_object('outcome','BLOCKED','code','LF_GATE_ERROR_V1_CHECK_IDS_INVALID','durable',false);
  end if;
  if exists(select 1 from unnest(v_seen) q where not(q=any(v_expected))) then
    return jsonb_build_object('outcome','BLOCKED','code','LF_GATE_ERROR_V1_UNDECLARED_CHECK','durable',false);
  end if;

  if coalesce(p_context->>'attempt_no','')<>'' and (p_context->>'attempt_no') !~ '^[0-9]+$' then
    return jsonb_build_object('outcome','BLOCKED','code','LF_GATE_ERROR_V1_ATTEMPT_INVALID','durable',false);
  end if;
  v_attempt:=coalesce(nullif(p_context->>'attempt_no','')::int,1);
  if v_attempt<1 then return jsonb_build_object('outcome','BLOCKED','code','LF_GATE_ERROR_V1_ATTEMPT_INVALID','durable',false); end if;

  v_source_commit:=btrim(coalesce(p_context->>'source_commit',''));
  v_source_path:=btrim(coalesce(p_context->>'source_path',''));
  v_run_id:=btrim(coalesce(p_context->>'run_id',p_execution_id));
  v_job_id:=nullif(btrim(coalesce(p_context->>'job_id','')),'');
  v_owner:=btrim(coalesce(p_context->>'owner',''));
  v_next_action:=btrim(coalesce(p_context->>'next_action',''));
  v_environment:=upper(btrim(coalesce(p_context->>'environment','CANDIDATE')));
  if v_source_commit='' or v_source_path='' or v_run_id='' or v_owner='' or v_next_action='' then
    return jsonb_build_object('outcome','BLOCKED','code','LF_GATE_ERROR_V1_CONTEXT_INCOMPLETE','durable',false);
  end if;

  v_batch:=jsonb_build_object('execution_id',p_execution_id,'operation_code',v_exec.operation_code,'step_id',p_step_id,
    'step_order',v_step.step_order,'gate_id',p_gate_id,'gate_mode',p_gate_mode,'attempt_no',v_attempt,
    'expected_check_ids',p_expected_check_ids,'checks',p_checks,'context',p_context);
  v_batch_sha:=encode(extensions.digest(v_batch::text,'sha256'),'hex');
  v_parent_trace:=coalesce(nullif(btrim(p_context->>'parent_trace_id'),''),'LF-GATE-'||upper(substr(v_batch_sha,1,20)));
  v_corr:=gen_random_uuid();

  select count(*)::int,count(distinct batch_sha256)::int into v_existing,v_existing_distinct
  from public.lf_operation_gate_check_results
  where execution_id=p_execution_id and step_id=p_step_id and gate_id=p_gate_id and attempt_no=v_attempt;
  if v_existing>0 then
    if v_existing_distinct=1 and exists(select 1 from public.lf_operation_gate_check_results
      where execution_id=p_execution_id and step_id=p_step_id and gate_id=p_gate_id and attempt_no=v_attempt and batch_sha256=v_batch_sha) then
      return public.lf_gate_check_diagnostic_v1(p_execution_id,p_step_id,p_gate_id,v_attempt)||jsonb_build_object('outcome','REPLAY');
    end if;
    return jsonb_build_object('outcome','BLOCKED','code','LF_GATE_ERROR_V1_ATTEMPT_CONFLICT','durable',true);
  end if;

  -- Validate all supplied check payloads before any durable write.
  for v_check in select value from jsonb_array_elements(p_checks) loop
    v_check_id:=btrim(coalesce(v_check->>'check_id',''));
    v_status:=upper(btrim(coalesce(v_check->>'status','')));
    v_condition:=btrim(coalesce(v_check->>'condition',''));
    v_producer:=btrim(coalesce(v_check->>'producer',''));
    v_evidence_ref:=btrim(coalesce(v_check->>'evidence_ref',''));
    v_error_class:=nullif(btrim(coalesce(v_check->>'error_class','')),'');
    if not(v_check?'expected') or not(v_check?'actual') or not(v_check?'rc') then
      return jsonb_build_object('outcome','BLOCKED','code','LF_GATE_ERROR_V1_CHECK_SHAPE_INCOMPLETE','check_id',v_check_id,'durable',false);
    end if;
    if v_status not in ('PASS','FAIL','BLOCKED','SKIPPED') or v_condition='' or v_producer='' or v_evidence_ref='' then
      return jsonb_build_object('outcome','BLOCKED','code','LF_GATE_ERROR_V1_CHECK_METADATA_INVALID','check_id',v_check_id,'durable',false);
    end if;
    if v_status in ('FAIL','BLOCKED') and v_error_class is null then
      return jsonb_build_object('outcome','BLOCKED','code','LF_GATE_ERROR_V1_ERROR_CLASS_REQUIRED','check_id',v_check_id,'durable',false);
    end if;
    if jsonb_typeof(v_check->'rc')<>'number' then
      return jsonb_build_object('outcome','BLOCKED','code','LF_GATE_ERROR_V1_RC_INVALID','check_id',v_check_id,'durable',false);
    end if;
  end loop;

  if p_gate_mode='COLLECT_ALL' then
    if v_seen_count<>v_expected_count or exists(select 1 from unnest(v_expected) q where not(q=any(v_seen))) then
      return jsonb_build_object('outcome','BLOCKED','code','LF_GATE_ERROR_V1_COLLECT_ALL_INCOMPLETE','expected_count',v_expected_count,'seen_count',v_seen_count,'durable',false);
    end if;
  else
    v_pos:=0;
    for v_check in select value from jsonb_array_elements(p_checks) loop
      v_pos:=v_pos+1;
      v_status:=upper(v_check->>'status');
      if v_status in ('FAIL','BLOCKED') and coalesce((v_check->>'critical')::boolean,false) then v_stop_pos:=v_pos; exit; end if;
    end loop;
    if v_stop_pos is null then
      if v_seen_count<>v_expected_count or exists(select 1 from unnest(v_expected) q where not(q=any(v_seen))) then
        return jsonb_build_object('outcome','BLOCKED','code','LF_GATE_ERROR_V1_FAIL_FAST_WITHOUT_CRITICAL_STOP_INCOMPLETE','durable',false);
      end if;
    else
      if v_seen_count<>v_stop_pos then return jsonb_build_object('outcome','BLOCKED','code','LF_GATE_ERROR_V1_FAIL_FAST_EXECUTED_AFTER_CRITICAL_FAILURE','durable',false); end if;
      select ord::int into v_expected_pos from unnest(v_expected) with ordinality t(v,ord) where v=(p_checks->(v_stop_pos-1)->>'check_id');
      if v_expected_pos is distinct from v_stop_pos then return jsonb_build_object('outcome','BLOCKED','code','LF_GATE_ERROR_V1_FAIL_FAST_ORDER_MISMATCH','durable',false); end if;
      if v_stop_pos<v_expected_count then v_remaining:=v_expected[(v_stop_pos+1):v_expected_count]; end if;
    end if;
  end if;

  for v_check in select value from jsonb_array_elements(p_checks) loop
    v_check_id:=btrim(v_check->>'check_id');
    v_status:=upper(btrim(v_check->>'status'));
    v_condition:=btrim(v_check->>'condition');
    v_expected_value:=v_check->'expected';
    v_actual_value:=v_check->'actual';
    v_producer:=btrim(v_check->>'producer');
    v_evidence_ref:=btrim(v_check->>'evidence_ref');
    v_input_ref:=nullif(btrim(coalesce(v_check->>'input_ref','')),'');
    v_error_class:=nullif(btrim(coalesce(v_check->>'error_class','')),'');
    v_rc:=(v_check->>'rc')::int;
    v_downstream:=coalesce(v_check->'downstream_impact',p_context->'downstream_impact','{}'::jsonb);
    v_trace:=lf_ops.new_trace_code();
    v_occurrence:=null;

    if v_status='PASS' then v_pass:=v_pass+1;
    elsif v_status='FAIL' then v_fail:=v_fail+1;
    elsif v_status='BLOCKED' then v_blocked:=v_blocked+1;
    else v_skipped:=v_skipped+1;
    end if;

    if v_status in ('FAIL','BLOCKED') then
      v_error_code:=case when v_status='FAIL' then 'LF-GATE-CHECK-FAILED' else 'LF-GATE-CHECK-BLOCKED' end;
      select * into v_error from lf_ops.errores_catalogo ec
      where ec.error_code=v_error_code and ec.status='VIGENTE' order by ec.error_id desc limit 1;
      if not found then raise exception 'LF_GATE_ERROR_V1_ERROR_CATALOG_MISSING:%',v_error_code; end if;
      insert into lf_ops.errores_ocurrencias(
        trace_code,error_code,error_id,correlation_id,technical_fingerprint,severity,environment,
        payload_redacted,resolution_status,provider_code,occurred_at
      ) values(
        v_trace,v_error_code,v_error.error_id,v_corr,
        encode(extensions.digest(v_batch_sha||':'||v_check_id||':'||v_attempt::text,'sha256'),'hex'),
        v_error.severity,v_environment,
        jsonb_build_object(
          'contract','LF_GATE_ERROR_V1','run_id',v_run_id,'job_id',v_job_id,
          'execution_id',p_execution_id,'operation_code',v_exec.operation_code,'step_id',p_step_id,'step_order',v_step.step_order,
          'gate_id',p_gate_id,'check_id',v_check_id,'error_class',v_error_class,'condition',v_condition,
          'expected',v_expected_value,'actual',v_actual_value,'input_ref',v_input_ref,'evidence_ref',v_evidence_ref,'producer',v_producer,
          'source_commit',v_source_commit,'source_path',v_source_path,'trace_id',v_trace,'parent_trace_id',v_parent_trace,'rc',v_rc,
          'downstream_impact',v_downstream,'owner',coalesce(nullif(btrim(v_check->>'owner'),''),v_owner),
          'next_action',coalesce(nullif(btrim(v_check->>'next_action'),''),v_next_action),'attempt_no',v_attempt,'batch_sha256',v_batch_sha
        ),'OPEN','LF_GATE_ERROR_V1',clock_timestamp()
      ) returning occurrence_id into v_occurrence;
      v_errors:=v_errors||jsonb_build_array(jsonb_build_object('check_id',v_check_id,'error_code',v_error_code,
        'error_id',v_error.error_id,'occurrence_id',v_occurrence,'trace_id',v_trace));
    end if;

    insert into public.lf_operation_gate_check_results(
      execution_id,operation_code,step_order,step_id,gate_id,gate_mode,attempt_no,check_id,check_status,
      error_id,error_occurrence_id,error_class,check_condition,expected,actual,input_ref,evidence_ref,producer,
      run_id,job_id,source_commit,source_path,trace_id,parent_trace_id,rc,downstream_impact,owner,next_action,batch_sha256,created_by_execution_id
    ) values(
      p_execution_id,v_exec.operation_code,v_step.step_order,p_step_id,p_gate_id,p_gate_mode,v_attempt,v_check_id,v_status,
      case when v_occurrence is null then null else v_error.error_id end,v_occurrence,v_error_class,v_condition,v_expected_value,v_actual_value,
      v_input_ref,v_evidence_ref,v_producer,v_run_id,v_job_id,v_source_commit,v_source_path,v_trace,v_parent_trace,v_rc,v_downstream,
      coalesce(nullif(btrim(v_check->>'owner'),''),v_owner),coalesce(nullif(btrim(v_check->>'next_action'),''),v_next_action),v_batch_sha,p_actor_execution_id
    );
  end loop;

  v_gate_result:=case when v_blocked>0 or v_skipped>0 then 'BLOCKED' when v_fail>0 then 'FAIL' else 'PASS' end;
  v_summary:=jsonb_build_object('contract','LF_GATE_ERROR_V1','gate_id',p_gate_id,'gate_mode',p_gate_mode,'attempt_no',v_attempt,
    'gate_result',v_gate_result,'expected_check_count',v_expected_count,'executed_check_count',v_seen_count,
    'pass_count',v_pass,'fail_count',v_fail,'blocked_count',v_blocked,'skipped_count',v_skipped,
    'parent_trace_id',v_parent_trace,'batch_sha256',v_batch_sha,'error_occurrences',v_errors,
    'remaining_after_fail_fast',to_jsonb(v_remaining),
    'diagnostic_ref','supabase://public/lf_operation_gate_check_results/'||p_execution_id||'/'||p_step_id||'/'||p_gate_id||'/attempt/'||v_attempt);

  select * into v_step_exec from public.lf_operation_execution_steps
  where execution_id=p_execution_id and step_order=v_step.step_order and step_id=p_step_id for update;
  if found then
    v_conflict:=v_gate_result<>'PASS' and v_step_exec.status in ('PASS','PASS_CLEAN','STEP_PASS_WITH_EVIDENCE','TOP_TIER_PASS');
    update public.lf_operation_execution_steps
    set evidence_payload=coalesce(evidence_payload,'{}'::jsonb)||jsonb_build_object('gate_check_contract_v1',v_summary),
        updated_by_execution_id=p_actor_execution_id,updated_at=clock_timestamp()
    where execution_id=p_execution_id and step_order=v_step.step_order and step_id=p_step_id;
  end if;

  return jsonb_build_object('outcome','RECORDED','execution_id',p_execution_id,'operation_code',v_exec.operation_code,
    'step_id',p_step_id,'step_order',v_step.step_order,'gate_id',p_gate_id,'gate_result',v_gate_result,
    'step_status_conflict',v_conflict,'summary',v_summary);
end;
$function$;

revoke execute on function public.lf_record_gate_checks_v1(text,text,text,text,jsonb,jsonb,jsonb,text) from public,anon,authenticated;
revoke execute on function public.lf_gate_check_diagnostic_v1(text,text,text,integer) from public,anon,authenticated;
grant execute on function public.lf_record_gate_checks_v1(text,text,text,text,jsonb,jsonb,jsonb,text) to service_role;
grant execute on function public.lf_gate_check_diagnostic_v1(text,text,text,integer) to service_role;

comment on table public.lf_operation_gate_check_results is
'Check-level ledger beneath the canonical LF operation execution/step workflow. Non-pass checks reuse lf_ops.errores_ocurrencias.';
comment on function public.lf_record_gate_checks_v1(text,text,text,text,jsonb,jsonb,jsonb,text) is
'LF_GATE_ERROR_V1. COLLECT_ALL requires every declared check; FAIL_FAST_CRITICAL may stop only at the declared critical failing check.';

commit;
