-- S30 remediation: canonical lifecycle state authority + terminal operational Strategy lifecycle operations.
-- Existing in-flight executions remain pinned to their start-time policy/manifest snapshots.
DO $pre$ DECLARE v text; BEGIN
 SELECT max(version) INTO v FROM supabase_migrations.schema_migrations;
 IF v IS DISTINCT FROM '20260914052654' THEN RAISE EXCEPTION 'S30_LIFECYCLE_MIGRATION_LEDGER_DRIFT:%',v; END IF;
 IF NOT EXISTS (SELECT 1 FROM public.lf_operation_execution WHERE execution_id='EXEC-S30-STATE-LIFECYCLE-CANONICALIZATION-20260914-001' AND operation_code='ACTUALIZACION_DB_LF' AND status='IN_PROGRESS') THEN RAISE EXCEPTION 'S30_LIFECYCLE_DB_EXECUTION_BINDING_INVALID'; END IF;
 IF NOT EXISTS (SELECT 1 FROM public.lf_operation_execution WHERE execution_id='EXEC-S30-STRATEGY-UPDATE-PROMOTE-20260914-001' AND operation_code='ACTUALIZACION_ESTRATEGIA_LF' AND status='IN_PROGRESS') THEN RAISE EXCEPTION 'S30_STRATEGY_UPDATE_PROMOTION_EXECUTION_BINDING_INVALID'; END IF;
 IF NOT EXISTS (SELECT 1 FROM public.lf_operation_execution WHERE execution_id='EXEC-S30-STRATEGY-EXEC-PROMOTE-20260914-001' AND operation_code='EJECUCION_ESTRATEGIA_LF' AND status='IN_PROGRESS') THEN RAISE EXCEPTION 'S30_STRATEGY_EXEC_PROMOTION_EXECUTION_BINDING_INVALID'; END IF;
END $pre$;

DO $ddl$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid='lf_ops.estados_catalogo'::regclass AND conname='estados_catalogo_state_code_uk') THEN ALTER TABLE lf_ops.estados_catalogo ADD CONSTRAINT estados_catalogo_state_code_uk UNIQUE (state_code); END IF; END $ddl$;

INSERT INTO lf_ops.estados_catalogo(state_code,entity_type,state_name,description,is_initial,is_terminal,status,source_decision_id)
SELECT * FROM (VALUES
 ('OP_CANDIDATE','OPERATION_LIFECYCLE','CANDIDATE','Operation exists but is not yet serving governed operational traffic.',true,false,'VIGENTE','S30-CANONICAL-LIFECYCLE-20260914'),
 ('OP_OPERATIONAL','OPERATION_LIFECYCLE','OPERATIONAL','Operation is serving through its governed Router/contract path.',false,false,'VIGENTE','S30-CANONICAL-LIFECYCLE-20260914'),
 ('OP_RETIRED','OPERATION_LIFECYCLE','RETIRED','Operation is no longer available for new governed executions.',false,true,'VIGENTE','S30-CANONICAL-LIFECYCLE-20260914'),
 ('STRATEGY_PLANNED','STRATEGY_LIFECYCLE','PLANNED','Strategy exists and is eligible to start execution.',true,false,'VIGENTE','S30-CANONICAL-LIFECYCLE-20260914'),
 ('STRATEGY_ACTIVE','STRATEGY_LIFECYCLE','ACTIVE','Strategy has started governed execution and remains open.',false,false,'VIGENTE','S30-CANONICAL-LIFECYCLE-20260914'),
 ('STRATEGY_CLOSED','STRATEGY_LIFECYCLE','CLOSED','Strategy reached governed terminal close.',false,true,'VIGENTE','S30-CANONICAL-LIFECYCLE-20260914'),
 ('STRATEGY_SUPERSEDED','STRATEGY_LIFECYCLE','SUPERSEDED','Strategy was replaced by a successor and is terminal.',false,true,'VIGENTE','S30-CANONICAL-LIFECYCLE-20260914')
) v(state_code,entity_type,state_name,description,is_initial,is_terminal,status,source_decision_id)
WHERE NOT EXISTS (SELECT 1 FROM lf_ops.estados_catalogo e WHERE e.state_code=v.state_code);

INSERT INTO lf_ops.estados_transiciones(transition_code,entity_type,from_state_code,to_state_code,action_code,required_permission_code,requires_comment,requires_idempotency_key,audit_required,condition_config,status,source_decision_id,from_state_id,to_state_id)
SELECT x.transition_code,x.entity_type,x.from_state_code,x.to_state_code,x.action_code,NULL,false,true,true,jsonb_build_object('canonical_lifecycle',true),'VIGENTE','S30-CANONICAL-LIFECYCLE-20260914',f.state_id,t.state_id
FROM (VALUES
 ('TR_OP_CANDIDATE_OPERATIONAL','OPERATION_LIFECYCLE','OP_CANDIDATE','OP_OPERATIONAL','PROMOTE_OPERATION'),('TR_OP_OPERATIONAL_RETIRED','OPERATION_LIFECYCLE','OP_OPERATIONAL','OP_RETIRED','RETIRE_OPERATION'),('TR_STRATEGY_PLANNED_ACTIVE','STRATEGY_LIFECYCLE','STRATEGY_PLANNED','STRATEGY_ACTIVE','START_EXECUTION'),('TR_STRATEGY_PLANNED_CLOSED','STRATEGY_LIFECYCLE','STRATEGY_PLANNED','STRATEGY_CLOSED','CLOSE_STRATEGY'),('TR_STRATEGY_ACTIVE_CLOSED','STRATEGY_LIFECYCLE','STRATEGY_ACTIVE','STRATEGY_CLOSED','CLOSE_STRATEGY'),('TR_STRATEGY_PLANNED_SUPERSEDED','STRATEGY_LIFECYCLE','STRATEGY_PLANNED','STRATEGY_SUPERSEDED','SUPERSEDE_STRATEGY'),('TR_STRATEGY_ACTIVE_SUPERSEDED','STRATEGY_LIFECYCLE','STRATEGY_ACTIVE','STRATEGY_SUPERSEDED','SUPERSEDE_STRATEGY')
) x(transition_code,entity_type,from_state_code,to_state_code,action_code)
JOIN lf_ops.estados_catalogo f ON f.state_code=x.from_state_code AND f.entity_type=x.entity_type
JOIN lf_ops.estados_catalogo t ON t.state_code=x.to_state_code AND t.entity_type=x.entity_type
ON CONFLICT (entity_type,from_state_code,to_state_code,action_code) DO NOTHING;

ALTER TABLE public.lf_operation_registry ADD COLUMN IF NOT EXISTS lifecycle_state_code text;
ALTER TABLE public.lf_strategy_snapshots ADD COLUMN IF NOT EXISTS lifecycle_state_code text;

CREATE OR REPLACE FUNCTION public.fn_lf_strategy_closed_immutable_v1() RETURNS trigger LANGUAGE plpgsql SET search_path TO 'pg_catalog','public' AS $fn$
BEGIN
 IF coalesce(OLD.metadata->'strategy_close'->>'status','')='CLOSED' THEN
  IF TG_OP='UPDATE' AND OLD.lifecycle_state_code IS NULL AND NEW.lifecycle_state_code IN ('STRATEGY_CLOSED','STRATEGY_SUPERSEDED') AND (to_jsonb(NEW)-'lifecycle_state_code') IS NOT DISTINCT FROM (to_jsonb(OLD)-'lifecycle_state_code') THEN RETURN NEW; END IF;
  RAISE EXCEPTION 'LF_STRATEGY_CLOSED_READ_ONLY:%',OLD.snapshot_code USING errcode='23514';
 END IF;
 IF TG_OP='DELETE' THEN RETURN OLD; END IF; RETURN NEW;
END $fn$;

UPDATE public.lf_operation_registry SET lifecycle_state_code=CASE WHEN status IN ('PRODUCCION_CONTROLADA_READ_ONLY','APROBADO_PRODUCCION_CONTROLADA_READ_ONLY','PRODUCCION_CONTROLADA','APROBADO_PRODUCCION_CONTROLADA') THEN 'OP_OPERATIONAL' WHEN status IN ('CANDIDATO_READ_ONLY','SANDBOX_ACTIVE','ACTIVE_ENFORCEMENT_TEST') THEN 'OP_CANDIDATE' ELSE NULL END WHERE lifecycle_state_code IS NULL;
UPDATE public.lf_strategy_snapshots SET lifecycle_state_code=CASE WHEN status IN ('SUPERSEDED','DEPRECATED_SANDBOX_NO_CANONICAL') THEN 'STRATEGY_SUPERSEDED' WHEN coalesce(metadata->'strategy_close'->>'status','')='CLOSED' OR coalesce(metadata->'progress'->>'progress_state','') ILIKE 'CLOSED%' OR coalesce(metadata->'progress'->>'current_stage','')='TERMINAL' THEN 'STRATEGY_CLOSED' WHEN status='IMPLEMENTACION_P0_EN_CURSO' OR nullif(metadata->'progress'->>'current_stage','') IS NOT NULL OR nullif(metadata->'progress'->>'progress_state','') IS NOT NULL THEN 'STRATEGY_ACTIVE' ELSE 'STRATEGY_PLANNED' END WHERE lifecycle_state_code IS NULL;

CREATE OR REPLACE FUNCTION public.fn_lf_strategy_closed_immutable_v1() RETURNS trigger LANGUAGE plpgsql SET search_path TO 'pg_catalog','public' AS $fn$ BEGIN IF coalesce(OLD.metadata->'strategy_close'->>'status','')='CLOSED' THEN RAISE EXCEPTION 'LF_STRATEGY_CLOSED_READ_ONLY:%',OLD.snapshot_code USING errcode='23514'; END IF; IF TG_OP='DELETE' THEN RETURN OLD; END IF; RETURN NEW; END $fn$;

DO $backfill$ BEGIN IF EXISTS (SELECT 1 FROM public.lf_operation_registry WHERE lifecycle_state_code IS NULL) THEN RAISE EXCEPTION 'S30_OPERATION_LIFECYCLE_BACKFILL_UNMAPPED'; END IF; IF EXISTS (SELECT 1 FROM public.lf_strategy_snapshots WHERE lifecycle_state_code IS NULL) THEN RAISE EXCEPTION 'S30_STRATEGY_LIFECYCLE_BACKFILL_UNMAPPED'; END IF; END $backfill$;
ALTER TABLE public.lf_operation_registry ALTER COLUMN lifecycle_state_code SET DEFAULT 'OP_CANDIDATE'; ALTER TABLE public.lf_operation_registry ALTER COLUMN lifecycle_state_code SET NOT NULL;
ALTER TABLE public.lf_strategy_snapshots ALTER COLUMN lifecycle_state_code SET DEFAULT 'STRATEGY_PLANNED'; ALTER TABLE public.lf_strategy_snapshots ALTER COLUMN lifecycle_state_code SET NOT NULL;
DO $constraints$ BEGIN
 IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid='public.lf_operation_registry'::regclass AND conname='lf_operation_registry_lifecycle_state_fkey') THEN ALTER TABLE public.lf_operation_registry ADD CONSTRAINT lf_operation_registry_lifecycle_state_fkey FOREIGN KEY (lifecycle_state_code) REFERENCES lf_ops.estados_catalogo(state_code) ON UPDATE RESTRICT ON DELETE RESTRICT; END IF;
 IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid='public.lf_strategy_snapshots'::regclass AND conname='lf_strategy_snapshots_lifecycle_state_fkey') THEN ALTER TABLE public.lf_strategy_snapshots ADD CONSTRAINT lf_strategy_snapshots_lifecycle_state_fkey FOREIGN KEY (lifecycle_state_code) REFERENCES lf_ops.estados_catalogo(state_code) ON UPDATE RESTRICT ON DELETE RESTRICT; END IF;
 IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid='public.lf_operation_registry'::regclass AND conname='lf_operation_registry_lifecycle_prefix_ck') THEN ALTER TABLE public.lf_operation_registry ADD CONSTRAINT lf_operation_registry_lifecycle_prefix_ck CHECK (lifecycle_state_code LIKE 'OP_%'); END IF;
 IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid='public.lf_strategy_snapshots'::regclass AND conname='lf_strategy_snapshots_lifecycle_prefix_ck') THEN ALTER TABLE public.lf_strategy_snapshots ADD CONSTRAINT lf_strategy_snapshots_lifecycle_prefix_ck CHECK (lifecycle_state_code LIKE 'STRATEGY_%'); END IF;
END $constraints$;
CREATE INDEX IF NOT EXISTS idx_lf_operation_registry_lifecycle_state ON public.lf_operation_registry(lifecycle_state_code); CREATE INDEX IF NOT EXISTS idx_lf_strategy_snapshots_lifecycle_state ON public.lf_strategy_snapshots(lifecycle_state_code);

CREATE OR REPLACE FUNCTION public.lf_enforce_lifecycle_transition_v1() RETURNS trigger LANGUAGE plpgsql SET search_path TO 'pg_catalog','public' AS $fn$ DECLARE v_entity_type text:=TG_ARGV[0]; BEGIN IF NEW.lifecycle_state_code IS NOT DISTINCT FROM OLD.lifecycle_state_code THEN RETURN NEW; END IF; IF NOT EXISTS (SELECT 1 FROM lf_ops.estados_catalogo s WHERE s.state_code=NEW.lifecycle_state_code AND s.entity_type=v_entity_type AND s.status='VIGENTE') THEN RAISE EXCEPTION 'LF_LIFECYCLE_TARGET_STATE_INVALID:%:%',v_entity_type,NEW.lifecycle_state_code; END IF; IF NOT EXISTS (SELECT 1 FROM lf_ops.estados_transiciones t WHERE t.entity_type=v_entity_type AND t.from_state_code=OLD.lifecycle_state_code AND t.to_state_code=NEW.lifecycle_state_code AND t.status='VIGENTE') THEN RAISE EXCEPTION 'LF_LIFECYCLE_TRANSITION_NOT_ALLOWED:%:%:%',v_entity_type,OLD.lifecycle_state_code,NEW.lifecycle_state_code; END IF; RETURN NEW; END $fn$;
DROP TRIGGER IF EXISTS trg_lf_operation_registry_lifecycle_transition_v1 ON public.lf_operation_registry; CREATE TRIGGER trg_lf_operation_registry_lifecycle_transition_v1 BEFORE UPDATE OF lifecycle_state_code ON public.lf_operation_registry FOR EACH ROW EXECUTE FUNCTION public.lf_enforce_lifecycle_transition_v1('OPERATION_LIFECYCLE');
DROP TRIGGER IF EXISTS trg_lf_strategy_snapshots_lifecycle_transition_v1 ON public.lf_strategy_snapshots; CREATE TRIGGER trg_lf_strategy_snapshots_lifecycle_transition_v1 BEFORE UPDATE OF lifecycle_state_code ON public.lf_strategy_snapshots FOR EACH ROW EXECUTE FUNCTION public.lf_enforce_lifecycle_transition_v1('STRATEGY_LIFECYCLE');

CREATE OR REPLACE FUNCTION public.lf_operation_policy_snapshot_guard_v1() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path TO '' AS $fn$ DECLARE r record; v_ok boolean; BEGIN IF OLD.manifest ? 'operation_policy_snapshots' AND (OLD.manifest->'operation_policy_snapshots') IS DISTINCT FROM (NEW.manifest->'operation_policy_snapshots') THEN RAISE EXCEPTION 'BLOCK_POLICY_SNAPSHOT_IMMUTABLE execution=% operation=%',NEW.execution_id,NEW.operation_code; END IF; IF NEW.status IS DISTINCT FROM OLD.status THEN IF NOT (NEW.manifest ? 'operation_policy_snapshots') THEN RAISE EXCEPTION 'BLOCK_OPERATION_POLICY_MISSING execution=% operation=%',NEW.execution_id,NEW.operation_code; END IF; FOR r IN SELECT key AS policy_role,value AS snapshot FROM jsonb_each(NEW.manifest->'operation_policy_snapshots') LOOP SELECT EXISTS(SELECT 1 FROM public.lf_policy_versions p WHERE p.policy_code=r.snapshot->>'policy_code' AND p.policy_version=r.snapshot->>'policy_version' AND p.policy_sha=r.snapshot->>'policy_sha' AND p.effective_at<=OLD.started_at AND (p.superseded_at IS NULL OR p.superseded_at>OLD.started_at)) INTO v_ok; IF NOT v_ok THEN RAISE EXCEPTION 'BLOCK_OPERATION_POLICY_START_SNAPSHOT_INVALID execution=% role=% policy=% version=%',NEW.execution_id,r.policy_role,r.snapshot->>'policy_code',r.snapshot->>'policy_version'; END IF; END LOOP; END IF; RETURN NEW; END $fn$;

UPDATE public.lf_policy_versions SET status='SUPERSEDED',superseded_at=clock_timestamp(),updated_by_execution_id='EXEC-S30-STATE-LIFECYCLE-CANONICALIZATION-20260914-001' WHERE policy_code='POL-LF-STATE-MODEL' AND status='ACTIVE';
DO $policy$ DECLARE p jsonb; BEGIN p:=jsonb_build_object('rules',jsonb_build_array('LIFECYCLE_STATE_FROM_CANONICAL_CATALOG','SANDBOX_READONLY_AND_IMPACT_ARE_NOT_LIFECYCLE_STATES','LEGACY_STATE_FIELDS_COMPATIBILITY_ONLY','UNKNOWN_STATE_BLOCKS_ACTION'),'scope','TRANSVERSAL_LF_GOVERNANCE','version','v2.0-canonical-lifecycle','authority','SUPABASE','policy_kind','STATE_MODEL_POLICY','canonical_catalog','lf_ops.estados_catalogo','transition_catalog','lf_ops.estados_transiciones','lifecycle_states',jsonb_build_object('OPERATION_LIFECYCLE',jsonb_build_array('OP_CANDIDATE','OP_OPERATIONAL','OP_RETIRED'),'STRATEGY_LIFECYCLE',jsonb_build_array('STRATEGY_PLANNED','STRATEGY_ACTIVE','STRATEGY_CLOSED','STRATEGY_SUPERSEDED')),'compatibility',jsonb_build_object('operation_registry_status','NON_AUTHORITATIVE_PROJECTION','strategy_snapshot_status','NON_AUTHORITATIVE_PROJECTION','runtime_state','EXECUTION_MODE_COMPATIBILITY_NOT_LIFECYCLE','visibility','ACCESS_MODE_COMPATIBILITY_NOT_LIFECYCLE','impact_policy','PERMISSION_GATE_NOT_LIFECYCLE','legacy_alias_catalog','public.cat_estado_normalizacion_lf'),'application','ALL_ROUTER_GOVERNED_ASSET_AND_OPERATION_STATE_DECISIONS'); INSERT INTO public.lf_policy_versions(policy_code,policy_version,policy_payload,policy_sha,status,effective_at,source_ref,created_by_execution_id,updated_by_execution_id) VALUES('POL-LF-STATE-MODEL','v2.0-canonical-lifecycle',p,encode(extensions.digest(convert_to(p::text,'UTF8'),'sha256'),'hex'),'ACTIVE',clock_timestamp(),'supabase://lf_ops/estados_catalogo','EXEC-S30-STATE-LIFECYCLE-CANONICALIZATION-20260914-001','EXEC-S30-STATE-LIFECYCLE-CANONICALIZATION-20260914-001'); END $policy$;

DO $router_patch$ DECLARE v_def text; v_old text:=$x$'operation_status',v_operation.status,'operation_applies_to_asset_type'$x$; v_new text:=$x$'operation_status',v_operation.status,'operation_lifecycle_state',v_operation.lifecycle_state_code,'operation_applies_to_asset_type'$x$; BEGIN SELECT pg_get_functiondef('public.lf_router_resolve_v1(text,text,text,text,text)'::regprocedure) INTO v_def; IF strpos(v_def,v_old)=0 THEN RAISE EXCEPTION 'S30_ROUTER_LIFECYCLE_PATCH_SOURCE_DRIFT'; END IF; EXECUTE replace(v_def,v_old,v_new); END $router_patch$;

DO $update_writer_patch$ DECLARE v_def text; v_old text; v_new text; BEGIN SELECT pg_get_functiondef('public.lf_strategy_update_write_v1(text,bigint,text,jsonb)'::regprocedure) INTO v_def; v_old:=$x$if coalesce(s.metadata->'strategy_close'->>'status','')='CLOSED' then$x$; v_new:=$x$if s.lifecycle_state_code in ('STRATEGY_CLOSED','STRATEGY_SUPERSEDED') or coalesce(s.metadata->'strategy_close'->>'status','')='CLOSED' then$x$; IF strpos(v_def,v_old)=0 THEN RAISE EXCEPTION 'S30_STRATEGY_UPDATE_CLOSED_GUARD_SOURCE_DRIFT'; END IF; v_def:=replace(v_def,v_old,v_new); v_old:=$x$if s.status<>'CANDIDATO_READ_ONLY' or s.visibility<>'READ_ONLY_INTERNAL' or s.runtime_state not in ('NO_HABILITADO','PLAN_ONLY') or s.impact_policy not in ('BLOQUEADO','NO_AUTOMATIC_PROMOTION') then$x$; v_new:=$x$if s.lifecycle_state_code not in ('STRATEGY_PLANNED','STRATEGY_ACTIVE') or s.impact_policy not in ('BLOQUEADO','NO_AUTOMATIC_PROMOTION') then$x$; IF strpos(v_def,v_old)=0 THEN RAISE EXCEPTION 'S30_STRATEGY_UPDATE_LEGACY_GUARD_SOURCE_DRIFT'; END IF; v_def:=replace(v_def,v_old,v_new); v_def:=replace(v_def,$x$raise exception 'LF_STRATEGY_UPDATE_CANDIDATE_READ_ONLY_CEILING_REQUIRED';$x$,$x$raise exception 'LF_STRATEGY_UPDATE_LIFECYCLE_STATE_REQUIRED';$x$); v_old:=$x$if a.status is distinct from s.status
     or a.visibility is distinct from s.visibility$x$; v_new:=$x$if a.lifecycle_state_code is distinct from s.lifecycle_state_code
     or a.status is distinct from s.status
     or a.visibility is distinct from s.visibility$x$; IF strpos(v_def,v_old)=0 THEN RAISE EXCEPTION 'S30_STRATEGY_UPDATE_POSTWRITE_GUARD_SOURCE_DRIFT'; END IF; v_def:=replace(v_def,v_old,v_new); EXECUTE v_def; END $update_writer_patch$;

DO $close_writer_patch$ DECLARE v_def text; v_old text; v_new text; BEGIN SELECT pg_get_functiondef('public.lf_strategy_close_write_v1(text,bigint,text,text,text,jsonb)'::regprocedure) INTO v_def; v_old:=$x$IF coalesce(s.metadata->'strategy_close'->>'status','')='CLOSED' THEN$x$; v_new:=$x$IF s.lifecycle_state_code IN ('STRATEGY_CLOSED','STRATEGY_SUPERSEDED') OR coalesce(s.metadata->'strategy_close'->>'status','')='CLOSED' THEN$x$; IF strpos(v_def,v_old)=0 THEN RAISE EXCEPTION 'S30_STRATEGY_CLOSE_CLOSED_GUARD_SOURCE_DRIFT'; END IF; v_def:=replace(v_def,v_old,v_new); v_old:=$x$UPDATE public.lf_strategy_snapshots SET metadata=$x$; v_new:=$x$UPDATE public.lf_strategy_snapshots SET lifecycle_state_code='STRATEGY_CLOSED',metadata=$x$; IF strpos(v_def,v_old)=0 THEN RAISE EXCEPTION 'S30_STRATEGY_CLOSE_UPDATE_SOURCE_DRIFT'; END IF; v_def:=replace(v_def,v_old,v_new); v_old:=$x$IF a.status IS DISTINCT FROM s.status OR a.archived_at$x$; v_new:=$x$IF a.lifecycle_state_code<>'STRATEGY_CLOSED' OR a.status IS DISTINCT FROM s.status OR a.archived_at$x$; IF strpos(v_def,v_old)=0 THEN RAISE EXCEPTION 'S30_STRATEGY_CLOSE_POSTWRITE_SOURCE_DRIFT'; END IF; v_def:=replace(v_def,v_old,v_new); EXECUTE v_def; END $close_writer_patch$;

CREATE OR REPLACE FUNCTION public.lf_strategy_lifecycle_from_execution_step_v1() RETURNS trigger LANGUAGE plpgsql SET search_path TO 'pg_catalog','public' AS $fn$ DECLARE x public.lf_operation_execution%rowtype; s public.lf_strategy_snapshots%rowtype; BEGIN IF NEW.step_id<>'strategy_resolve' OR NEW.status<>'PASS_CLEAN' THEN RETURN NEW; END IF; SELECT * INTO x FROM public.lf_operation_execution WHERE execution_id=NEW.execution_id; IF NOT FOUND OR x.operation_code<>'EJECUCION_ESTRATEGIA_LF' OR x.target_type<>'STRATEGY' THEN RETURN NEW; END IF; SELECT * INTO s FROM public.lf_strategy_snapshots WHERE snapshot_code=x.target_code FOR UPDATE; IF NOT FOUND THEN RAISE EXCEPTION 'LF_STRATEGY_EXECUTION_TARGET_MISSING:%',x.target_code; END IF; IF s.lifecycle_state_code IN ('STRATEGY_CLOSED','STRATEGY_SUPERSEDED') THEN RAISE EXCEPTION 'LF_STRATEGY_EXECUTION_TERMINAL_STRATEGY:%:%',s.snapshot_code,s.lifecycle_state_code; END IF; IF s.lifecycle_state_code='STRATEGY_PLANNED' THEN UPDATE public.lf_strategy_snapshots SET lifecycle_state_code='STRATEGY_ACTIVE',updated_at=clock_timestamp(),updated_by_execution_id=x.execution_id WHERE id=s.id; END IF; RETURN NEW; END $fn$;
DROP TRIGGER IF EXISTS trg_lf_strategy_lifecycle_from_execution_step_v1 ON public.lf_operation_execution_steps; CREATE TRIGGER trg_lf_strategy_lifecycle_from_execution_step_v1 AFTER INSERT OR UPDATE OF status ON public.lf_operation_execution_steps FOR EACH ROW EXECUTE FUNCTION public.lf_strategy_lifecycle_from_execution_step_v1();

UPDATE public.lf_operation_contracts SET allowed=(allowed-'candidate_read_only_only'-'allowed_runtime_states') || jsonb_build_object('allowed_lifecycle_states',jsonb_build_array('STRATEGY_PLANNED','STRATEGY_ACTIVE'),'legacy_state_fields_authoritative',false,'production_execution_allowed',true,'state_mutation',false,'runtime_change',false,'production_change',false),blocked=(SELECT coalesce(jsonb_agg(to_jsonb(v)),'[]'::jsonb) FROM jsonb_array_elements_text(blocked) v WHERE v<>'production'),updated_by_execution_id='EXEC-S30-STRATEGY-UPDATE-PROMOTE-20260914-001',updated_at=clock_timestamp() WHERE operation_code='ACTUALIZACION_ESTRATEGIA_LF' AND status='ACTIVE_ENFORCEMENT';
UPDATE public.lf_operation_registry SET status='PRODUCCION_CONTROLADA',version='v1.0',lifecycle_state_code='OP_OPERATIONAL',notes='Operational governed Strategy update. Canonical lifecycle PLANNED/ACTIVE are writable; CLOSED/SUPERSEDED fail closed. Legacy status/runtime/visibility are compatibility projections. No automatic strategy/runtime/impact promotion.',updated_by_execution_id='EXEC-S30-STRATEGY-UPDATE-PROMOTE-20260914-001',updated_at=clock_timestamp() WHERE operation_code='ACTUALIZACION_ESTRATEGIA_LF';

UPDATE public.lf_operation_contracts SET contract_code='CONTRACT-EJECUCION-ESTRATEGIA-LF-v1',allowed=allowed || jsonb_build_object('production_execution_allowed',true,'production_activation',false,'business_effect_dispatch_allowed',true,'governed_child_dispatch_only',true,'direct_business_write_allowed',false,'execution_start_snapshot_pinning',true,'legacy_state_fields_authoritative',false,'scheduler_activation',false,'orchestrator_activation',false),updated_by_execution_id='EXEC-S30-STRATEGY-EXEC-PROMOTE-20260914-001',updated_at=clock_timestamp() WHERE operation_code='EJECUCION_ESTRATEGIA_LF' AND contract_code='CONTRACT-EJECUCION-ESTRATEGIA-LF-v0.1-candidate';
UPDATE public.lf_operation_step_contracts SET contract_code='CONTRACT-EJECUCION-ESTRATEGIA-LF-v1',pass_condition=(pass_condition-'runtime_mode'-'source_contract') || jsonb_build_object('runtime_mode','GOVERNED_OPERATIONAL_OR_START_PINNED','source_contract','CONTRACT-EJECUCION-ESTRATEGIA-LF-v1_OR_PINNED'),block_condition=(block_condition-'runtime_mode_not_sandbox_controlled') || jsonb_build_object('runtime_mode_not_governed_or_pinned',true,'effect_without_guard',true,'direct_business_write_attempt',true),notes='Operational v1. New executions use governed operational path; executions started before promotion retain immutable start policy/manifest snapshots. Child effects require idempotency/effect guard; no direct business write, scheduler or orchestrator activation.',updated_by_execution_id='EXEC-S30-STRATEGY-EXEC-PROMOTE-20260914-001',updated_at=clock_timestamp() WHERE operation_code='EJECUCION_ESTRATEGIA_LF';
UPDATE public.lf_operation_judges SET pass_if=(pass_if-'runtime_mode'-'source_contract'-'business_effect_dispatch_allowed') || jsonb_build_object('runtime_mode','GOVERNED_OPERATIONAL_OR_START_PINNED','source_contract','CONTRACT-EJECUCION-ESTRATEGIA-LF-v1_OR_PINNED','business_effect_dispatch_allowed',true),fail_if=(fail_if-'business_effect_dispatch_attempt'-'runtime_mode_not_sandbox_controlled') || jsonb_build_object('effect_without_guard',true,'direct_business_write_attempt',true,'runtime_mode_not_governed_or_pinned',true,'scheduler_activation_attempt',true,'orchestrator_activation_attempt',true),updated_by_execution_id='EXEC-S30-STRATEGY-EXEC-PROMOTE-20260914-001',updated_at=clock_timestamp() WHERE operation_code='EJECUCION_ESTRATEGIA_LF';
UPDATE public.lf_router_action_registry SET write_allowed=true,notes='Canonical operational Strategy execution route. One Strategy per child execution. Governed child effects only after idempotency/effect guard; no direct business write, scheduler or orchestrator activation.',updated_at=clock_timestamp() WHERE operation_code='EJECUCION_ESTRATEGIA_LF' AND asset_type='STRATEGY' AND action_code='STRATEGY_EXECUTION' AND status='ACTIVE';
UPDATE public.lf_operation_registry SET status='PRODUCCION_CONTROLADA',version='v1.0',lifecycle_state_code='OP_OPERATIONAL',notes='Operational governed single-Strategy executor. Router-bound, checkpoint/idempotency/effect-guard controlled, governed child-effect dispatch enabled. Existing pre-promotion runs stay pinned to start snapshots. No scheduler, orchestrator or automatic asset promotion.',updated_by_execution_id='EXEC-S30-STRATEGY-EXEC-PROMOTE-20260914-001',updated_at=clock_timestamp() WHERE operation_code='EJECUCION_ESTRATEGIA_LF';

DO $update_canary$ DECLARE s public.lf_strategy_snapshots%rowtype; b text; a text; r jsonb; rr jsonb; BEGIN SELECT * INTO s FROM public.lf_strategy_snapshots WHERE id=35 AND lifecycle_state_code='STRATEGY_ACTIVE' FOR SHARE; IF NOT FOUND THEN RAISE EXCEPTION 'S30_UPDATE_CANARY_FIXTURE_NOT_ACTIVE'; END IF; b:=encode(extensions.digest(to_jsonb(s)::text,'sha256'),'hex'); BEGIN rr:=public.fn_lf_operation_reserve_execution_v1('EXEC-S30-STRATEGY-UPDATE-LIFECYCLE-CANARY-20260914-001','ACTUALIZACION_ESTRATEGIA_LF','STRATEGY',s.snapshot_code,'S30:STRATEGY_UPDATE:LIFECYCLE:ROLLBACK_CANARY:20260914:001',encode(extensions.digest('S30_STRATEGY_UPDATE_LIFECYCLE_ROLLBACK_CANARY','sha256'),'hex'),'EXEC-S30-STRATEGY-UPDATE-LIFECYCLE-CANARY-20260914-001','cristhianlujan/claude-persona-lf-patch',format('supabase://public/lf_strategy_snapshots/%s',s.id),jsonb_build_object('scope','ROLLBACK_CANARY_CANONICAL_LIFECYCLE','persistent_mutation_allowed',false)); IF rr->>'result'<>'RESERVED_NEW_EXECUTION' THEN RAISE EXCEPTION 'S30_UPDATE_CANARY_RESERVATION_FAIL:%',rr; END IF; r:=public.lf_strategy_update_write_v1('EXEC-S30-STRATEGY-UPDATE-LIFECYCLE-CANARY-20260914-001',s.id,b,jsonb_build_object('progress',s.metadata->'progress','metadata_merge','{}'::jsonb,'backlog',coalesce(s.backlog,'[]'::jsonb),'evidence_refs_append',jsonb_build_array(jsonb_build_object('type','S30_LIFECYCLE_ROLLBACK_CANARY','persistent',false)),'change_log_append',jsonb_build_array(jsonb_build_object('change_type','S30_LIFECYCLE_ROLLBACK_CANARY','persistent',false)))); IF r->>'result'<>'STRATEGY_UPDATED_WITH_EVIDENCE' THEN RAISE EXCEPTION 'S30_UPDATE_CANARY_RESULT_FAIL:%',r; END IF; RAISE EXCEPTION USING ERRCODE='P0C11',MESSAGE='S30_UPDATE_CANARY_INTENTIONAL_ROLLBACK'; EXCEPTION WHEN SQLSTATE 'P0C11' THEN NULL; END; SELECT encode(extensions.digest(to_jsonb(x)::text,'sha256'),'hex') INTO a FROM public.lf_strategy_snapshots x WHERE id=s.id; IF a IS DISTINCT FROM b THEN RAISE EXCEPTION 'S30_UPDATE_CANARY_ROLLBACK_FAIL:%:%',b,a; END IF; END $update_canary$;

DO $exec_canary$ DECLARE s public.lf_strategy_snapshots%rowtype; rr jsonb; after_state text; ev jsonb; BEGIN SELECT * INTO s FROM public.lf_strategy_snapshots WHERE id=2 AND lifecycle_state_code='STRATEGY_PLANNED' FOR SHARE; IF NOT FOUND THEN RAISE EXCEPTION 'S30_EXEC_CANARY_FIXTURE_NOT_PLANNED'; END IF; BEGIN rr:=public.fn_lf_operation_reserve_execution_v1('EXEC-S30-STRATEGY-EXEC-LIFECYCLE-CANARY-20260914-001','EJECUCION_ESTRATEGIA_LF','STRATEGY',s.snapshot_code,'S30:STRATEGY_EXEC:LIFECYCLE:ROLLBACK_CANARY:20260914:001',encode(extensions.digest('S30_STRATEGY_EXEC_LIFECYCLE_ROLLBACK_CANARY','sha256'),'hex'),'EXEC-S30-STRATEGY-EXEC-LIFECYCLE-CANARY-20260914-001','cristhianlujan/claude-persona-lf-patch',format('supabase://public/lf_strategy_snapshots/%s',s.id),jsonb_build_object('mode','GOVERNED_OPERATIONAL','scope','ROLLBACK_CANARY_LIFECYCLE_TRANSITION','business_effect_dispatch_allowed',false)); IF rr->>'result'<>'RESERVED_NEW_EXECUTION' THEN RAISE EXCEPTION 'S30_EXEC_CANARY_RESERVATION_FAIL:%',rr; END IF; ev:=jsonb_build_object('strategy_snapshot_ref',format('snapshot:%s/%s@%s',s.id,s.snapshot_code,s.version),'strategy_currentness_ref',format('revision:%s',encode(extensions.digest(to_jsonb(s)::text,'sha256'),'hex')),'assertions_checked',jsonb_build_array('r16_quality_bound','c05_reliability_bound','required_evidence_present','authority_currentness_pass','runtime_activation_authorized','business_effect_dispatch_allowed'),'hard_fails_checked','[]'::jsonb,'blocking_findings','[]'::jsonb,'return_to_worker_reasons','[]'::jsonb,'runtime_mode','GOVERNED_OPERATIONAL','operation_code','EJECUCION_ESTRATEGIA_LF','source_contract','CONTRACT-EJECUCION-ESTRATEGIA-LF-v1','r16_quality_bound',true,'c05_reliability_bound',true,'required_evidence_present',true,'authority_currentness_pass',true,'runtime_activation_authorized',true,'business_effect_dispatch_allowed',false,'scheduler_activation',false,'production_activation',false,'orchestrator_activation',false); INSERT INTO public.lf_operation_execution_steps(execution_id,step_order,step_id,status,evidence_ref,evidence_payload,created_by_execution_id) VALUES('EXEC-S30-STRATEGY-EXEC-LIFECYCLE-CANARY-20260914-001',20,'strategy_resolve','PASS_CLEAN','rollback-canary',ev,'EXEC-S30-STRATEGY-EXEC-LIFECYCLE-CANARY-20260914-001'); SELECT lifecycle_state_code INTO after_state FROM public.lf_strategy_snapshots WHERE id=s.id; IF after_state<>'STRATEGY_ACTIVE' THEN RAISE EXCEPTION 'S30_EXEC_CANARY_TRANSITION_FAIL:%',after_state; END IF; RAISE EXCEPTION USING ERRCODE='P0C12',MESSAGE='S30_EXEC_CANARY_INTENTIONAL_ROLLBACK'; EXCEPTION WHEN SQLSTATE 'P0C12' THEN NULL; END; SELECT lifecycle_state_code INTO after_state FROM public.lf_strategy_snapshots WHERE id=s.id; IF after_state<>'STRATEGY_PLANNED' THEN RAISE EXCEPTION 'S30_EXEC_CANARY_ROLLBACK_FAIL:%',after_state; END IF; END $exec_canary$;

UPDATE public.lf_operation_execution SET status='COMPLETED',completed_at=clock_timestamp(),updated_at=clock_timestamp(),updated_by_execution_id=execution_id,manifest=manifest || jsonb_build_object('result','CANONICAL_LIFECYCLE_STATE_MODEL_APPLIED','state_catalog','lf_ops.estados_catalogo','transition_catalog','lf_ops.estados_transiciones','state_policy_version','v2.0-canonical-lifecycle','legacy_fields_authority',false) WHERE execution_id='EXEC-S30-STATE-LIFECYCLE-CANONICALIZATION-20260914-001';
UPDATE public.lf_operation_execution SET status='COMPLETED',completed_at=clock_timestamp(),updated_at=clock_timestamp(),updated_by_execution_id=execution_id,manifest=manifest || jsonb_build_object('result','STRATEGY_UPDATE_OPERATIONAL','registry_status','PRODUCCION_CONTROLADA','lifecycle_state','OP_OPERATIONAL','writer_gate','STRATEGY_PLANNED_OR_ACTIVE','rollback_canary','PASS') WHERE execution_id='EXEC-S30-STRATEGY-UPDATE-PROMOTE-20260914-001';
UPDATE public.lf_operation_execution SET status='COMPLETED',completed_at=clock_timestamp(),updated_at=clock_timestamp(),updated_by_execution_id=execution_id,manifest=manifest || jsonb_build_object('result','STRATEGY_EXECUTION_OPERATIONAL','registry_status','PRODUCCION_CONTROLADA','lifecycle_state','OP_OPERATIONAL','business_effect_dispatch_allowed',true,'direct_business_write_allowed',false,'scheduler_activation',false,'orchestrator_activation',false,'lifecycle_transition_canary','PASS') WHERE execution_id='EXEC-S30-STRATEGY-EXEC-PROMOTE-20260914-001';

DO $post$ DECLARE v jsonb; c int; BEGIN SELECT count(*) INTO c FROM lf_ops.estados_catalogo WHERE entity_type='OPERATION_LIFECYCLE' AND status='VIGENTE'; IF c<>3 THEN RAISE EXCEPTION 'S30_POST_OPERATION_STATE_COUNT:%',c; END IF; SELECT count(*) INTO c FROM lf_ops.estados_catalogo WHERE entity_type='STRATEGY_LIFECYCLE' AND status='VIGENTE'; IF c<>4 THEN RAISE EXCEPTION 'S30_POST_STRATEGY_STATE_COUNT:%',c; END IF; IF EXISTS (SELECT 1 FROM public.lf_operation_registry WHERE lifecycle_state_code IS NULL) OR EXISTS (SELECT 1 FROM public.lf_strategy_snapshots WHERE lifecycle_state_code IS NULL) THEN RAISE EXCEPTION 'S30_POST_NULL_CANONICAL_LIFECYCLE'; END IF; IF NOT EXISTS (SELECT 1 FROM public.lf_operation_registry WHERE operation_code='ACTUALIZACION_ESTRATEGIA_LF' AND status='PRODUCCION_CONTROLADA' AND lifecycle_state_code='OP_OPERATIONAL' AND version='v1.0') THEN RAISE EXCEPTION 'S30_POST_STRATEGY_UPDATE_NOT_OPERATIONAL'; END IF; IF NOT EXISTS (SELECT 1 FROM public.lf_operation_registry WHERE operation_code='EJECUCION_ESTRATEGIA_LF' AND status='PRODUCCION_CONTROLADA' AND lifecycle_state_code='OP_OPERATIONAL' AND version='v1.0') THEN RAISE EXCEPTION 'S30_POST_STRATEGY_EXEC_NOT_OPERATIONAL'; END IF; IF NOT EXISTS (SELECT 1 FROM public.lf_router_action_registry WHERE operation_code='EJECUCION_ESTRATEGIA_LF' AND action_code='STRATEGY_EXECUTION' AND status='ACTIVE' AND write_allowed=true) THEN RAISE EXCEPTION 'S30_POST_STRATEGY_EXEC_ROUTER_WRITE_NOT_ENABLED'; END IF; IF NOT EXISTS (SELECT 1 FROM public.lf_operation_contracts WHERE operation_code='EJECUCION_ESTRATEGIA_LF' AND contract_code='CONTRACT-EJECUCION-ESTRATEGIA-LF-v1' AND status='ACTIVE_ENFORCEMENT' AND coalesce((allowed->>'business_effect_dispatch_allowed')::boolean,false)) THEN RAISE EXCEPTION 'S30_POST_STRATEGY_EXEC_CONTRACT_NOT_OPERATIONAL'; END IF; IF EXISTS (SELECT 1 FROM public.lf_operation_contracts WHERE operation_code='EJECUCION_ESTRATEGIA_LF' AND contract_code ILIKE '%candidate%') THEN RAISE EXCEPTION 'S30_POST_CANDIDATE_EXECUTOR_CONTRACT_REMAINS'; END IF; IF NOT EXISTS (SELECT 1 FROM public.lf_policy_versions WHERE policy_code='POL-LF-STATE-MODEL' AND policy_version='v2.0-canonical-lifecycle' AND status='ACTIVE') THEN RAISE EXCEPTION 'S30_POST_STATE_POLICY_V2_NOT_ACTIVE'; END IF; v:=public.lf_router_resolve_v1('ejecutar estrategia',null,'STRATEGY_EXECUTION','STRATEGY','ROUTER'); IF v->>'status'<>'READY_TO_EXECUTE' OR v->>'operation_code'<>'EJECUCION_ESTRATEGIA_LF' OR v->>'operation_lifecycle_state'<>'OP_OPERATIONAL' OR v->>'operation_status'<>'PRODUCCION_CONTROLADA' THEN RAISE EXCEPTION 'S30_POST_ROUTER_OPERATIONAL_READBACK_FAIL:%',v; END IF; END $post$;